export { AGENTSDK_ERP_MCP_ARTIFACT_PATCH_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpArtifactPatchToolScript'
export { AGENTSDK_ERP_MCP_ARTIFACT_READ_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpArtifactReadToolScript'
export { AGENTSDK_ERP_MCP_ARTIFACT_WRITE_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpArtifactWriteToolScript'
export { AGENTSDK_ERP_MCP_CRUD_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpCrudToolScript'
export { AGENTSDK_ERP_MCP_ECOMMERCE_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpEcommerceToolScript'
export { AGENTSDK_ERP_MCP_MARKETING_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpMarketingToolScript'
export { AGENTSDK_ERP_MCP_SQL_EXECUTION_TOOL_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpSqlExecutionToolScript'
export { AGENTSDK_ERP_MCP_TOOLS_SCRIPT } from '@/products/chat/backend/agents/agentsdk/tools/schema/erpToolsScript'
