BEGIN;

CREATE SCHEMA IF NOT EXISTS ecommerce;

-- =========================
-- Integração / sincronização
-- =========================

CREATE TABLE IF NOT EXISTS ecommerce.canais_contas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  ambiente TEXT NOT NULL DEFAULT 'production',
  external_id TEXT,
  conta_slug TEXT,
  nome_conta TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ativo',
  moeda_padrao TEXT,
  pais TEXT,
  timezone TEXT,
  seller_id TEXT,
  loja_principal_external_id TEXT,
  config_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.canais_credenciais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'oauth',
  status TEXT NOT NULL DEFAULT 'ativo',
  segredo_ref TEXT,
  credenciais_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  segredos_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  escopos_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
  expira_em TIMESTAMPTZ,
  rotacionado_em TIMESTAMPTZ,
  ultimo_erro TEXT,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.sync_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  entidade TEXT NOT NULL, -- pedidos, produtos, estoque, payouts, etc
  escopo TEXT,            -- endpoint/recurso específico
  modo TEXT NOT NULL DEFAULT 'incremental', -- full|incremental|backfill
  status TEXT NOT NULL DEFAULT 'pending',   -- pending|running|success|error|cancelled
  prioridade SMALLINT NOT NULL DEFAULT 5,
  requested_from TIMESTAMPTZ,
  requested_to TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  rows_lidos INTEGER NOT NULL DEFAULT 0,
  rows_upsertados INTEGER NOT NULL DEFAULT 0,
  rows_ignorados INTEGER NOT NULL DEFAULT 0,
  request_params_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_summary_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  erro_msg TEXT,
  erro_detalhe_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.sync_cursores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  entidade TEXT NOT NULL,
  escopo TEXT,
  chave_cursor TEXT NOT NULL DEFAULT 'default',
  cursor_valor_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  cursor_texto TEXT,
  cursor_data TIMESTAMPTZ,
  ultima_execucao_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.webhook_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  external_event_id TEXT,
  topico TEXT,
  tipo_evento TEXT,
  status_processamento TEXT NOT NULL DEFAULT 'pendente',
  recebido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  processado_em TIMESTAMPTZ,
  tentativas INTEGER NOT NULL DEFAULT 0,
  headers_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  resultado_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  erro_msg TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.raw_api_payloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  entidade TEXT,
  operacao TEXT,
  endpoint TEXT,
  http_method TEXT,
  request_id TEXT,
  external_id TEXT,
  status_http INTEGER,
  erro_msg TEXT,
  request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- Cadastros canônicos
-- =========================

CREATE TABLE IF NOT EXISTS ecommerce.lojas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  external_id TEXT,
  codigo TEXT,
  nome TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ativo',
  url TEXT,
  pais TEXT,
  moeda TEXT,
  timezone TEXT,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  external_id TEXT,
  codigo TEXT,
  nome TEXT,
  email TEXT,
  telefone TEXT,
  documento TEXT,
  tipo_pessoa TEXT,
  status TEXT,
  tags_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.enderecos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  cliente_id BIGINT REFERENCES ecommerce.clientes(id) ON DELETE CASCADE,
  external_id TEXT,
  tipo TEXT, -- billing|shipping|return|other
  nome_destinatario TEXT,
  documento_destinatario TEXT,
  telefone TEXT,
  email TEXT,
  pais TEXT,
  estado TEXT,
  cidade TEXT,
  bairro TEXT,
  logradouro TEXT,
  numero TEXT,
  complemento TEXT,
  cep TEXT,
  referencia TEXT,
  latitude NUMERIC(12,8),
  longitude NUMERIC(12,8),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL DEFAULT 'internal' CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  external_id TEXT,
  sku_principal TEXT,
  codigo_interno TEXT,
  nome TEXT NOT NULL,
  descricao TEXT,
  marca TEXT,
  categoria TEXT,
  status TEXT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  peso_kg NUMERIC(12,4),
  altura_cm NUMERIC(12,4),
  largura_cm NUMERIC(12,4),
  comprimento_cm NUMERIC(12,4),
  atributos_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.produto_variantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL DEFAULT 'internal' CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT REFERENCES ecommerce.canais_contas(id) ON DELETE SET NULL,
  produto_id BIGINT NOT NULL REFERENCES ecommerce.produtos(id) ON DELETE CASCADE,
  external_id TEXT,
  sku TEXT,
  gtin TEXT,
  ean TEXT,
  asin TEXT,
  mpn TEXT,
  nome TEXT,
  status TEXT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  preco_sugerido NUMERIC(18,4),
  custo_unitario NUMERIC(18,4),
  peso_kg NUMERIC(12,4),
  atributos_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  produto_id BIGINT REFERENCES ecommerce.produtos(id) ON DELETE SET NULL,
  produto_variante_id BIGINT REFERENCES ecommerce.produto_variantes(id) ON DELETE SET NULL,
  external_id TEXT NOT NULL,
  parent_external_id TEXT,
  sku TEXT,
  titulo TEXT,
  status TEXT,
  condicao TEXT,
  moeda TEXT,
  preco_anunciado NUMERIC(18,4),
  preco_promocional NUMERIC(18,4),
  estoque_disponivel NUMERIC(18,4),
  estoque_reservado NUMERIC(18,4),
  url TEXT,
  imagem_url TEXT,
  categoria_canal_id TEXT,
  categoria_canal_nome TEXT,
  atributos_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.listing_variantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  listing_id BIGINT NOT NULL REFERENCES ecommerce.listings(id) ON DELETE CASCADE,
  produto_variante_id BIGINT REFERENCES ecommerce.produto_variantes(id) ON DELETE SET NULL,
  external_id TEXT,
  sku TEXT,
  status TEXT,
  moeda TEXT,
  preco NUMERIC(18,4),
  preco_promocional NUMERIC(18,4),
  estoque_disponivel NUMERIC(18,4),
  atributos_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- Pedidos / financeiro / fulfillment
-- =========================

CREATE TABLE IF NOT EXISTS ecommerce.pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  cliente_id BIGINT REFERENCES ecommerce.clientes(id) ON DELETE SET NULL,
  endereco_entrega_id BIGINT REFERENCES ecommerce.enderecos(id) ON DELETE SET NULL,
  endereco_cobranca_id BIGINT REFERENCES ecommerce.enderecos(id) ON DELETE SET NULL,
  external_id TEXT NOT NULL,
  parent_external_id TEXT,
  numero_pedido TEXT,
  numero_pedido_canal TEXT,
  status TEXT NOT NULL DEFAULT 'novo',
  status_pagamento TEXT,
  status_fulfillment TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  subtotal NUMERIC(18,4) NOT NULL DEFAULT 0,
  desconto_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  frete_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  impostos_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  taxa_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_pago NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_reembolsado NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_liquido_estimado NUMERIC(18,4),
  data_pedido TIMESTAMPTZ,
  data_aprovacao TIMESTAMPTZ,
  data_cancelamento TIMESTAMPTZ,
  observacoes TEXT,
  tags_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.pedido_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  listing_id BIGINT REFERENCES ecommerce.listings(id) ON DELETE SET NULL,
  produto_id BIGINT REFERENCES ecommerce.produtos(id) ON DELETE SET NULL,
  produto_variante_id BIGINT REFERENCES ecommerce.produto_variantes(id) ON DELETE SET NULL,
  external_id TEXT,
  linha_numero INTEGER,
  sku TEXT,
  titulo_item TEXT,
  status TEXT,
  quantidade NUMERIC(18,4) NOT NULL DEFAULT 0,
  preco_unitario NUMERIC(18,4) NOT NULL DEFAULT 0,
  desconto_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  impostos_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  frete_rateado NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  moeda TEXT DEFAULT 'BRL',
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.pagamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  external_id TEXT,
  status TEXT,
  metodo TEXT,
  provedor TEXT,
  parcelado_em INTEGER,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  valor_autorizado NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_capturado NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_taxa NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_liquido NUMERIC(18,4),
  data_autorizacao TIMESTAMPTZ,
  data_captura TIMESTAMPTZ,
  data_vencimento TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.transacoes_pagamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pagamento_id BIGINT NOT NULL REFERENCES ecommerce.pagamentos(id) ON DELETE CASCADE,
  pedido_id BIGINT REFERENCES ecommerce.pedidos(id) ON DELETE SET NULL,
  external_id TEXT,
  tipo TEXT,   -- auth|capture|refund|chargeback|fee
  status TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  valor NUMERIC(18,4) NOT NULL DEFAULT 0,
  taxa NUMERIC(18,4) NOT NULL DEFAULT 0,
  referencia_externa TEXT,
  ocorrido_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.envios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  endereco_entrega_id BIGINT REFERENCES ecommerce.enderecos(id) ON DELETE SET NULL,
  external_id TEXT,
  status TEXT,
  transportadora TEXT,
  servico TEXT,
  tracking_code TEXT,
  tracking_url TEXT,
  etiqueta_url TEXT,
  moeda TEXT DEFAULT 'BRL',
  frete_cobrado NUMERIC(18,4) NOT NULL DEFAULT 0,
  frete_custo NUMERIC(18,4) NOT NULL DEFAULT 0,
  prazo_dias INTEGER,
  despachado_em TIMESTAMPTZ,
  entregue_em TIMESTAMPTZ,
  cancelado_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.eventos_fulfillment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  envio_id BIGINT NOT NULL REFERENCES ecommerce.envios(id) ON DELETE CASCADE,
  pedido_id BIGINT REFERENCES ecommerce.pedidos(id) ON DELETE SET NULL,
  external_id TEXT,
  status TEXT,
  substatus TEXT,
  descricao TEXT,
  local_evento TEXT,
  ocorrido_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.devolucoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  pedido_item_id BIGINT REFERENCES ecommerce.pedido_itens(id) ON DELETE SET NULL,
  envio_id BIGINT REFERENCES ecommerce.envios(id) ON DELETE SET NULL,
  external_id TEXT,
  status TEXT,
  motivo TEXT,
  quantidade NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_solicitado NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_aprovado NUMERIC(18,4),
  moeda TEXT DEFAULT 'BRL',
  solicitado_em TIMESTAMPTZ,
  aprovado_em TIMESTAMPTZ,
  concluido_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.reembolsos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  pagamento_id BIGINT REFERENCES ecommerce.pagamentos(id) ON DELETE SET NULL,
  devolucao_id BIGINT REFERENCES ecommerce.devolucoes(id) ON DELETE SET NULL,
  external_id TEXT,
  status TEXT,
  motivo TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  valor NUMERIC(18,4) NOT NULL DEFAULT 0,
  taxa NUMERIC(18,4) NOT NULL DEFAULT 0,
  solicitado_em TIMESTAMPTZ,
  processado_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.taxas_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  pedido_id BIGINT NOT NULL REFERENCES ecommerce.pedidos(id) ON DELETE CASCADE,
  pedido_item_id BIGINT REFERENCES ecommerce.pedido_itens(id) ON DELETE SET NULL,
  external_id TEXT,
  tipo_taxa TEXT NOT NULL,  -- comissao, gateway, ads, frete_subsidiado, ajuste, etc
  descricao TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  base_calculo NUMERIC(18,4),
  aliquota NUMERIC(12,6),
  valor NUMERIC(18,4) NOT NULL DEFAULT 0,
  competencia_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  external_id TEXT NOT NULL,
  status TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  periodo_inicio TIMESTAMPTZ,
  periodo_fim TIMESTAMPTZ,
  data_pagamento TIMESTAMPTZ,
  valor_bruto NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_taxas NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_reembolsos NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_ajustes NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_liquido NUMERIC(18,4) NOT NULL DEFAULT 0,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.payout_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  payout_id BIGINT NOT NULL REFERENCES ecommerce.payouts(id) ON DELETE CASCADE,
  pedido_id BIGINT REFERENCES ecommerce.pedidos(id) ON DELETE SET NULL,
  pedido_item_id BIGINT REFERENCES ecommerce.pedido_itens(id) ON DELETE SET NULL,
  taxa_pedido_id BIGINT REFERENCES ecommerce.taxas_pedido(id) ON DELETE SET NULL,
  reembolso_id BIGINT REFERENCES ecommerce.reembolsos(id) ON DELETE SET NULL,
  external_id TEXT,
  tipo_item TEXT NOT NULL, -- pedido, taxa, reembolso, ajuste, chargeback
  descricao TEXT,
  moeda TEXT NOT NULL DEFAULT 'BRL',
  valor_bruto NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_taxa NUMERIC(18,4) NOT NULL DEFAULT 0,
  valor_liquido NUMERIC(18,4) NOT NULL DEFAULT 0,
  data_referencia TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- Estoque
-- =========================

CREATE TABLE IF NOT EXISTS ecommerce.estoque_saldos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  produto_id BIGINT REFERENCES ecommerce.produtos(id) ON DELETE SET NULL,
  produto_variante_id BIGINT REFERENCES ecommerce.produto_variantes(id) ON DELETE SET NULL,
  listing_id BIGINT REFERENCES ecommerce.listings(id) ON DELETE SET NULL,
  external_id TEXT,
  armazem_external_id TEXT,
  armazem_nome TEXT,
  status TEXT,
  quantidade_total NUMERIC(18,4) NOT NULL DEFAULT 0,
  quantidade_disponivel NUMERIC(18,4) NOT NULL DEFAULT 0,
  quantidade_reservada NUMERIC(18,4) NOT NULL DEFAULT 0,
  quantidade_em_transito NUMERIC(18,4) NOT NULL DEFAULT 0,
  snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
  capturado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ecommerce.estoque_movimentacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plataforma TEXT NOT NULL CHECK (btrim(plataforma) <> ''),
  canal_conta_id BIGINT NOT NULL REFERENCES ecommerce.canais_contas(id) ON DELETE CASCADE,
  loja_id BIGINT REFERENCES ecommerce.lojas(id) ON DELETE SET NULL,
  produto_id BIGINT REFERENCES ecommerce.produtos(id) ON DELETE SET NULL,
  produto_variante_id BIGINT REFERENCES ecommerce.produto_variantes(id) ON DELETE SET NULL,
  listing_id BIGINT REFERENCES ecommerce.listings(id) ON DELETE SET NULL,
  pedido_id BIGINT REFERENCES ecommerce.pedidos(id) ON DELETE SET NULL,
  external_id TEXT,
  tipo_movimento TEXT NOT NULL, -- entrada, saida, reserva, ajuste, transferencia
  origem TEXT,                 -- pedido, devolucao, ajuste_manual, reconciliacao, ...
  quantidade NUMERIC(18,4) NOT NULL DEFAULT 0,
  saldo_apos NUMERIC(18,4),
  armazem_external_id TEXT,
  armazem_nome TEXT,
  ocorrido_em TIMESTAMPTZ,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- Índices e unicidade
-- =========================

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_canais_contas_ext
  ON ecommerce.canais_contas (tenant_id, plataforma, ambiente, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_canais_contas_tenant_plataforma_status
  ON ecommerce.canais_contas (tenant_id, plataforma, status);

CREATE INDEX IF NOT EXISTS ix_ec_sync_jobs_lookup
  ON ecommerce.sync_jobs (tenant_id, plataforma, canal_conta_id, entidade, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_sync_cursores_key
  ON ecommerce.sync_cursores (tenant_id, plataforma, canal_conta_id, entidade, COALESCE(escopo, ''), chave_cursor);

CREATE INDEX IF NOT EXISTS ix_ec_webhooks_status
  ON ecommerce.webhook_eventos (tenant_id, plataforma, status_processamento, recebido_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_webhooks_ext
  ON ecommerce.webhook_eventos (tenant_id, plataforma, canal_conta_id, external_event_id)
  WHERE external_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_raw_payloads_lookup
  ON ecommerce.raw_api_payloads (tenant_id, plataforma, canal_conta_id, entidade, ocorrido_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_lojas_ext
  ON ecommerce.lojas (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_clientes_ext
  ON ecommerce.clientes (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_enderecos_ext
  ON ecommerce.enderecos (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_produtos_ext
  ON ecommerce.produtos (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_prod_variantes_sku
  ON ecommerce.produto_variantes (tenant_id, sku)
  WHERE sku IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_prod_variantes_ext
  ON ecommerce.produto_variantes (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_listings_ext
  ON ecommerce.listings (tenant_id, plataforma, canal_conta_id, external_id);

CREATE INDEX IF NOT EXISTS ix_ec_listings_lookup
  ON ecommerce.listings (tenant_id, plataforma, status, produto_variante_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_listing_variantes_ext
  ON ecommerce.listing_variantes (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_listing_variantes_listing
  ON ecommerce.listing_variantes (listing_id, produto_variante_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_pedidos_ext
  ON ecommerce.pedidos (tenant_id, plataforma, canal_conta_id, external_id);

CREATE INDEX IF NOT EXISTS ix_ec_pedidos_data
  ON ecommerce.pedidos (tenant_id, plataforma, data_pedido DESC);

CREATE INDEX IF NOT EXISTS ix_ec_pedidos_status
  ON ecommerce.pedidos (tenant_id, plataforma, status, status_pagamento, status_fulfillment);

CREATE INDEX IF NOT EXISTS ix_ec_pedidos_cliente
  ON ecommerce.pedidos (cliente_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_pedido_itens_ext
  ON ecommerce.pedido_itens (pedido_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_pedido_itens_linha
  ON ecommerce.pedido_itens (pedido_id, linha_numero)
  WHERE linha_numero IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_pedido_itens_lookup
  ON ecommerce.pedido_itens (pedido_id, produto_variante_id, listing_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_pagamentos_ext
  ON ecommerce.pagamentos (pedido_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_pagamentos_lookup
  ON ecommerce.pagamentos (tenant_id, plataforma, pedido_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_trans_pag_ext
  ON ecommerce.transacoes_pagamento (pagamento_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_trans_pag_lookup
  ON ecommerce.transacoes_pagamento (tenant_id, plataforma, pedido_id, ocorrido_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_envios_ext
  ON ecommerce.envios (pedido_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_envios_tracking
  ON ecommerce.envios (tenant_id, plataforma, tracking_code);

CREATE INDEX IF NOT EXISTS ix_ec_eventos_fulfillment_envio
  ON ecommerce.eventos_fulfillment (envio_id, ocorrido_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_devolucoes_ext
  ON ecommerce.devolucoes (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_devolucoes_lookup
  ON ecommerce.devolucoes (pedido_id, pedido_item_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_reembolsos_ext
  ON ecommerce.reembolsos (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_reembolsos_lookup
  ON ecommerce.reembolsos (pedido_id, pagamento_id, status, processado_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_taxas_pedido_ext
  ON ecommerce.taxas_pedido (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_taxas_pedido_lookup
  ON ecommerce.taxas_pedido (pedido_id, pedido_item_id, tipo_taxa, competencia_em DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_payouts_ext
  ON ecommerce.payouts (tenant_id, plataforma, canal_conta_id, external_id);

CREATE INDEX IF NOT EXISTS ix_ec_payouts_lookup
  ON ecommerce.payouts (tenant_id, plataforma, data_pagamento DESC, status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_payout_itens_ext
  ON ecommerce.payout_itens (payout_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_payout_itens_lookup
  ON ecommerce.payout_itens (payout_id, pedido_id, tipo_item, data_referencia DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_estoque_saldos_ext
  ON ecommerce.estoque_saldos (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_estoque_saldos_snapshot
  ON ecommerce.estoque_saldos (tenant_id, plataforma, snapshot_date DESC, produto_variante_id, listing_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ec_estoque_mov_ext
  ON ecommerce.estoque_movimentacoes (tenant_id, plataforma, canal_conta_id, external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ec_estoque_mov_lookup
  ON ecommerce.estoque_movimentacoes (tenant_id, plataforma, produto_variante_id, ocorrido_em DESC);

COMMIT;

