export const AGENTSDK_ERP_MCP_DOCUMENTO_TOOL_SCRIPT = `tool('documento','Gera e consulta documentos operacionais (OS/proposta/NFSe/fatura/contrato), retornando PDF. Com save_to_drive=true, salva no Drive (workspace_id obrigatório na prática) e retorna metadados/drive_file_id; por padrão o payload fica enxuto (sem attachment.content/base64) quando salvo no Drive. Use include_attachment_content=true somente se precisar do PDF inline/base64.', {
  action: z.enum(['gerar','status']),
  tipo: z.enum(['proposta','os','fatura','contrato','nfse']).optional(),
  origem_tipo: z.string().optional(),
  origem_id: z.number().int().optional(),
  titulo: z.string().optional(),
  dados: z.any().optional(),
  save_to_drive: z.boolean().optional(),
  workspace_id: z.string().optional(),
  folder_id: z.string().optional(),
  file_name: z.string().optional(),
  drive: z.object({
    workspace_id: z.string().optional(),
    folder_id: z.string().optional(),
    file_name: z.string().optional(),
  }).optional(),
  include_attachment_content: z.boolean().optional(),
  template_id: z.number().int().optional(),
  template_version_id: z.number().int().optional(),
  idempotency_key: z.string().optional(),
  documento_id: z.number().int().optional(),
  tenant_id: z.number().int().optional(),
}, async (args) => callDocumento(args))`;
