export const AGENTSDK_ERP_MCP_EMAIL_TOOL_SCRIPT = `tool('email','Tool de Email para consultar inbox/messages e enviar emails. Também suporta batch (múltiplos envios/requests em sequência). Prefira anexar por drive_file_id/drive_file_ids (backend resolve URL assinada); use URL/base64 (attachments/attachment_url) como fallback. Em email/messages, use filtros como subject, q/search, has_attachments, unread e date_from/date_to quando precisar localizar mensagens.', {
  action: z.enum(['request','send','send_email','batch']).default('request'),
  method: z.enum(['GET','POST','DELETE']).optional(),
  resource: z.string().optional(),
  params: z.any().optional(),
  data: z.any().optional(),
  inbox_id: z.string().optional(),
  inboxId: z.string().optional(),
  to: z.union([z.string(), z.array(z.string())]).optional(),
  cc: z.union([z.string(), z.array(z.string())]).optional(),
  bcc: z.union([z.string(), z.array(z.string())]).optional(),
  labels: z.any().optional(),
  subject: z.string().optional(),
  text: z.string().optional(),
  html: z.string().optional(),
  attachments: z.any().optional(),
  drive_file_id: z.string().optional(),
  drive_file_ids: z.array(z.string()).optional(),
  attachment_url: z.string().optional(),
  signed_url: z.string().optional(),
  filename: z.string().optional(),
  content_type: z.string().optional(),
  content_disposition: z.string().optional(),
  content_id: z.string().optional(),
  operations: z.array(z.any()).optional(),
  continue_on_error: z.boolean().optional(),
}, async (args) => callEmail(args))`;
