#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'

const root = process.cwd()
const tmpDir = path.join(root, '.next/cache/plugin-smoke')

function assert(condition, message) {
  if (!condition) throw new Error(message)
}

function compileTsModule(sourceFile, outputName) {
  mkdirSync(tmpDir, { recursive: true })
  const source = readFileSync(path.join(root, sourceFile), 'utf8')
  const output = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
      jsx: ts.JsxEmit.Preserve,
    },
    fileName: sourceFile,
    reportDiagnostics: true,
  })

  const diagnostics = output.diagnostics || []
  if (diagnostics.length) {
    const text = diagnostics
      .map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))
      .join('\n')
    throw new Error(`TypeScript diagnostics in ${sourceFile}:\n${text}`)
  }

  const outputPath = path.join(tmpDir, outputName)
  writeFileSync(outputPath, output.outputText)
  return outputPath
}

async function main() {
  console.log('Testing Plugin shared layer')

  const widgetHtmlPath = path.join(root, 'src/products/plugin/web/dist/widget.html')
  assert(existsSync(widgetHtmlPath), 'widget.html missing; run pnpm plugin:build')
  const widgetHtml = await readFile(widgetHtmlPath, 'utf8')
  assert(widgetHtml.includes('Cognito Dashboards'), 'widget HTML missing title')
  assert(widgetHtml.includes('CognitoPlugin'), 'widget HTML missing Plugin runtime')
  assert(widgetHtml.includes('CognitoChatGptApp'), 'widget HTML missing ChatGPT compatibility alias')
  assert(widgetHtml.includes('createElement("iframe"') || widgetHtml.includes('iframe'), 'widget HTML missing iframe renderer')
  assert(widgetHtml.includes('dashboard-embed-frame'), 'widget HTML missing embed frame styles')
  console.log('widget html ok')

  const resourcesPath = compileTsModule('src/products/plugin/server/appResources.ts', 'appResources.cjs')
  const resources = await import(`file://${resourcesPath}`)
  const list = resources.listCognitoPluginResources()
  assert(list.resources.some((resource) => resource.uri === resources.DASHBOARD_WIDGET_RESOURCE_URI), 'resources/list missing dashboard widget')
  assert(!list.resources.some((resource) => resource.uri === resources.DASHBOARD_WIDGET_PREVIOUS_RESOURCE_URI), 'resources/list should not advertise previous dashboard widget')
  assert(!list.resources.some((resource) => resource.uri === resources.DASHBOARD_WIDGET_LEGACY_RESOURCE_URI), 'resources/list should not advertise legacy dashboard widget')
  const read = resources.readCognitoPluginResource(resources.DASHBOARD_WIDGET_RESOURCE_URI)
  const content = read?.contents?.[0]
  assert(content?.mimeType === 'text/html;profile=plugin', 'resource mime type should be Plugin HTML')
  const previousRead = resources.readCognitoPluginResource(resources.DASHBOARD_WIDGET_PREVIOUS_RESOURCE_URI)
  assert(previousRead?.contents?.[0]?.uri === resources.DASHBOARD_WIDGET_PREVIOUS_RESOURCE_URI, 'previous resource read should preserve requested uri')
  const legacyRead = resources.readCognitoPluginResource(resources.DASHBOARD_WIDGET_LEGACY_RESOURCE_URI)
  assert(legacyRead?.contents?.[0]?.uri === resources.DASHBOARD_WIDGET_LEGACY_RESOURCE_URI, 'legacy resource read should preserve requested uri')
  assert(content?._meta?.ui?.resourceUri === undefined, 'resource content should not declare tool resourceUri')
  assert(content?._meta?.ui?.csp?.resourceDomains?.length > 0, 'resource UI CSP missing resourceDomains')
  assert(content?._meta?.ui?.csp?.frameDomains?.length > 0, 'resource UI CSP missing frameDomains')
  assert(!content?._meta?.['openai/widgetCSP'], 'plugin resource should not include OpenAI CSP metadata')
  console.log('resources metadata ok')

  const toolsSource = await readFile(path.join(root, 'src/products/plugin/server/appTools.ts'), 'utf8')
  assert(toolsSource.includes("dashboards: 'dashboards'"), 'dashboards public tool constant missing')
  assert(toolsSource.includes("analysis: 'analysis'"), 'analysis public tool constant missing')
  assert(toolsSource.includes("table: 'table'"), 'table public tool constant missing')
  assert(toolsSource.includes("actions: 'actions'"), 'actions public tool constant missing')
  assert(toolsSource.includes("alerts: 'alerts'"), 'alerts public tool constant missing')
  assert(toolsSource.includes("schedules: 'schedules'"), 'schedules public tool constant missing')
  assert(toolsSource.includes("connectors: 'connectors'"), 'connectors public tool constant missing')
  assert(!toolsSource.includes("openDashboard: 'open_dashboard'"), 'open_dashboard legacy public tool should be removed')
  assert(toolsSource.includes("openArtifact: 'open_artifact'"), 'open_artifact public tool constant missing')
  assert(toolsSource.includes("artifactAuthoring: 'artifact_authoring'"), 'artifact_authoring public tool constant missing')
  assert(toolsSource.includes('function callDashboards'), 'dashboards implementation missing')
  assert(toolsSource.includes("enum: ['dashboard', 'report', 'slide']"), 'artifact kind enum should include reports and slides')
  assert(toolsSource.includes('Use kind=dashboard, report ou slide'), 'artifact_authoring description should mention supported artifact kinds')
  assert(toolsSource.includes('function callAnalysis'), 'analysis implementation missing')
  assert(toolsSource.includes('function callTable'), 'table implementation missing')
  assert(toolsSource.includes('function callActions'), 'actions implementation missing')
  assert(toolsSource.includes('function callAlerts'), 'alerts implementation missing')
  assert(toolsSource.includes('function callSchedules'), 'schedules implementation missing')
  assert(toolsSource.includes('function callConnectors'), 'connectors implementation missing')
  assert(!toolsSource.includes('function callOpenDashboard'), 'open_dashboard implementation should be removed')
  assert(toolsSource.includes('function callOpenArtifact'), 'open_artifact implementation missing')
  assert(toolsSource.includes('function callArtifactAuthoring'), 'artifact_authoring implementation missing')
  assert(!toolsSource.includes("dashboardAuthoring: 'dashboard_authoring'"), 'dashboard_authoring legacy public tool should be removed')
  assert(toolsSource.includes('Use kind=dashboard, report ou slide; action=get_contract'), 'artifact_authoring description should mention supported artifact kinds')
  assert(!toolsSource.includes('openai/outputTemplate'), 'plugin tools should not include OpenAI outputTemplate')
  assert(!toolsSource.includes('openai/widgetAccessible'), 'plugin tools should not include OpenAI widgetAccessible')
  console.log('tools source ok')

  const artifactsAdapterSource = await readFile(path.join(root, 'src/products/mcp/adapters/artifactsAdapter.ts'), 'utf8')
  assert(artifactsAdapterSource.includes('thumbnail_data_url: thumbnailDataUrl || null'), 'dashboard list should expose thumbnail_data_url')
  assert(artifactsAdapterSource.includes('buildArtifactUrl'), 'generic artifact URL builder missing')
  assert(artifactsAdapterSource.includes('listMcpArtifacts'), 'generic artifact list adapter missing')
  assert(artifactsAdapterSource.includes('createMcpArtifact'), 'generic artifact create adapter missing')
  console.log('artifact adapter source ok')

  const domainToolsSource = await readFile(path.join(root, 'src/products/plugin/server/domainTools.ts'), 'utf8')
  assert(domainToolsSource.includes('function buildFinancialAccountsPayableQuery'), 'contas-a-pagar semantic query missing')
  assert(domainToolsSource.includes('function buildFinancialAccountsReceivableQuery'), 'contas-a-receber semantic query missing')
  assert(domainToolsSource.includes('AS fornecedor'), 'contas-a-pagar should expose fornecedor name column')
  assert(domainToolsSource.includes('AS cliente'), 'contas-a-receber should expose cliente name column')
  assert(domainToolsSource.includes('LEFT JOIN entidades.fornecedores'), 'contas-a-pagar should join fornecedores')
  assert(domainToolsSource.includes('LEFT JOIN entidades.clientes'), 'contas-a-receber should join clientes')
  assert(domainToolsSource.includes('LEFT JOIN compras.compras'), 'contas-a-pagar should join compras')
  assert(domainToolsSource.includes('LEFT JOIN vendas.pedidos'), 'contas-a-receber should join vendas')
  assert(domainToolsSource.includes('AS departamento'), 'financial account queries should expose departamento')
  assert(domainToolsSource.includes('AS filial'), 'financial account queries should expose filial')
  assert(domainToolsSource.includes('AS unidade_negocio'), 'financial account queries should expose unidade_negocio')
  assert(domainToolsSource.includes('function buildSalesOrdersQuery'), 'vendas/pedidos semantic query missing')
  assert(domainToolsSource.includes('function buildPurchaseOrdersQuery'), 'compras/pedidos semantic query missing')
  assert(domainToolsSource.includes('const ECOMMERCE_PARAMS_SCHEMA'), 'ecommerce params schema missing')
  assert(domainToolsSource.includes("enum: ['shopify', 'shopee', 'amazon', 'mercadolivre']"), 'ecommerce platform filter enum missing')
  assert(domainToolsSource.includes('status_pagamento'), 'ecommerce payment status filter missing')
  assert(domainToolsSource.includes('status_fulfillment'), 'ecommerce fulfillment status filter missing')
  assert(domainToolsSource.includes('const MARKETING_PARAMS_SCHEMA'), 'marketing params schema missing')
  assert(domainToolsSource.includes("enum: ['meta_ads', 'google_ads']"), 'marketing platform filter enum missing')
  assert(domainToolsSource.includes("enum: ['conta', 'campanha', 'grupo', 'anuncio']"), 'marketing level filter enum missing')
  assert(domainToolsSource.includes('campanha_id'), 'marketing campaign filter missing')
  assert(domainToolsSource.includes('anuncio_id'), 'marketing ad filter missing')
  assert(domainToolsSource.includes("crm: 'crm'"), 'crm domain tool constant missing')
  assert(domainToolsSource.includes("erpAcoes: 'erp_acoes'"), 'erp_acoes domain tool constant missing')
  assert(domainToolsSource.includes("dataCatalog: 'data_catalog'"), 'data_catalog domain tool constant missing')
  assert(domainToolsSource.includes('const DATA_CATALOG_DOMAIN_TOOL_DEFINITION'), 'data_catalog domain tool definition missing')
  assert(domainToolsSource.includes('function callDataCatalog'), 'data_catalog implementation missing')
  assert(domainToolsSource.includes('pronto_para_dashboard'), 'data_catalog readiness action missing')
  assert(domainToolsSource.includes('const ERP_ACOES_DOMAIN_TOOL_DEFINITION'), 'erp_acoes domain tool definition missing')
  assert(domainToolsSource.includes('dry_run e true por padrao'), 'erp_acoes description should mention safe dry-run default')
  assert(domainToolsSource.includes('case PLUGIN_DOMAIN_TOOL_NAMES.erpAcoes'), 'erp_acoes dispatch missing')
  assert(domainToolsSource.includes('case PLUGIN_DOMAIN_TOOL_NAMES.dataCatalog'), 'data_catalog dispatch missing')
  assert(domainToolsSource.includes('const CRM_DOMAIN_TOOL_DEFINITION'), 'crm domain tool definition missing')
  assert(domainToolsSource.includes('CRM_ALLOWED_RESOURCES'), 'crm allowed resources missing')
  assert(domainToolsSource.includes('case PLUGIN_DOMAIN_TOOL_NAMES.crm'), 'crm dispatch missing')
  assert(!domainToolsSource.includes('Use para financeiro, vendas, compras, CRM e estoque'), 'erp description should not include CRM')
  assert(domainToolsSource.includes('function buildCrmAccountsQuery'), 'crm/contas semantic query missing')
  assert(domainToolsSource.includes('function buildCrmContactsQuery'), 'crm/contatos semantic query missing')
  assert(domainToolsSource.includes('function buildCrmLeadsQuery'), 'crm/leads semantic query missing')
  assert(domainToolsSource.includes('function buildCrmOpportunitiesQuery'), 'crm/oportunidades semantic query missing')
  assert(domainToolsSource.includes('function buildCrmActivitiesQuery'), 'crm/atividades semantic query missing')
  assert(domainToolsSource.includes('function buildCrmInteractionsQuery'), 'crm/interacoes semantic query missing')
  assert(domainToolsSource.includes('crm/contas, crm/contatos, crm/leads, crm/oportunidades, crm/atividades e crm/interacoes'), 'crm description should list all CRM resources')
  assert(domainToolsSource.includes('Shopify, Shopee, Amazon e Mercado Livre'), 'ecommerce description should mention supported platforms')
  assert(domainToolsSource.includes('Meta Ads e Google Ads'), 'marketing description should mention supported platforms')
  assert(domainToolsSource.includes('erp, crm, ecommerce ou marketing'), 'sql description should mention crm fallback')
  assert(domainToolsSource.includes('function buildStockCurrentQuery'), 'estoque/estoque-atual semantic query missing')
  assert(domainToolsSource.includes('function buildStockMovementsQuery'), 'estoque/movimentacoes semantic query missing')
  assert(domainToolsSource.includes('LEFT JOIN vendas.canais_venda'), 'vendas/pedidos should resolve canal name')
  assert(domainToolsSource.includes('LEFT JOIN comercial.vendedores'), 'sales/crm queries should resolve vendedor/responsavel name')
  assert(domainToolsSource.includes('LEFT JOIN crm.contatos'), 'crm/atividades should resolve contato name')
  assert(domainToolsSource.includes('LEFT JOIN crm.fases_pipeline'), 'crm/oportunidades should resolve fase name')
  assert(domainToolsSource.includes('LEFT JOIN produtos.produto'), 'estoque queries should resolve produto name')
  assert(domainToolsSource.includes("'compras/pedidos': 'compras.compras'"), 'compras/pedidos should map to compras.compras')
  assert(domainToolsSource.includes("'estoque/estoque-atual': 'estoque.estoques_atual'"), 'estoque/estoque-atual should map to estoque.estoques_atual')
  console.log('domain tools source ok')

  const dashboardToolsSource = await readFile(path.join(root, 'src/products/mcp/tools/dashboardTools.ts'), 'utf8')
  const dashboardManifestSource = await readFile(
    path.join(root, 'src/products/artifacts/dashboard/language/dashboardLanguageManifest.ts'),
    'utf8',
  )
  assert(dashboardManifestSource.includes("DASHBOARD_DSL_VERSION = 'dashboard.v1'"), 'dashboard DSL version missing')
  assert(dashboardToolsSource.includes('dashboardLanguageManifest') || dashboardToolsSource.includes('dashboardLanguageManifest'.toUpperCase()) || dashboardToolsSource.includes('DASHBOARD_SUPPORTED_COMPONENTS'), 'dashboard tools should derive supported values from the language manifest')
  assert(dashboardToolsSource.includes('component_props: DASHBOARD_COMPONENT_PROPS'), 'dashboard contract should expose component props')
  assert(dashboardToolsSource.includes('data_query_contract: DASHBOARD_DATA_QUERY_CONTRACT'), 'dashboard contract should expose data query contract')
  assert(dashboardToolsSource.includes('supported_html_tags'), 'dashboard contract should expose supported HTML tags')
  assert(dashboardToolsSource.includes('id="dashboard-comercial"'), 'dashboard example should include root Dashboard id')
  assert(dashboardToolsSource.includes('dataQuery={{'), 'dashboard example should use dataQuery')
  assert(!dashboardToolsSource.includes('<KPI id="receita-total" label="Receita" value='), 'dashboard example should not use static KPI.value')
  assert(!dashboardToolsSource.includes('data={[{ label:'), 'dashboard example should not use Chart.data')
  console.log('dashboard authoring contract ok')

  const artifactToolsSource = await readFile(path.join(root, 'src/products/mcp/tools/artifactTools.ts'), 'utf8')
  assert(artifactToolsSource.includes('getDashboardContract'), 'artifact tool should reuse dashboard contract')
  assert(!artifactToolsSource.includes('getPagedArtifactContract'), 'artifact tool should not expose paged artifact contracts')
  assert(artifactToolsSource.includes('assertSourceMatchesKind'), 'artifact source kind guard missing')
  const artifactSchemasSource = await readFile(path.join(root, 'src/products/mcp/tools/artifactSchemas.ts'), 'utf8')
  assert(artifactSchemasSource.includes("enum: ['dashboard', 'report', 'slide']"), 'artifact authoring kind enum should include reports and slides')
  assert(artifactSchemasSource.includes("enum: ['get_contract', 'create', 'patch', 'update_full', 'query_preview']"), 'artifact authoring action enum missing')
  console.log('artifact authoring contract ok')

  const appSource = await readFile(path.join(root, 'src/products/plugin/web/src/App.tsx'), 'utf8')
  const toolCallCardSource = await readFile(path.join(root, 'src/products/plugin/web/src/components/ToolCallCard.tsx'), 'utf8')
  const formatSource = await readFile(path.join(root, 'src/products/plugin/web/src/utils/format.ts'), 'utf8')
  const resultShellSource = await readFile(path.join(root, 'src/products/plugin/web/src/components/ResultShell.tsx'), 'utf8')
  const dataTableSource = await readFile(path.join(root, 'src/products/plugin/web/src/components/DataTable.tsx'), 'utf8')
  const dashboardPreviewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/DashboardPreviewView.tsx'), 'utf8')
  const stylesSource = await readFile(path.join(root, 'src/products/plugin/web/src/styles.css'), 'utf8')
  assert(appSource.includes("tool === 'erp_acoes'"), 'erp_acoes results should render in data view')
  assert(appSource.includes('<ToolCallCard structuredContent={structuredContent}'), 'tool call card should render with structured content')
  assert(appSource.includes('<ToolCallCard toolInput={toolInput} status="running"'), 'tool call card should render during tool input loading')
  assert(appSource.includes("tool === 'crm'"), 'crm results should render in data view')
  assert(appSource.includes("view === 'data_catalog'"), 'data_catalog results should render in catalog view')
  assert(appSource.includes("view === 'analysis'"), 'analysis results should render in analysis view')
  assert(appSource.includes("view === 'table'"), 'table results should render in table view')
  assert(appSource.includes("view === 'automation'"), 'automation results should render in automation view')
  assert(appSource.includes("view === 'automation_list'"), 'automation list results should render in automation view')
  assert(appSource.includes("view === 'connectors'"), 'connectors results should render in connectors view')
  assert(formatSource.includes("tool === 'crm'"), 'crm tool label missing')
  assert(formatSource.includes("tool === 'data_catalog'"), 'data_catalog tool label missing')
  assert(formatSource.includes("tool === 'analysis'"), 'analysis tool label missing')
  assert(formatSource.includes("tool === 'actions'"), 'actions tool label missing')
  assert(formatSource.includes("tool === 'connectors'"), 'connectors tool label missing')
  assert(toolCallCardSource.includes('function getToolName'), 'tool call card should detect tool name')
  assert(toolCallCardSource.includes('function collectChips'), 'tool call card should summarize tool arguments')
  assert(stylesSource.includes('.tool-call-card'), 'tool call card styles missing')
  assert(resultShellSource.includes('result-shell__icon'), 'result shell icon markup missing')
  const dataCatalogViewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/DataCatalogView.tsx'), 'utf8')
  assert(dataCatalogViewSource.includes('catalog-tabs'), 'data catalog view tabs missing')
  assert(dataCatalogViewSource.includes('catalog-kpis'), 'data catalog view KPIs missing')
  const analysisViewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/AnalysisView.tsx'), 'utf8')
  const tableViewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/TableResultView.tsx'), 'utf8')
  const automationViewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/AutomationView.tsx'), 'utf8')
  const connectorsViewSource = await readFile(path.join(root, 'src/products/plugin/web/src/views/ConnectorsView.tsx'), 'utf8')
  assert(analysisViewSource.includes('analysis-card'), 'analysis view cards missing')
  assert(tableViewSource.includes('data-table'), 'table view data table missing')
  assert(automationViewSource.includes('automation-summary'), 'automation view summary missing')
  assert(automationViewSource.includes('automation-list-card'), 'automation list cards missing')
  assert(connectorsViewSource.includes('connector-row'), 'connectors view rows missing')
  assert(toolsSource.includes("action === 'listar'"), 'automation list alias listar missing')
  assert(toolsSource.includes("view: 'automation_list'"), 'automation list view missing')
  const dashboardCardSource = await readFile(path.join(root, 'src/products/plugin/web/src/components/DashboardCard.tsx'), 'utf8')
  assert(dashboardCardSource.includes('dashboard-card__thumbnail'), 'dashboard card thumbnail markup missing')
  assert(dashboardCardSource.includes('dashboard-card__body'), 'dashboard card body markup missing')
  assert(dashboardCardSource.includes('dashboard-card__footer'), 'dashboard card footer markup missing')
  assert(dashboardCardSource.includes('dashboard-card__open'), 'dashboard card open action missing')
  assert(dashboardCardSource.includes('thumbnail_data_url'), 'dashboard card should read thumbnail_data_url')
  assert(dashboardPreviewSource.includes('dashboard-preview-layout'), 'dashboard preview layout wrapper missing')
  assert(formatSource.includes('getToolVisual'), 'tool visual helper missing')
  assert(formatSource.includes('SiTotvs'), 'erp TOTVS icon missing')
  assert(formatSource.includes('SiHubspot'), 'crm HubSpot icon missing')
  assert(formatSource.includes("tone: 'erp'"), 'erp visual tone missing')
  assert(formatSource.includes("tone: 'crm'"), 'crm visual tone missing')
  assert(formatSource.includes("tone: 'ecommerce'"), 'ecommerce visual tone missing')
  assert(formatSource.includes("tone: 'marketing'"), 'marketing visual tone missing')
  assert(formatSource.includes("tone: 'sql'"), 'sql visual tone missing')
  assert(stylesSource.includes('.result-shell__icon--erp'), 'erp icon style missing')
  assert(stylesSource.includes('.result-shell__icon--crm'), 'crm icon style missing')
  assert(stylesSource.includes('.dashboard-card__thumbnail'), 'dashboard thumbnail style missing')
  assert(stylesSource.includes('.dashboard-card__open'), 'dashboard open action style missing')
  assert(stylesSource.includes('repeat(auto-fit, minmax(220px, 1fr))'), 'dashboard grid should be compact and responsive')
  assert(stylesSource.includes('--cognito-green'), 'shared ui tokens missing')
  assert(stylesSource.includes('.dashboard-preview-layout'), 'dashboard preview layout style missing')
  assert(stylesSource.includes('.data-table tbody tr:hover'), 'data table hover style missing')
  assert(dataTableSource.includes('const defaultPageSize = 25'), 'data table default page size should be 25')
  assert(dataTableSource.includes('pageSizeOptions = [25, 50, 100]'), 'data table page size options missing')
  assert(dataTableSource.includes('table-pagination'), 'data table pagination markup missing')
  assert(stylesSource.includes('.table-pagination'), 'data table pagination style missing')
  assert(stylesSource.includes('.catalog-panel'), 'data catalog panel style missing')
  assert(stylesSource.includes('.analysis-panel'), 'analysis panel style missing')
  assert(stylesSource.includes('.automation-panel'), 'automation panel style missing')
  assert(stylesSource.includes('.automation-list-card'), 'automation list card style missing')
  assert(stylesSource.includes('.connector-row'), 'connectors row style missing')
  console.log('web source ok')

  const chatGptToolsSource = await readFile(path.join(root, 'src/products/chatgpt-app/server/appTools.ts'), 'utf8')
  assert(chatGptToolsSource.includes("case 'artifact_authoring'"), 'ChatGPT tool invocation text should handle artifact_authoring')
  assert(chatGptToolsSource.includes("case 'open_artifact'"), 'ChatGPT tool invocation text should handle open_artifact')
  assert(chatGptToolsSource.includes("case 'chart'"), 'ChatGPT tool invocation text should handle chart')
  assert(chatGptToolsSource.includes("case 'crm'"), 'ChatGPT tool invocation text should handle crm')
  assert(chatGptToolsSource.includes("case 'erp_acoes'"), 'ChatGPT tool invocation text should handle erp_acoes')
  assert(chatGptToolsSource.includes("case 'data_catalog'"), 'ChatGPT tool invocation text should handle data_catalog')
  assert(chatGptToolsSource.includes("case 'analysis'"), 'ChatGPT tool invocation text should handle analysis')
  assert(chatGptToolsSource.includes("case 'actions'"), 'ChatGPT tool invocation text should handle actions')
  assert(chatGptToolsSource.includes("case 'alerts'"), 'ChatGPT tool invocation text should handle alerts')
  assert(chatGptToolsSource.includes("case 'schedules'"), 'ChatGPT tool invocation text should handle schedules')
  assert(chatGptToolsSource.includes("case 'connectors'"), 'ChatGPT tool invocation text should handle connectors')
  assert(chatGptToolsSource.includes('Consultando CRM...'), 'ChatGPT crm invoking text missing')
  assert(chatGptToolsSource.includes('Preparando acao no ERP...'), 'ChatGPT erp_acoes invoking text missing')
  assert(chatGptToolsSource.includes('Lendo catalogo de dados...'), 'ChatGPT data_catalog invoking text missing')
  assert(chatGptToolsSource.includes('Dados de CRM carregados.'), 'ChatGPT crm invoked text missing')
  console.log('chatgpt tool metadata ok')

  const chatGptResourcesSource = await readFile(path.join(root, 'src/products/chatgpt-app/server/appResources.ts'), 'utf8')
  assert(chatGptResourcesSource.includes('frameDomains'), 'ChatGPT resource mapper should read frameDomains')
  assert(chatGptResourcesSource.includes('frame_domains'), 'ChatGPT widget CSP should expose frame_domains')
  console.log('chatgpt resource metadata ok')

  const componentPath = path.join(root, 'src/products/plugin/web/dist/component.js')
  const componentJs = await readFile(componentPath, 'utf8')
  assert(componentJs.includes('CognitoPlugin'), 'component missing Plugin runtime')
  assert(componentJs.includes('CognitoChatGptApp'), 'component missing ChatGPT alias')
  console.log('component runtime ok')

  console.log('Plugin smoke test passed')
}

main().catch((error) => {
  console.error(error?.stack || error?.message || String(error))
  process.exit(1)
})
