BEGIN;

SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';

-- Serializacao nao bloqueante evita validar agregados com snapshot anterior.
CREATE FUNCTION erp.travar_evolucao(p_tenant bigint) RETURNS void
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_periodo_empresa(p_tenant,false);
 IF NOT pg_try_advisory_xact_lock(172943,hashint8(p_tenant)) THEN
  RAISE EXCEPTION 'Operacao concorrente; repetir transacao inteira' USING ERRCODE='40001';
 END IF;
END $$;

CREATE FUNCTION erp.proteger_identidade_nova() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END);
 IF TG_OP='UPDATE' AND (OLD.id<>NEW.id OR OLD.tenant_id<>NEW.tenant_id) THEN
  RAISE EXCEPTION 'Identidade imutavel' USING ERRCODE='23514';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;

CREATE TABLE erp.entidades_contatos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL, nome text NOT NULL CHECK(btrim(nome)<>''),
 cargo text, email text, telefone text, whatsapp boolean NOT NULL DEFAULT false,
 finalidades text[] NOT NULL DEFAULT ARRAY['comercial']::text[],
 principais text[] NOT NULL DEFAULT '{}'::text[],
 ativo boolean NOT NULL DEFAULT true,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 atualizado_em timestamptz NOT NULL DEFAULT now(),
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 CHECK(cardinality(finalidades)>0 AND finalidades <@ ARRAY['comercial','financeiro','operacional']::text[]),
 CHECK(principais <@ finalidades AND (ativo OR cardinality(principais)=0)),
 CHECK(nullif(btrim(email),'') IS NOT NULL OR nullif(btrim(telefone),'') IS NOT NULL)
);
CREATE TABLE erp.entidades_enderecos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL, identificacao text NOT NULL CHECK(btrim(identificacao)<>''),
 logradouro text NOT NULL CHECK(btrim(logradouro)<>''), numero text, complemento text,
 bairro text, cidade text NOT NULL CHECK(btrim(cidade)<>''), uf text, cep text,
 pais text NOT NULL DEFAULT 'Brasil',
 finalidades text[] NOT NULL DEFAULT ARRAY['comercial']::text[],
 principais text[] NOT NULL DEFAULT '{}'::text[], ativo boolean NOT NULL DEFAULT true,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 atualizado_em timestamptz NOT NULL DEFAULT now(),
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 CHECK(cardinality(finalidades)>0 AND finalidades <@ ARRAY['comercial','cobranca','prestacao']::text[]),
 CHECK(principais <@ finalidades AND (ativo OR cardinality(principais)=0))
);
CREATE FUNCTION erp.validar_principais_entidade() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE conflito boolean;
BEGIN
 IF array_position(NEW.finalidades,NULL) IS NOT NULL OR array_position(NEW.principais,NULL) IS NOT NULL
  OR cardinality(NEW.finalidades)<>(SELECT count(DISTINCT x) FROM unnest(NEW.finalidades) x)
  OR cardinality(NEW.principais)<>(SELECT count(DISTINCT x) FROM unnest(NEW.principais) x) THEN
  RAISE EXCEPTION 'Finalidades invalidas' USING ERRCODE='23514';
 END IF;
 EXECUTE format('SELECT EXISTS(SELECT 1 FROM erp.%I WHERE tenant_id=$1 AND entidade_id=$2 AND id<>$3 AND ativo AND principais && $4)',TG_TABLE_NAME)
 INTO conflito USING NEW.tenant_id,NEW.entidade_id,NEW.id,NEW.principais;
 IF conflito THEN RAISE EXCEPTION 'Principal ja definido para finalidade' USING ERRCODE='23514'; END IF;
 NEW.atualizado_em:=now();
 RETURN NEW;
END $$;

CREATE TABLE erp.contratos_vendas_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,contrato_id,arquivo_id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.contratos_vendas_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.vendas_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 venda_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,venda_id,arquivo_id),
 FOREIGN KEY(tenant_id,venda_id) REFERENCES erp.vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.vendas_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.ordens_servico_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 ordem_servico_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,ordem_servico_id,arquivo_id),
 FOREIGN KEY(tenant_id,ordem_servico_id) REFERENCES erp.ordens_servico(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.ordens_servico_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.contas_receber_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 conta_receber_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,conta_receber_id,arquivo_id),
 FOREIGN KEY(tenant_id,conta_receber_id) REFERENCES erp.contas_receber(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.contas_receber_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.contas_receber_eventos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 conta_receber_id bigint NOT NULL, conta_receber_parcela_id bigint, pagamento_id bigint,
 evento text NOT NULL CHECK(btrim(evento)<>''), dados jsonb NOT NULL DEFAULT '{}',
 criado_em timestamptz NOT NULL DEFAULT now(), data_evento date NOT NULL DEFAULT current_date,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 motivo text, chave_operacao text,
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,conta_receber_id) REFERENCES erp.contas_receber(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_receber_parcela_id) REFERENCES erp.contas_receber_parcelas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,pagamento_id) REFERENCES erp.pagamentos(tenant_id,id) ON DELETE RESTRICT,
 CHECK(jsonb_typeof(dados)='object')
);
CREATE UNIQUE INDEX contas_receber_eventos_operacao_idx ON erp.contas_receber_eventos(tenant_id,conta_receber_id,chave_operacao,evento) WHERE chave_operacao IS NOT NULL;
CREATE INDEX contas_receber_eventos_titulo_idx ON erp.contas_receber_eventos(tenant_id,conta_receber_id,criado_em);
CREATE TRIGGER preservar_evento BEFORE UPDATE OR DELETE ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();
CREATE FUNCTION erp.validar_evento_receber() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF NEW.conta_receber_parcela_id IS NOT NULL AND NOT EXISTS(
 SELECT 1 FROM erp.contas_receber_parcelas WHERE tenant_id=NEW.tenant_id AND id=NEW.conta_receber_parcela_id AND conta_receber_id=NEW.conta_receber_id) THEN
 RAISE EXCEPTION 'Parcela nao pertence ao titulo' USING ERRCODE='23514'; END IF;
 IF NEW.pagamento_id IS NOT NULL AND (NEW.conta_receber_parcela_id IS NULL OR NOT EXISTS(
 SELECT 1 FROM erp.pagamentos WHERE tenant_id=NEW.tenant_id AND id=NEW.pagamento_id AND conta_receber_parcela_id=NEW.conta_receber_parcela_id)) THEN
 RAISE EXCEPTION 'Pagamento nao pertence a parcela' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER validar_evento BEFORE INSERT ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.validar_evento_receber();

CREATE TABLE erp.contratos_vendas_versoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, numero integer NOT NULL CHECK(numero>0),
 vigencia_inicio date NOT NULL, vigencia_fim date,
 status text NOT NULL DEFAULT 'rascunho' CHECK(status IN ('rascunho','efetivada')),
 periodicidade text NOT NULL CHECK(periodicidade IN ('semanal','quinzenal','mensal','bimestral','trimestral','semestral','anual')),
 dia_vencimento integer NOT NULL CHECK(dia_vencimento BETWEEN 1 AND 31),
 regra_vencimento text NOT NULL DEFAULT 'dia_fixo' CHECK(regra_vencimento IN ('dia_fixo','dias_apos_periodo')),
 dias_apos_periodo integer CHECK(dias_apos_periodo>=0),
 fim_mes text NOT NULL DEFAULT 'ultimo_dia' CHECK(fim_mes IN ('ultimo_dia','proximo_mes')),
 reajuste_indice text, reajuste_percentual numeric(9,4),
 categoria_id bigint, centro_custo_id bigint, conta_financeira_id bigint, metodo_pagamento_id bigint,
 motivo text NOT NULL CHECK(btrim(motivo)<>''), cliente_snapshot jsonb NOT NULL,
 criado_em timestamptz NOT NULL DEFAULT now(), efetivada_em timestamptz,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,contrato_id,numero), UNIQUE(tenant_id,contrato_id,id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,categoria_id) REFERENCES erp.categorias(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,centro_custo_id) REFERENCES erp.centros_custo(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_financeira_id) REFERENCES erp.contas_financeiras(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,metodo_pagamento_id) REFERENCES erp.metodos_pagamento(tenant_id,id) ON DELETE RESTRICT,
 CHECK(vigencia_fim IS NULL OR vigencia_fim>=vigencia_inicio),
 CHECK(jsonb_typeof(cliente_snapshot)='object'),
 CHECK((status='efetivada')=(efetivada_em IS NOT NULL)),
 CHECK((regra_vencimento='dias_apos_periodo')=(dias_apos_periodo IS NOT NULL))
);
ALTER TABLE erp.contratos_vendas_itens ADD COLUMN contrato_versao_id bigint;
ALTER TABLE erp.contratos_vendas_itens ADD COLUMN item_logico text;
-- Snapshot observado, sem inventar historico de alteracoes passadas.
INSERT INTO erp.contratos_vendas_versoes(tenant_id,contrato_id,numero,vigencia_inicio,vigencia_fim,periodicidade,dia_vencimento,
 reajuste_indice,reajuste_percentual,categoria_id,centro_custo_id,conta_financeira_id,metodo_pagamento_id,motivo,cliente_snapshot,criado_por)
 SELECT c.tenant_id,c.id,1,c.data_inicio,c.data_fim,c.periodicidade,c.dia_vencimento,c.reajuste_indice,c.reajuste_percentual,
 c.categoria_id,c.centro_custo_id,c.conta_financeira_id,c.metodo_pagamento_id,'Estado inicial observado na migracao',
 jsonb_build_object('nome',e.nome,'documento',e.documento,'email',e.email,'logradouro',e.logradouro,'numero',e.numero,'cidade',e.cidade,'uf',e.uf),c.criado_por
 FROM erp.contratos_vendas c JOIN erp.entidades e ON e.tenant_id=c.tenant_id AND e.id=c.cliente_id;
UPDATE erp.contratos_vendas_itens i SET contrato_versao_id=v.id,item_logico=i.id::text FROM erp.contratos_vendas_versoes v WHERE v.tenant_id=i.tenant_id AND v.contrato_id=i.contrato_id;
ALTER TABLE erp.contratos_vendas_itens ALTER COLUMN contrato_versao_id SET NOT NULL;
ALTER TABLE erp.contratos_vendas_itens ALTER COLUMN item_logico SET NOT NULL;
ALTER TABLE erp.contratos_vendas_itens ADD CONSTRAINT contrato_item_versao_fk FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX contrato_item_logico_idx ON erp.contratos_vendas_itens(tenant_id,contrato_versao_id,item_logico);
CREATE TABLE erp.contratos_vendas_eventos(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, contrato_versao_id bigint,
 evento text NOT NULL CHECK(btrim(evento)<>''), motivo text, dados jsonb NOT NULL DEFAULT '{}',
 criado_em timestamptz NOT NULL DEFAULT now(), data_efeito date NOT NULL DEFAULT current_date,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT,
 CHECK(jsonb_typeof(dados)='object')
);
CREATE INDEX contratos_eventos_data_idx ON erp.contratos_vendas_eventos(tenant_id,contrato_id,criado_em);
CREATE TRIGGER preservar_evento BEFORE UPDATE OR DELETE ON erp.contratos_vendas_eventos FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN contrato_versao_id bigint;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN periodo_inicio date;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN periodo_fim date;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN legado_sem_versao boolean NOT NULL DEFAULT false;
UPDATE erp.contratos_vendas_geracoes SET legado_sem_versao=true;
ALTER TABLE erp.contratos_vendas_geracoes ADD CONSTRAINT geracao_versao_fk FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT;
ALTER TABLE erp.contratos_vendas_geracoes ADD CONSTRAINT geracao_periodo_chk CHECK(
 (legado_sem_versao AND contrato_versao_id IS NULL) OR (NOT legado_sem_versao AND contrato_versao_id IS NOT NULL AND periodo_inicio IS NOT NULL AND periodo_fim>=periodo_inicio));
DROP INDEX erp.contratos_vendas_geracoes_competencia_idx;
CREATE UNIQUE INDEX contratos_geracao_ciclo_idx ON erp.contratos_vendas_geracoes(tenant_id,contrato_id,periodo_inicio) WHERE NOT legado_sem_versao;
CREATE UNIQUE INDEX contratos_geracao_legado_idx ON erp.contratos_vendas_geracoes(tenant_id,contrato_id,competencia) WHERE legado_sem_versao;
CREATE INDEX contratos_geracao_venda_idx ON erp.contratos_vendas_geracoes(tenant_id,venda_id);
CREATE TABLE erp.contratos_vendas_geracoes_tentativas(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 geracao_id bigint NOT NULL, numero integer NOT NULL CHECK(numero>0),
 inicio timestamptz NOT NULL DEFAULT now(), fim timestamptz,
 status text NOT NULL DEFAULT 'executando' CHECK(status IN ('executando','sucesso','falha','abandonada')),
 erro text, execucao_id text NOT NULL CHECK(btrim(execucao_id)<>''),
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,geracao_id,numero), UNIQUE(tenant_id,execucao_id),
 FOREIGN KEY(tenant_id,geracao_id) REFERENCES erp.contratos_vendas_geracoes(tenant_id,id) ON DELETE RESTRICT,
 CHECK((status='executando')=(fim IS NULL)), CHECK(fim IS NULL OR fim>=inicio),
 CHECK(erro IS NULL OR length(erro)<=2000)
);
CREATE UNIQUE INDEX contrato_tentativa_ativa_idx ON erp.contratos_vendas_geracoes_tentativas(tenant_id,geracao_id) WHERE status='executando';

CREATE FUNCTION erp.validar_contrato_versionado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE v erp.contratos_vendas_versoes; g erp.contratos_vendas_geracoes; cid bigint; tid bigint;
BEGIN
 tid:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 PERFORM erp.travar_evolucao(tid);
 IF TG_TABLE_NAME='contratos_vendas_versoes' THEN
  IF TG_OP='DELETE' AND OLD.status='efetivada' THEN RAISE EXCEPTION 'Versao efetivada imutavel' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND OLD.status='efetivada' THEN
   IF (to_jsonb(OLD)-'vigencia_fim') IS DISTINCT FROM (to_jsonb(NEW)-'vigencia_fim')
    OR NEW.vigencia_fim IS NULL OR (OLD.vigencia_fim IS NOT NULL AND NEW.vigencia_fim>OLD.vigencia_fim)
    OR EXISTS(SELECT 1 FROM erp.contratos_vendas_geracoes WHERE tenant_id=tid AND contrato_versao_id=OLD.id AND periodo_fim>NEW.vigencia_fim) THEN
    RAISE EXCEPTION 'Condicoes utilizadas imutaveis' USING ERRCODE='23514';
   END IF;
  END IF;
  IF TG_OP<>'DELETE' AND NEW.status='efetivada' THEN
   IF NOT EXISTS(SELECT 1 FROM erp.contratos_vendas WHERE tenant_id=tid AND id=NEW.contrato_id AND data_inicio<=NEW.vigencia_inicio AND coalesce(data_fim,'infinity'::date)>=coalesce(NEW.vigencia_fim,'infinity'::date)) THEN
    RAISE EXCEPTION 'Vigencia fora do contrato' USING ERRCODE='23514'; END IF;
   IF NOT EXISTS(SELECT 1 FROM erp.contratos_vendas_itens WHERE tenant_id=tid AND contrato_versao_id=NEW.id) THEN
    RAISE EXCEPTION 'Versao exige itens antes de efetivar' USING ERRCODE='23514'; END IF;
   IF EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND contrato_id=NEW.contrato_id AND id<>NEW.id AND status='efetivada'
     AND vigencia_inicio<=coalesce(NEW.vigencia_fim,'infinity'::date) AND coalesce(vigencia_fim,'infinity'::date)>=NEW.vigencia_inicio) THEN
    RAISE EXCEPTION 'Vigencias sobrepostas' USING ERRCODE='23514'; END IF;
  END IF;
 ELSIF TG_TABLE_NAME='contratos_vendas_itens' THEN
  IF TG_OP<>'INSERT' THEN
   SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=OLD.contrato_versao_id;
   IF v.status='efetivada' THEN RAISE EXCEPTION 'Itens efetivados imutaveis' USING ERRCODE='23514'; END IF;
  END IF;
  IF TG_OP<>'DELETE' THEN
   SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=NEW.contrato_versao_id;
   IF v.status='efetivada' THEN RAISE EXCEPTION 'Itens efetivados imutaveis' USING ERRCODE='23514'; END IF;
   IF NEW.total<>round(NEW.quantidade*NEW.valor_unitario,2)-NEW.desconto THEN
    RAISE EXCEPTION 'Total do item inconsistente' USING ERRCODE='23514'; END IF;
  END IF;
 ELSIF TG_TABLE_NAME='contratos_vendas_geracoes' THEN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Preserve geracoes' USING ERRCODE='23514'; END IF;
  IF TG_OP='INSERT' AND NEW.legado_sem_versao THEN RAISE EXCEPTION 'Marcador reservado ao historico migrado' USING ERRCODE='23514'; END IF;
  IF TG_OP='INSERT' AND NOT EXISTS(SELECT 1 FROM erp.contratos_vendas WHERE tenant_id=tid AND id=NEW.contrato_id AND status='ativo' AND excluido_em IS NULL) THEN
   RAISE EXCEPTION 'Geracao exige contrato ativo' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND (OLD.legado_sem_versao OR
   (to_jsonb(OLD)-ARRAY['status','erro','processado_em','venda_id']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['status','erro','processado_em','venda_id'])
   OR (OLD.venda_id IS NOT NULL AND OLD.venda_id IS DISTINCT FROM NEW.venda_id)
   OR OLD.status IN ('concluida','ignorada')) THEN
   RAISE EXCEPTION 'Identidade e resultado da geracao preservados' USING ERRCODE='23514'; END IF;
  SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=NEW.contrato_versao_id;
  IF v.status IS DISTINCT FROM 'efetivada' OR NEW.periodo_inicio<v.vigencia_inicio OR NEW.periodo_fim>coalesce(v.vigencia_fim,'infinity'::date)
   OR EXISTS(SELECT 1 FROM erp.contratos_vendas_geracoes x WHERE x.tenant_id=tid AND x.contrato_id=NEW.contrato_id AND x.id<>NEW.id
    AND ((NOT x.legado_sem_versao AND x.periodo_inicio<=NEW.periodo_fim AND x.periodo_fim>=NEW.periodo_inicio)
      OR (x.legado_sem_versao AND date_trunc('month',x.competencia)=date_trunc('month',NEW.competencia)))) THEN
   RAISE EXCEPTION 'Ciclo ou versao invalida; historico legado exige revisao explicita' USING ERRCODE='23514'; END IF;
  IF NEW.periodo_fim<>(NEW.periodo_inicio+CASE v.periodicidade WHEN 'semanal' THEN interval '7 days' WHEN 'quinzenal' THEN interval '15 days' WHEN 'mensal' THEN interval '1 month' WHEN 'bimestral' THEN interval '2 months' WHEN 'trimestral' THEN interval '3 months' WHEN 'semestral' THEN interval '6 months' ELSE interval '1 year' END-interval '1 day')::date THEN
   RAISE EXCEPTION 'Duracao do ciclo incompativel com periodicidade' USING ERRCODE='23514'; END IF;
  IF (NEW.status='concluida') IS DISTINCT FROM (NEW.venda_id IS NOT NULL) THEN RAISE EXCEPTION 'Resultado da geracao inconsistente' USING ERRCODE='23514'; END IF;
  IF NEW.venda_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM erp.vendas s JOIN erp.contratos_vendas c ON c.tenant_id=s.tenant_id AND c.cliente_id=s.cliente_id WHERE c.tenant_id=tid AND c.id=NEW.contrato_id AND s.id=NEW.venda_id) THEN
   RAISE EXCEPTION 'Venda pertence a outro cliente' USING ERRCODE='23514'; END IF;
 ELSE
  IF TG_OP='DELETE' OR (TG_OP='UPDATE' AND (OLD.status<>'executando'
    OR (to_jsonb(OLD)-ARRAY['fim','status','erro']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['fim','status','erro']))) THEN
   RAISE EXCEPTION 'Tentativa encerrada imutavel' USING ERRCODE='23514'; END IF;
  SELECT * INTO g FROM erp.contratos_vendas_geracoes WHERE tenant_id=tid AND id=NEW.geracao_id;
  IF (NEW.status='sucesso' AND g.status<>'concluida') OR (NEW.status='executando' AND g.status<>'processando') THEN
   RAISE EXCEPTION 'Tentativa incompativel com geracao' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['contratos_vendas_versoes','contratos_vendas_itens','contratos_vendas_geracoes','contratos_vendas_geracoes_tentativas'] LOOP
 EXECUTE format('CREATE TRIGGER validar_contrato_versionado BEFORE INSERT OR UPDATE OR DELETE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.validar_contrato_versionado()',t);
 END LOOP;
END $$;
-- Eventos gerados pelo banco compartilham a transacao da alteracao.
CREATE FUNCTION erp.registrar_evolucao_documento() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE j jsonb; antes jsonb; tid bigint; doc bigint; parcela bigint; pagamento bigint; lado text; autor bigint; ev text;
BEGIN
 j:=CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 IF TG_OP<>'INSERT' THEN antes:=to_jsonb(OLD); END IF;
 tid:=(j->>'tenant_id')::bigint;
 autor:=nullif(current_setting('app.erp_user_id',true),'')::bigint;
 ev:=TG_TABLE_NAME||'.'||lower(TG_OP);
 IF TG_TABLE_NAME='contratos_vendas' OR TG_TABLE_NAME='contratos_vendas_versoes' THEN
  doc:=CASE WHEN TG_TABLE_NAME='contratos_vendas' THEN (j->>'id')::bigint ELSE (j->>'contrato_id')::bigint END;
  INSERT INTO erp.contratos_vendas_eventos(tenant_id,contrato_id,contrato_versao_id,evento,criado_por,dados)
   VALUES(tid,doc,CASE WHEN TG_TABLE_NAME='contratos_vendas_versoes' THEN (j->>'id')::bigint END,ev,autor,jsonb_build_object('antes',antes,'depois',j));
 ELSE
  IF TG_TABLE_NAME='pagamentos' THEN
   lado:=j->>'tipo'; pagamento:=(j->>'id')::bigint; parcela:=(j->>('conta_'||lado||'_parcela_id'))::bigint;
   EXECUTE format('SELECT conta_%s_id FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND id=$2',lado,lado) INTO doc USING tid,parcela;
  ELSE
   lado:=CASE WHEN TG_TABLE_NAME LIKE 'contas_receber%' THEN 'receber' ELSE 'pagar' END;
   IF TG_TABLE_NAME LIKE '%parcelas' THEN doc:=(j->>('conta_'||lado||'_id'))::bigint; parcela:=(j->>'id')::bigint;
   ELSE doc:=(j->>'id')::bigint; END IF;
  END IF;
  IF lado='receber' THEN
   INSERT INTO erp.contas_receber_eventos(tenant_id,conta_receber_id,conta_receber_parcela_id,pagamento_id,evento,criado_por,dados)
   VALUES(tid,doc,parcela,pagamento,ev,autor,jsonb_build_object('antes',antes,'depois',j));
  ELSE
   INSERT INTO erp.contas_pagar_eventos(tenant_id,conta_pagar_id,evento,criado_por,dados)
   VALUES(tid,doc,ev,autor,jsonb_build_object('antes',antes,'depois',j));
  END IF;
 END IF;
 RETURN NULL;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['contas_receber','contas_receber_parcelas','contas_pagar','contas_pagar_parcelas','pagamentos','contratos_vendas','contratos_vendas_versoes'] LOOP
 EXECUTE format('CREATE TRIGGER registrar_evolucao AFTER INSERT OR UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.registrar_evolucao_documento()',t);
 END LOOP;
END $$;
-- Dados antigos sao copiados apenas quando suficientes para formar um registro real.
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,email,telefone,criado_por)
 SELECT tenant_id,id,nome,nullif(btrim(email),''),coalesce(nullif(btrim(telefone),''),nullif(btrim(celular),'')),criado_por FROM erp.entidades
 WHERE nullif(btrim(email),'') IS NOT NULL OR coalesce(nullif(btrim(telefone),''),nullif(btrim(celular),'')) IS NOT NULL;
INSERT INTO erp.entidades_enderecos(tenant_id,entidade_id,identificacao,logradouro,numero,complemento,bairro,cidade,uf,cep,pais,criado_por)
 SELECT tenant_id,id,'Endereco existente',logradouro,numero,complemento,bairro,cidade,uf,cep,pais,criado_por FROM erp.entidades
 WHERE nullif(btrim(logradouro),'') IS NOT NULL AND nullif(btrim(cidade),'') IS NOT NULL;

CREATE FUNCTION erp.preservar_arquivo_referenciado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(OLD.tenant_id);
 IF EXISTS(SELECT 1 FROM erp.contratos_vendas_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.vendas_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.ordens_servico_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.contas_receber_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id) THEN
  IF TG_OP='DELETE' OR (to_jsonb(OLD)-ARRAY['atualizado_em','atualizado_por']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['atualizado_em','atualizado_por']) THEN
  RAISE EXCEPTION 'Arquivo referenciado preservado' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
CREATE TRIGGER preservar_arquivo_referenciado BEFORE UPDATE OR DELETE ON erp.arquivos FOR EACH ROW EXECUTE FUNCTION erp.preservar_arquivo_referenciado();
CREATE FUNCTION erp.validar_arquivo_anexo() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM erp.arquivos WHERE tenant_id=NEW.tenant_id AND id=NEW.arquivo_id AND excluido_em IS NULL) THEN
 RAISE EXCEPTION 'Arquivo indisponivel' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION erp.snapshot_documento_cliente() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE e erp.entidades;
BEGIN
 IF TG_OP='INSERT' THEN
  SELECT * INTO e FROM erp.entidades WHERE tenant_id=NEW.tenant_id AND id=NEW.cliente_id;
  NEW.cliente_snapshot:=jsonb_build_object('nome',e.nome,'documento',e.documento,'email',e.email,'logradouro',e.logradouro,'numero',e.numero,'cidade',e.cidade,'uf',e.uf,'origem','cadastro_na_criacao');
 ELSIF OLD.cliente_snapshot IS DISTINCT FROM NEW.cliente_snapshot THEN
  RAISE EXCEPTION 'Snapshot documental preservado' USING ERRCODE='23514';
 ELSIF OLD.cliente_id IS DISTINCT FROM NEW.cliente_id THEN
  RAISE EXCEPTION 'Troca de cliente exige novo documento para preservar identidade' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['vendas','ordens_servico','contratos_vendas'] LOOP
 -- Nao atualizar documentos antigos: nao ha evidencia para reconstruir seu snapshot.
 EXECUTE format('ALTER TABLE erp.%I ADD COLUMN cliente_snapshot jsonb NOT NULL DEFAULT ''{"origem":"historico_sem_snapshot"}''::jsonb CHECK(jsonb_typeof(cliente_snapshot)=''object'')',t);
 EXECUTE format('CREATE TRIGGER snapshot_documento_cliente BEFORE INSERT OR UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.snapshot_documento_cliente()',t);
 END LOOP;
END $$;
CREATE FUNCTION erp.preservar_contato_legado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF pg_trigger_depth()>1 THEN RETURN NEW; END IF;
 IF ROW(OLD.email,OLD.telefone,OLD.celular,OLD.contato_cobranca_emails,OLD.contato_cobranca_whatsapp,OLD.logradouro,OLD.numero,OLD.complemento,OLD.bairro,OLD.cidade,OLD.uf,OLD.cep,OLD.pais)
 IS DISTINCT FROM ROW(NEW.email,NEW.telefone,NEW.celular,NEW.contato_cobranca_emails,NEW.contato_cobranca_whatsapp,NEW.logradouro,NEW.numero,NEW.complemento,NEW.bairro,NEW.cidade,NEW.uf,NEW.cep,NEW.pais) THEN
 RAISE EXCEPTION 'Atualize contatos e enderecos nas estruturas normalizadas; campos legados preservados' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER preservar_contato_legado BEFORE UPDATE ON erp.entidades FOR EACH ROW EXECUTE FUNCTION erp.preservar_contato_legado();

ALTER TABLE erp.entidades_contatos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.entidades_contatos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.entidades_contatos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.entidades_contatos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.entidades_contatos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE INDEX entidades_contatos_entidade_idx ON erp.entidades_contatos(tenant_id,entidade_id);
CREATE TRIGGER validar_principais BEFORE INSERT OR UPDATE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.validar_principais_entidade();

ALTER TABLE erp.entidades_enderecos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.entidades_enderecos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.entidades_enderecos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.entidades_enderecos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.entidades_enderecos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE INDEX entidades_enderecos_entidade_idx ON erp.entidades_enderecos(tenant_id,entidade_id);
CREATE TRIGGER validar_principais BEFORE INSERT OR UPDATE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.validar_principais_entidade();

ALTER TABLE erp.contratos_vendas_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contratos_vendas_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.contratos_vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.vendas_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.vendas_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.vendas_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.vendas_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.vendas_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.ordens_servico_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.ordens_servico_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.ordens_servico_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.ordens_servico_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.ordens_servico_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.ordens_servico_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.ordens_servico_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.contas_receber_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contas_receber_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contas_receber_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contas_receber_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contas_receber_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contas_receber_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.contas_receber_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.contas_receber_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contas_receber_eventos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contas_receber_eventos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contas_receber_eventos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contas_receber_eventos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_versoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_versoes FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.contratos_vendas_versoes TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_versoes_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_versoes FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_versoes FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_eventos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contratos_vendas_eventos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_eventos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_eventos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_eventos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_geracoes_tentativas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_geracoes_tentativas FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.contratos_vendas_geracoes_tentativas TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_geracoes_tentativas_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_geracoes_tentativas FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_geracoes_tentativas FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

REVOKE ALL ON FUNCTION erp.travar_evolucao(bigint),erp.proteger_identidade_nova(),erp.validar_principais_entidade(),
 erp.validar_evento_receber(),erp.validar_contrato_versionado(),erp.registrar_evolucao_documento(),
 erp.preservar_arquivo_referenciado(),erp.validar_arquivo_anexo(),erp.snapshot_documento_cliente(),erp.preservar_contato_legado() FROM PUBLIC;
UPDATE erp.entidades_contatos c SET finalidades=ARRAY['comercial','financeiro']::text[]
 FROM erp.entidades e WHERE e.tenant_id=c.tenant_id AND e.id=c.entidade_id AND c.email=ANY(e.contato_cobranca_emails);
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,email,finalidades,criado_por)
 SELECT DISTINCT e.tenant_id,e.id,e.nome,btrim(endereco),ARRAY['financeiro']::text[],e.criado_por
 FROM erp.entidades e CROSS JOIN LATERAL unnest(e.contato_cobranca_emails) endereco
 WHERE nullif(btrim(endereco),'') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM erp.entidades_contatos c WHERE c.tenant_id=e.tenant_id AND c.entidade_id=e.id AND c.email=btrim(endereco));
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,telefone,whatsapp,finalidades,criado_por)
 SELECT tenant_id,id,nome,contato_cobranca_whatsapp,true,ARRAY['financeiro']::text[],criado_por FROM erp.entidades WHERE nullif(btrim(contato_cobranca_whatsapp),'') IS NOT NULL;
CREATE FUNCTION erp.refletir_cadastro_normalizado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t bigint; e bigint; c erp.entidades_contatos; a erp.entidades_enderecos;
BEGIN
 t:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 e:=CASE WHEN TG_OP='DELETE' THEN OLD.entidade_id ELSE NEW.entidade_id END;
 IF TG_OP='UPDATE' AND OLD.entidade_id<>NEW.entidade_id THEN RAISE EXCEPTION 'Nao mover contato ou endereco entre entidades' USING ERRCODE='23514'; END IF;
 IF TG_TABLE_NAME='entidades_contatos' THEN
  SELECT * INTO c FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'comercial'=ANY(finalidades)
   ORDER BY ('comercial'=ANY(principais)) DESC,id LIMIT 1;
  UPDATE erp.entidades SET email=c.email,telefone=c.telefone,celular=NULL,
   contato_cobranca_emails=ARRAY(SELECT DISTINCT email FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'financeiro'=ANY(finalidades) AND nullif(btrim(email),'') IS NOT NULL),
   contato_cobranca_whatsapp=(SELECT telefone FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND whatsapp AND 'financeiro'=ANY(finalidades) ORDER BY ('financeiro'=ANY(principais)) DESC,id LIMIT 1)
   WHERE tenant_id=t AND id=e;
 ELSE
  SELECT * INTO a FROM erp.entidades_enderecos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'comercial'=ANY(finalidades)
   ORDER BY ('comercial'=ANY(principais)) DESC,id LIMIT 1;
  UPDATE erp.entidades SET logradouro=a.logradouro,numero=a.numero,complemento=a.complemento,bairro=a.bairro,cidade=a.cidade,uf=a.uf,cep=a.cep,pais=coalesce(a.pais,'Brasil') WHERE tenant_id=t AND id=e;
 END IF;
 RETURN NULL;
END $$;
CREATE TRIGGER refletir_cadastro AFTER INSERT OR UPDATE OR DELETE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.refletir_cadastro_normalizado();
CREATE TRIGGER refletir_cadastro AFTER INSERT OR UPDATE OR DELETE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.refletir_cadastro_normalizado();
REVOKE ALL ON FUNCTION erp.refletir_cadastro_normalizado() FROM PUBLIC;
CREATE FUNCTION erp.validar_cabecalho_contrato() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(NEW.tenant_id);
 IF NEW.status='ativo' AND NOT EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=NEW.tenant_id AND contrato_id=NEW.id AND status='efetivada') THEN
  RAISE EXCEPTION 'Contrato ativo exige versao efetivada' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' AND EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=OLD.tenant_id AND contrato_id=OLD.id) AND
 ROW(OLD.data_inicio,OLD.data_fim,OLD.periodicidade,OLD.dia_vencimento,OLD.reajuste_indice,OLD.reajuste_percentual,OLD.categoria_id,OLD.centro_custo_id,OLD.conta_financeira_id,OLD.metodo_pagamento_id)
 IS DISTINCT FROM ROW(NEW.data_inicio,NEW.data_fim,NEW.periodicidade,NEW.dia_vencimento,NEW.reajuste_indice,NEW.reajuste_percentual,NEW.categoria_id,NEW.centro_custo_id,NEW.conta_financeira_id,NEW.metodo_pagamento_id) THEN
 RAISE EXCEPTION 'Condicoes comerciais devem ser alteradas por nova versao' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER validar_cabecalho_contrato BEFORE INSERT OR UPDATE ON erp.contratos_vendas FOR EACH ROW EXECUTE FUNCTION erp.validar_cabecalho_contrato();
REVOKE ALL ON FUNCTION erp.validar_cabecalho_contrato() FROM PUBLIC;


SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';

CREATE TABLE erp.adiantamentos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL,
 lado text NOT NULL CHECK(lado IN ('receber','pagar')),
 tipo text NOT NULL CHECK(tipo IN ('constituicao','devolucao','reversao')),
 adiantamento_id bigint, reversao_de_id bigint,
 conta_financeira_id bigint NOT NULL, metodo_pagamento_id bigint,
 data_movimento date NOT NULL, data_credito date,
 valor numeric(18,2) NOT NULL CHECK(valor>0),
 motivo text NOT NULL CHECK(btrim(motivo)<>''),
 chave_idempotencia text NOT NULL CHECK(btrim(chave_idempotencia)<>''),
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,chave_idempotencia), UNIQUE(tenant_id,reversao_de_id),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,adiantamento_id) REFERENCES erp.adiantamentos(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,reversao_de_id) REFERENCES erp.adiantamentos(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_financeira_id) REFERENCES erp.contas_financeiras(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,metodo_pagamento_id) REFERENCES erp.metodos_pagamento(tenant_id,id) ON DELETE RESTRICT,
 CHECK((tipo='constituicao' AND adiantamento_id IS NULL AND reversao_de_id IS NULL)
  OR(tipo='devolucao' AND adiantamento_id IS NOT NULL AND reversao_de_id IS NULL)
  OR(tipo='reversao' AND adiantamento_id IS NOT NULL AND reversao_de_id IS NOT NULL)),
 CHECK(id IS DISTINCT FROM adiantamento_id AND id IS DISTINCT FROM reversao_de_id)
);
CREATE INDEX adiantamento_entidade_idx ON erp.adiantamentos(tenant_id,entidade_id,data_movimento);
CREATE INDEX adiantamento_origem_idx ON erp.adiantamentos(tenant_id,adiantamento_id);
CREATE TABLE erp.adiantamentos_aplicacoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 adiantamento_id bigint NOT NULL,
 conta_receber_parcela_id bigint, conta_pagar_parcela_id bigint,
 valor numeric(18,2) NOT NULL CHECK(valor>0), data_aplicacao date NOT NULL,
 reversao_de_id bigint, motivo text NOT NULL CHECK(btrim(motivo)<>''),
 chave_idempotencia text NOT NULL CHECK(btrim(chave_idempotencia)<>''),
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,chave_idempotencia), UNIQUE(tenant_id,reversao_de_id),
 FOREIGN KEY(tenant_id,adiantamento_id) REFERENCES erp.adiantamentos(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,reversao_de_id) REFERENCES erp.adiantamentos_aplicacoes(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_receber_parcela_id) REFERENCES erp.contas_receber_parcelas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_pagar_parcela_id) REFERENCES erp.contas_pagar_parcelas(tenant_id,id) ON DELETE RESTRICT,
 CHECK(num_nonnulls(conta_receber_parcela_id,conta_pagar_parcela_id)=1),
 CHECK(id IS DISTINCT FROM reversao_de_id)
);
CREATE INDEX aplicacao_adiantamento_idx ON erp.adiantamentos_aplicacoes(tenant_id,adiantamento_id);
CREATE INDEX aplicacao_receber_idx ON erp.adiantamentos_aplicacoes(tenant_id,conta_receber_parcela_id);
CREATE INDEX aplicacao_pagar_idx ON erp.adiantamentos_aplicacoes(tenant_id,conta_pagar_parcela_id);

CREATE TABLE erp.renegociacoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL,
 lado text NOT NULL CHECK(lado IN ('receber','pagar')),
 numero text NOT NULL CHECK(btrim(numero)<>''),
 data_acordo date NOT NULL,
 status text NOT NULL DEFAULT 'rascunho' CHECK(status IN ('rascunho','efetivada','revertida')),
 desconto numeric(18,2) NOT NULL DEFAULT 0 CHECK(desconto>=0),
 encargos numeric(18,2) NOT NULL DEFAULT 0 CHECK(encargos>=0),
 categoria_ajuste_id bigint,
 motivo text NOT NULL CHECK(btrim(motivo)<>''),
 condicoes text NOT NULL,
 efetivada_em timestamptz, revertida_em timestamptz, motivo_reversao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 efetivada_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 revertida_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 chave_idempotencia text NOT NULL CHECK(btrim(chave_idempotencia)<>''),
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,numero), UNIQUE(tenant_id,chave_idempotencia),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,categoria_ajuste_id) REFERENCES erp.categorias(tenant_id,id) ON DELETE RESTRICT,
 CHECK((status='rascunho' AND efetivada_em IS NULL AND revertida_em IS NULL)
 OR(status='efetivada' AND efetivada_em IS NOT NULL AND revertida_em IS NULL)
 OR(status='revertida' AND efetivada_em IS NOT NULL AND revertida_em>=efetivada_em AND nullif(btrim(motivo_reversao),'') IS NOT NULL)),
 CHECK((desconto=0 AND encargos=0) OR categoria_ajuste_id IS NOT NULL)
);
CREATE TABLE erp.renegociacoes_parcelas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 renegociacao_id bigint NOT NULL,
 papel text NOT NULL CHECK(papel IN ('origem','destino')),
 conta_receber_parcela_id bigint, conta_pagar_parcela_id bigint,
 valor numeric(18,2) NOT NULL CHECK(valor>0), ordem integer NOT NULL CHECK(ordem>0),
 criado_em timestamptz NOT NULL DEFAULT now(),
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,renegociacao_id,papel,ordem),
 FOREIGN KEY(tenant_id,renegociacao_id) REFERENCES erp.renegociacoes(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_receber_parcela_id) REFERENCES erp.contas_receber_parcelas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_pagar_parcela_id) REFERENCES erp.contas_pagar_parcelas(tenant_id,id) ON DELETE RESTRICT,
 CHECK(num_nonnulls(conta_receber_parcela_id,conta_pagar_parcela_id)=1)
);
CREATE UNIQUE INDEX renegociacao_receber_parcela_idx ON erp.renegociacoes_parcelas(tenant_id,renegociacao_id,conta_receber_parcela_id);
CREATE UNIQUE INDEX renegociacao_pagar_parcela_idx ON erp.renegociacoes_parcelas(tenant_id,renegociacao_id,conta_pagar_parcela_id);
CREATE INDEX renegociacao_receber_busca_idx ON erp.renegociacoes_parcelas(tenant_id,conta_receber_parcela_id);
CREATE INDEX renegociacao_pagar_busca_idx ON erp.renegociacoes_parcelas(tenant_id,conta_pagar_parcela_id);

-- valor do pagamento e principal liquidado; encargos/desconto/taxa explicam caixa.
ALTER TABLE erp.pagamentos ADD CONSTRAINT pagamento_caixa_formula_chk CHECK(
 valor>0 AND desconto<=valor+juros+multa
 AND valor_liquido=valor+juros+multa-desconto+CASE WHEN tipo='pagar' THEN taxa ELSE -taxa END);
DROP INDEX erp.pagamentos_chave_idempotencia_unica_idx;
CREATE UNIQUE INDEX pagamentos_chave_idempotencia_unica_idx ON erp.pagamentos(tenant_id,chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
CREATE UNIQUE INDEX pagamento_reversao_unica_idx ON erp.pagamentos(tenant_id,estorno_de_pagamento_id) WHERE estorno_de_pagamento_id IS NOT NULL;
CREATE INDEX pagamentos_receber_parcela_idx ON erp.pagamentos(tenant_id,conta_receber_parcela_id);
CREATE INDEX pagamentos_pagar_parcela_idx ON erp.pagamentos(tenant_id,conta_pagar_parcela_id);
ALTER TABLE erp.contas_receber ADD COLUMN chave_idempotencia text;
CREATE UNIQUE INDEX receber_idempotencia_idx ON erp.contas_receber(tenant_id,chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
ALTER TABLE erp.transferencias_financeiras ADD COLUMN IF NOT EXISTS chave_idempotencia text;
CREATE UNIQUE INDEX transferencia_idempotencia_idx ON erp.transferencias_financeiras(tenant_id,chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
DO $$ DECLARE t text; c record; BEGIN
 FOREACH t IN ARRAY ARRAY['contas_receber','contas_pagar','contas_receber_parcelas','contas_pagar_parcelas'] LOOP
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid=('erp.'||t)::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE 'CHECK ((status =%' LOOP
 EXECUTE format('ALTER TABLE erp.%I DROP CONSTRAINT %I',t,c.conname);
 END LOOP;
 EXECUTE format('ALTER TABLE erp.%I ADD CONSTRAINT %I CHECK(status IN (''aberto'',''parcial'',''pago'',''cancelado'',''vencido'',''renegociado''))',t,t||'_status_chk');
 END LOOP;
END $$;
ALTER TABLE erp.conciliacoes_bancarias_itens ADD COLUMN adiantamento_id bigint;
ALTER TABLE erp.conciliacoes_bancarias_itens ADD CONSTRAINT conciliacao_adiantamento_fk FOREIGN KEY(tenant_id,adiantamento_id) REFERENCES erp.adiantamentos(tenant_id,id) ON DELETE RESTRICT;
ALTER TABLE erp.conciliacoes_bancarias_itens DROP CONSTRAINT conciliacoes_bancarias_itens_origem_chk;
ALTER TABLE erp.conciliacoes_bancarias_itens ADD CONSTRAINT conciliacoes_bancarias_itens_origem_chk CHECK(num_nonnulls(pagamento_id,transferencia_financeira_id,adiantamento_id)=1);
DROP INDEX erp.conciliacoes_bancarias_itens_transacao_ativa_idx;
CREATE INDEX conciliacoes_transacao_ativa_idx ON erp.conciliacoes_bancarias_itens(tenant_id,transacao_bancaria_id) WHERE desfeito_em IS NULL;
CREATE UNIQUE INDEX conciliacoes_pagamento_par_idx ON erp.conciliacoes_bancarias_itens(tenant_id,transacao_bancaria_id,pagamento_id) WHERE desfeito_em IS NULL;
CREATE UNIQUE INDEX conciliacoes_transferencia_par_idx ON erp.conciliacoes_bancarias_itens(tenant_id,transacao_bancaria_id,transferencia_financeira_id) WHERE desfeito_em IS NULL;

CREATE UNIQUE INDEX conciliacoes_adiantamento_par_idx ON erp.conciliacoes_bancarias_itens(tenant_id,transacao_bancaria_id,adiantamento_id) WHERE desfeito_em IS NULL;
ALTER TABLE erp.contas_receber ADD COLUMN renegociacao_origem_id bigint;
ALTER TABLE erp.contas_pagar ADD COLUMN renegociacao_origem_id bigint;
ALTER TABLE erp.contas_receber ADD CONSTRAINT receber_renegociacao_fk FOREIGN KEY(tenant_id,renegociacao_origem_id) REFERENCES erp.renegociacoes(tenant_id,id) ON DELETE RESTRICT;
ALTER TABLE erp.contas_pagar ADD CONSTRAINT pagar_renegociacao_fk FOREIGN KEY(tenant_id,renegociacao_origem_id) REFERENCES erp.renegociacoes(tenant_id,id) ON DELETE RESTRICT;

CREATE FUNCTION erp.composicao_parcela(p_tenant bigint,p_lado text,p_id bigint)
RETURNS TABLE(valor numeric,dinheiro numeric,credito numeric,transferido numeric,saldo numeric,entidade_id bigint,titulo_id bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF p_lado NOT IN ('receber','pagar') THEN RAISE EXCEPTION 'Lado invalido' USING ERRCODE='23514'; END IF;
 EXECUTE format('SELECT p.valor,t.%I,p.conta_%s_id FROM erp.contas_%s_parcelas p JOIN erp.contas_%s t ON t.tenant_id=p.tenant_id AND t.id=p.conta_%s_id WHERE p.tenant_id=$1 AND p.id=$2',
  CASE WHEN p_lado='receber' THEN 'cliente_id' ELSE 'fornecedor_id' END,p_lado,p_lado,p_lado,p_lado)
 INTO valor,entidade_id,titulo_id USING p_tenant,p_id;
 IF valor IS NULL THEN RETURN; END IF;
 EXECUTE format('SELECT coalesce(sum(valor),0) FROM erp.pagamentos WHERE tenant_id=$1 AND conta_%s_parcela_id=$2 AND excluido_em IS NULL AND estornado_em IS NULL AND estorno_de_pagamento_id IS NULL',p_lado)
 INTO dinheiro USING p_tenant,p_id;
 EXECUTE format('SELECT coalesce(sum(CASE WHEN reversao_de_id IS NULL THEN valor ELSE -valor END),0) FROM erp.adiantamentos_aplicacoes WHERE tenant_id=$1 AND conta_%s_parcela_id=$2',p_lado)
 INTO credito USING p_tenant,p_id;
 EXECUTE format('SELECT coalesce(sum(p.valor),0) FROM erp.renegociacoes_parcelas p JOIN erp.renegociacoes r ON r.tenant_id=p.tenant_id AND r.id=p.renegociacao_id WHERE p.tenant_id=$1 AND p.conta_%s_parcela_id=$2 AND p.papel=''origem'' AND r.status=''efetivada''',p_lado)
 INTO transferido USING p_tenant,p_id;
 saldo:=valor-dinheiro-credito-transferido;
 RETURN NEXT;
END $$;

CREATE FUNCTION erp.validar_movimento_evolucao() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE j jsonb; a erp.adiantamentos; original erp.adiantamentos; ap erp.adiantamentos_aplicacoes;
 r erp.renegociacoes; p record; t bigint; lado text; parcela bigint; pgto erp.pagamentos;
BEGIN
 j:=CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 t:=(j->>'tenant_id')::bigint;
 PERFORM erp.travar_evolucao(t);
 IF TG_OP='UPDATE' AND (OLD.tenant_id<>NEW.tenant_id OR OLD.id<>NEW.id) THEN RAISE EXCEPTION 'Identidade imutavel' USING ERRCODE='23514'; END IF;
 IF TG_TABLE_NAME IN ('adiantamentos','adiantamentos_aplicacoes') THEN
  IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'Movimento imutavel; registre reversao' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME='adiantamentos' THEN
   PERFORM erp.exigir_periodos_abertos(t,'financeiro',ARRAY[NEW.data_movimento,NEW.data_credito]);
   IF NOT EXISTS(SELECT 1 FROM erp.entidades WHERE tenant_id=t AND id=NEW.entidade_id AND
    CASE WHEN NEW.lado='receber' THEN eh_cliente ELSE eh_fornecedor END) THEN RAISE EXCEPTION 'Papel da entidade incompativel' USING ERRCODE='23514'; END IF;
   IF NEW.tipo<>'constituicao' THEN
    SELECT * INTO a FROM erp.adiantamentos WHERE tenant_id=t AND id=NEW.adiantamento_id;
    IF a.tipo IS DISTINCT FROM 'constituicao' OR a.entidade_id<>NEW.entidade_id OR a.lado<>NEW.lado OR NEW.data_movimento<a.data_movimento THEN RAISE EXCEPTION 'Origem do adiantamento invalida' USING ERRCODE='23514'; END IF;
   END IF;
   IF NEW.tipo='reversao' THEN
    SELECT * INTO original FROM erp.adiantamentos WHERE tenant_id=t AND id=NEW.reversao_de_id;
    IF original.tipo NOT IN ('constituicao','devolucao') OR original.id IS NULL
     OR coalesce(original.adiantamento_id,original.id)<>NEW.adiantamento_id OR original.valor<>NEW.valor
     OR original.conta_financeira_id<>NEW.conta_financeira_id OR NEW.data_movimento<original.data_movimento THEN
     RAISE EXCEPTION 'Reversao deve corresponder ao movimento inteiro' USING ERRCODE='23514'; END IF;
   END IF;
  ELSE
   PERFORM erp.exigir_periodos_abertos(t,'financeiro',ARRAY[NEW.data_aplicacao]);
   SELECT * INTO a FROM erp.adiantamentos WHERE tenant_id=t AND id=NEW.adiantamento_id;
   lado:=CASE WHEN NEW.conta_receber_parcela_id IS NOT NULL THEN 'receber' ELSE 'pagar' END;
   parcela:=coalesce(NEW.conta_receber_parcela_id,NEW.conta_pagar_parcela_id);
   SELECT * INTO p FROM erp.composicao_parcela(t,lado,parcela);
   IF a.tipo IS DISTINCT FROM 'constituicao' OR a.lado<>lado OR a.entidade_id IS DISTINCT FROM p.entidade_id OR NEW.data_aplicacao<coalesce(a.data_credito,a.data_movimento) THEN
    RAISE EXCEPTION 'Aplicacao pertence a outra entidade/lado ou antecede credito' USING ERRCODE='23514'; END IF;
   IF NEW.reversao_de_id IS NOT NULL THEN
    SELECT * INTO ap FROM erp.adiantamentos_aplicacoes WHERE tenant_id=t AND id=NEW.reversao_de_id;
    IF ap.id IS NULL OR ap.reversao_de_id IS NOT NULL OR ap.adiantamento_id<>NEW.adiantamento_id OR ap.valor<>NEW.valor
     OR ap.conta_receber_parcela_id IS DISTINCT FROM NEW.conta_receber_parcela_id OR ap.conta_pagar_parcela_id IS DISTINCT FROM NEW.conta_pagar_parcela_id OR NEW.data_aplicacao<ap.data_aplicacao THEN
     RAISE EXCEPTION 'Reversao da aplicacao inconsistente' USING ERRCODE='23514'; END IF;
   END IF;
  END IF;
 ELSIF TG_TABLE_NAME='renegociacoes' THEN
  IF TG_OP='DELETE' THEN
   IF OLD.status<>'rascunho' THEN RAISE EXCEPTION 'Acordo efetivado preservado' USING ERRCODE='23514'; END IF;
   RETURN OLD;
  END IF;
  PERFORM erp.exigir_periodos_abertos(t,'financeiro',ARRAY[NEW.data_acordo]);
  IF TG_OP='INSERT' AND NEW.status<>'rascunho' THEN RAISE EXCEPTION 'Crie rascunho e parcelas antes de efetivar' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND OLD.status<>'rascunho' THEN
   PERFORM erp.exigir_periodos_abertos(t,'financeiro',ARRAY[OLD.data_acordo]);
   IF OLD.status='revertida' OR NEW.status<>'revertida'
    OR (to_jsonb(OLD)-ARRAY['status','revertida_em','revertida_por','motivo_reversao']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['status','revertida_em','revertida_por','motivo_reversao']) THEN
    RAISE EXCEPTION 'Acordo efetivado imutavel; somente reversao controlada' USING ERRCODE='23514'; END IF;
  END IF;
 ELSIF TG_TABLE_NAME='renegociacoes_parcelas' THEN
  SELECT * INTO r FROM erp.renegociacoes WHERE tenant_id=t AND id=(j->>'renegociacao_id')::bigint;
  IF r.status IS DISTINCT FROM 'rascunho' THEN RAISE EXCEPTION 'Parcelas de acordo efetivado imutaveis' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND OLD.renegociacao_id<>NEW.renegociacao_id THEN RAISE EXCEPTION 'Nao mover vinculos entre acordos' USING ERRCODE='23514'; END IF;
 ELSIF TG_TABLE_NAME='pagamentos' THEN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Preserve pagamento; registre estorno' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND (to_jsonb(OLD)-ARRAY['estornado_em','conciliado','atualizado_em','atualizado_por'])
   IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['estornado_em','conciliado','atualizado_em','atualizado_por']) THEN
   RAISE EXCEPTION 'Pagamento efetivado imutavel' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND OLD.estornado_em IS NOT NULL AND OLD.estornado_em IS DISTINCT FROM NEW.estornado_em THEN
   RAISE EXCEPTION 'Estorno preservado' USING ERRCODE='23514'; END IF;
  IF NEW.excluido_em IS NOT NULL THEN RAISE EXCEPTION 'Nao excluir pagamento efetivado' USING ERRCODE='23514'; END IF;
  IF NEW.estorno_de_pagamento_id IS NOT NULL THEN
   SELECT * INTO pgto FROM erp.pagamentos WHERE tenant_id=t AND id=NEW.estorno_de_pagamento_id;
   IF pgto.id IS NULL OR pgto.estorno_de_pagamento_id IS NOT NULL OR pgto.estornado_em IS NULL
    OR ROW(pgto.tipo,pgto.conta_receber_parcela_id,pgto.conta_pagar_parcela_id,pgto.conta_financeira_id,pgto.valor,pgto.juros,pgto.multa,pgto.desconto,pgto.taxa,pgto.valor_liquido)
     IS DISTINCT FROM ROW(NEW.tipo,NEW.conta_receber_parcela_id,NEW.conta_pagar_parcela_id,NEW.conta_financeira_id,NEW.valor,NEW.juros,NEW.multa,NEW.desconto,NEW.taxa,NEW.valor_liquido)
    OR NEW.data_pagamento<pgto.data_pagamento OR nullif(btrim(NEW.motivo_estorno),'') IS NULL THEN
    RAISE EXCEPTION 'Estorno integral incompativel' USING ERRCODE='23514'; END IF;
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;

CREATE FUNCTION erp.validar_saldos_evolucao() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t bigint; a record; r record; l record; c record; p record; lado text;
 saldo_adiantamento numeric; soma_origem numeric; soma_destino numeric; novo_status text; valido boolean; titulo record; agregado record;
BEGIN
 t:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 PERFORM erp.travar_evolucao(t);
 FOR a IN SELECT * FROM erp.adiantamentos WHERE tenant_id=t AND tipo='constituicao' LOOP
  SELECT a.valor-coalesce(sum(CASE WHEN m.tipo='devolucao' THEN m.valor
     WHEN m.tipo='reversao' AND o.tipo='constituicao' THEN m.valor
     WHEN m.tipo='reversao' AND o.tipo='devolucao' THEN -m.valor ELSE 0 END),0)
  INTO saldo_adiantamento
  FROM erp.adiantamentos m LEFT JOIN erp.adiantamentos o ON o.tenant_id=m.tenant_id AND o.id=m.reversao_de_id
  WHERE m.tenant_id=t AND m.adiantamento_id=a.id;
  SELECT saldo_adiantamento-coalesce(sum(CASE WHEN reversao_de_id IS NULL THEN valor ELSE -valor END),0)
  INTO saldo_adiantamento FROM erp.adiantamentos_aplicacoes WHERE tenant_id=t AND adiantamento_id=a.id;
  IF saldo_adiantamento<0 OR saldo_adiantamento>a.valor THEN RAISE EXCEPTION 'Saldo de adiantamento excedido' USING ERRCODE='23514'; END IF;
  IF EXISTS(WITH movimentos AS (
   SELECT coalesce(a.data_credito,a.data_movimento) dia,a.valor delta
   UNION ALL SELECT coalesce(m.data_credito,m.data_movimento),CASE WHEN m.tipo='devolucao' OR o.tipo='constituicao' THEN -m.valor ELSE m.valor END
    FROM erp.adiantamentos m LEFT JOIN erp.adiantamentos o ON o.tenant_id=m.tenant_id AND o.id=m.reversao_de_id WHERE m.tenant_id=t AND m.adiantamento_id=a.id
   UNION ALL SELECT data_aplicacao,CASE WHEN reversao_de_id IS NULL THEN -valor ELSE valor END FROM erp.adiantamentos_aplicacoes WHERE tenant_id=t AND adiantamento_id=a.id
  ), por_dia AS (SELECT dia,sum(delta) delta FROM movimentos GROUP BY dia), saldos AS (SELECT sum(delta) OVER(ORDER BY dia) saldo FROM por_dia)
  SELECT 1 FROM saldos WHERE saldo<0) THEN RAISE EXCEPTION 'Saldo historico do adiantamento negativo' USING ERRCODE='23514'; END IF;
 END LOOP;
 IF EXISTS(SELECT 1 FROM erp.pagamentos origem WHERE origem.tenant_id=t AND origem.estornado_em IS NOT NULL AND origem.estorno_de_pagamento_id IS NULL
  AND NOT EXISTS(SELECT 1 FROM erp.pagamentos x WHERE x.tenant_id=t AND x.estorno_de_pagamento_id=origem.id)) THEN
  RAISE EXCEPTION 'Estorno exige contramovimento na mesma transacao' USING ERRCODE='23514'; END IF;
 IF EXISTS(WITH RECURSIVE arestas AS (
  SELECT head.renegociacao_origem_id origem,link.renegociacao_id destino FROM erp.renegociacoes_parcelas link
  JOIN erp.contas_receber_parcelas par ON par.tenant_id=link.tenant_id AND par.id=link.conta_receber_parcela_id
  JOIN erp.contas_receber head ON head.tenant_id=par.tenant_id AND head.id=par.conta_receber_id
  WHERE link.tenant_id=t AND link.papel='origem' AND head.renegociacao_origem_id IS NOT NULL
  UNION SELECT head.renegociacao_origem_id,link.renegociacao_id FROM erp.renegociacoes_parcelas link
  JOIN erp.contas_pagar_parcelas par ON par.tenant_id=link.tenant_id AND par.id=link.conta_pagar_parcela_id
  JOIN erp.contas_pagar head ON head.tenant_id=par.tenant_id AND head.id=par.conta_pagar_id
  WHERE link.tenant_id=t AND link.papel='origem' AND head.renegociacao_origem_id IS NOT NULL
 ), caminhos AS (
  SELECT destino,ARRAY[origem,destino] caminho,origem=destino ciclo FROM arestas
  UNION ALL SELECT edge.destino,path.caminho||edge.destino,edge.destino=ANY(path.caminho) FROM caminhos path JOIN arestas edge ON edge.origem=path.destino WHERE NOT path.ciclo
 ) SELECT 1 FROM caminhos WHERE ciclo) THEN RAISE EXCEPTION 'Ciclo entre renegociacoes' USING ERRCODE='23514'; END IF;
 FOR r IN SELECT * FROM erp.renegociacoes WHERE tenant_id=t LOOP
  soma_origem:=0; soma_destino:=0;
  FOR l IN SELECT * FROM erp.renegociacoes_parcelas WHERE tenant_id=t AND renegociacao_id=r.id LOOP
   lado:=CASE WHEN l.conta_receber_parcela_id IS NOT NULL THEN 'receber' ELSE 'pagar' END;
   SELECT * INTO c FROM erp.composicao_parcela(t,lado,coalesce(l.conta_receber_parcela_id,l.conta_pagar_parcela_id));
   IF c.entidade_id IS DISTINCT FROM r.entidade_id OR lado<>r.lado THEN RAISE EXCEPTION 'Entidade/lado do acordo incompativel' USING ERRCODE='23514'; END IF;
   IF l.papel='origem' THEN
    soma_origem:=soma_origem+l.valor;
    IF r.status='efetivada' AND (c.saldo<>0 OR c.transferido<>l.valor) THEN RAISE EXCEPTION 'Acordo deve transferir saldo integral uma unica vez' USING ERRCODE='23514'; END IF;
   ELSE
    soma_destino:=soma_destino+l.valor;
    EXECUTE format('SELECT renegociacao_origem_id=$3 FROM erp.contas_%s WHERE tenant_id=$1 AND id=$2',lado) INTO valido USING t,c.titulo_id,r.id;
    IF valido IS DISTINCT FROM true OR l.valor<>c.valor THEN RAISE EXCEPTION 'Destino exige titulo proprio do acordo e valor correspondente' USING ERRCODE='23514'; END IF;
    IF r.status='rascunho' THEN RAISE EXCEPTION 'Parcelas destino devem ser criadas na transacao da efetivacao' USING ERRCODE='23514'; END IF;
    IF r.status='revertida' THEN
     EXECUTE format('SELECT status=''cancelado'' FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND id=$2',lado) INTO valido USING t,coalesce(l.conta_receber_parcela_id,l.conta_pagar_parcela_id);
     IF c.dinheiro<>0 OR c.credito<>0 OR c.transferido<>0 OR valido IS DISTINCT FROM true THEN RAISE EXCEPTION 'Reversao exige destino sem liquidacoes/dependencias e cancelado' USING ERRCODE='23514'; END IF;
    END IF;
   END IF;
  END LOOP;
  IF r.status<>'rascunho' AND (soma_origem<=0 OR soma_destino<=0 OR soma_destino<>soma_origem-r.desconto+r.encargos) THEN
   RAISE EXCEPTION 'Equacao da renegociacao inconsistente' USING ERRCODE='23514'; END IF;
 END LOOP;
 FOREACH lado IN ARRAY ARRAY['receber','pagar'] LOOP
  FOR p IN EXECUTE format('SELECT p.*,t.status titulo_status,t.excluido_em titulo_excluido FROM erp.contas_%s_parcelas p JOIN erp.contas_%s t ON t.tenant_id=p.tenant_id AND t.id=p.conta_%s_id WHERE p.tenant_id=$1',lado,lado,lado) USING t LOOP
   SELECT * INTO c FROM erp.composicao_parcela(t,lado,p.id);
   IF c.saldo<0 OR c.credito<0 OR
    ((p.status='cancelado' OR p.excluido_em IS NOT NULL OR p.titulo_status='cancelado' OR p.titulo_excluido IS NOT NULL) AND (c.dinheiro<>0 OR c.credito<>0 OR c.transferido<>0)) THEN
    RAISE EXCEPTION 'Saldo excedido ou liquidacao em obrigacao cancelada' USING ERRCODE='23514'; END IF;
   novo_status:=CASE WHEN p.status='cancelado' THEN 'cancelado'
    WHEN c.transferido>0 THEN 'renegociado' WHEN c.saldo=0 THEN 'pago'
    WHEN c.dinheiro+c.credito>0 THEN 'parcial' ELSE 'aberto' END;
   EXECUTE format('UPDATE erp.contas_%s_parcelas SET valor_pago=$3,status=$4 WHERE tenant_id=$1 AND id=$2 AND (valor_pago IS DISTINCT FROM $3 OR (status IS DISTINCT FROM $4 AND NOT(status=''vencido'' AND $4=''aberto'')))',lado)
    USING t,p.id,c.dinheiro,novo_status;
  END LOOP;
  FOR titulo IN EXECUTE format('SELECT * FROM erp.contas_%s WHERE tenant_id=$1 AND excluido_em IS NULL',lado) USING t LOOP
   IF titulo.renegociacao_origem_id IS NOT NULL THEN
    SELECT * INTO r FROM erp.renegociacoes WHERE tenant_id=t AND id=titulo.renegociacao_origem_id;
    IF r.lado<>lado OR r.status='rascunho' OR (r.status='revertida' AND titulo.status<>'cancelado') THEN
     RAISE EXCEPTION 'Titulo de renegociacao sem acordo efetivo correspondente' USING ERRCODE='23514'; END IF;
    EXECUTE format('SELECT EXISTS(SELECT 1 FROM erp.contas_%s_parcelas par WHERE par.tenant_id=$1 AND par.conta_%s_id=$2 AND par.excluido_em IS NULL AND NOT EXISTS(SELECT 1 FROM erp.renegociacoes_parcelas link WHERE link.tenant_id=par.tenant_id AND link.conta_%s_parcela_id=par.id AND link.renegociacao_id=$3 AND link.papel=''destino''))',lado,lado,lado)
     INTO valido USING t,titulo.id,titulo.renegociacao_origem_id;
    IF valido THEN RAISE EXCEPTION 'Parcela destino sem vinculo no acordo' USING ERRCODE='23514'; END IF;
   END IF;
   EXECUTE format('SELECT count(*) n,coalesce(sum(valor),0) total,bool_and(status IN (''pago'',''renegociado'')) quitado,bool_or(status=''renegociado'') renegociado,bool_or(status IN (''pago'',''parcial'',''renegociado'')) parcial FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND conta_%s_id=$2 AND excluido_em IS NULL',lado,lado)
    INTO agregado USING t,titulo.id;
   IF agregado.n>0 AND titulo.valor_total<>agregado.total THEN RAISE EXCEPTION 'Total do titulo diverge das parcelas' USING ERRCODE='23514'; END IF;
   IF agregado.n>0 AND titulo.status<>'cancelado' THEN
    novo_status:=CASE WHEN agregado.quitado AND agregado.renegociado THEN 'renegociado' WHEN agregado.quitado THEN 'pago' WHEN agregado.parcial THEN 'parcial' ELSE 'aberto' END;
    EXECUTE format('UPDATE erp.contas_%s SET status=$3 WHERE tenant_id=$1 AND id=$2 AND status<>$3 AND NOT(status=''vencido'' AND $3=''aberto'')',lado) USING t,titulo.id,novo_status;
   END IF;
  END LOOP;
 END LOOP;
 RETURN NULL;
END $$;

CREATE FUNCTION erp.validar_conciliacao_evolucao() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t bigint; i record; b erp.transacoes_bancarias; h erp.conciliacoes_bancarias;
 p erp.pagamentos; a erp.adiantamentos; o erp.adiantamentos; tr erp.transferencias_financeiras;
 sentido text; conta bigint; limite numeric; total numeric;
BEGIN
 t:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 PERFORM erp.travar_evolucao(t);
 FOR i IN SELECT * FROM erp.conciliacoes_bancarias_itens WHERE tenant_id=t AND desfeito_em IS NULL LOOP
  SELECT * INTO b FROM erp.transacoes_bancarias WHERE tenant_id=t AND id=i.transacao_bancaria_id;
  SELECT * INTO h FROM erp.conciliacoes_bancarias WHERE tenant_id=t AND id=i.conciliacao_id;
  IF b.excluido_em IS NOT NULL OR h.excluido_em IS NOT NULL OR h.status='cancelada' OR h.conta_financeira_id<>b.conta_financeira_id
   OR b.data_transacao<coalesce(h.periodo_inicio,'-infinity'::date) OR b.data_transacao>coalesce(h.periodo_fim,'infinity'::date) THEN
   RAISE EXCEPTION 'Extrato incompativel com conciliacao' USING ERRCODE='23514'; END IF;
  IF i.pagamento_id IS NOT NULL THEN
   SELECT * INTO p FROM erp.pagamentos WHERE tenant_id=t AND id=i.pagamento_id;
   conta:=p.conta_financeira_id; limite:=p.valor_liquido;
   sentido:=CASE WHEN (p.tipo='receber')=(p.estorno_de_pagamento_id IS NULL) THEN 'credito' ELSE 'debito' END;
   SELECT coalesce(sum(valor_conciliado),0) INTO total FROM erp.conciliacoes_bancarias_itens WHERE tenant_id=t AND pagamento_id=p.id AND desfeito_em IS NULL;
   IF p.excluido_em IS NOT NULL THEN RAISE EXCEPTION 'Pagamento indisponivel' USING ERRCODE='23514'; END IF;
  ELSIF i.adiantamento_id IS NOT NULL THEN
   SELECT * INTO a FROM erp.adiantamentos WHERE tenant_id=t AND id=i.adiantamento_id;
   conta:=a.conta_financeira_id; limite:=a.valor;
   IF a.tipo='reversao' THEN SELECT * INTO o FROM erp.adiantamentos WHERE tenant_id=t AND id=a.reversao_de_id; ELSE o:=a; END IF;
   sentido:=CASE WHEN ((a.lado='receber')=(o.tipo='constituicao'))=(a.tipo<>'reversao') THEN 'credito' ELSE 'debito' END;
   SELECT coalesce(sum(valor_conciliado),0) INTO total FROM erp.conciliacoes_bancarias_itens WHERE tenant_id=t AND adiantamento_id=a.id AND desfeito_em IS NULL;
  ELSE
   SELECT * INTO tr FROM erp.transferencias_financeiras WHERE tenant_id=t AND id=i.transferencia_financeira_id;
   IF tr.status='cancelada' OR tr.excluido_em IS NOT NULL OR b.conta_financeira_id NOT IN (tr.conta_origem_id,tr.conta_destino_id) THEN RAISE EXCEPTION 'Transferencia indisponivel ou conta incorreta' USING ERRCODE='23514'; END IF;
   conta:=b.conta_financeira_id; limite:=tr.valor;
   sentido:=CASE WHEN conta=tr.conta_origem_id THEN 'debito' ELSE 'credito' END;
   SELECT coalesce(sum(x.valor_conciliado),0) INTO total FROM erp.conciliacoes_bancarias_itens x
    JOIN erp.transacoes_bancarias z ON z.tenant_id=x.tenant_id AND z.id=x.transacao_bancaria_id
    WHERE x.tenant_id=t AND x.transferencia_financeira_id=tr.id AND x.desfeito_em IS NULL AND z.conta_financeira_id=conta;
  END IF;
  IF conta IS DISTINCT FROM b.conta_financeira_id OR sentido IS DISTINCT FROM b.tipo OR total>limite THEN RAISE EXCEPTION 'Conciliacao excede origem ou diverge em conta/sentido' USING ERRCODE='23514'; END IF;
  SELECT sum(valor_conciliado) INTO total FROM erp.conciliacoes_bancarias_itens WHERE tenant_id=t AND transacao_bancaria_id=b.id AND desfeito_em IS NULL;
  IF total>b.valor THEN RAISE EXCEPTION 'Conciliacao excede extrato' USING ERRCODE='23514'; END IF;
 END LOOP;
 FOR i IN SELECT pgto.id,pgto.conciliado,pgto.valor_liquido,coalesce(sum(link.valor_conciliado),0) conciliacao
  FROM erp.pagamentos pgto LEFT JOIN erp.conciliacoes_bancarias_itens link ON link.tenant_id=pgto.tenant_id AND link.pagamento_id=pgto.id AND link.desfeito_em IS NULL
  WHERE pgto.tenant_id=t GROUP BY pgto.id LOOP
  IF i.conciliado IS DISTINCT FROM (i.valor_liquido>0 AND i.conciliacao=i.valor_liquido) THEN
   UPDATE erp.pagamentos SET conciliado=(i.valor_liquido>0 AND i.conciliacao=i.valor_liquido) WHERE tenant_id=t AND id=i.id;
  END IF;
 END LOOP;
 FOR i IN SELECT bank.id,bank.status,bank.valor,coalesce(sum(link.valor_conciliado),0) conciliacao
  FROM erp.transacoes_bancarias bank LEFT JOIN erp.conciliacoes_bancarias_itens link ON link.tenant_id=bank.tenant_id AND link.transacao_bancaria_id=bank.id AND link.desfeito_em IS NULL
  WHERE bank.tenant_id=t GROUP BY bank.id LOOP
  sentido:=CASE WHEN i.conciliacao=i.valor THEN 'conciliada' WHEN i.status='ignorada' AND i.conciliacao=0 THEN 'ignorada' ELSE 'pendente' END;
  IF i.status IS DISTINCT FROM sentido THEN UPDATE erp.transacoes_bancarias SET status=sentido WHERE tenant_id=t AND id=i.id; END IF;
 END LOOP;
 RETURN NULL;
END $$;

CREATE FUNCTION erp.proteger_dependencias_financeiras() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE j jsonb; anterior jsonb; t bigint; b erp.transacoes_bancarias;
BEGIN
 j:=CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 t:=(j->>'tenant_id')::bigint;
 PERFORM erp.travar_evolucao(t);
 IF TG_OP='UPDATE' THEN
  anterior:=to_jsonb(OLD);
  IF OLD.tenant_id<>NEW.tenant_id OR OLD.id<>NEW.id THEN RAISE EXCEPTION 'Identidade imutavel' USING ERRCODE='23514'; END IF;
  IF TG_TABLE_NAME IN ('contas_receber','contas_pagar','contas_receber_parcelas','contas_pagar_parcelas') AND
   (anterior->'cliente_id' IS DISTINCT FROM j->'cliente_id' OR anterior->'fornecedor_id' IS DISTINCT FROM j->'fornecedor_id'
    OR anterior->'conta_receber_id' IS DISTINCT FROM j->'conta_receber_id' OR anterior->'conta_pagar_id' IS DISTINCT FROM j->'conta_pagar_id'
    OR anterior->'renegociacao_origem_id' IS DISTINCT FROM j->'renegociacao_origem_id') THEN
   RAISE EXCEPTION 'Origem da obrigacao preservada' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_TABLE_NAME='conciliacoes_bancarias_itens' THEN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Desfaca a conciliacao sem apagar historico' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND ((to_jsonb(OLD)-ARRAY['desfeito_em','desfeito_por']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['desfeito_em','desfeito_por'])
   OR OLD.desfeito_em IS NOT NULL OR NEW.desfeito_em IS NULL OR NEW.desfeito_por IS NULL) THEN
   RAISE EXCEPTION 'Somente desfazimento identificado e permitido' USING ERRCODE='23514'; END IF;
  SELECT * INTO b FROM erp.transacoes_bancarias WHERE tenant_id=t AND id=NEW.transacao_bancaria_id;
  PERFORM erp.exigir_periodos_abertos(t,'financeiro',ARRAY[b.data_transacao,b.data_compensacao]);
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;

CREATE FUNCTION erp.evento_credito_acordo() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE l record; lado text; doc bigint; j jsonb;
BEGIN
 j:=to_jsonb(NEW);
 IF TG_TABLE_NAME='adiantamentos_aplicacoes' THEN
  lado:=CASE WHEN NEW.conta_receber_parcela_id IS NOT NULL THEN 'receber' ELSE 'pagar' END;
  EXECUTE format('SELECT conta_%s_id FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND id=$2',lado,lado)
   INTO doc USING NEW.tenant_id,coalesce(NEW.conta_receber_parcela_id,NEW.conta_pagar_parcela_id);
  IF lado='receber' THEN
   INSERT INTO erp.contas_receber_eventos(tenant_id,conta_receber_id,conta_receber_parcela_id,evento,dados,criado_por)
    VALUES(NEW.tenant_id,doc,NEW.conta_receber_parcela_id,'adiantamento.aplicacao',j,NEW.criado_por);
  ELSE
   INSERT INTO erp.contas_pagar_eventos(tenant_id,conta_pagar_id,evento,dados,criado_por)
    VALUES(NEW.tenant_id,doc,'adiantamento.aplicacao',j,NEW.criado_por);
  END IF;
 ELSE
  FOR l IN SELECT * FROM erp.renegociacoes_parcelas WHERE tenant_id=NEW.tenant_id AND renegociacao_id=NEW.id LOOP
   lado:=NEW.lado;
   EXECUTE format('SELECT conta_%s_id FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND id=$2',lado,lado)
    INTO doc USING NEW.tenant_id,coalesce(l.conta_receber_parcela_id,l.conta_pagar_parcela_id);
   IF lado='receber' THEN
    INSERT INTO erp.contas_receber_eventos(tenant_id,conta_receber_id,conta_receber_parcela_id,evento,dados,criado_por)
    VALUES(NEW.tenant_id,doc,l.conta_receber_parcela_id,'renegociacao.'||NEW.status,j,NEW.criado_por);
   ELSE
    INSERT INTO erp.contas_pagar_eventos(tenant_id,conta_pagar_id,evento,dados,criado_por)
    VALUES(NEW.tenant_id,doc,'renegociacao.'||NEW.status,j,NEW.criado_por);
   END IF;
  END LOOP;
 END IF;
 RETURN NULL;
END $$;
CREATE TRIGGER evento_credito AFTER INSERT ON erp.adiantamentos_aplicacoes FOR EACH ROW EXECUTE FUNCTION erp.evento_credito_acordo();
CREATE TRIGGER evento_acordo AFTER UPDATE OF status ON erp.renegociacoes FOR EACH ROW WHEN(OLD.status IS DISTINCT FROM NEW.status) EXECUTE FUNCTION erp.evento_credito_acordo();

DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['adiantamentos','adiantamentos_aplicacoes','renegociacoes','renegociacoes_parcelas','pagamentos'] LOOP
 EXECUTE format('CREATE TRIGGER a_validar_movimento_evolucao BEFORE INSERT OR UPDATE OR DELETE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.validar_movimento_evolucao()',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['contas_receber','contas_pagar','contas_receber_parcelas','contas_pagar_parcelas','conciliacoes_bancarias_itens','conciliacoes_bancarias','transacoes_bancarias','transferencias_financeiras'] LOOP
 EXECUTE format('CREATE TRIGGER a_proteger_dependencias BEFORE INSERT OR UPDATE OR DELETE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.proteger_dependencias_financeiras()',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['adiantamentos','adiantamentos_aplicacoes','renegociacoes','renegociacoes_parcelas','pagamentos','contas_receber','contas_pagar','contas_receber_parcelas','contas_pagar_parcelas'] LOOP
 EXECUTE format('CREATE CONSTRAINT TRIGGER validar_saldos AFTER INSERT OR UPDATE OR DELETE ON erp.%I DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION erp.validar_saldos_evolucao()',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['adiantamentos','pagamentos','conciliacoes_bancarias_itens','conciliacoes_bancarias','transacoes_bancarias','transferencias_financeiras'] LOOP
 EXECUTE format('CREATE CONSTRAINT TRIGGER validar_conciliacao AFTER INSERT OR UPDATE OR DELETE ON erp.%I DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION erp.validar_conciliacao_evolucao()',t);
 END LOOP;
END $$;

ALTER TABLE erp.adiantamentos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.adiantamentos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.adiantamentos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.adiantamentos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.adiantamentos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));

ALTER TABLE erp.adiantamentos_aplicacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.adiantamentos_aplicacoes FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.adiantamentos_aplicacoes TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.adiantamentos_aplicacoes_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.adiantamentos_aplicacoes FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));

ALTER TABLE erp.renegociacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.renegociacoes FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.renegociacoes TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.renegociacoes_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.renegociacoes FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));

ALTER TABLE erp.renegociacoes_parcelas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.renegociacoes_parcelas FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.renegociacoes_parcelas TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.renegociacoes_parcelas_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.renegociacoes_parcelas FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));
REVOKE ALL ON FUNCTION erp.composicao_parcela(bigint,text,bigint),erp.validar_movimento_evolucao(),erp.validar_saldos_evolucao(),erp.validar_conciliacao_evolucao(),erp.proteger_dependencias_financeiras(),erp.evento_credito_acordo() FROM PUBLIC;
ALTER TABLE erp.adiantamentos ADD COLUMN requisicao_original jsonb;
ALTER TABLE erp.adiantamentos_aplicacoes ADD COLUMN requisicao_original jsonb;
ALTER TABLE erp.renegociacoes ADD COLUMN requisicao_original jsonb;
CREATE FUNCTION erp.preservar_requisicao_original() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 IF TG_OP='INSERT' THEN
  NEW.requisicao_original:=to_jsonb(NEW)-ARRAY['id','criado_em','requisicao_original'];
 ELSIF OLD.requisicao_original IS DISTINCT FROM NEW.requisicao_original THEN
  RAISE EXCEPTION 'Requisicao inicial preservada' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['adiantamentos','adiantamentos_aplicacoes','renegociacoes'] LOOP
 EXECUTE format('CREATE TRIGGER b_preservar_requisicao BEFORE INSERT OR UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.preservar_requisicao_original()',t);
 END LOOP;
END $$;
CREATE FUNCTION erp.registrar_operacao_idempotente(p_tabela text,p_dados jsonb) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t bigint; existente bigint; original jsonb; cols text; dados jsonb; k text;
BEGIN
 IF p_tabela NOT IN ('adiantamentos','adiantamentos_aplicacoes','renegociacoes') OR jsonb_typeof(p_dados) IS DISTINCT FROM 'object' THEN
  RAISE EXCEPTION 'Operacao invalida' USING ERRCODE='23514'; END IF;
 t:=(p_dados->>'tenant_id')::bigint;
 IF NOT coalesce(shared.has_erp_capability(t,'erp.financeiro.gerenciar'),false) THEN RAISE EXCEPTION 'Sem permissao financeira' USING ERRCODE='42501'; END IF;
 IF nullif(btrim(p_dados->>'chave_idempotencia'),'') IS NULL OR p_dados ?| ARRAY['id','criado_em','criado_por','requisicao_original'] THEN
  RAISE EXCEPTION 'Chave obrigatoria; campos internos nao aceitos' USING ERRCODE='23514'; END IF;
 PERFORM erp.travar_evolucao(t);
 dados:=p_dados||jsonb_build_object('criado_por',nullif(current_setting('app.erp_user_id',true),'')::bigint);
 FOR k IN SELECT jsonb_object_keys(dados) LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=('erp.'||p_tabela)::regclass AND attname=k AND attnum>0 AND NOT attisdropped) THEN
   RAISE EXCEPTION 'Campo desconhecido' USING ERRCODE='23514'; END IF;
 END LOOP;
 EXECUTE format('SELECT id,requisicao_original FROM erp.%I WHERE tenant_id=$1 AND chave_idempotencia=$2',p_tabela) INTO existente,original USING t,p_dados->>'chave_idempotencia';
 IF existente IS NOT NULL THEN
  IF NOT original @> dados THEN RAISE EXCEPTION 'Chave reutilizada com conteudo diferente' USING ERRCODE='23514'; END IF;
  RETURN existente;
 END IF;
 SELECT string_agg(format('%I',key),',') INTO cols FROM jsonb_object_keys(dados) key;
 EXECUTE format('INSERT INTO erp.%I(%s) SELECT %s FROM jsonb_populate_record(NULL::erp.%I,$1) RETURNING id',p_tabela,cols,cols,p_tabela) INTO existente USING dados;
 RETURN existente;
END $$;
REVOKE ALL ON FUNCTION erp.preservar_requisicao_original(),erp.registrar_operacao_idempotente(text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION erp.registrar_operacao_idempotente(text,jsonb) TO erp_runtime;

COMMIT;
