export const commonScript=String.raw`
const labels={id:'ID',nome:'Nome',numero:'Número',descricao:'Descrição',cliente:'Cliente',cliente_nome:'Cliente',fornecedor:'Fornecedor',fornecedor_nome:'Fornecedor',data:'Data',data_venda:'Data da venda',data_compra:'Data da compra',vencimento:'Vencimento',total:'Total',subtotal:'Subtotal',valor:'Valor',valor_unitario:'Valor unitário',valor_pago:'Pago em dinheiro',valor_liquido:'Valor líquido',valor_medio:'Valor médio',saldo:'Saldo',credito:'Créditos aplicados',renegociado:'Transferido em renegociação',status:'Situação',parcela:'Parcela',conta_id:'Título',tipo:'Tipo',tipo_documento:'Documento',quantidade:'Quantidade',sku:'SKU',codigo:'Código',preco:'Preço',categoria:'Categoria',documento:'Documento',email:'E-mail',telefone:'Telefone',cidade:'Cidade',versao:'Versão',controla_estoque:'Controla estoque',estoque_minimo:'Estoque mínimo',periodo:'Período',data_pagamento:'Data de pagamento',conta_financeira:'Conta financeira',estornado_em:'Estornado em',estorno_de_pagamento_id:'Estorno do pagamento',registro_id:'Registro',cliente_id:'Cliente (ID)',produto_id:'Produto (ID)',item_id:'Item (ID)',conta_financeira_id:'Conta financeira (ID)',desconto:'Desconto',data_vencimento:'Vencimento',observacoes:'Observações',motivo:'Motivo',quantidade_atendida:'Atendida',quantidade_recebida:'Recebida',atendimento_status:'Atendimento',fiscal_status:'Fiscal',tipo_lancamento:'Lançamento',expira_em:'Expira em',criado_em:'Criado em',rascunho_id:'Rascunho'};
Object.assign(labels,{valor_total:'Valor total',fornecedor_id:'Fornecedor (ID)',categoria_id:'Categoria (ID)',centro_custo_id:'Centro de custo (ID)',data_competencia:'Competência',data_emissao:'Emissão',numero_parcela:'Parcela',origem:'Origem',saldo_inicial:'Saldo inicial',data_saldo_inicial:'Data do saldo inicial',padrao:'Padrão',produto:'Produto',vendedor:'Vendedor',local:'Local',quantidade_fisica:'Quantidade física',quantidade_reservada:'Reservado',quantidade_disponivel:'Disponível',custo_medio:'Custo médio',valor_estoque:'Valor do estoque',numero_documento:'Documento',conta_receber_parcela_id:'Parcela a receber',conta_pagar_parcela_id:'Parcela a pagar'});
const states={pending:'Aguardando revisão',saved:'Salvo no ERP',cancelled:'Cancelado',expired:'Expirado',aberto:'Em aberto',pendente:'Pendente',parcial:'Parcial',vencido:'Vencido',pago:'Pago',cancelado:'Cancelado',confirmada:'Confirmada',parcialmente_recebida:'Parcialmente recebida',recebida:'Recebida',rascunho:'Rascunho',ativo:'Ativo',inativo:'Inativo',renegociado:'Renegociado'};
const moneyKeys=new Set(['total','subtotal','valor','valor_pago','valor_liquido','saldo','credito','renegociado','preco','valor_unitario','desconto','valor_medio','receita','custo','lucro','valor_total','saldo_inicial','valor_estoque','custo_medio','saldoReceber','saldoPagar','receberVencido']);
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function element(tag,value,className){const node=document.createElement(tag);if(value!==undefined)node.textContent=String(value==null?'—':value);if(className)node.className=className;return node}
Object.assign(labels,{saldoReceber:'A receber',saldoPagar:'A pagar',receberVencido:'A receber vencido',vendasRascunho:'Vendas em rascunho',comprasAbertas:'Compras abertas',clientesAtivos:'Clientes ativos',vendas:'Vendas',compras:'Compras',pagar:'Contas a pagar',receber:'Contas a receber','dre-caixa':'DRE por caixa','dre-competencia':'Resultado por competência','fluxo-de-caixa':'Fluxo de caixa','aging-receber':'Recebimentos em atraso','aging-pagar':'Pagamentos em atraso',a_vencer:'A vencer',vencido_1_30:'Vencido 1–30 dias',vencido_31_60:'Vencido 31–60 dias',vencido_61_90:'Vencido 61–90 dias',vencido_mais_90:'Vencido +90 dias',vencido:'Vencido',entradas_realizadas:'Entradas realizadas',saidas_realizadas:'Saídas realizadas',entradas_previstas:'Entradas previstas',saidas_previstas:'Saídas previstas',saldo_mes:'Saldo do mês',saldo_acumulado:'Saldo acumulado',saldo_inicial_contas:'Saldo inicial de contas',competencia:'Competência','posicao-financeira':'Posição financeira','vendas-clientes':'Vendas por cliente','vendas-vendedores':'Vendas por vendedor','vendas-produtos':'Vendas por produto','compras-fornecedores':'Compras por fornecedor','compras-categorias':'Compras por categoria','valor-estoque':'Valor do estoque',administrador:'Administrador',consulta:'Consulta',em_aberto:'Em aberto',vencidas:'Vencidas',vence_em_7_dias:'Vence em 7 dias',valor_confirmado:'Valor confirmado',produto:'Produto',servico:'Serviço'});
for(const key of ['em_aberto','vencidas','vence_em_7_dias','valor_confirmado','a_vencer','vencido_1_30','vencido_31_60','vencido_61_90','vencido_mais_90','vencido','entradas_realizadas','saidas_realizadas','entradas_previstas','saidas_previstas','saldo_mes','saldo_acumulado','saldo_inicial_contas'])moneyKeys.add(key);
function formatted(key,value){if(value===null||value===undefined||value==='')return '—';if(moneyKeys.has(key))return money(value);if(['quantidade','quantidade_fisica','quantidade_reservada','quantidade_disponivel','quantidade_recebida','quantidade_atendida','estoque_minimo'].includes(key))return Number(value).toLocaleString('pt-BR',{maximumFractionDigits:4});if(key==='status')return states[value]||value;if(key==='tipo'&&['fisica','juridica'].includes(value))return value==='fisica'?'Pessoa física':'Pessoa jurídica';if(['criado_em','expira_em','estornado_em'].includes(key)&&String(value).length>10&&!Number.isNaN(Date.parse(value)))return new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});if(typeof value==='boolean')return value?'Sim':'Não';if(/^(data|vencimento|criado_em|expira_em|estornado_em)/.test(key)&&/^\d{4}-\d{2}-\d{2}/.test(String(value))){const iso=String(value).slice(0,10);return iso.slice(8,10)+'/'+iso.slice(5,7)+'/'+iso.slice(0,4)}return String(value)}
function button(label,fn,primary=false){const b=element('button',label,primary?'primary':'');b.type='button';b.onclick=()=>run(fn);return b}
function pill(status){return element('span',states[status]||status||'—','pill pill-'+String(status||'').replace(/[^a-z_]/g,''))}
function notice(text,kind='info'){const p=element('p',text,'notice notice-'+kind);p.setAttribute('role',kind==='danger'?'alert':'status');return p}
function label(key){return labels[key]||fieldLabels[key]||String(key).replaceAll('_',' ')}
function fields(record,keys){const dl=element('dl',undefined,'fields');for(const key of keys||Object.keys(record||{})){if(record[key]===undefined||(record[key]!==null&&typeof record[key]==='object'))continue;dl.append(element('dt',label(key)),element('dd',formatted(key,record[key])))}return dl}
function columns(rows,limit=5){const keys=[];for(const row of rows)for(const key of Object.keys(row)){const value=row[key];if(keys.includes(key)||(value!==null&&typeof value==="object")||/(_id|versao|chave_idempotencia)$/.test(key))continue;keys.push(key)}const preferred=["numero","nome","descricao","cliente","cliente_nome","fornecedor","fornecedor_nome","produto","local","data_venda","data_compra","vencimento","data_vencimento","data_pagamento","total","valor","saldo","quantidade_disponivel","status"];const rank=key=>{const index=preferred.indexOf(key);return index<0?99:index};return keys.sort((a,b)=>rank(a)-rank(b)).slice(0,limit)}
function table(rows,keys,caption){const t=element('table');if(caption)t.append(element('caption',caption));const head=element('thead'),tr=element('tr');for(const key of keys)tr.append(element('th',label(key)));head.append(tr);const body=element('tbody');for(const row of rows){const line=element('tr');for(const key of keys){const cell=element('td',formatted(key,row[key]));if(moneyKeys.has(key)||/quantidade/.test(key))cell.className='num';line.append(cell)}body.append(line)}t.append(head,body);return t}
function metrics(items){const box=element('div',undefined,'metrics');for(const item of items){const m=element('div',undefined,'metric');m.append(element('span',item.label),element('strong',item.value));box.append(m)}return box}
`
