export const commonScript=String.raw`
const labels={id:'ID',nome:'Nome',numero:'Número',descricao:'Descrição',cliente:'Cliente',cliente_nome:'Cliente',fornecedor:'Fornecedor',fornecedor_nome:'Fornecedor',data:'Data',data_venda:'Data da venda',data_compra:'Data da compra',vencimento:'Vencimento',total:'Total',subtotal:'Subtotal',valor:'Valor',valor_unitario:'Valor unitário',valor_pago:'Pago em dinheiro',valor_liquido:'Valor líquido',valor_medio:'Valor médio',saldo:'Saldo',credito:'Créditos aplicados',renegociado:'Transferido em renegociação',status:'Situação',parcela:'Parcela',conta_id:'Título',tipo:'Tipo',tipo_documento:'Documento',quantidade:'Quantidade',sku:'SKU',codigo:'Código',preco:'Preço',categoria:'Categoria',documento:'Documento',email:'E-mail',telefone:'Telefone',cidade:'Cidade',versao:'Versão',controla_estoque:'Controla estoque',estoque_minimo:'Estoque mínimo',periodo:'Período',data_pagamento:'Data de pagamento',conta_financeira:'Conta financeira',estornado_em:'Estornado em',estorno_de_pagamento_id:'Estorno do pagamento',registro_id:'Registro',cliente_id:'Cliente (ID)',produto_id:'Produto (ID)',item_id:'Item (ID)',conta_financeira_id:'Conta financeira (ID)',desconto:'Desconto',data_vencimento:'Vencimento',observacoes:'Observações',motivo:'Motivo',quantidade_atendida:'Atendida',quantidade_recebida:'Recebida',atendimento_status:'Atendimento',fiscal_status:'Fiscal',tipo_lancamento:'Lançamento',expira_em:'Expira em',criado_em:'Criado em',rascunho_id:'Rascunho'};
Object.assign(labels,{produto:'Produto',vendedor:'Vendedor',local:'Local',quantidade_fisica:'Quantidade física',quantidade_reservada:'Reservado',quantidade_disponivel:'Disponível',custo_medio:'Custo médio',valor_estoque:'Valor do estoque',numero_documento:'Documento',conta_receber_parcela_id:'Parcela a receber',conta_pagar_parcela_id:'Parcela a pagar'});
const states={pending:'Aguardando revisão',saved:'Salvo no ERP',cancelled:'Cancelado',expired:'Expirado',aberto:'Em aberto',pendente:'Pendente',parcial:'Parcial',vencido:'Vencido',pago:'Pago',cancelado:'Cancelado',confirmada:'Confirmada',recebida:'Recebida',rascunho:'Rascunho',ativo:'Ativo',inativo:'Inativo',renegociado:'Renegociado'};
const moneyKeys=new Set(['total','subtotal','valor','valor_pago','valor_liquido','saldo','credito','renegociado','preco','valor_unitario','desconto','valor_medio','receita','custo','lucro','valor_total','valor_estoque','custo_medio','saldoReceber','saldoPagar','receberVencido']);
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function element(tag,value,className){const node=document.createElement(tag);if(value!==undefined)node.textContent=String(value==null?'—':value);if(className)node.className=className;return node}
function formatted(key,value){if(value===null||value===undefined||value==='')return '—';if(moneyKeys.has(key))return money(value);if(['quantidade','quantidade_fisica','quantidade_reservada','quantidade_disponivel','quantidade_recebida','quantidade_atendida','estoque_minimo'].includes(key))return Number(value).toLocaleString('pt-BR',{maximumFractionDigits:4});if(key==='status')return states[value]||value;if(key==='tipo'&&['fisica','juridica'].includes(value))return value==='fisica'?'Pessoa física':'Pessoa jurídica';if(['criado_em','expira_em','estornado_em'].includes(key)&&String(value).length>10&&!Number.isNaN(Date.parse(value)))return new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});if(typeof value==='boolean')return value?'Sim':'Não';if(/^(data|vencimento|criado_em|expira_em|estornado_em)/.test(key)&&/^\d{4}-\d{2}-\d{2}/.test(String(value))){const iso=String(value).slice(0,10);return iso.slice(8,10)+'/'+iso.slice(5,7)+'/'+iso.slice(0,4)}return String(value)}
function button(label,fn,primary=false){const b=element('button',label,primary?'primary':'');b.type='button';b.onclick=()=>Promise.resolve(fn()).catch(showError);return b}
function pill(status){if(status==null)return element('span','—');return element('span',states[status]||status,'pill '+(['saved','pago','ativo','confirmada','recebida'].includes(status)?'good':['vencido','expired','cancelled','cancelado'].includes(status)?'warn':''))}
function notice(text,success=false){return element('p',text,'notice'+(success?' success':''))}
function fields(record){const dl=element('dl');for(const [key,value] of Object.entries(record||{})){if(value===undefined||Array.isArray(value)||typeof value==='object'&&value!==null)continue;const group=element('div');group.append(element('dt',labels[key]||key.replaceAll('_',' ')));const dd=element('dd');dd.append(key==='status'?pill(value):element('span',formatted(key,value)));group.append(dd);dl.append(group)}return dl}
function metrics(items){const grid=element('section',undefined,'metrics');grid.setAttribute('aria-label','Indicadores');for(const [label,value,isMoney=true] of items){const tile=element('div',undefined,'metric');tile.append(element('span',label,'muted'),element('strong',isMoney?money(value):value));grid.append(tile)}return grid}
function table(rows,keys,action,caption){if(!rows.length)return element('p','Nenhum registro encontrado para esta consulta.','empty');keys=keys||Array.from(new Set(rows.flatMap(row=>Object.keys(row)))).filter(k=>!k.startsWith('__')&&rows.every(row=>row[k]==null||typeof row[k]!=='object'));const wrap=element('div',undefined,'scroll'),t=element('table');if(caption)t.append(element('caption',caption));const head=element('thead'),tr=element('tr');for(const key of keys){const th=element('th',labels[key]||key.replaceAll('_',' '));th.scope='col';tr.append(th)}if(action)tr.append(element('th','Ação'));head.append(tr);t.append(head);const body=element('tbody');for(const row of rows){const line=element('tr');for(const key of keys){const td=element('td');td.append(key==='status'?pill(row[key]):element('span',formatted(key,row[key])));line.append(td)}if(action){const td=element('td');td.append(button(action.label,()=>action.run(row)));line.append(td)}body.append(line)}t.append(body);wrap.append(t);return wrap}
function inputField(label,value,type='text'){const box=element('label',label),input=element('input');input.type=type;input.value=value||'';if(type==='text')input.maxLength=200;box.append(input);return {box,input}}
function sourceTitle(p){if(p.consulta==='consultar_financeiro'||p.consulta==='obter_parcela_financeira')return p.parametros.tipo==='pagar'?'Contas a pagar':'Contas a receber';if(p.consulta==='buscar_cadastros'||p.consulta==='obter_cadastro')return {clientes:'Clientes',fornecedores:'Fornecedores',produtos:'Produtos',servicos:'Serviços'}[p.parametros.tipo];return {listar_vendas:'Vendas',listar_compras:'Compras',listar_orcamentos:'Orçamentos',consultar_estoque:'Estoque',obter_cliente:'Cliente',obter_venda:'Venda',obter_compra:'Compra',listar_pagamentos:'Pagamentos',listar_contas_financeiras:'Contas financeiras',meu_acesso:'Empresas',consultar_relatorio:'Relatório',analisar_periodo:{vendas:'Vendas',compras:'Compras',pagar:'Contas a pagar',receber:'Contas a receber'}[p.parametros.tipo]}[p.consulta]||'ERP'}
function heading(p,title){const header=element('header');header.append(element('span','◈ Cognito','brand'),element('span',p.empresa?.nome||'Sua conexão com o ERP','muted'));body.append(header,element('h1',title));const subtitle=['revisao','resultado'].includes(p.card)?'Aprovação no ERP':sourceTitle(p);if(subtitle&&subtitle!==title)body.append(element('p',subtitle,'scope muted'))}
function detailRequest(p,row){const args=p.parametros,company=p.empresa?.id;let consulta,parametros;if(['listar_vendas','listar_orcamentos'].includes(p.consulta)){consulta='obter_venda';parametros={venda_id:Number(row.id)}}else if(p.consulta==='listar_compras'){consulta='obter_compra';parametros={compra_id:Number(row.id)}}else if(p.consulta==='consultar_financeiro'){consulta='obter_parcela_financeira';parametros={tipo:args.tipo,parcela_id:Number(row.id)}}else if(p.consulta==='buscar_cadastros'){consulta='obter_cadastro';parametros={tipo:args.tipo,registro_id:Number(row.id)}}else return null;return {card:'detalhes',empresa_id:company,consulta,parametros}}
function pager(p,data){if(data.page===undefined)return;const page=data.page||1,size=data.pageSize||20;const nav=element('div',undefined,'pager'),previous=button('Anterior',()=>reload({...p.parametros,pagina:page-1})),next=button('Próxima',()=>reload({...p.parametros,pagina:page+1}));previous.disabled=page<=1;next.disabled=!(data.hasMore??page*size<Number(data.total));nav.append(previous,element('span','Página '+page+(data.total!==undefined?' · '+data.total+' registros':''),'muted'),next);body.append(nav)}
function filterForm(p,{dates=false,statuses=[],search=true}={}){const form=element('form',undefined,'toolbar');const values=[];if(search){const f=inputField('Buscar',p.parametros.busca);values.push(['busca',f.input]);form.append(f.box)}if(statuses.length){const label=element('label','Situação'),select=element('select');select.setAttribute('aria-label','Situação');const all=element('option','Todas');all.value='';select.append(all);for(const state of statuses){const o=element('option',states[state]||state);o.value=state;select.append(o)}select.value=p.parametros.status||'';values.push(['status',select]);label.append(select);form.append(label)}if(dates){const financial=p.consulta==='consultar_financeiro';for(const [label,key] of [['De',financial?'vencimento_inicio':'inicio'],['Até',financial?'vencimento_fim':'fim']]){const f=inputField(label,p.parametros[key],'date');values.push([key,f.input]);form.append(f.box)}}const submit=element('button','Aplicar');submit.type='submit';form.append(submit);form.onsubmit=e=>{e.preventDefault();const args={...p.parametros};for(const [key,input] of values){delete args[key];if(input.value.trim())args[key]=input.value.trim()}if(values.some(([key])=>key==='busca'||key==='status'))args.pagina=1;reload(args).catch(showError)};body.append(form)}
`
