import {
  OTTO_INVOICE_CHATGPT_TV_CONTENT_HEIGHT,
  OTTO_INVOICE_CHATGPT_TV_CONTENT_NO_INTRO_DURATION,
  OTTO_INVOICE_CHATGPT_TV_CONTENT_WIDTH,
  OttoInvoiceChatGptTvContent,
} from '@/assets/remotion/compositions/OttoInvoiceChatGptTvContent'

export const OTTO_INVOICE_CHATGPT_MONITOR_CONTENT_DURATION = OTTO_INVOICE_CHATGPT_TV_CONTENT_NO_INTRO_DURATION
export const OTTO_INVOICE_CHATGPT_MONITOR_CONTENT_WIDTH = OTTO_INVOICE_CHATGPT_TV_CONTENT_WIDTH
export const OTTO_INVOICE_CHATGPT_MONITOR_CONTENT_HEIGHT = OTTO_INVOICE_CHATGPT_TV_CONTENT_HEIGHT

export function OttoInvoiceChatGptMonitorContent() {
  return <OttoInvoiceChatGptTvContent titleFontSize={180} withIntro={false} />
}
