// Whitelist para ordenação segura por view
export const ORDER_BY_WHITELIST: Record<string, Record<string, string>> = {
  'lancamentos': {
    lancamento_id: 'lc.id',
    data_lancamento: 'lc.data_lancamento',
    conta_id: 'lcl.conta_id',
    debito: 'lcl.debito',
    credito: 'lcl.credito',
    criado_em: 'lcl.criado_em',
  },
  'plano-contas': {
    id: 'pc.id',
    codigo: 'pc.codigo',
    nome: 'pc.nome',
    grupo_principal: "LEFT(pc.codigo, 1)",
    nivel: 'pc.nivel',
    aceita_lancamento: 'pc.aceita_lancamento',
    codigo_pai: 'pai.codigo',
    conta_pai: 'pai.nome',
    criado_em: 'pc.criado_em',
    atualizado_em: 'pc.atualizado_em',
  },
  'categorias': {
    id: 'pcc.id',
    codigo: 'pcc.codigo',
    nome: 'pcc.nome',
    tipo: 'pcc.tipo',
    nivel: 'pcc.nivel',
    ordem: 'pcc.ordem',
    ativo: 'pcc.ativo',
    criado_em: 'pcc.criado_em',
  },
  'segmentos': {
    id: 'pcs.id',
    codigo: 'pcs.codigo',
    nome: 'pcs.nome',
    ordem: 'pcs.ordem',
    separador: 'pcs.separador',
    ativo: 'pcs.ativo',
    criado_em: 'pcs.criado_em',
  },
  'centros-de-custo': {
    id: 'cc.id',
    codigo: 'cc.codigo',
    nome: 'cc.nome',
    criado_em: 'cc.criado_em',
    atualizado_em: 'cc.atualizado_em',
  },
  'centros-de-lucro': {
    id: 'cl.id',
    codigo: 'cl.codigo',
    nome: 'cl.nome',
    criado_em: 'cl.criado_em',
    atualizado_em: 'cl.atualizado_em',
  },
  'regras-contabeis': {
    id: 'r.id',
    origem: 'r.origem',
    subtipo: 'r.subtipo',
    plano_conta_id: 'r.plano_conta_id',
    conta_debito_id: 'r.conta_debito_id',
    codigo_conta_debito: 'd.codigo',
    conta_debito: 'd.nome',
    conta_credito_id: 'r.conta_credito_id',
    codigo_conta_credito: 'c.codigo',
    conta_credito: 'c.nome',
    descricao: 'r.descricao',
    criado_em: 'r.criado_em',
    atualizado_em: 'r.atualizado_em',
  },
}
