import type { NormalizedTableName } from '@/products/integracoes/datawarehouse/normalization/contracts'

export type BigQueryFieldSchema = {
  name: string
  type: 'STRING' | 'INTEGER' | 'NUMERIC' | 'DATE' | 'TIMESTAMP' | 'JSON'
  mode?: 'REQUIRED' | 'NULLABLE'
}

const COMMON_FIELDS: BigQueryFieldSchema[] = [
  { name: 'tenant_id', type: 'INTEGER', mode: 'REQUIRED' },
  { name: 'connection_id', type: 'STRING', mode: 'REQUIRED' },
  { name: 'provider', type: 'STRING', mode: 'REQUIRED' },
  { name: 'resource', type: 'STRING', mode: 'REQUIRED' },
  { name: 'external_id', type: 'STRING' },
  { name: 'source_run_id', type: 'STRING' },
  { name: 'source_table', type: 'STRING' },
  { name: 'synced_at', type: 'TIMESTAMP', mode: 'REQUIRED' },
  { name: 'normalized_at', type: 'TIMESTAMP', mode: 'REQUIRED' },
]

const CONTACT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'documento', type: 'STRING' },
  { name: 'tipo_pessoa', type: 'STRING' },
  { name: 'email', type: 'STRING' },
  { name: 'telefone', type: 'STRING' },
  { name: 'cidade', type: 'STRING' },
  { name: 'uf', type: 'STRING' },
  { name: 'status', type: 'STRING' },
]

const BASIC_REGISTRY_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'codigo', type: 'STRING' },
  { name: 'descricao', type: 'STRING' },
  { name: 'tipo', type: 'STRING' },
  { name: 'status', type: 'STRING' },
]

const OPERATIONAL_EVENT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'numero', type: 'STRING' },
  { name: 'descricao', type: 'STRING' },
  { name: 'status', type: 'STRING' },
  { name: 'data', type: 'DATE' },
  { name: 'valor_total', type: 'NUMERIC' },
]

const CRM_PERSON_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'email', type: 'STRING' },
  { name: 'telefone', type: 'STRING' },
  { name: 'cargo', type: 'STRING' },
  { name: 'conta_id', type: 'STRING' },
  { name: 'conta_nome', type: 'STRING' },
  { name: 'responsavel_id', type: 'STRING' },
  { name: 'responsavel_nome', type: 'STRING' },
  { name: 'status', type: 'STRING' },
  { name: 'criado_em', type: 'TIMESTAMP' },
  { name: 'atualizado_em', type: 'TIMESTAMP' },
]

const CRM_PIPELINE_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'codigo', type: 'STRING' },
  { name: 'ordem', type: 'INTEGER' },
  { name: 'status', type: 'STRING' },
  { name: 'criado_em', type: 'TIMESTAMP' },
  { name: 'atualizado_em', type: 'TIMESTAMP' },
]

const SOCIAL_CONTENT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'profile_id', type: 'STRING' },
  { name: 'titulo', type: 'STRING' },
  { name: 'texto', type: 'STRING' },
  { name: 'url', type: 'STRING' },
  { name: 'tipo', type: 'STRING' },
  { name: 'published_at', type: 'TIMESTAMP' },
  { name: 'views', type: 'NUMERIC' },
  { name: 'likes', type: 'NUMERIC' },
  { name: 'comments', type: 'NUMERIC' },
  { name: 'shares', type: 'NUMERIC' },
  { name: 'saves', type: 'NUMERIC' },
  { name: 'status', type: 'STRING' },
]

const SOCIAL_DAILY_METRIC_FIELDS: BigQueryFieldSchema[] = [
  { name: 'profile_id', type: 'STRING' },
  { name: 'data_ref', type: 'DATE' },
  { name: 'metric', type: 'STRING' },
  { name: 'value', type: 'NUMERIC' },
  { name: 'views', type: 'NUMERIC' },
  { name: 'impressions', type: 'NUMERIC' },
  { name: 'reach', type: 'NUMERIC' },
  { name: 'likes', type: 'NUMERIC' },
  { name: 'comments', type: 'NUMERIC' },
  { name: 'shares', type: 'NUMERIC' },
  { name: 'followers', type: 'NUMERIC' },
  { name: 'engagement_rate', type: 'NUMERIC' },
]

const PAID_MEDIA_ENTITY_FIELDS: BigQueryFieldSchema[] = [
  { name: 'account_id', type: 'STRING' },
  { name: 'campaign_id', type: 'STRING' },
  { name: 'ad_group_id', type: 'STRING' },
  { name: 'ad_id', type: 'STRING' },
  { name: 'nome', type: 'STRING' },
  { name: 'status', type: 'STRING' },
  { name: 'tipo', type: 'STRING' },
  { name: 'objetivo', type: 'STRING' },
  { name: 'orcamento', type: 'NUMERIC' },
  { name: 'criado_em', type: 'TIMESTAMP' },
  { name: 'atualizado_em', type: 'TIMESTAMP' },
]

const PAID_MEDIA_METRIC_FIELDS: BigQueryFieldSchema[] = [
  { name: 'data_ref', type: 'DATE' },
  { name: 'nivel', type: 'STRING' },
  { name: 'account_id', type: 'STRING' },
  { name: 'campaign_id', type: 'STRING' },
  { name: 'campaign_name', type: 'STRING' },
  { name: 'ad_group_id', type: 'STRING' },
  { name: 'ad_group_name', type: 'STRING' },
  { name: 'ad_id', type: 'STRING' },
  { name: 'ad_name', type: 'STRING' },
  { name: 'spend', type: 'NUMERIC' },
  { name: 'currency', type: 'STRING' },
  { name: 'impressions', type: 'NUMERIC' },
  { name: 'reach', type: 'NUMERIC' },
  { name: 'clicks', type: 'NUMERIC' },
  { name: 'conversions', type: 'NUMERIC' },
  { name: 'conversion_value', type: 'NUMERIC' },
  { name: 'ctr', type: 'NUMERIC' },
  { name: 'cpc', type: 'NUMERIC' },
  { name: 'cpm', type: 'NUMERIC' },
  { name: 'roas', type: 'NUMERIC' },
]

const ECOMMERCE_PRODUCT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'produto_id', type: 'STRING' },
  { name: 'nome', type: 'STRING' },
  { name: 'sku', type: 'STRING' },
  { name: 'descricao', type: 'STRING' },
  { name: 'categoria_id', type: 'STRING' },
  { name: 'categoria_nome', type: 'STRING' },
  { name: 'preco', type: 'NUMERIC' },
  { name: 'preco_promocional', type: 'NUMERIC' },
  { name: 'custo', type: 'NUMERIC' },
  { name: 'estoque', type: 'NUMERIC' },
  { name: 'status', type: 'STRING' },
  { name: 'url', type: 'STRING' },
  { name: 'criado_em', type: 'TIMESTAMP' },
  { name: 'atualizado_em', type: 'TIMESTAMP' },
]

const ECOMMERCE_ORDER_FIELDS: BigQueryFieldSchema[] = [
  { name: 'pedido_id', type: 'STRING' },
  { name: 'numero', type: 'STRING' },
  { name: 'cliente_id', type: 'STRING' },
  { name: 'cliente_nome', type: 'STRING' },
  { name: 'cliente_email', type: 'STRING' },
  { name: 'status', type: 'STRING' },
  { name: 'status_pagamento', type: 'STRING' },
  { name: 'status_fulfillment', type: 'STRING' },
  { name: 'currency', type: 'STRING' },
  { name: 'subtotal', type: 'NUMERIC' },
  { name: 'desconto', type: 'NUMERIC' },
  { name: 'frete', type: 'NUMERIC' },
  { name: 'impostos', type: 'NUMERIC' },
  { name: 'valor_total', type: 'NUMERIC' },
  { name: 'data_pedido', type: 'TIMESTAMP' },
  { name: 'atualizado_em', type: 'TIMESTAMP' },
]

const ANALYTICS_DAILY_METRIC_FIELDS: BigQueryFieldSchema[] = [
  { name: 'data_ref', type: 'DATE' },
  { name: 'property_id', type: 'STRING' },
  { name: 'site_url', type: 'STRING' },
  { name: 'location_id', type: 'STRING' },
  { name: 'channel', type: 'STRING' },
  { name: 'page_url', type: 'STRING' },
  { name: 'query', type: 'STRING' },
  { name: 'event_name', type: 'STRING' },
  { name: 'metric', type: 'STRING' },
  { name: 'value', type: 'NUMERIC' },
  { name: 'active_users', type: 'NUMERIC' },
  { name: 'total_users', type: 'NUMERIC' },
  { name: 'sessions', type: 'NUMERIC' },
  { name: 'pageviews', type: 'NUMERIC' },
  { name: 'events', type: 'NUMERIC' },
  { name: 'conversions', type: 'NUMERIC' },
  { name: 'clicks', type: 'NUMERIC' },
  { name: 'impressions', type: 'NUMERIC' },
  { name: 'ctr', type: 'NUMERIC' },
  { name: 'position', type: 'NUMERIC' },
]

const TABLE_FIELDS: Record<NormalizedTableName, BigQueryFieldSchema[]> = {
  clientes: CONTACT_FIELDS,
  fornecedores: CONTACT_FIELDS,
  produtos: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'unidade', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  servicos: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'tipo_servico', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  contas_receber: [
    { name: 'pessoa_id', type: 'STRING' },
    { name: 'pessoa_nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'valor_pago', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
  ],
  contas_pagar: [
    { name: 'pessoa_id', type: 'STRING' },
    { name: 'pessoa_nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'valor_pago', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
  ],
  vendas: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_pedido', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  contratos: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_inicio', type: 'DATE' },
    { name: 'data_fim', type: 'DATE' },
    { name: 'frequencia', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  itens_venda: [
    { name: 'venda_id', type: 'STRING' },
    { name: 'item_id', type: 'STRING' },
    { name: 'produto_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'valor_unitario', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  venda_detalhes: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_pedido', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'vendedor_id', type: 'STRING' },
    { name: 'vendedor_nome', type: 'STRING' },
    { name: 'categoria_id', type: 'STRING' },
    { name: 'centro_custo_id', type: 'STRING' },
    { name: 'observacoes', type: 'STRING' },
  ],
  notas_fiscais: [
    { name: 'chave_acesso', type: 'STRING' },
    { name: 'numero_nota', type: 'STRING' },
    { name: 'destinatario_nome', type: 'STRING' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  notas_fiscais_servico: [
    { name: 'id', type: 'STRING' },
    { name: 'id_venda', type: 'STRING' },
    { name: 'id_contrato', type: 'STRING' },
    { name: 'numero_nfse', type: 'STRING' },
    { name: 'numero_rps', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'data_competencia', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  categorias: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'categoria_pai_id', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  centros_custo: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  contas_financeiras: [
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'banco', type: 'STRING' },
    { name: 'agencia', type: 'STRING' },
    { name: 'conta', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  transferencias: [
    { name: 'conta_origem_id', type: 'STRING' },
    { name: 'conta_destino_id', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'data_transferencia', type: 'DATE' },
    { name: 'descricao', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  estoque_atual: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'produto_nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'unidade', type: 'STRING' },
    { name: 'local', type: 'STRING' },
    { name: 'updated_at', type: 'DATE' },
  ],
  compras: [
    { name: 'fornecedor_id', type: 'STRING' },
    { name: 'fornecedor_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_compra', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  parcelas_venda: [
    { name: 'venda_id', type: 'STRING' },
    { name: 'parcela_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  vendedores: CONTACT_FIELDS,
  variacoes: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  marcas: BASIC_REGISTRY_FIELDS,
  notas_consumidor: [
    { name: 'chave_acesso', type: 'STRING' },
    { name: 'numero_nota', type: 'STRING' },
    { name: 'destinatario_nome', type: 'STRING' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  expedicoes: [
    { name: 'pedido_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'transportadora', type: 'STRING' },
    { name: 'codigo_rastreio', type: 'STRING' },
    { name: 'data_envio', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  separacoes: [
    { name: 'pedido_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'responsavel', type: 'STRING' },
    { name: 'data', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  estoque_movimentacoes: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'produto_nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'tipo', type: 'STRING' },
    { name: 'local', type: 'STRING' },
    { name: 'data', type: 'DATE' },
  ],
  listas_preco: BASIC_REGISTRY_FIELDS,
  formas_envio: BASIC_REGISTRY_FIELDS,
  formas_pagamento: BASIC_REGISTRY_FIELDS,
  intermediadores: BASIC_REGISTRY_FIELDS,
  transportadoras: BASIC_REGISTRY_FIELDS,
  canais_venda: BASIC_REGISTRY_FIELDS,
  lojas: BASIC_REGISTRY_FIELDS,
  depositos: BASIC_REGISTRY_FIELDS,
  produto_categorias: BASIC_REGISTRY_FIELDS,
  produto_cest: BASIC_REGISTRY_FIELDS,
  produto_ecommerce_marcas: BASIC_REGISTRY_FIELDS,
  produto_ncm: BASIC_REGISTRY_FIELDS,
  produto_unidades_medida: BASIC_REGISTRY_FIELDS,
  categorias_dre: BASIC_REGISTRY_FIELDS,
  saldos_contas_financeiras: [
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'banco', type: 'STRING' },
    { name: 'agencia', type: 'STRING' },
    { name: 'conta', type: 'STRING' },
    { name: 'saldo', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  eventos_financeiros_alteracoes: OPERATIONAL_EVENT_FIELDS,
  saldos_iniciais: OPERATIONAL_EVENT_FIELDS,
  venda_proximo_numero: OPERATIONAL_EVENT_FIELDS,
  contrato_proximo_numero: OPERATIONAL_EVENT_FIELDS,
  lancamentos_financeiros: OPERATIONAL_EVENT_FIELDS,
  contas_correntes: [
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'banco', type: 'STRING' },
    { name: 'agencia', type: 'STRING' },
    { name: 'conta', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  empresa_conectada: [
    { name: 'nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'cidade', type: 'STRING' },
    { name: 'uf', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  uso_api: [
    { name: 'nome', type: 'STRING' },
    { name: 'limite', type: 'NUMERIC' },
    { name: 'utilizado', type: 'NUMERIC' },
    { name: 'disponivel', type: 'NUMERIC' },
    { name: 'periodo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  gatilhos: OPERATIONAL_EVENT_FIELDS,
  contas: [
    { name: 'nome', type: 'STRING' },
    { name: 'dominio', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'setor', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'cidade', type: 'STRING' },
    { name: 'uf', type: 'STRING' },
    { name: 'pais', type: 'STRING' },
    { name: 'responsavel_id', type: 'STRING' },
    { name: 'responsavel_nome', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  contatos: CRM_PERSON_FIELDS,
  leads: [
    { name: 'nome', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'empresa', type: 'STRING' },
    { name: 'origem', type: 'STRING' },
    { name: 'pipeline_id', type: 'STRING' },
    { name: 'fase_id', type: 'STRING' },
    { name: 'responsavel_id', type: 'STRING' },
    { name: 'responsavel_nome', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  oportunidades: [
    { name: 'nome', type: 'STRING' },
    { name: 'conta_id', type: 'STRING' },
    { name: 'conta_nome', type: 'STRING' },
    { name: 'contato_id', type: 'STRING' },
    { name: 'contato_nome', type: 'STRING' },
    { name: 'pipeline_id', type: 'STRING' },
    { name: 'fase_id', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'moeda', type: 'STRING' },
    { name: 'probabilidade', type: 'NUMERIC' },
    { name: 'data_fechamento', type: 'DATE' },
    { name: 'responsavel_id', type: 'STRING' },
    { name: 'responsavel_nome', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  atividades: [
    { name: 'titulo', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'due_at', type: 'TIMESTAMP' },
    { name: 'concluido_em', type: 'TIMESTAMP' },
    { name: 'conta_id', type: 'STRING' },
    { name: 'contato_id', type: 'STRING' },
    { name: 'oportunidade_id', type: 'STRING' },
    { name: 'responsavel_id', type: 'STRING' },
    { name: 'responsavel_nome', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  usuarios: [
    { name: 'nome', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'cargo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  pipelines: CRM_PIPELINE_FIELDS,
  fases_pipeline: [
    { name: 'pipeline_id', type: 'STRING' },
    { name: 'pipeline_nome', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'ordem', type: 'INTEGER' },
    { name: 'probabilidade', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  social_profiles: [
    { name: 'nome', type: 'STRING' },
    { name: 'username', type: 'STRING' },
    { name: 'url', type: 'STRING' },
    { name: 'avatar_url', type: 'STRING' },
    { name: 'followers', type: 'NUMERIC' },
    { name: 'following', type: 'NUMERIC' },
    { name: 'posts_count', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  social_posts: SOCIAL_CONTENT_FIELDS,
  social_videos: SOCIAL_CONTENT_FIELDS,
  social_comments: [
    { name: 'post_id', type: 'STRING' },
    { name: 'profile_id', type: 'STRING' },
    { name: 'author_id', type: 'STRING' },
    { name: 'author_name', type: 'STRING' },
    { name: 'texto', type: 'STRING' },
    { name: 'created_at', type: 'TIMESTAMP' },
    { name: 'likes', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  social_audience_daily: SOCIAL_DAILY_METRIC_FIELDS,
  social_performance_daily: SOCIAL_DAILY_METRIC_FIELDS,
  social_engagement_daily: SOCIAL_DAILY_METRIC_FIELDS,
  paid_media_accounts: [
    { name: 'account_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'currency', type: 'STRING' },
    { name: 'timezone', type: 'STRING' },
  ],
  paid_media_campaigns: PAID_MEDIA_ENTITY_FIELDS,
  paid_media_ad_groups: PAID_MEDIA_ENTITY_FIELDS,
  paid_media_ads: PAID_MEDIA_ENTITY_FIELDS,
  paid_media_creatives: [
    { name: 'account_id', type: 'STRING' },
    { name: 'campaign_id', type: 'STRING' },
    { name: 'ad_group_id', type: 'STRING' },
    { name: 'ad_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'titulo', type: 'STRING' },
    { name: 'texto', type: 'STRING' },
    { name: 'url', type: 'STRING' },
    { name: 'thumbnail_url', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  paid_media_keywords: [
    { name: 'account_id', type: 'STRING' },
    { name: 'campaign_id', type: 'STRING' },
    { name: 'ad_group_id', type: 'STRING' },
    { name: 'keyword_id', type: 'STRING' },
    { name: 'keyword_text', type: 'STRING' },
    { name: 'match_type', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'data_ref', type: 'DATE' },
    { name: 'spend', type: 'NUMERIC' },
    { name: 'impressions', type: 'NUMERIC' },
    { name: 'clicks', type: 'NUMERIC' },
    { name: 'conversions', type: 'NUMERIC' },
  ],
  paid_media_conversions: [
    { name: 'account_id', type: 'STRING' },
    { name: 'campaign_id', type: 'STRING' },
    { name: 'conversion_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'data_ref', type: 'DATE' },
    { name: 'conversions', type: 'NUMERIC' },
    { name: 'conversion_value', type: 'NUMERIC' },
  ],
  paid_media_insights_daily: PAID_MEDIA_METRIC_FIELDS,
  analytics_accounts: [
    { name: 'account_id', type: 'STRING' },
    { name: 'property_id', type: 'STRING' },
    { name: 'site_url', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'currency', type: 'STRING' },
    { name: 'timezone', type: 'STRING' },
  ],
  analytics_locations: [
    { name: 'account_id', type: 'STRING' },
    { name: 'location_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'store_code', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'endereco', type: 'STRING' },
    { name: 'cidade', type: 'STRING' },
    { name: 'uf', type: 'STRING' },
    { name: 'pais', type: 'STRING' },
    { name: 'website_url', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  analytics_traffic_daily: ANALYTICS_DAILY_METRIC_FIELDS,
  analytics_pages_daily: ANALYTICS_DAILY_METRIC_FIELDS,
  analytics_queries_daily: ANALYTICS_DAILY_METRIC_FIELDS,
  analytics_events_daily: ANALYTICS_DAILY_METRIC_FIELDS,
  analytics_reviews: [
    { name: 'review_id', type: 'STRING' },
    { name: 'location_id', type: 'STRING' },
    { name: 'author_name', type: 'STRING' },
    { name: 'rating', type: 'STRING' },
    { name: 'comment', type: 'STRING' },
    { name: 'reply_comment', type: 'STRING' },
    { name: 'created_at', type: 'TIMESTAMP' },
    { name: 'updated_at', type: 'TIMESTAMP' },
    { name: 'status', type: 'STRING' },
  ],
  analytics_local_posts: [
    { name: 'post_id', type: 'STRING' },
    { name: 'location_id', type: 'STRING' },
    { name: 'titulo', type: 'STRING' },
    { name: 'texto', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'url', type: 'STRING' },
    { name: 'created_at', type: 'TIMESTAMP' },
    { name: 'updated_at', type: 'TIMESTAMP' },
  ],
  ecommerce_stores: [
    { name: 'loja_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'dominio', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'currency', type: 'STRING' },
    { name: 'timezone', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  ecommerce_customers: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'cidade', type: 'STRING' },
    { name: 'uf', type: 'STRING' },
    { name: 'total_pedidos', type: 'NUMERIC' },
    { name: 'valor_total_gasto', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  ecommerce_products: ECOMMERCE_PRODUCT_FIELDS,
  ecommerce_variants: [
    { name: 'variante_id', type: 'STRING' },
    { name: 'produto_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'preco_promocional', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'estoque', type: 'NUMERIC' },
    { name: 'peso', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
    { name: 'criado_em', type: 'TIMESTAMP' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  ecommerce_orders: ECOMMERCE_ORDER_FIELDS,
  ecommerce_order_items: [
    { name: 'pedido_id', type: 'STRING' },
    { name: 'item_id', type: 'STRING' },
    { name: 'produto_id', type: 'STRING' },
    { name: 'variante_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'valor_unitario', type: 'NUMERIC' },
    { name: 'desconto', type: 'NUMERIC' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  ecommerce_payments: [
    { name: 'pagamento_id', type: 'STRING' },
    { name: 'pedido_id', type: 'STRING' },
    { name: 'metodo', type: 'STRING' },
    { name: 'gateway', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'currency', type: 'STRING' },
    { name: 'data_pagamento', type: 'TIMESTAMP' },
  ],
  ecommerce_refunds: [
    { name: 'reembolso_id', type: 'STRING' },
    { name: 'pedido_id', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'motivo', type: 'STRING' },
    { name: 'data_reembolso', type: 'TIMESTAMP' },
  ],
  ecommerce_shipping: [
    { name: 'frete_id', type: 'STRING' },
    { name: 'pedido_id', type: 'STRING' },
    { name: 'transportadora', type: 'STRING' },
    { name: 'servico', type: 'STRING' },
    { name: 'codigo_rastreio', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'enviado_em', type: 'TIMESTAMP' },
    { name: 'entregue_em', type: 'TIMESTAMP' },
  ],
  ecommerce_inventory: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'variante_id', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'local_id', type: 'STRING' },
    { name: 'local_nome', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'atualizado_em', type: 'TIMESTAMP' },
  ],
  ecommerce_categories: [
    { name: 'categoria_id', type: 'STRING' },
    { name: 'categoria_pai_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'url', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  ecommerce_coupons: [
    { name: 'cupom_id', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
    { name: 'inicio_em', type: 'TIMESTAMP' },
    { name: 'fim_em', type: 'TIMESTAMP' },
  ],
  ecommerce_abandoned_checkouts: [
    { name: 'checkout_id', type: 'STRING' },
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_email', type: 'STRING' },
    { name: 'status', type: 'STRING' },
    { name: 'currency', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_abandono', type: 'TIMESTAMP' },
    { name: 'url_recuperacao', type: 'STRING' },
  ],
}

export const NORMALIZED_TABLE_NAMES = Object.freeze(
  Object.keys(TABLE_FIELDS) as NormalizedTableName[],
)

export function getNormalizedTableSchema(table: NormalizedTableName): BigQueryFieldSchema[] {
  return [
    ...COMMON_FIELDS,
    ...TABLE_FIELDS[table],
    { name: 'source_payload', type: 'JSON', mode: 'REQUIRED' },
  ]
}
