import type { NormalizedTableName } from '@/products/integracoes/datawarehouse/normalization/contracts'

export type BigQueryFieldSchema = {
  name: string
  type: 'STRING' | 'INTEGER' | 'NUMERIC' | 'DATE' | 'TIMESTAMP' | 'JSON'
  mode?: 'REQUIRED' | 'NULLABLE'
}

const COMMON_FIELDS: BigQueryFieldSchema[] = [
  { name: 'tenant_id', type: 'INTEGER', mode: 'REQUIRED' },
  { name: 'connection_id', type: 'STRING', mode: 'REQUIRED' },
  { name: 'provider', type: 'STRING', mode: 'REQUIRED' },
  { name: 'resource', type: 'STRING', mode: 'REQUIRED' },
  { name: 'external_id', type: 'STRING' },
  { name: 'source_run_id', type: 'STRING' },
  { name: 'source_table', type: 'STRING' },
  { name: 'synced_at', type: 'TIMESTAMP', mode: 'REQUIRED' },
  { name: 'normalized_at', type: 'TIMESTAMP', mode: 'REQUIRED' },
]

const CONTACT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'documento', type: 'STRING' },
  { name: 'tipo_pessoa', type: 'STRING' },
  { name: 'email', type: 'STRING' },
  { name: 'telefone', type: 'STRING' },
  { name: 'cidade', type: 'STRING' },
  { name: 'uf', type: 'STRING' },
  { name: 'status', type: 'STRING' },
]

const BASIC_REGISTRY_FIELDS: BigQueryFieldSchema[] = [
  { name: 'nome', type: 'STRING' },
  { name: 'codigo', type: 'STRING' },
  { name: 'descricao', type: 'STRING' },
  { name: 'tipo', type: 'STRING' },
  { name: 'status', type: 'STRING' },
]

const OPERATIONAL_EVENT_FIELDS: BigQueryFieldSchema[] = [
  { name: 'numero', type: 'STRING' },
  { name: 'descricao', type: 'STRING' },
  { name: 'status', type: 'STRING' },
  { name: 'data', type: 'DATE' },
  { name: 'valor_total', type: 'NUMERIC' },
]

const TABLE_FIELDS: Record<NormalizedTableName, BigQueryFieldSchema[]> = {
  clientes: CONTACT_FIELDS,
  fornecedores: CONTACT_FIELDS,
  produtos: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'unidade', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  servicos: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'tipo_servico', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  contas_receber: [
    { name: 'pessoa_id', type: 'STRING' },
    { name: 'pessoa_nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'valor_pago', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
  ],
  contas_pagar: [
    { name: 'pessoa_id', type: 'STRING' },
    { name: 'pessoa_nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'valor_pago', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'categoria', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
  ],
  vendas: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_pedido', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  contratos: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_inicio', type: 'DATE' },
    { name: 'data_fim', type: 'DATE' },
    { name: 'frequencia', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  itens_venda: [
    { name: 'venda_id', type: 'STRING' },
    { name: 'item_id', type: 'STRING' },
    { name: 'produto_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'valor_unitario', type: 'NUMERIC' },
    { name: 'custo', type: 'NUMERIC' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  venda_detalhes: [
    { name: 'cliente_id', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_pedido', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'vendedor_id', type: 'STRING' },
    { name: 'vendedor_nome', type: 'STRING' },
    { name: 'categoria_id', type: 'STRING' },
    { name: 'centro_custo_id', type: 'STRING' },
    { name: 'observacoes', type: 'STRING' },
  ],
  notas_fiscais: [
    { name: 'chave_acesso', type: 'STRING' },
    { name: 'numero_nota', type: 'STRING' },
    { name: 'destinatario_nome', type: 'STRING' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  notas_fiscais_servico: [
    { name: 'id', type: 'STRING' },
    { name: 'id_venda', type: 'STRING' },
    { name: 'id_contrato', type: 'STRING' },
    { name: 'numero_nfse', type: 'STRING' },
    { name: 'numero_rps', type: 'STRING' },
    { name: 'cliente_nome', type: 'STRING' },
    { name: 'data_competencia', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  categorias: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'categoria_pai_id', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  centros_custo: [
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  contas_financeiras: [
    { name: 'nome', type: 'STRING' },
    { name: 'tipo', type: 'STRING' },
    { name: 'banco', type: 'STRING' },
    { name: 'agencia', type: 'STRING' },
    { name: 'conta', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  transferencias: [
    { name: 'conta_origem_id', type: 'STRING' },
    { name: 'conta_destino_id', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'data_transferencia', type: 'DATE' },
    { name: 'descricao', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  estoque_atual: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'produto_nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'unidade', type: 'STRING' },
    { name: 'local', type: 'STRING' },
    { name: 'updated_at', type: 'DATE' },
  ],
  compras: [
    { name: 'fornecedor_id', type: 'STRING' },
    { name: 'fornecedor_nome', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'data_compra', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  parcelas_venda: [
    { name: 'venda_id', type: 'STRING' },
    { name: 'parcela_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'valor', type: 'NUMERIC' },
    { name: 'data_vencimento', type: 'DATE' },
    { name: 'data_pagamento', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  vendedores: CONTACT_FIELDS,
  variacoes: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'descricao', type: 'STRING' },
    { name: 'preco', type: 'NUMERIC' },
    { name: 'status', type: 'STRING' },
  ],
  marcas: BASIC_REGISTRY_FIELDS,
  notas_consumidor: [
    { name: 'chave_acesso', type: 'STRING' },
    { name: 'numero_nota', type: 'STRING' },
    { name: 'destinatario_nome', type: 'STRING' },
    { name: 'data_emissao', type: 'DATE' },
    { name: 'status', type: 'STRING' },
    { name: 'valor_total', type: 'NUMERIC' },
  ],
  expedicoes: [
    { name: 'pedido_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'transportadora', type: 'STRING' },
    { name: 'codigo_rastreio', type: 'STRING' },
    { name: 'data_envio', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  separacoes: [
    { name: 'pedido_id', type: 'STRING' },
    { name: 'numero', type: 'STRING' },
    { name: 'responsavel', type: 'STRING' },
    { name: 'data', type: 'DATE' },
    { name: 'status', type: 'STRING' },
  ],
  estoque_movimentacoes: [
    { name: 'produto_id', type: 'STRING' },
    { name: 'produto_nome', type: 'STRING' },
    { name: 'codigo', type: 'STRING' },
    { name: 'sku', type: 'STRING' },
    { name: 'quantidade', type: 'NUMERIC' },
    { name: 'tipo', type: 'STRING' },
    { name: 'local', type: 'STRING' },
    { name: 'data', type: 'DATE' },
  ],
  listas_preco: BASIC_REGISTRY_FIELDS,
  formas_envio: BASIC_REGISTRY_FIELDS,
  formas_pagamento: BASIC_REGISTRY_FIELDS,
  intermediadores: BASIC_REGISTRY_FIELDS,
  empresa_conectada: [
    { name: 'nome', type: 'STRING' },
    { name: 'documento', type: 'STRING' },
    { name: 'email', type: 'STRING' },
    { name: 'telefone', type: 'STRING' },
    { name: 'cidade', type: 'STRING' },
    { name: 'uf', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  uso_api: [
    { name: 'nome', type: 'STRING' },
    { name: 'limite', type: 'NUMERIC' },
    { name: 'utilizado', type: 'NUMERIC' },
    { name: 'disponivel', type: 'NUMERIC' },
    { name: 'periodo', type: 'STRING' },
    { name: 'status', type: 'STRING' },
  ],
  gatilhos: OPERATIONAL_EVENT_FIELDS,
}

export function getNormalizedTableSchema(table: NormalizedTableName): BigQueryFieldSchema[] {
  return [
    ...COMMON_FIELDS,
    ...TABLE_FIELDS[table],
    { name: 'source_payload', type: 'JSON', mode: 'REQUIRED' },
  ]
}
