import assert from 'node:assert/strict'
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import ts from 'typescript'

const root = resolve('.')
const normalized = path => relative(root, path).replaceAll('\\', '/')
const read = path => readFileSync(path, 'utf8').replaceAll('\r\n', '\n')
function files(path) {
  return readdirSync(path, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? files(resolve(path, entry.name)) : [resolve(path, entry.name)])
}
const verbs = new Set(['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'])
const routes = []
for (const file of files(resolve(root, 'src/app/api/erp')).filter(file => file.endsWith('route.ts')).sort()) {
  const source = ts.createSourceFile(file, read(file), ts.ScriptTarget.Latest, true)
  const exports = source.statements.filter(ts.isExportDeclaration)
  assert.equal(exports.length, 1, `${normalized(file)}: expected one handler export`)
  const declaration = exports[0]
  const handlerModule = declaration.moduleSpecifier?.text
  assert(handlerModule?.startsWith('@/products/erp/api/handlers/'), `${normalized(file)}: handler must be in erp/api`)
  assert(ts.isNamedExports(declaration.exportClause))
  const methods = declaration.exportClause.elements.map(item => item.name.text)
  assert(methods.length && methods.every(method => verbs.has(method)))
  for (const statement of source.statements) assert(ts.isExportDeclaration(statement) || ts.isVariableStatement(statement), `${normalized(file)}: route must contain only configuration and exports`)
  const handler = resolve(root, 'src', handlerModule.slice(2) + '.ts'), body = read(handler)
  assert(!/\b(?:runQuery|withTransaction|SELECT\s+.+FROM|INSERT\s+INTO)\b/i.test(body), `${normalized(handler)}: database access belongs in server`)
  const ast = ts.createSourceFile(handler, body, ts.ScriptTarget.Latest, true), wrappers = new Map()
  for (const statement of ast.statements.filter(ts.isVariableStatement)) {
    if (!statement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword)) continue
    for (const item of statement.declarationList.declarations) {
      if (!verbs.has(item.name.getText(ast))) continue
      assert(ts.isCallExpression(item.initializer) && item.initializer.expression.getText(ast) === 'withErpHttp', `${normalized(handler)}: HTTP method must use withErpHttp`)
      const options = Object.fromEntries(item.initializer.arguments[1].properties.map(property => {
        const value = property.initializer
        assert(ts.isStringLiteral(value) || ts.isNumericLiteral(value))
        return [property.name.getText(ast).replaceAll('"','').replaceAll("'",''), ts.isNumericLiteral(value) ? Number(value.text) : value.text]
      }))
      wrappers.set(item.name.getText(ast), options)
    }
  }
  assert.deepEqual([...wrappers.keys()].sort(), [...methods].sort(), `${normalized(file)}: route/handler methods differ`)
  const path = '/api/erp' + normalized(file).replace(/^src\/app\/api\/erp/, '').replace(/\/route\.ts$/, '')
  for (const method of methods) assert.equal(wrappers.get(method).operation, `${method} ${path}`)
  const options = methods.map(method => wrappers.get(method))
  const capabilities = [...new Set([...body.matchAll(/['"](erp\.[a-z_]+\.[a-z_]+)['"]/g)].map(match => match[1]))].sort()
  routes.push({ path, route: normalized(file), handler: normalized(handler), methods,
    authentication: options[0].authentication ?? 'session',
    maxBodyBytes: Math.max(...options.map(option => option.maxBodyBytes ?? 1048576)),
    capabilities, permissionRule: capabilities.length ? 'Capabilities vary by method; see handler.' : 'Session or dynamic module/operation capability; see handler.',
    idempotency: /requiresDurableOperation/.test(body) ? 'Required for selected resources; see handler.' : /readErpIdempotencyKey\(request.headers,\s*true\)/.test(body) ? 'Required for one or more writes; see handler.' : /readErpIdempotencyKey/.test(body) ? 'Optional header; operation-specific behavior.' : 'Business-operation rules; see handler.',
    transportOnlyFiscal: /faturar|fiscal|notas-compra/.test(path),
  })
}
for (const file of files(resolve(root,'src/products/erp/server')).filter(file=>file.endsWith('.ts'))) {
  assert(!/from\s+['"][^'"]*products\/chatgptplugin/.test(read(file)), `${normalized(file)}: ERP must not depend on plugin`)
}
const output = '// Generated by scripts/erp/api-catalog.mjs. Permissions are enforced in each handler.\nexport const ERP_API_ROUTES = ' + JSON.stringify(routes,null,2) + ' as const\n'
const table = '| Endpoint | Métodos | Autenticação | Limite do corpo | Permissões citadas no handler¹ |\n| --- | --- | --- | --- | --- |\n' + routes.map(route => `| \`${route.path}\` | ${route.methods.join(', ')} | ${route.authentication} | ${route.maxBodyBytes/1048576} MiB | ${route.capabilities.map(capability=>`\`${capability}\``).join(', ') || 'Sessão / regra dinâmica'} |`).join('\n')
const catalog = resolve(root,'src/products/erp/api/routeCatalog.ts'), guide = resolve(root,'src/products/erp/api/README.md')
const marker = /<!-- API-CATALOG:START -->[\s\S]*?<!-- API-CATALOG:END -->/
const originalGuide = read(guide)
assert(marker.test(originalGuide), 'README catalog markers missing')
const documentation = originalGuide.replace(marker, '<!-- API-CATALOG:START -->\n' + table + '\n<!-- API-CATALOG:END -->')
if (process.argv.includes('--write')) { writeFileSync(catalog,output); writeFileSync(guide,documentation) }
else { assert.equal(read(catalog), output, 'Catalog outdated: run erp:api-catalog:write'); assert.equal(originalGuide,documentation,'README catalog outdated: run erp:api-catalog:write') }
console.log(JSON.stringify({status:'passed',routes:routes.length,methods:routes.reduce((total,route)=>total+route.methods.length,0),mode:process.argv.includes('--write')?'write':'check'}))
