import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// Banco PostgreSQL local em memoria. Nao le .env nem aceita conexao remota.
let PGlite;
try { ({ PGlite } = await import('@electric-sql/pglite')); }
catch { ({ PGlite } = await import('../../.next/cache/retirement-pg/node_modules/@electric-sql/pglite/dist/index.js')); }
const db = new PGlite();
const root = new URL('../../', import.meta.url);
const catalog = JSON.parse(readFileSync(new URL('docs/avaliacao-erp/catalogo-revisao-tabelas.json', root), 'utf8'));
const sql1 = readFileSync(new URL('scripts/erp/sql/01-integridade-historicos.sql', root), 'utf8');
const sql2 = readFileSync(new URL('scripts/erp/sql/02-periodos-fechados.sql', root), 'utf8');
const ident = value => '"' + value.replaceAll('"', '""') + '"';
const qualified = (schema, name) => ident(schema) + '.' + ident(name);
const value = async sql => (await db.query(sql)).rows[0];
const checks = [];
async function check(name, test) { await test(); checks.push(name); }
async function isolated(sql, expectedCode, { role, tenant = 1, user = 1 } = {}) {
  await db.exec('BEGIN');
  try {
    if (role) {
      await db.exec(`SET LOCAL ROLE ${ident(role)}`);
      await db.query("SELECT set_config('app.erp_tenant_id',$1,true),set_config('app.erp_user_id',$2,true)", [String(tenant), String(user)]);
    }
    if (expectedCode) await assert.rejects(db.exec(sql), e => {
      assert.equal(e.code,expectedCode,`${sql}: ${e.message}`);
      return true;
    }, sql);
    else await db.exec(sql);
  } finally { await db.exec('ROLLBACK'); }
}

async function restoreCatalog() {
  await db.exec(`CREATE SCHEMA erp; CREATE SCHEMA shared; CREATE SCHEMA auth;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE ROLE erp_runtime NOLOGIN NOBYPASSRLS NOINHERIT;
    GRANT USAGE ON SCHEMA shared,erp TO erp_runtime,authenticated,service_role;
    CREATE SEQUENCE shared.tenants_id_seq; CREATE SEQUENCE shared.users_id_seq;
    SET check_function_bodies=off;`);
  for (const table of catalog.rls.filter(x => x.relkind === 'r')) {
    const cols = catalog.columns.filter(x => x.table_schema === table.schema && x.table_name === table.relname);
    const defs = cols.map(x => {
      const type = x.udt_name === 'numeric' ? `numeric(${x.numeric_precision},${x.numeric_scale})`
        : x.data_type === 'ARRAY' ? x.udt_name.slice(1) + '[]' : x.data_type;
      return `${ident(x.column_name)} ${type}${x.is_identity === 'YES' ? ' GENERATED BY DEFAULT AS IDENTITY'
        : x.column_default ? ' DEFAULT ' + x.column_default : ''}${x.is_nullable === 'NO' ? ' NOT NULL' : ''}`;
    });
    await db.exec(`CREATE TABLE ${qualified(table.schema,table.relname)} (${defs.join(',')})`);
  }
  // Referencias somente depois de todas as PKs/unicidades estarem presentes.
  for (const type of ['p','u','c','f']) for (const c of catalog.constraints.filter(x => x.type === type)) {
    await db.exec(`ALTER TABLE ${qualified(c.schema,c.table_name)} ADD CONSTRAINT ${ident(c.name)} ${c.definition}`);
  }
  const constraintIndexes = new Set(catalog.constraints.filter(x=>['p','u'].includes(x.type)).map(x=>x.schema+'.'+x.name));
  for (const index of catalog.indexes) if (!constraintIndexes.has(index.schemaname+'.'+index.indexname)) await db.exec(index.indexdef);
  for (const f of catalog.functions) await db.exec(f.definition);
  await db.exec('SET check_function_bodies=on');
  // Giro depende de posicao; manter as views originais para provar preservacao.
  const views = [...catalog.views].sort((a,b) => Number(b.viewname==='vw_posicao_estoque')-Number(a.viewname==='vw_posicao_estoque'));
  for (const view of views) {
    const options = catalog.rls.find(x=>x.schema===view.schemaname&&x.relname===view.viewname)?.reloptions;
    await db.exec(`CREATE VIEW ${qualified(view.schemaname,view.viewname)}${options ? ' WITH ('+options.join(',')+')' : ''} AS ${view.definition}`);
  }
  for (const t of catalog.triggers) {
    await db.exec(t.definition);
    if (t.tgenabled==='D') await db.exec(`ALTER TABLE ${qualified(t.schema,t.table_name)} DISABLE TRIGGER ${ident(t.name)}`);
  }
  for (const p of catalog.policies) {
    const roles = Array.isArray(p.roles) ? p.roles : p.roles.replace(/[{}]/g,'').split(',');
    await db.exec(`CREATE POLICY ${ident(p.policyname)} ON ${qualified(p.schemaname,p.tablename)} AS ${p.permissive}
      FOR ${p.cmd} TO ${roles.map(r=>r==='public'?'PUBLIC':ident(r)).join(',')}
      ${p.qual?'USING ('+p.qual+')':''} ${p.with_check?'WITH CHECK ('+p.with_check+')':''}`);
  }
  for (const table of catalog.rls.filter(x => x.relkind==='r'&&x.relrowsecurity)) await db.exec(`ALTER TABLE ${qualified(table.schema,table.relname)} ENABLE ROW LEVEL SECURITY`);
  for (const g of catalog.grants) await db.exec(`GRANT ${g.privilege_type} ON ${qualified(g.table_schema,g.table_name)} TO ${g.grantee==='PUBLIC'?'PUBLIC':ident(g.grantee)}`);
  await db.exec('GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime,authenticated; GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA shared TO erp_runtime,authenticated;');
}


export {db,restoreCatalog,isolated,root,assert};

