import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// Banco PostgreSQL local em memoria. Nao le .env nem aceita conexao remota.
let PGlite;
try { ({ PGlite } = await import('@electric-sql/pglite')); }
catch { ({ PGlite } = await import('../../.next/cache/retirement-pg/node_modules/@electric-sql/pglite/dist/index.js')); }
const db = new PGlite();
const root = new URL('../../', import.meta.url);
const catalog = JSON.parse(readFileSync(new URL('docs/avaliacao-erp/catalogo-revisao-tabelas.json', root), 'utf8'));
const sql1 = readFileSync(new URL('scripts/erp/sql/01-integridade-historicos.sql', root), 'utf8');
const sql2 = readFileSync(new URL('scripts/erp/sql/02-periodos-fechados.sql', root), 'utf8');
const ident = value => '"' + value.replaceAll('"', '""') + '"';
const qualified = (schema, name) => ident(schema) + '.' + ident(name);
const value = async sql => (await db.query(sql)).rows[0];
const checks = [];
async function check(name, test) { await test(); checks.push(name); }
async function isolated(sql, expectedCode, { role, tenant = 1, user = 1 } = {}) {
  await db.exec('BEGIN');
  try {
    if (role) {
      await db.exec(`SET LOCAL ROLE ${ident(role)}`);
      await db.query("SELECT set_config('app.erp_tenant_id',$1,true),set_config('app.erp_user_id',$2,true)", [String(tenant), String(user)]);
    }
    if (expectedCode) await assert.rejects(db.exec(sql), e => {
      assert.equal(e.code,expectedCode,`${sql}: ${e.message}`);
      return true;
    }, sql);
    else await db.exec(sql);
  } finally { await db.exec('ROLLBACK'); }
}

async function restoreCatalog() {
  await db.exec(`CREATE SCHEMA erp; CREATE SCHEMA shared; CREATE SCHEMA auth;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE ROLE erp_runtime NOLOGIN NOBYPASSRLS NOINHERIT;
    GRANT USAGE ON SCHEMA shared,erp TO erp_runtime,authenticated,service_role;
    CREATE SEQUENCE shared.tenants_id_seq; CREATE SEQUENCE shared.users_id_seq;
    SET check_function_bodies=off;`);
  for (const table of catalog.rls.filter(x => x.relkind === 'r')) {
    const cols = catalog.columns.filter(x => x.table_schema === table.schema && x.table_name === table.relname);
    const defs = cols.map(x => {
      const type = x.udt_name === 'numeric' ? `numeric(${x.numeric_precision},${x.numeric_scale})`
        : x.data_type === 'ARRAY' ? x.udt_name.slice(1) + '[]' : x.data_type;
      return `${ident(x.column_name)} ${type}${x.is_identity === 'YES' ? ' GENERATED BY DEFAULT AS IDENTITY'
        : x.column_default ? ' DEFAULT ' + x.column_default : ''}${x.is_nullable === 'NO' ? ' NOT NULL' : ''}`;
    });
    await db.exec(`CREATE TABLE ${qualified(table.schema,table.relname)} (${defs.join(',')})`);
  }
  // Referencias somente depois de todas as PKs/unicidades estarem presentes.
  for (const type of ['p','u','c','f']) for (const c of catalog.constraints.filter(x => x.type === type)) {
    await db.exec(`ALTER TABLE ${qualified(c.schema,c.table_name)} ADD CONSTRAINT ${ident(c.name)} ${c.definition}`);
  }
  const constraintIndexes = new Set(catalog.constraints.filter(x=>['p','u'].includes(x.type)).map(x=>x.schema+'.'+x.name));
  for (const index of catalog.indexes) if (!constraintIndexes.has(index.schemaname+'.'+index.indexname)) await db.exec(index.indexdef);
  for (const f of catalog.functions) await db.exec(f.definition);
  await db.exec('SET check_function_bodies=on');
  // Giro depende de posicao; manter as views originais para provar preservacao.
  const views = [...catalog.views].sort((a,b) => Number(b.viewname==='vw_posicao_estoque')-Number(a.viewname==='vw_posicao_estoque'));
  for (const view of views) {
    const options = catalog.rls.find(x=>x.schema===view.schemaname&&x.relname===view.viewname)?.reloptions;
    await db.exec(`CREATE VIEW ${qualified(view.schemaname,view.viewname)}${options ? ' WITH ('+options.join(',')+')' : ''} AS ${view.definition}`);
  }
  for (const t of catalog.triggers) {
    await db.exec(t.definition);
    if (t.tgenabled==='D') await db.exec(`ALTER TABLE ${qualified(t.schema,t.table_name)} DISABLE TRIGGER ${ident(t.name)}`);
  }
  for (const p of catalog.policies) {
    const roles = Array.isArray(p.roles) ? p.roles : p.roles.replace(/[{}]/g,'').split(',');
    await db.exec(`CREATE POLICY ${ident(p.policyname)} ON ${qualified(p.schemaname,p.tablename)} AS ${p.permissive}
      FOR ${p.cmd} TO ${roles.map(r=>r==='public'?'PUBLIC':ident(r)).join(',')}
      ${p.qual?'USING ('+p.qual+')':''} ${p.with_check?'WITH CHECK ('+p.with_check+')':''}`);
  }
  for (const table of catalog.rls.filter(x => x.relkind==='r'&&x.relrowsecurity)) await db.exec(`ALTER TABLE ${qualified(table.schema,table.relname)} ENABLE ROW LEVEL SECURITY`);
  for (const g of catalog.grants) await db.exec(`GRANT ${g.privilege_type} ON ${qualified(g.table_schema,g.table_name)} TO ${g.grantee==='PUBLIC'?'PUBLIC':ident(g.grantee)}`);
  await db.exec('GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime,authenticated; GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA shared TO erp_runtime,authenticated;');
}

async function seed() {
  await db.exec(`BEGIN;
    INSERT INTO shared.erp_permission_profiles(id,nome) VALUES ('consulta','Consulta');
    INSERT INTO shared.tenants(id,name,slug) VALUES (1,'Empresa teste A','teste-a'),(2,'Empresa teste B','teste-b');
    INSERT INTO shared.users(id,email,full_name) VALUES(1,'owner@example.invalid','Owner'),(2,'reader@example.invalid','Reader');
    INSERT INTO shared.tenant_memberships(tenant_id,user_id,role,status) VALUES (1,1,'owner','active'),(1,2,'viewer','active'),(2,1,'owner','active');
    INSERT INTO erp.entidades(id,tenant_id,nome,eh_cliente,eh_fornecedor) VALUES (101,1,'Cliente teste',true,true),(201,2,'Cliente B',true,true);
    INSERT INTO erp.servicos(id,tenant_id,nome) VALUES(101,1,'Servico teste');
    INSERT INTO erp.categorias(id,tenant_id,nome,tipo) VALUES(101,1,'Categoria teste','receita');
    INSERT INTO erp.centros_custo(id,tenant_id,nome) VALUES(101,1,'Centro teste');
    INSERT INTO erp.contas_financeiras(id,tenant_id,nome) VALUES(101,1,'Banco A'),(102,1,'Banco B');
    INSERT INTO erp.vendas(id,tenant_id,cliente_id,numero,data_venda,subtotal,total) VALUES
      (101,1,101,'V-JAN','2026-01-10',100,100),(102,1,101,'V-FEV','2026-02-10',100,100);
    INSERT INTO erp.vendas_itens(id,tenant_id,venda_id,servico_id,descricao,valor_unitario,total) VALUES (101,1,101,101,'Item',100,100),(102,1,102,101,'Item',100,100);
    INSERT INTO erp.vendas_recebimentos_previstos(id,tenant_id,venda_id,numero_parcela,data_vencimento,valor) VALUES (101,1,101,1,'2026-02-10',100),(102,1,102,1,'2026-03-10',100);
    INSERT INTO erp.compras(id,tenant_id,fornecedor_id,numero,data_compra,subtotal,total,tipo_compra) VALUES (101,1,101,'C-JAN','2026-01-10',100,100,'servico');
    INSERT INTO erp.compras_itens(id,tenant_id,compra_id,servico_id,descricao,valor_unitario,total) VALUES (101,1,101,101,'Terceiro',100,100);
    INSERT INTO erp.compras_parcelas_previstas(id,tenant_id,compra_id,numero_parcela,data_vencimento,valor) VALUES(101,1,101,1,'2026-02-10',100);
    INSERT INTO erp.contas_receber(id,tenant_id,cliente_id,descricao,data_competencia,data_emissao,valor_total) VALUES
      (101,1,101,'Jan','2026-01-10','2026-01-10',100),
      (102,1,101,'Fev com recebimento jan','2026-02-10','2026-02-10',200),
      (103,1,101,'Fev livre','2026-02-10','2026-02-10',100);
    INSERT INTO erp.contas_receber_parcelas(id,tenant_id,conta_receber_id,data_vencimento,valor) VALUES
      (101,1,101,'2026-02-15',100),(102,1,102,'2026-03-15',200),(103,1,103,'2026-03-15',100);
    INSERT INTO erp.contas_pagar(id,tenant_id,fornecedor_id,descricao,data_competencia,data_emissao,valor_total) VALUES (101,1,101,'Despesa jan','2026-01-10','2026-01-10',100);
    INSERT INTO erp.contas_pagar_parcelas(id,tenant_id,conta_pagar_id,data_vencimento,valor) VALUES(101,1,101,'2026-02-15',100);
    INSERT INTO erp.pagamentos(id,tenant_id,tipo,conta_receber_parcela_id,conta_financeira_id,data_pagamento,valor,valor_liquido) VALUES(101,1,'receber',102,101,'2026-01-20',50,50);
    INSERT INTO erp.transferencias_financeiras(id,tenant_id,conta_origem_id,conta_destino_id,data_transferencia,valor) VALUES(101,1,101,102,'2026-01-20',20);
    INSERT INTO erp.importacoes_bancarias(id,tenant_id,conta_financeira_id,nome_arquivo,hash_arquivo) VALUES(101,1,101,'fixture.ofx','fixture-hash');
    INSERT INTO erp.transacoes_bancarias(id,tenant_id,conta_financeira_id,importacao_bancaria_id,data_transacao,tipo,valor,descricao) VALUES(101,1,101,101,'2026-01-20','credito',50,'Fixture');
    INSERT INTO erp.rateios_financeiros(id,tenant_id,tipo,conta_receber_id,categoria_id,valor) VALUES(101,1,'receber',101,101,100);
    INSERT INTO erp.ordens_servico(id,tenant_id,cliente_id,numero) VALUES(101,1,101,'OS teste');
    INSERT INTO erp.ordens_servico_eventos(id,tenant_id,ordem_servico_id,evento) VALUES(101,1,101,'criada');
    INSERT INTO erp.vendas_eventos(id,tenant_id,venda_id,evento,versao) VALUES(101,1,101,'criada',1);
    COMMIT;`);
}

try {
  await restoreCatalog();
  await seed();
  const stockBefore = catalog.triggers.filter(x=>/estoque|inventarios/.test(x.table_name)).map(x=>x.definition);
  const baseline = await value("SELECT count(*)::int n FROM pg_tables WHERE schemaname='erp'");
  await check('antes: RLS bloqueia evento autorizado', () => isolated("INSERT INTO erp.vendas_eventos(tenant_id,venda_id,evento,versao,criado_por) VALUES(1,101,'teste',1,1)", '42501', {role:'erp_runtime'}));
  await check('antes: exclusao da importacao tenta anular tenant', () => isolated('DELETE FROM erp.importacoes_bancarias WHERE id=101', '23502'));
  await check('antes: historico de OS pode ser alterado pelo owner', () => isolated("UPDATE erp.ordens_servico_eventos SET evento='alterado' WHERE id=101"));
  await check('indice divergente aborta todo o primeiro SQL',async()=>{
    await db.exec('DROP INDEX erp.fechamentos_periodos_ativo_unico_idx; CREATE INDEX fechamentos_periodos_ativo_unico_idx ON erp.fechamentos_periodos(tenant_id)');
    await assert.rejects(db.exec(sql1),e=>e.code==='P0001'&&/divergentes/.test(e.message));
    await db.exec('ROLLBACK');
    assert.equal((await value("SELECT count(*)::int n FROM pg_policies WHERE schemaname='erp' AND policyname='vendas_eventos_runtime_insert'")).n,0);
    assert.match((await value("SELECT pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname='transacoes_bancarias_importacao_fk'")).definition,/ON DELETE SET NULL/);
    await db.exec('DROP INDEX erp.fechamentos_periodos_ativo_unico_idx');
    await db.exec(catalog.indexes.find(x=>x.indexname==='fechamentos_periodos_ativo_unico_idx').indexdef);
  });
  await db.exec(sql1);
  await check('evento de venda autorizado', () => isolated("INSERT INTO erp.vendas_eventos(tenant_id,venda_id,evento,versao,criado_por) VALUES(1,101,'teste',1,1)", null, {role:'erp_runtime'}));
  await check('evento de cadastro autorizado', () => isolated("INSERT INTO erp.cadastros_eventos(tenant_id,entidade_tipo,entidade_id,evento,versao,criado_por) VALUES(1,'entidade',101,'teste',1,1)", null, {role:'erp_runtime'}));
  await check('consulta nao ganha escrita de evento', () => isolated("INSERT INTO erp.vendas_eventos(tenant_id,venda_id,evento,versao) VALUES(1,101,'teste',1)", '42501', {role:'erp_runtime',user:2}));
  await check('evento de outra empresa continua bloqueado', () => isolated("INSERT INTO erp.cadastros_eventos(tenant_id,entidade_tipo,entidade_id,evento,versao) VALUES(2,'entidade',201,'teste',1)", '42501', {role:'erp_runtime'}));
  await check('authenticated nao ganha INSERT direto', () => isolated("INSERT INTO erp.vendas_eventos(tenant_id,venda_id,evento,versao) VALUES(1,101,'teste',1)", '42501', {role:'authenticated'}));
  for (const operation of ["UPDATE erp.ordens_servico_eventos SET evento='alterado' WHERE id=101",'DELETE FROM erp.ordens_servico_eventos WHERE id=101']) {
    await check('historico OS imutavel ate para owner: '+operation.split(' ')[0],()=>isolated(operation,'P0001'));
  }
  await check('runtime nao reescreve eventos', () => isolated("UPDATE erp.vendas_eventos SET evento='alterado' WHERE id=101", '42501', {role:'erp_runtime'}));
  await check('FK preserva importacao com erro de referencia', () => isolated('DELETE FROM erp.importacoes_bancarias WHERE id=101', '23001'));
  await check('duplicata removida e indice preservado', async () => assert.deepEqual(await value("SELECT to_regclass('erp.fechamentos_periodos_ativo_idx') IS NOT NULL AS kept, to_regclass('erp.fechamentos_periodos_ativo_unico_idx') IS NULL AS removed"), {kept:true,removed:true}));
  await check('primeiro SQL repetivel', () => db.exec(sql1));

  await db.exec("INSERT INTO erp.fechamentos_periodos(id,tenant_id,modulo,periodo_inicio,periodo_fim,criado_por) VALUES(101,1,'financeiro','2026-01-01','2026-01-31',1)");
  await check('antes: data antiga pode escapar para periodo aberto', () => isolated("UPDATE erp.pagamentos SET data_pagamento='2026-02-20' WHERE id=101"));
  await check('antes: rateio fechado pode ser alterado', () => isolated('UPDATE erp.rateios_financeiros SET valor=90 WHERE id=101'));
  await db.exec(sql2);
  const denied = [
    ['mover pagamento antigo para data aberta', "UPDATE erp.pagamentos SET data_pagamento='2026-02-20' WHERE id=101"],
    ['excluir pagamento antigo', 'DELETE FROM erp.pagamentos WHERE id=101'],
    ['excluir transferencia antiga', 'DELETE FROM erp.transferencias_financeiras WHERE id=101'],
    ['excluir transacao antiga', 'DELETE FROM erp.transacoes_bancarias WHERE id=101'],
    ['inserir pagamento retroativo', "INSERT INTO erp.pagamentos(tenant_id,tipo,conta_receber_parcela_id,conta_financeira_id,data_pagamento,valor,valor_liquido) VALUES(1,'receber',103,101,'2026-01-25',10,10)"],
    ['credito bancario em periodo fechado', "INSERT INTO erp.pagamentos(tenant_id,tipo,conta_receber_parcela_id,conta_financeira_id,data_pagamento,data_credito,valor,valor_liquido) VALUES(1,'receber',103,101,'2026-02-25','2026-01-25',10,10)"],
    ['mover competencia para data aberta', "UPDATE erp.contas_receber SET data_competencia='2026-02-10' WHERE id=101"],
    ['mover competencia aberta para data fechada', "UPDATE erp.contas_receber SET data_competencia='2026-01-10' WHERE id=103"],
    ['mudar classificacao do titulo fechado', 'UPDATE erp.contas_receber SET categoria_id=101 WHERE id=101'],
    ['mudar titulo cuja baixa pertence a periodo fechado', 'UPDATE erp.contas_receber SET categoria_id=101 WHERE id=102'],
    ['mudar vencimento de parcela fechada', "UPDATE erp.contas_receber_parcelas SET data_vencimento='2026-03-10' WHERE id=101"],
    ['excluir parcela fechada', 'DELETE FROM erp.contas_pagar_parcelas WHERE id=101'],
    ['mudar valor do rateio', 'UPDATE erp.rateios_financeiros SET valor=90 WHERE id=101'],
    ['mover rateio para titulo aberto', 'UPDATE erp.rateios_financeiros SET conta_receber_id=103 WHERE id=101'],
    ['alterar item comercial fechado', 'UPDATE erp.vendas_itens SET total=90 WHERE id=101'],
    ['mover item comercial para documento aberto', 'UPDATE erp.vendas_itens SET venda_id=102 WHERE id=101'],
    ['alterar parcela prevista de venda', "UPDATE erp.vendas_recebimentos_previstos SET data_vencimento='2026-03-10' WHERE id=101"],
    ['alterar item de contratacao de terceiro', 'UPDATE erp.compras_itens SET total=90 WHERE id=101'],
    ['alterar parcela prevista de compra', "UPDATE erp.compras_parcelas_previstas SET data_vencimento='2026-03-10' WHERE id=101"],
    ['cancelar obrigacao antiga', "UPDATE erp.contas_receber SET status='cancelado' WHERE id=101"],
    ['forjar resumo pago para escapar da protecao', 'UPDATE erp.contas_receber_parcelas SET valor_pago=100 WHERE id=101'],
    ['excluir fechamento', 'DELETE FROM erp.fechamentos_periodos WHERE id=101'],
    ['mudar empresa do fechamento', 'UPDATE erp.fechamentos_periodos SET tenant_id=2 WHERE id=101'],
    ['reduzir intervalo do fechamento', "UPDATE erp.fechamentos_periodos SET periodo_fim='2026-01-15' WHERE id=101"],
    ['reabrir sem motivo', 'UPDATE erp.fechamentos_periodos SET reaberto_em=now(),reaberto_por=1 WHERE id=101'],
    ['criar fechamento sobreposto', "INSERT INTO erp.fechamentos_periodos(tenant_id,modulo,periodo_inicio,periodo_fim) VALUES(1,'financeiro','2026-01-15','2026-02-15')"],
    ['criar todos sobre fechamento financeiro', "INSERT INTO erp.fechamentos_periodos(tenant_id,modulo,periodo_inicio,periodo_fim) VALUES(1,'todos','2026-01-01','2026-01-31')"],
  ];
  for (const [name, sql] of denied) await check('bloqueia: '+name,()=>isolated(sql,'23514'));
  for (const side of ['receber','pagar']) await check('permite baixa atual de obrigacao antiga: '+side,()=>isolated(`
    INSERT INTO erp.pagamentos(tenant_id,tipo,conta_${side}_parcela_id,conta_financeira_id,data_pagamento,valor,valor_liquido)
      VALUES(1,'${side}',101,101,'2026-02-20',100,100);
    UPDATE erp.contas_${side}_parcelas SET valor_pago=100,data_pagamento='2026-02-20',status='pago' WHERE id=101;
    UPDATE erp.contas_${side} SET status='pago' WHERE id=101;`,null,{role:'erp_runtime'}));
  await check('permite status de atraso sem alterar obrigacao',()=>isolated("UPDATE erp.contas_receber_parcelas SET status='vencido' WHERE id=101",null,{role:'erp_runtime'}));
  await check('permite alteracoes em periodo aberto',()=>isolated('UPDATE erp.contas_receber SET categoria_id=101 WHERE id=103',null,{role:'erp_runtime'}));
  await check('fechamento de outra empresa nao interfere',()=>isolated("INSERT INTO erp.contas_financeiras(id,tenant_id,nome) VALUES(201,2,'Banco B'),(202,2,'Banco C'); INSERT INTO erp.transferencias_financeiras(tenant_id,conta_origem_id,conta_destino_id,data_transferencia,valor) VALUES(2,201,202,'2026-01-15',10)",null,{role:'erp_runtime',tenant:2}));
  await check('fechamento exclusivo de vendas bloqueia venda',()=>isolated("INSERT INTO erp.fechamentos_periodos(tenant_id,modulo,periodo_inicio,periodo_fim) VALUES(1,'vendas','2026-02-01','2026-02-28'); UPDATE erp.vendas SET observacoes='Edicao' WHERE id=102",'23514'));
  await check('fechamento exclusivo de vendas nao fecha financeiro',()=>isolated("INSERT INTO erp.fechamentos_periodos(tenant_id,modulo,periodo_inicio,periodo_fim) VALUES(1,'vendas','2026-02-01','2026-02-28'); UPDATE erp.contas_receber SET categoria_id=101 WHERE id=103"));
  await check('perfil de consulta nao reabre periodo',()=>isolated("UPDATE erp.fechamentos_periodos SET reaberto_em=now(),reaberto_por=2,motivo_reabertura='Teste' WHERE id=101; DO $$ BEGIN IF EXISTS(SELECT 1 FROM erp.fechamentos_periodos WHERE id=101 AND reaberto_em IS NOT NULL) THEN RAISE EXCEPTION 'RLS falhou'; END IF; END $$",null,{role:'erp_runtime',user:2}));
  await check('helpers internos nao podem ser chamados pelo runtime',()=>isolated("SELECT erp.exigir_periodo_titulo_aberto(2,101,'receber')",'42501',{role:'erp_runtime'}));
  await check('isolamento por snapshot antigo nao e aceito',()=>isolated("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ; UPDATE erp.contas_receber SET categoria_id=101 WHERE id=103",'40001'));
  await check('reabertura com motivo libera alteracao',()=>isolated("UPDATE erp.fechamentos_periodos SET reaberto_em=now(),reaberto_por=1,motivo_reabertura='Correcao autorizada' WHERE id=101; UPDATE erp.rateios_financeiros SET valor=90 WHERE id=101"));
  await check('reabertura nao pode ser apagada',()=>isolated("UPDATE erp.fechamentos_periodos SET reaberto_em=now(),reaberto_por=1,motivo_reabertura='Correcao' WHERE id=101; UPDATE erp.fechamentos_periodos SET reaberto_em=NULL,reaberto_por=NULL,motivo_reabertura=NULL WHERE id=101",'23514'));
  await check('novo fechamento apos reabertura preserva o anterior',()=>isolated("UPDATE erp.fechamentos_periodos SET reaberto_em=now(),reaberto_por=1,motivo_reabertura='Correcao' WHERE id=101; INSERT INTO erp.fechamentos_periodos(tenant_id,modulo,periodo_inicio,periodo_fim) VALUES(1,'financeiro','2026-01-01','2026-01-31')"));
  await check('segundo SQL repetivel',()=>db.exec(sql2));
  await check('nenhuma tabela nova',async()=>assert.deepEqual(await value("SELECT count(*)::int n FROM pg_tables WHERE schemaname='erp'"),baseline));
  await check('nenhuma view removida neste bloco',async()=>assert.equal((await value("SELECT count(*)::int n FROM pg_views WHERE schemaname='erp'")).n,6));
  await check('gatilhos de estoque preservados',async()=>{
    const actual=(await db.query("SELECT pg_get_triggerdef(t.oid) definition FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='erp' AND NOT t.tgisinternal AND (c.relname LIKE '%estoque%' OR c.relname LIKE '%inventarios%')")).rows.map(x=>x.definition);
    assert.deepEqual(actual.sort(),stockBefore.sort());
  });
  console.log(JSON.stringify({engine:'PGlite/PostgreSQL em memoria',snapshot:catalog.date,passed:checks.length,checks},null,2));
} catch (error) {
  console.error(JSON.stringify({passed:checks.length,code:error.code,message:error.message},null,2));
  process.exitCode=1;
} finally { await db.close(); }
