const labels: Record<string, string> = {
  pendente: 'Pendente',
  processando: 'Em processamento',
  concluida: 'Concluída',
  falha: 'Falha',
  cancelada: 'Cancelada',
  parcial: 'Parcial',
  validando: 'Em validação',
  pronta: 'Pronta',
  valida: 'Válida',
  erro: 'Erro',
  importada: 'Importada',
  ignorada: 'Ignorada',
  agendada: 'Agendada',
  enviando: 'Em envio',
  enviada: 'Enviada',
  entregue: 'Entregue',
  visualizada: 'Visualizada',
  rascunho: 'Rascunho',
  emitida: 'Emitida',
  paga: 'Paga (estado externo)',
  vencida: 'Vencida',
  aberto: 'Aberto',
  pago: 'Pago',
  vencido: 'Vencido',
  cancelado: 'Cancelado',
  renegociado: 'Renegociado',
  ativo: 'Ativo',
  inativo: 'Inativo',
  encerrado: 'Encerrado',
  suspenso: 'Suspenso',
  pausado: 'Pausado',
  confirmada: 'Confirmada',
  faturada: 'Faturada',
  recebida: 'Recebida',
  aprovada: 'Aprovada',
  em_execucao: 'Em execução',
  efetivada: 'Efetivada',
  revertida: 'Revertida',
  sucesso: 'Sucesso',
  em_aberto: 'Em aberto',
}
export function operationalStateLabel(value: unknown) {
  if (value == null || value === '') return 'Não registrado'
  return labels[String(value)] || `Situação não reconhecida (${String(value)})`
}
