import {
  createBigQueryErpAdapter,
  makeErpConfigs,
} from '@/products/plugin/server/domain-adapters/erp/providers/createBigQueryErpAdapter'

export const contaAzulErpAdapter = createBigQueryErpAdapter('conta_azul', makeErpConfigs({
  clientes: 'clientes',
  fornecedores: 'fornecedores',
  'contas-a-receber': 'contas_receber',
  'contas-a-pagar': 'contas_pagar',
  'pedidos-venda': 'vendas',
  'venda-detalhes': 'venda_detalhes',
  'venda-proximo-numero': 'venda_proximo_numero',
  'itens-venda': 'itens_venda',
  'notas-fiscais': 'notas_fiscais',
  'notas-fiscais-servico': 'notas_fiscais_servico',
  'centros-custo': 'centros_custo',
  'contas-financeiras': 'contas_financeiras',
  'saldos-contas-financeiras': 'saldos_contas_financeiras',
  transferencias: 'transferencias',
  'eventos-financeiros-alteracoes': 'eventos_financeiros_alteracoes',
  'saldos-iniciais': 'saldos_iniciais',
  'contrato-proximo-numero': 'contrato_proximo_numero',
  vendedores: 'vendedores',
  categorias: 'categorias',
  'categorias-dre': 'categorias_dre',
  produtos: 'produtos',
  'produto-categorias': 'produto_categorias',
  'produto-cest': 'produto_cest',
  'produto-ecommerce-marcas': 'produto_ecommerce_marcas',
  'produto-ncm': 'produto_ncm',
  'produto-unidades-medida': 'produto_unidades_medida',
  servicos: 'servicos',
  contratos: 'contratos',
  'empresa-conectada': 'empresa_conectada',
}))
