import type { ToolkitDefinition } from '@/products/integracoes/shared/types'

export const TOOLKITS: ToolkitDefinition[] = [
  { slug: 'gmail', name: 'Gmail', description: 'Enviar e ler emails' },
  { slug: 'GOOGLEDRIVE', name: 'Google Drive', description: 'Arquivos e pastas' },
  { slug: 'GOOGLECALENDAR', name: 'Google Calendar', description: 'Agenda e eventos' },
  { slug: 'GOOGLEDOCS', name: 'Google Docs', description: 'Documentos do Google' },
  { slug: 'WHATSAPP', name: 'WhatsApp', description: 'Mensageria e notificações' },
  { slug: 'NOTION', name: 'Notion', description: 'Blocos e páginas de notas' },
  { slug: 'GOOGLESHEETS', name: 'Google Sheets', description: 'Planilhas do Google' },
  { slug: 'GOOGLESLIDES', name: 'Google Slides', description: 'Apresentações do Google' },
  { slug: 'GOOGLE_ANALYTICS', name: 'Google Analytics', description: 'Métricas e análises' },
  { slug: 'GOOGLEADS', name: 'Google Ads', description: 'Anúncios e campanhas' },
  { slug: 'METAADS', name: 'Meta Ads', description: 'Anúncios no ecossistema Meta' },
  { slug: 'SLACK', name: 'Slack', description: 'Mensageria e canais' },
  { slug: 'SHOPIFY', name: 'Shopify', description: 'Loja e catálogo' },
  { slug: 'HUBSPOT', name: 'HubSpot', description: 'CRM e automação de marketing' },
  { slug: 'FACEBOOK', name: 'Facebook', description: 'Páginas e posts' },
  { slug: 'INSTAGRAM', name: 'Instagram', description: 'Posts e mídia social' },
  { slug: 'ACTIVE_CAMPAIGN', name: 'ActiveCampaign', description: 'Email marketing e automação' },
  { slug: 'AIRTABLE', name: 'Airtable', description: 'Bases e automações' },
  { slug: 'SALESFORCE', name: 'Salesforce', description: 'CRM' },
  { slug: 'SALESFORCE_SERVICE_CLOUD', name: 'Salesforce Service Cloud', description: 'Atendimento e serviços' },
  { slug: 'MAILCHIMP', name: 'Mailchimp', description: 'Email marketing e automação' },
  { slug: 'CALENDLY', name: 'Calendly', description: 'Agendamento de reuniões' },
  { slug: 'CAL', name: 'Cal.com', description: 'Agendamento e calendários' },
  { slug: 'CANVA', name: 'Canva', description: 'Design e criação de artes' },
  { slug: 'CLICKUP', name: 'ClickUp', description: 'Gestão de projetos e tarefas' },
  { slug: 'CLICKHOUSE', name: 'ClickHouse', description: 'Banco de dados analítico' },
  { slug: 'CODA', name: 'Coda', description: 'Documentos e automações' },
  { slug: 'DATABRICKS', name: 'Databricks', description: 'Lakehouse e engenharia de dados' },
  { slug: 'DISCORD', name: 'Discord', description: 'Canais e mensagens' },
  { slug: 'DOCUSIGN', name: 'DocuSign', description: 'Assinaturas eletrônicas' },
  { slug: 'DROPBOX', name: 'Dropbox', description: 'Arquivos e armazenamento' },
  { slug: 'DYNAMICS365', name: 'Dynamics 365', description: 'CRM/ERP Microsoft' },
  { slug: 'ELEVENLABS', name: 'ElevenLabs', description: 'Geração de voz e áudio' },
  { slug: 'FIGMA', name: 'Figma', description: 'Design colaborativo e prototipagem' },
  { slug: 'GITHUB', name: 'GitHub', description: 'Repositórios e issues' },
  { slug: 'GONG', name: 'Gong', description: 'Inteligência de conversas de vendas' },
  { slug: 'JIRA', name: 'Jira', description: 'Gestão de projetos e issues' },
  { slug: 'JOTFORM', name: 'Jotform', description: 'Formulários e coletas' },
  { slug: 'KOMMO', name: 'Kommo', description: 'CRM e automações' },
  { slug: 'LINKEDIN', name: 'LinkedIn', description: 'Rede profissional e páginas' },
  { slug: 'LINEAR', name: 'Linear', description: 'Issues e planejamento' },
  { slug: 'METABASE', name: 'Metabase', description: 'BI e dashboards' },
  { slug: 'MICROSOFT_CLARITY', name: 'Microsoft Clarity', description: 'Mapas de calor e sessões' },
  { slug: 'MICROSOFT_TEAMS', name: 'Microsoft Teams', description: 'Canais e reuniões' },
  { slug: 'MIXPANEL', name: 'Mixpanel', description: 'Analytics de produto' },
  { slug: 'MONDAY', name: 'Monday.com', description: 'Projetos e workflows' },
  { slug: 'NETSUITE', name: 'NetSuite', description: 'ERP da Oracle' },
  { slug: 'ONE_DRIVE', name: 'OneDrive', description: 'Arquivos e armazenamento' },
  { slug: 'OUTLOOK', name: 'Outlook', description: 'Email e calendário' },
  { slug: 'PIPEDRIVE', name: 'Pipedrive', description: 'CRM de vendas' },
  { slug: 'POSTHOG', name: 'PostHog', description: 'Product analytics e feature flags' },
  { slug: 'REMOVE_BG', name: 'Remove.bg', description: 'Remoção de fundo de imagens' },
  { slug: 'SENDGRID', name: 'SendGrid', description: 'Envio de emails transacionais' },
  { slug: 'SENDLANE', name: 'Sendlane', description: 'Email marketing e automação' },
  { slug: 'SENTRY', name: 'Sentry', description: 'Monitoramento de erros' },
  { slug: 'SERVICENOW', name: 'ServiceNow', description: 'ITSM e workflows' },
  { slug: 'SNOWFLAKE', name: 'Snowflake', description: 'Data warehouse' },
  { slug: 'STRIPE', name: 'Stripe', description: 'Pagamentos e faturamento' },
  { slug: 'SUPABASE', name: 'Supabase', description: 'Banco de dados e auth' },
  { slug: 'TALLY', name: 'Tally', description: 'Formulários (tally.so)' },
  { slug: 'TELEGRAM', name: 'Telegram', description: 'Mensageria e bots' },
  { slug: 'TIKTOK', name: 'TikTok', description: 'Conteúdo e anúncios' },
  { slug: 'TRELLO', name: 'Trello', description: 'Quadros e cartões' },
  { slug: 'TWITTER', name: 'Twitter (X)', description: 'Posts e integrações' },
  { slug: 'TYPEFORM', name: 'Typeform', description: 'Formulários e respostas' },
  { slug: 'VERCEL', name: 'Vercel', description: 'Deploy e projetos' },
  { slug: 'YOUTUBE', name: 'YouTube', description: 'Canais e vídeos' },
  { slug: 'ZENDESK', name: 'Zendesk', description: 'Suporte e tickets' },
  { slug: 'ZOOM', name: 'Zoom', description: 'Reuniões e gravações' },
]
