import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { createServer } from 'node:http'
import { existsSync,mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { chromium } from 'playwright-core'
import { executeTool,type ExecutionDependencies } from '../src/products/chatgptplugin/application/executeTool'
import { ERP_CAPABILITIES } from '../src/products/erp/shared/professionalContracts'
import type { PluginPrincipal } from '../src/products/chatgptplugin/shared/contracts'
import type { PluginConfig } from '../src/products/chatgptplugin/shared/config'
import { renderCardsHtml } from '../src/products/chatgptplugin/ui/resource'
import { getErpDatabaseContext } from '../src/lib/erpDatabaseContext'

async function main(){
  const settings:PluginConfig={resource:'https://erp.example.invalid/api/mcp',metadataUrl:'https://erp.example.invalid/.well-known/oauth-protected-resource/api/mcp',issuer:'https://test.clerk.accounts.dev',scope:'erp:read',clientIds:['test'],origins:[],toolTimeoutMs:1000,requestsPerMinute:60}
  const principal:PluginPrincipal={userId:1,clerkUserId:'user_1',clientId:'test',scopes:['erp:read'],companies:[{id:2,name:'Empresa Teste',profile:'administrador',capabilities:[...ERP_CAPABILITIES]}]}
  const draftId='d0000000-0000-4000-8000-000000000001',evil='<img src=x onerror="window.hacked=true">'
  let draftStatus:'pending'|'saved'|'cancelled'|'expired'='pending',queryCalls=0
  const checkedCompany=(company:number)=>{queryCalls++;assert.equal(company,2);assert.equal(getErpDatabaseContext()?.tenantId,2);assert.equal(getErpDatabaseContext()?.readOnly,true)}
  const rows=[{id:'1',descricao:evil,fornecedor:'Fornecedor A',vencimento:'2026-10-08',valor:1234.56,saldo:1234.56,status:'aberto'},{id:'2',descricao:'Licença ERP',fornecedor:'Fornecedor B',vencimento:'2026-09-10',valor:2000,saldo:1800,status:'vencido'}]
  const deps:ExecutionDependencies={reserve:async()=>randomUUID(),finish:async()=>{},queries:{
    financialTitle:async company=>{checkedCompany(company);return {record:{id:'1',descricao:'Aluguel revisado',valor_total:100},installments:[{id:'10',parcela:1,vencimento:'2026-10-20',valor:100,saldo:100,status:'aberto'}],installmentsTruncated:false,history:[],historyTruncated:false}},
    fiscal:async company=>{checkedCompany(company);return {ready:false,issues:[]}},
    customer:async company=>{checkedCompany(company);return {record:{id:'1',nome:evil}}},
    registration:async company=>{checkedCompany(company);return {record:{id:'1',nome:evil,email:'teste@example.invalid'}}},
    installment:async(company,_type,id)=>{checkedCompany(company);return {record:{...rows[0],id:String(id)},history:[{id:'10',data_pagamento:'2026-09-20',valor:200,estornado_em:null}],historyTruncated:false}},
    analysis:async(company,type,from,to)=>{checkedCompany(company);return {tipo:type,inicio:from,fim:to,criterio:'Vendas confirmadas por data.',summary:{quantidade:30,valor_total:30000,valor_medio:1000},records:[{periodo:'2026-08',quantidade:10,valor:10000},{periodo:'2026-09',quantidade:20,valor:20000}]}},
    page:async(company,type,input)=>{checkedCompany(company);return {records:input.query==='vazio'?[]:type==='clientes'?[{id:'1',nome:evil,status:'ativo'}]:rows,total:input.query==='vazio'?0:22,page:input.page||1,pageSize:input.pageSize||20,summary:{quantidade:22,referencia:'2026-10-04',em_aberto:90000,vencidas:1800,vence_em_7_dias:17545.6}}},
    sale:async company=>{checkedCompany(company);return {sale:{id:'1',numero:'VEN-001',total:1234.56,data_vencimento:null},items:[{descricao:'Serviço',quantidade:1,total:1234.56}],totalItems:1,itemsTruncated:false,installments:[],installmentsTruncated:false}},
    purchase:async company=>{checkedCompany(company);return {purchase:{id:'1',data_vencimento:null},items:[],totalItems:0,itemsTruncated:false,installments:[],installmentsTruncated:false}},
    financialAccounts:async company=>{checkedCompany(company);return {records:[{id:'1',nome:'Banco ERP',tipo:'banco'}],hasMore:false}},
    payments:async(company,input)=>{checkedCompany(company);return {records:[],page:input.page,pageSize:input.pageSize,hasMore:false}},
    stock:async(company,input)=>{checkedCompany(company);return {records:[],total:0,page:input.page||1,pageSize:input.pageSize||20}},
    overview:async company=>{checkedCompany(company);return {saldoReceber:0,saldoPagar:0,receberVencido:0,vendasRascunho:0,comprasAbertas:0,clientesAtivos:0}},
    report:async(company,report,from,to,input)=>{checkedCompany(company);return {report,from,to,records:[],page:input.page||1,pageSize:input.pageSize||20,hasMore:false}},
  },actions:{prepare:async()=>{throw new Error('UI não deve criar registros')},list:async()=>({records:[],page:1,pageSize:20,hasMore:false}),get:async(p,company,id)=>{checkedCompany(company);assert.equal(p.userId,1);assert.equal(id,draftId);return {rascunho_id:id,empresa_id:company,status:draftStatus,registro_id:draftStatus==='saved'?'1':null,criado_em:'2026-10-04T10:00:00Z',expira_em:'2026-10-05T10:00:00Z',proposta:{tipo:'cliente' as const,dados:{nome:'Cliente novo',tipo:'juridica' as const}},alvo:null,revisao_url:'https://erp.example.invalid/chatgptplugin/approvals/'+id}}}}
  const render=async(args:Record<string,unknown>,who=principal)=>executeTool(who,'renderizar_card',args,settings,deps)
  const denied=async(args:Record<string,unknown>,code:string,who=principal)=>{const count=queryCalls,result=await render(args,who);assert(result.isError);assert.equal(JSON.parse((result.content[0] as {text:string}).text).code,code);assert.equal(queryCalls,count)}
  await denied({card:'tabela',consulta:'consultar_financeiro',empresa_id:999,parametros:{tipo:'pagar'}},'ACCESS_DENIED')
  await denied({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar',empresa_id:999}},'INVALID_INPUT')
  await denied({card:'revisao',consulta:'listar_vendas',empresa_id:2},'INVALID_INPUT')
  await denied({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar',records:[{valor:999}]}},'INVALID_INPUT')
  await denied({card:'analise',consulta:'analisar_periodo',empresa_id:2,parametros:{tipo:'vendas',inicio:'2026-12-31',fim:'2026-01-01'}},'INVALID_INPUT')
  await denied({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar'}},'ACCESS_DENIED',{...principal,companies:[{...principal.companies[0],capabilities:[]}]})
  await denied({card:'tabela',consulta:'consultar_financeiro',parametros:{tipo:'pagar'}},'COMPANY_REQUIRED',{...principal,companies:[principal.companies[0],{...principal.companies[0],id:3}]})
  const html=renderCardsHtml(settings.resource),encoded=JSON.stringify(html).replaceAll('<','\\u003c')
  const host=`<!doctype html><html><body style="margin:0"><iframe id="app" title="ERP" style="width:100%;height:1450px;border:0"></iframe><script>window.calls=[];window.opened=[];window.messages=[];window.ready=false;const frame=document.getElementById('app');frame.srcdoc=${encoded};window.deliver=data=>frame.contentWindow.postMessage({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:data},'*');addEventListener('message',async e=>{if(e.source!==frame.contentWindow)return;const m=e.data;if(m.method==='ui/notifications/initialized'){window.ready=true;return}if(m.id===undefined)return;let result={};if(m.method==='ui/initialize')result={protocolVersion:'2026-01-26',hostInfo:{name:'test',version:'1'},hostCapabilities:{},hostContext:{theme:'light'}};if(m.method==='tools/call'){calls.push(m.params);result=await(await fetch('/call',{method:'POST',body:JSON.stringify(m.params.arguments)})).json()}if(m.method==='ui/message'||m.method==='ui/update-model-context')messages.push(m);if(m.method==='ui/open-link')opened.push(m.params.url);frame.contentWindow.postMessage({jsonrpc:'2.0',id:m.id,result},'*')});</script></body></html>`
  const server=createServer(async(req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');if(req.url==='/call'){const chunks=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(await render(JSON.parse(Buffer.concat(chunks).toString()))));return}res.end(host)})
  await new Promise<void>(r=>server.listen(0,'127.0.0.1',r))
  const executable=process.env.CHATGPTPLUGIN_TEST_BROWSER||['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe'].find(existsSync)
  assert(executable,'Navegador necessário para verificar os cards')
  const browser=await chromium.launch({executablePath:executable,headless:true})
  try{
    const page=await browser.newPage({viewport:{width:1050,height:1100}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
    await page.goto('http://127.0.0.1:'+(server.address() as {port:number}).port);await page.waitForFunction(()=>Boolean((window as any).ready))
    const frame=page.frameLocator('#app'),show=async(args:Record<string,unknown>)=>{const result=await render(args);assert(!result.isError);await page.evaluate(data=>(window as any).deliver(data),result)}
    const shot=async(name:string)=>{mkdirSync('.cache/chatgptplugin-cards',{recursive:true});await frame.locator('main').screenshot({path:resolve('.cache/chatgptplugin-cards/'+name+'.png')})}
    await show({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar'}})
    await frame.getByText('R$ 90.000,00',{exact:true}).waitFor();assert.equal(await frame.locator('img').count(),0);assert.equal(await frame.locator('nav').count(),0);await shot('tabela')
    await frame.getByRole('button',{name:'Próxima',exact:true}).click();await frame.getByText('Página 2 · 22 registros').waitFor();await frame.getByLabel('Situação',{exact:true}).selectOption('vencido');await frame.getByRole('button',{name:'Aplicar',exact:true}).click();await frame.getByText('Página 1 · 22 registros').waitFor()
    await frame.getByRole('button',{name:'Ver detalhes',exact:true}).first().click();await frame.getByText('Histórico de pagamentos',{exact:true}).waitFor();await shot('detalhes');await frame.getByRole('button',{name:'Voltar à consulta',exact:true}).click();await frame.getByRole('button',{name:'Ver detalhes',exact:true}).first().waitFor()
    await show({card:'analise',consulta:'analisar_periodo',empresa_id:2,parametros:{tipo:'vendas',inicio:'2026-08-01',fim:'2026-09-30'}});await frame.getByText('R$ 30.000,00',{exact:true}).waitFor();assert.equal(await frame.locator('.bar').count(),2);await shot('analise')
    await frame.getByLabel('De',{exact:true}).fill('2026-12-31');await frame.getByRole('button',{name:'Aplicar',exact:true}).click();await frame.locator('#status[role=alert]').waitFor();await frame.getByRole('button',{name:'Tentar novamente',exact:true}).click();await frame.getByText('R$ 30.000,00',{exact:true}).waitFor()
    await show({card:'selecao',consulta:'buscar_cadastros',empresa_id:2,parametros:{tipo:'clientes'}});await frame.getByRole('button',{name:'Selecionar',exact:true}).waitFor();await shot('selecao');await frame.getByRole('button',{name:'Selecionar',exact:true}).click();await frame.getByText(/A escolha foi enviada/).waitFor();const message=await page.evaluate(()=>(window as any).messages.find((m:any)=>m.method==='ui/message'));assert(message.params.content[0].text.includes('"empresa_id":2'))
    await show({card:'revisao',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}});await frame.getByRole('button',{name:'Abrir revisão no ERP',exact:true}).waitFor();await shot('revisao');await frame.getByRole('button',{name:'Abrir revisão no ERP',exact:true}).click();await page.waitForFunction(()=>(window as any).opened.length===1)
    const invalid=await render({card:'revisao',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}});(invalid.structuredContent!.data as any).dados.revisao_url='https://attacker.invalid/chatgptplugin/approvals/'+draftId;await page.evaluate(data=>(window as any).deliver(data),invalid);await frame.getByRole('button',{name:'Abrir revisão no ERP',exact:true}).click();await frame.getByText('Link de revisão inválido.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).opened.length),1);await show({card:'revisao',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}});await frame.getByRole('button',{name:'Solicitar ajuste',exact:true}).click();await page.waitForFunction(()=>(window as any).messages.some((m:any)=>m.method==='ui/message'&&m.params.content[0].text.includes('Quero ajustar')))
    await frame.getByRole('button',{name:'Consultar resultado',exact:true}).click();await frame.getByText('A proposta aguarda sua revisão no ERP. A operação ainda não foi executada.',{exact:true}).waitFor();draftStatus='saved';await frame.getByRole('button',{name:'Atualizar resultado',exact:true}).click();await frame.getByText('Operação concluída',{exact:true}).waitFor();await shot('resultado');await frame.getByRole('button',{name:'Ver registro',exact:true}).click();await frame.getByText('Detalhes',{exact:true}).waitFor()
    for(const status of ['cancelled','expired'] as const){draftStatus=status;await show({card:'resultado',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}});await frame.getByRole('heading',{name:status==='expired'?'Expirado':'Cancelado',exact:true}).waitFor();assert.equal(await frame.getByRole('button',{name:'Ver registro',exact:true}).count(),0)}
    draftStatus='pending';const financialReview=await render({card:'revisao',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}}),financialDraft=(financialReview.structuredContent!.data as any).dados;
    financialDraft.proposta={tipo:'conta_pagar',dados:{descricao:'Aluguel revisado',valor_total:100,parcelas:[{data_vencimento:'2026-10-20',valor:100}]},total:100};await page.evaluate(data=>(window as any).deliver(data),financialReview);await frame.getByRole('heading',{name:'Criar conta a pagar',exact:true}).waitFor();await frame.getByRole('heading',{name:'Parcelas da proposta',exact:true}).waitFor();await shot('revisao-financeiro');
    const financialResult=await render({card:'resultado',consulta:'obter_rascunho',empresa_id:2,parametros:{rascunho_id:draftId}}),resultDraft=(financialResult.structuredContent!.data as any).dados;resultDraft.proposta=financialDraft.proposta;resultDraft.status='saved';resultDraft.registro_id='1';await page.evaluate(data=>(window as any).deliver(data),financialResult);await frame.getByRole('button',{name:'Ver registro',exact:true}).click();await frame.getByRole('heading',{name:'Parcelas do título',exact:true}).waitFor();await frame.getByText('Aluguel revisado',{exact:true}).waitFor();await shot('detalhes-titulo');
    resultDraft.proposta={tipo:'excluir_conta_pagar',dados:{registro_id:1,motivo:'Registro duplicado'}};await page.evaluate(data=>(window as any).deliver(data),financialResult);await frame.getByText('O registro foi excluído das consultas. O histórico foi preservado.',{exact:true}).waitFor();assert.equal(await frame.getByRole('button',{name:'Ver registro',exact:true}).count(),0);
    await show({card:'selecao',consulta:'meu_acesso',parametros:{}});await frame.getByRole('heading',{name:'Selecionar empresa',exact:true}).waitFor();await frame.getByRole('button',{name:'Selecionar',exact:true}).click();await frame.getByText(/A escolha foi enviada/).waitFor()
    await show({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar',busca:'vazio'}});await frame.getByText('Nenhum registro encontrado para esta consulta.',{exact:true}).waitFor();await show({card:'tabela',consulta:'consultar_financeiro',empresa_id:2,parametros:{tipo:'pagar'}});await frame.getByRole('button',{name:'Aplicar',exact:true}).waitFor();await page.setViewportSize({width:390,height:1000});await page.evaluate(()=>{const f=document.querySelector('iframe')!;f.contentWindow!.postMessage({jsonrpc:'2.0',method:'ui/notifications/host-context-changed',params:{theme:'dark'}},'*')});await page.waitForTimeout(100);await shot('tabela-mobile-dark');const sizes=await frame.locator('main').evaluate(el=>({width:el.getBoundingClientRect().width,viewport:window.innerWidth}));assert(sizes.width<=sizes.viewport)
    const calls=await page.evaluate(()=>(window as any).calls);assert(calls.every((c:any)=>c.name==='renderizar_card'));assert(calls.some((c:any)=>c.arguments.parametros.pagina===2));assert(calls.some((c:any)=>c.arguments.parametros.status==='vencido'));assert.deepEqual(errors,[])
    console.log(JSON.stringify({status:'passed',cards:6,checks:'permissões, empresa, parâmetros forjados, filtros, paginação, detalhes, seleção, revisão, estado real do rascunho, erro/repetição, mobile, tema, XSS',screenshots:'.cache/chatgptplugin-cards',realChatGPT:false,realDatabase:false}))
  }finally{await browser.close();await new Promise<void>((r,j)=>server.close(error=>error?j(error):r()))}
}
void main().catch(error=>{console.error(error.stack);process.exitCode=1})
