import type { IntegrationResource } from '@/products/integracoes/shared/providers/providerTypes'
import { erpProvider } from '@/products/integracoes/shared/providers/erp/erpProviderFactory'

export const CONTA_AZUL_RESOURCES: IntegrationResource[] = [
  {
    slug: 'clientes',
    name: 'Clientes',
    description: 'Cadastro de clientes, documentos e dados comerciais.',
    defaultEnabled: true,
  },
  {
    slug: 'fornecedores',
    name: 'Fornecedores',
    description: 'Cadastro de fornecedores e parceiros de compra.',
    defaultEnabled: true,
  },
  {
    slug: 'empresa_conectada',
    name: 'Empresa conectada',
    description: 'Dados cadastrais da empresa autorizada no OAuth.',
    defaultEnabled: false,
  },
  {
    slug: 'produtos',
    name: 'Produtos',
    description: 'Catalogo de produtos, servicos e precos.',
    defaultEnabled: true,
  },
  {
    slug: 'produto_categorias',
    name: 'Categorias de produtos',
    description: 'Categorias usadas no cadastro de produtos.',
    defaultEnabled: false,
  },
  {
    slug: 'produto_cest',
    name: 'CEST',
    description: 'Codigos CEST usados na classificacao fiscal de produtos.',
    defaultEnabled: false,
  },
  {
    slug: 'produto_ecommerce_marcas',
    name: 'Marcas de e-commerce',
    description: 'Marcas de produtos usadas no contexto de e-commerce.',
    defaultEnabled: false,
  },
  {
    slug: 'produto_ncm',
    name: 'NCM',
    description: 'Codigos NCM usados na classificacao fiscal de produtos.',
    defaultEnabled: false,
  },
  {
    slug: 'produto_unidades_medida',
    name: 'Unidades de medida',
    description: 'Unidades de medida disponiveis para produtos.',
    defaultEnabled: false,
  },
  {
    slug: 'contas_receber',
    name: 'Contas a receber',
    description: 'Titulos, vencimentos, recebimentos e inadimplencia.',
    defaultEnabled: true,
  },
  {
    slug: 'contas_pagar',
    name: 'Contas a pagar',
    description: 'Titulos, vencimentos, pagamentos e fornecedores.',
    defaultEnabled: true,
  },
  {
    slug: 'contas_financeiras',
    name: 'Contas financeiras',
    description: 'Contas bancarias, cartoes e demais contas financeiras.',
    defaultEnabled: false,
  },
  {
    slug: 'saldos_contas_financeiras',
    name: 'Saldos de contas',
    description: 'Saldo atual por conta financeira cadastrada.',
    defaultEnabled: false,
  },
  {
    slug: 'transferencias',
    name: 'Transferencias',
    description: 'Transferencias entre contas financeiras.',
    defaultEnabled: false,
  },
  {
    slug: 'eventos_financeiros_alteracoes',
    name: 'Alteracoes financeiras',
    description: 'IDs de eventos financeiros alterados no periodo.',
    defaultEnabled: false,
  },
  {
    slug: 'saldos_iniciais',
    name: 'Saldos iniciais',
    description: 'Saldos iniciais das contas financeiras.',
    defaultEnabled: false,
  },
  {
    slug: 'categorias',
    name: 'Categorias',
    description: 'Categorias financeiras e classificacoes operacionais.',
    defaultEnabled: false,
  },
  {
    slug: 'categorias_dre',
    name: 'Categorias DRE',
    description: 'Categorias usadas na estrutura de DRE.',
    defaultEnabled: false,
  },
  {
    slug: 'centros_custo',
    name: 'Centros de custo',
    description: 'Estrutura gerencial para rateios e analises.',
    defaultEnabled: false,
  },
  {
    slug: 'servicos',
    name: 'Servicos',
    description: 'Catalogo de servicos, precos e informacoes comerciais.',
    defaultEnabled: false,
  },
  {
    slug: 'vendedores',
    name: 'Vendedores',
    description: 'Vendedores cadastrados para atribuicao comercial.',
    defaultEnabled: false,
  },
  {
    slug: 'vendas',
    name: 'Vendas',
    description: 'Vendas filtradas por periodo, cliente, situacao e tipo.',
    defaultEnabled: false,
  },
  {
    slug: 'venda_detalhes',
    name: 'Detalhes de vendas',
    description: 'Detalhamento individual de cada venda sincronizada.',
    defaultEnabled: false,
  },
  {
    slug: 'itens_venda',
    name: 'Itens de venda',
    description: 'Produtos e servicos vinculados a cada venda.',
    defaultEnabled: false,
  },
  {
    slug: 'venda_proximo_numero',
    name: 'Proximo numero de venda',
    description: 'Proximo numero disponivel para criacao de venda.',
    defaultEnabled: false,
  },
  {
    slug: 'contratos',
    name: 'Contratos',
    description: 'Contratos recorrentes, clientes, valores e periodicidade.',
    defaultEnabled: false,
  },
  {
    slug: 'contrato_proximo_numero',
    name: 'Proximo numero de contrato',
    description: 'Proximo numero disponivel para criacao de contrato.',
    defaultEnabled: false,
  },
  {
    slug: 'notas_fiscais',
    name: 'Notas fiscais',
    description: 'Notas fiscais emitidas, chaves, valores e status fiscais.',
    defaultEnabled: false,
  },
  {
    slug: 'notas_fiscais_servico',
    name: 'Notas fiscais de servico',
    description: 'Notas fiscais de servico emitidas no ERP.',
    defaultEnabled: false,
  },
]

export const CONTA_AZUL_PROVIDER = erpProvider({
  slug: 'conta_azul',
  toolkitSlug: 'CONTA_AZUL',
  name: 'Conta Azul',
  description: 'ERP financeiro, faturamento, vendas e conciliacao para pequenas e medias empresas.',
  authType: 'oauth2',
  supportsOAuthCallback: true,
  resources: CONTA_AZUL_RESOURCES,
  tags: ['brasil', 'pme', 'financeiro'],
})
