export const bridgeScript=String.raw`
const pending=new Map();let sequence=1,current=null,backRequest=null,busy=false,generation=0,connected=false,queued=null;
const body=document.getElementById('card'),status=document.getElementById('status');
function request(method,params){return new Promise((resolve,reject)=>{const id=sequence++,timer=setTimeout(()=>{pending.delete(id);reject(new Error('A conexão demorou. Tente novamente.'))},20000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function notify(method,params){window.parent.postMessage({jsonrpc:'2.0',method,params},'*')}
function unpack(result){if(result?.isError){let error;try{error=JSON.parse(result.content?.find(c=>c.type==='text')?.text)}catch{}throw new Error(error?.message||'Não foi possível consultar.')}if(!result?.structuredContent?.ok||!result.structuredContent.data?.card)throw new Error('Resposta indisponível.');return result.structuredContent.data}
function showError(error){status.textContent=error?.message||'Não foi possível concluir. Tente novamente.';status.setAttribute('role','alert');const retry=document.getElementById('retry');retry.hidden=!current}
function applyTheme(theme){if(theme==='light'||theme==='dark')document.documentElement.style.colorScheme=theme}
function display(p){if(!p||!['tabela','detalhes','analise','selecao','revisao','resultado'].includes(p.card))throw new Error('Card indisponível.');generation++;current=p;body.replaceChildren();status.textContent='';status.setAttribute('role','status');document.getElementById('retry').hidden=true;document.getElementById('card').setAttribute('aria-busy','false');({tabela:renderTable,detalhes:renderDetails,analise:renderAnalysis,selecao:renderSelection,revisao:renderReview,resultado:renderResult})[p.card](p);notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight})}
async function navigate(args){if(busy)return;busy=true;const ticket=generation;body.setAttribute('aria-busy','true');status.textContent='Consultando…';status.setAttribute('role','status');for(const control of body.querySelectorAll('button,input,select')){control.dataset.wasDisabled=String(control.disabled);control.disabled=true}try{const result=await request('tools/call',{name:'renderizar_card',arguments:args});if(ticket===generation)display(unpack(result))}catch(error){if(ticket===generation)showError(error)}finally{busy=false;body.setAttribute('aria-busy','false');if(ticket===generation)for(const control of body.querySelectorAll('button,input,select'))control.disabled=control.dataset.wasDisabled==='true'}}
function reload(parametros){return navigate({card:current.card,consulta:current.consulta,...(current.empresa?{empresa_id:current.empresa.id}:{}),parametros})}
document.getElementById('retry').onclick=()=>reload(current.parametros);
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const m=event.data;if(!m||m.jsonrpc!=='2.0')return;const waiting=pending.get(m.id);if(waiting){clearTimeout(waiting.timer);pending.delete(m.id);m.error?waiting.reject(new Error(m.error.message||'Falha na conexão')):waiting.resolve(m.result);return}if(m.method==='ui/notifications/host-context-changed')applyTheme(m.params?.theme);if(m.method==='ui/notifications/tool-result'){try{const p=unpack(m.params);if(connected)display(p);else queued=p}catch(error){if(m.params?.isError)showError(error)}}if(m.method==='ui/notifications/tool-cancelled'){generation++;busy=false;body.setAttribute('aria-busy','false');for(const control of body.querySelectorAll('button,input,select'))if(control.dataset.wasDisabled!==undefined)control.disabled=control.dataset.wasDisabled==='true';showError(new Error('Consulta cancelada.'))}});
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'chatgptplugin-cards',version:'1.0.0'},appCapabilities:{}}).then(result=>{connected=true;applyTheme(result?.hostContext?.theme);notify('ui/notifications/initialized',{});if(queued)display(queued);else status.textContent='Aguardando os dados desta consulta…'}).catch(showError);
new ResizeObserver(()=>notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight})).observe(body);
`
