BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';

-- Serializacao nao bloqueante evita validar agregados com snapshot anterior.
CREATE FUNCTION erp.travar_evolucao(p_tenant bigint) RETURNS void
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_periodo_empresa(p_tenant,false);
 IF NOT pg_try_advisory_xact_lock(172943,hashint8(p_tenant)) THEN
  RAISE EXCEPTION 'Operacao concorrente; repetir transacao inteira' USING ERRCODE='40001';
 END IF;
END $$;

CREATE FUNCTION erp.proteger_identidade_nova() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END);
 IF TG_OP='UPDATE' AND (OLD.id<>NEW.id OR OLD.tenant_id<>NEW.tenant_id) THEN
  RAISE EXCEPTION 'Identidade imutavel' USING ERRCODE='23514';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;

CREATE TABLE erp.entidades_contatos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL, nome text NOT NULL CHECK(btrim(nome)<>''),
 cargo text, email text, telefone text, whatsapp boolean NOT NULL DEFAULT false,
 finalidades text[] NOT NULL DEFAULT ARRAY['comercial']::text[],
 principais text[] NOT NULL DEFAULT '{}'::text[],
 ativo boolean NOT NULL DEFAULT true,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 atualizado_em timestamptz NOT NULL DEFAULT now(),
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 CHECK(cardinality(finalidades)>0 AND finalidades <@ ARRAY['comercial','financeiro','operacional']::text[]),
 CHECK(principais <@ finalidades AND (ativo OR cardinality(principais)=0)),
 CHECK(nullif(btrim(email),'') IS NOT NULL OR nullif(btrim(telefone),'') IS NOT NULL)
);
CREATE TABLE erp.entidades_enderecos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 entidade_id bigint NOT NULL, identificacao text NOT NULL CHECK(btrim(identificacao)<>''),
 logradouro text NOT NULL CHECK(btrim(logradouro)<>''), numero text, complemento text,
 bairro text, cidade text NOT NULL CHECK(btrim(cidade)<>''), uf text, cep text,
 pais text NOT NULL DEFAULT 'Brasil',
 finalidades text[] NOT NULL DEFAULT ARRAY['comercial']::text[],
 principais text[] NOT NULL DEFAULT '{}'::text[], ativo boolean NOT NULL DEFAULT true,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 atualizado_em timestamptz NOT NULL DEFAULT now(),
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,entidade_id) REFERENCES erp.entidades(tenant_id,id) ON DELETE RESTRICT,
 CHECK(cardinality(finalidades)>0 AND finalidades <@ ARRAY['comercial','cobranca','prestacao']::text[]),
 CHECK(principais <@ finalidades AND (ativo OR cardinality(principais)=0))
);
CREATE FUNCTION erp.validar_principais_entidade() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE conflito boolean;
BEGIN
 IF array_position(NEW.finalidades,NULL) IS NOT NULL OR array_position(NEW.principais,NULL) IS NOT NULL
  OR cardinality(NEW.finalidades)<>(SELECT count(DISTINCT x) FROM unnest(NEW.finalidades) x)
  OR cardinality(NEW.principais)<>(SELECT count(DISTINCT x) FROM unnest(NEW.principais) x) THEN
  RAISE EXCEPTION 'Finalidades invalidas' USING ERRCODE='23514';
 END IF;
 EXECUTE format('SELECT EXISTS(SELECT 1 FROM erp.%I WHERE tenant_id=$1 AND entidade_id=$2 AND id<>$3 AND ativo AND principais && $4)',TG_TABLE_NAME)
 INTO conflito USING NEW.tenant_id,NEW.entidade_id,NEW.id,NEW.principais;
 IF conflito THEN RAISE EXCEPTION 'Principal ja definido para finalidade' USING ERRCODE='23514'; END IF;
 NEW.atualizado_em:=now();
 RETURN NEW;
END $$;

CREATE TABLE erp.contratos_vendas_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,contrato_id,arquivo_id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.contratos_vendas_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.vendas_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 venda_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,venda_id,arquivo_id),
 FOREIGN KEY(tenant_id,venda_id) REFERENCES erp.vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.vendas_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.ordens_servico_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 ordem_servico_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,ordem_servico_id,arquivo_id),
 FOREIGN KEY(tenant_id,ordem_servico_id) REFERENCES erp.ordens_servico(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.ordens_servico_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.contas_receber_arquivos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 conta_receber_id bigint NOT NULL, arquivo_id bigint NOT NULL,
 finalidade text NOT NULL CHECK(btrim(finalidade)<>''), descricao text,
 criado_em timestamptz NOT NULL DEFAULT now(),
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,conta_receber_id,arquivo_id),
 FOREIGN KEY(tenant_id,conta_receber_id) REFERENCES erp.contas_receber(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,arquivo_id) REFERENCES erp.arquivos(tenant_id,id) ON DELETE RESTRICT
);
CREATE TRIGGER preservar_anexo BEFORE UPDATE OR DELETE ON erp.contas_receber_arquivos
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

CREATE TABLE erp.contas_receber_eventos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 conta_receber_id bigint NOT NULL, conta_receber_parcela_id bigint, pagamento_id bigint,
 evento text NOT NULL CHECK(btrim(evento)<>''), dados jsonb NOT NULL DEFAULT '{}',
 criado_em timestamptz NOT NULL DEFAULT now(), data_evento date NOT NULL DEFAULT current_date,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 motivo text, chave_operacao text,
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,conta_receber_id) REFERENCES erp.contas_receber(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_receber_parcela_id) REFERENCES erp.contas_receber_parcelas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,pagamento_id) REFERENCES erp.pagamentos(tenant_id,id) ON DELETE RESTRICT,
 CHECK(jsonb_typeof(dados)='object')
);
CREATE UNIQUE INDEX contas_receber_eventos_operacao_idx ON erp.contas_receber_eventos(tenant_id,conta_receber_id,chave_operacao,evento) WHERE chave_operacao IS NOT NULL;
CREATE INDEX contas_receber_eventos_titulo_idx ON erp.contas_receber_eventos(tenant_id,conta_receber_id,criado_em);
CREATE TRIGGER preservar_evento BEFORE UPDATE OR DELETE ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();
CREATE FUNCTION erp.validar_evento_receber() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF NEW.conta_receber_parcela_id IS NOT NULL AND NOT EXISTS(
 SELECT 1 FROM erp.contas_receber_parcelas WHERE tenant_id=NEW.tenant_id AND id=NEW.conta_receber_parcela_id AND conta_receber_id=NEW.conta_receber_id) THEN
 RAISE EXCEPTION 'Parcela nao pertence ao titulo' USING ERRCODE='23514'; END IF;
 IF NEW.pagamento_id IS NOT NULL AND (NEW.conta_receber_parcela_id IS NULL OR NOT EXISTS(
 SELECT 1 FROM erp.pagamentos WHERE tenant_id=NEW.tenant_id AND id=NEW.pagamento_id AND conta_receber_parcela_id=NEW.conta_receber_parcela_id)) THEN
 RAISE EXCEPTION 'Pagamento nao pertence a parcela' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER validar_evento BEFORE INSERT ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.validar_evento_receber();

CREATE TABLE erp.contratos_vendas_versoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, numero integer NOT NULL CHECK(numero>0),
 vigencia_inicio date NOT NULL, vigencia_fim date,
 status text NOT NULL DEFAULT 'rascunho' CHECK(status IN ('rascunho','efetivada')),
 periodicidade text NOT NULL CHECK(periodicidade IN ('semanal','quinzenal','mensal','bimestral','trimestral','semestral','anual')),
 dia_vencimento integer NOT NULL CHECK(dia_vencimento BETWEEN 1 AND 31),
 regra_vencimento text NOT NULL DEFAULT 'dia_fixo' CHECK(regra_vencimento IN ('dia_fixo','dias_apos_periodo')),
 dias_apos_periodo integer CHECK(dias_apos_periodo>=0),
 fim_mes text NOT NULL DEFAULT 'ultimo_dia' CHECK(fim_mes IN ('ultimo_dia','proximo_mes')),
 reajuste_indice text, reajuste_percentual numeric(9,4),
 categoria_id bigint, centro_custo_id bigint, conta_financeira_id bigint, metodo_pagamento_id bigint,
 motivo text NOT NULL CHECK(btrim(motivo)<>''), cliente_snapshot jsonb NOT NULL,
 criado_em timestamptz NOT NULL DEFAULT now(), efetivada_em timestamptz,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,contrato_id,numero), UNIQUE(tenant_id,contrato_id,id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,categoria_id) REFERENCES erp.categorias(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,centro_custo_id) REFERENCES erp.centros_custo(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,conta_financeira_id) REFERENCES erp.contas_financeiras(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,metodo_pagamento_id) REFERENCES erp.metodos_pagamento(tenant_id,id) ON DELETE RESTRICT,
 CHECK(vigencia_fim IS NULL OR vigencia_fim>=vigencia_inicio),
 CHECK(jsonb_typeof(cliente_snapshot)='object'),
 CHECK((status='efetivada')=(efetivada_em IS NOT NULL)),
 CHECK((regra_vencimento='dias_apos_periodo')=(dias_apos_periodo IS NOT NULL))
);
ALTER TABLE erp.contratos_vendas_itens ADD COLUMN contrato_versao_id bigint;
ALTER TABLE erp.contratos_vendas_itens ADD COLUMN item_logico text;
-- Snapshot observado, sem inventar historico de alteracoes passadas.
INSERT INTO erp.contratos_vendas_versoes(tenant_id,contrato_id,numero,vigencia_inicio,vigencia_fim,periodicidade,dia_vencimento,
 reajuste_indice,reajuste_percentual,categoria_id,centro_custo_id,conta_financeira_id,metodo_pagamento_id,motivo,cliente_snapshot,criado_por)
 SELECT c.tenant_id,c.id,1,c.data_inicio,c.data_fim,c.periodicidade,c.dia_vencimento,c.reajuste_indice,c.reajuste_percentual,
 c.categoria_id,c.centro_custo_id,c.conta_financeira_id,c.metodo_pagamento_id,'Estado inicial observado na migracao',
 jsonb_build_object('nome',e.nome,'documento',e.documento,'email',e.email,'logradouro',e.logradouro,'numero',e.numero,'cidade',e.cidade,'uf',e.uf),c.criado_por
 FROM erp.contratos_vendas c JOIN erp.entidades e ON e.tenant_id=c.tenant_id AND e.id=c.cliente_id;
UPDATE erp.contratos_vendas_itens i SET contrato_versao_id=v.id,item_logico=i.id::text FROM erp.contratos_vendas_versoes v WHERE v.tenant_id=i.tenant_id AND v.contrato_id=i.contrato_id;
ALTER TABLE erp.contratos_vendas_itens ALTER COLUMN contrato_versao_id SET NOT NULL;
ALTER TABLE erp.contratos_vendas_itens ALTER COLUMN item_logico SET NOT NULL;
ALTER TABLE erp.contratos_vendas_itens ADD CONSTRAINT contrato_item_versao_fk FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX contrato_item_logico_idx ON erp.contratos_vendas_itens(tenant_id,contrato_versao_id,item_logico);
CREATE TABLE erp.contratos_vendas_eventos(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 contrato_id bigint NOT NULL, contrato_versao_id bigint,
 evento text NOT NULL CHECK(btrim(evento)<>''), motivo text, dados jsonb NOT NULL DEFAULT '{}',
 criado_em timestamptz NOT NULL DEFAULT now(), data_efeito date NOT NULL DEFAULT current_date,
 criado_por bigint REFERENCES shared.users(id) ON DELETE RESTRICT,
 UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,contrato_id) REFERENCES erp.contratos_vendas(tenant_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT,
 CHECK(jsonb_typeof(dados)='object')
);
CREATE INDEX contratos_eventos_data_idx ON erp.contratos_vendas_eventos(tenant_id,contrato_id,criado_em);
CREATE TRIGGER preservar_evento BEFORE UPDATE OR DELETE ON erp.contratos_vendas_eventos FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN contrato_versao_id bigint;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN periodo_inicio date;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN periodo_fim date;
ALTER TABLE erp.contratos_vendas_geracoes ADD COLUMN legado_sem_versao boolean NOT NULL DEFAULT false;
UPDATE erp.contratos_vendas_geracoes SET legado_sem_versao=true;
ALTER TABLE erp.contratos_vendas_geracoes ADD CONSTRAINT geracao_versao_fk FOREIGN KEY(tenant_id,contrato_id,contrato_versao_id) REFERENCES erp.contratos_vendas_versoes(tenant_id,contrato_id,id) ON DELETE RESTRICT;
ALTER TABLE erp.contratos_vendas_geracoes ADD CONSTRAINT geracao_periodo_chk CHECK(
 (legado_sem_versao AND contrato_versao_id IS NULL) OR (NOT legado_sem_versao AND contrato_versao_id IS NOT NULL AND periodo_inicio IS NOT NULL AND periodo_fim>=periodo_inicio));
DROP INDEX erp.contratos_vendas_geracoes_competencia_idx;
CREATE UNIQUE INDEX contratos_geracao_ciclo_idx ON erp.contratos_vendas_geracoes(tenant_id,contrato_id,periodo_inicio) WHERE NOT legado_sem_versao;
CREATE UNIQUE INDEX contratos_geracao_legado_idx ON erp.contratos_vendas_geracoes(tenant_id,contrato_id,competencia) WHERE legado_sem_versao;
CREATE INDEX contratos_geracao_venda_idx ON erp.contratos_vendas_geracoes(tenant_id,venda_id);
CREATE TABLE erp.contratos_vendas_geracoes_tentativas(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id bigint NOT NULL REFERENCES shared.tenants(id) ON DELETE RESTRICT,
 geracao_id bigint NOT NULL, numero integer NOT NULL CHECK(numero>0),
 inicio timestamptz NOT NULL DEFAULT now(), fim timestamptz,
 status text NOT NULL DEFAULT 'executando' CHECK(status IN ('executando','sucesso','falha','abandonada')),
 erro text, execucao_id text NOT NULL CHECK(btrim(execucao_id)<>''),
 UNIQUE(tenant_id,id), UNIQUE(tenant_id,geracao_id,numero), UNIQUE(tenant_id,execucao_id),
 FOREIGN KEY(tenant_id,geracao_id) REFERENCES erp.contratos_vendas_geracoes(tenant_id,id) ON DELETE RESTRICT,
 CHECK((status='executando')=(fim IS NULL)), CHECK(fim IS NULL OR fim>=inicio),
 CHECK(erro IS NULL OR length(erro)<=2000)
);
CREATE UNIQUE INDEX contrato_tentativa_ativa_idx ON erp.contratos_vendas_geracoes_tentativas(tenant_id,geracao_id) WHERE status='executando';

CREATE FUNCTION erp.validar_contrato_versionado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE v erp.contratos_vendas_versoes; g erp.contratos_vendas_geracoes; cid bigint; tid bigint;
BEGIN
 tid:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 PERFORM erp.travar_evolucao(tid);
 IF TG_TABLE_NAME='contratos_vendas_versoes' THEN
  IF TG_OP='DELETE' AND OLD.status='efetivada' THEN RAISE EXCEPTION 'Versao efetivada imutavel' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND OLD.status='efetivada' THEN
   IF (to_jsonb(OLD)-'vigencia_fim') IS DISTINCT FROM (to_jsonb(NEW)-'vigencia_fim')
    OR NEW.vigencia_fim IS NULL OR (OLD.vigencia_fim IS NOT NULL AND NEW.vigencia_fim>OLD.vigencia_fim)
    OR EXISTS(SELECT 1 FROM erp.contratos_vendas_geracoes WHERE tenant_id=tid AND contrato_versao_id=OLD.id AND periodo_fim>NEW.vigencia_fim) THEN
    RAISE EXCEPTION 'Condicoes utilizadas imutaveis' USING ERRCODE='23514';
   END IF;
  END IF;
  IF TG_OP<>'DELETE' AND NEW.status='efetivada' THEN
   IF NOT EXISTS(SELECT 1 FROM erp.contratos_vendas WHERE tenant_id=tid AND id=NEW.contrato_id AND data_inicio<=NEW.vigencia_inicio AND coalesce(data_fim,'infinity'::date)>=coalesce(NEW.vigencia_fim,'infinity'::date)) THEN
    RAISE EXCEPTION 'Vigencia fora do contrato' USING ERRCODE='23514'; END IF;
   IF NOT EXISTS(SELECT 1 FROM erp.contratos_vendas_itens WHERE tenant_id=tid AND contrato_versao_id=NEW.id) THEN
    RAISE EXCEPTION 'Versao exige itens antes de efetivar' USING ERRCODE='23514'; END IF;
   IF EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND contrato_id=NEW.contrato_id AND id<>NEW.id AND status='efetivada'
     AND vigencia_inicio<=coalesce(NEW.vigencia_fim,'infinity'::date) AND coalesce(vigencia_fim,'infinity'::date)>=NEW.vigencia_inicio) THEN
    RAISE EXCEPTION 'Vigencias sobrepostas' USING ERRCODE='23514'; END IF;
  END IF;
 ELSIF TG_TABLE_NAME='contratos_vendas_itens' THEN
  IF TG_OP<>'INSERT' THEN
   SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=OLD.contrato_versao_id;
   IF v.status='efetivada' THEN RAISE EXCEPTION 'Itens efetivados imutaveis' USING ERRCODE='23514'; END IF;
  END IF;
  IF TG_OP<>'DELETE' THEN
   SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=NEW.contrato_versao_id;
   IF v.status='efetivada' THEN RAISE EXCEPTION 'Itens efetivados imutaveis' USING ERRCODE='23514'; END IF;
   IF NEW.total<>round(NEW.quantidade*NEW.valor_unitario,2)-NEW.desconto THEN
    RAISE EXCEPTION 'Total do item inconsistente' USING ERRCODE='23514'; END IF;
  END IF;
 ELSIF TG_TABLE_NAME='contratos_vendas_geracoes' THEN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Preserve geracoes' USING ERRCODE='23514'; END IF;
  IF TG_OP='INSERT' AND NEW.legado_sem_versao THEN RAISE EXCEPTION 'Marcador reservado ao historico migrado' USING ERRCODE='23514'; END IF;
  IF TG_OP='INSERT' AND NOT EXISTS(SELECT 1 FROM erp.contratos_vendas WHERE tenant_id=tid AND id=NEW.contrato_id AND status='ativo' AND excluido_em IS NULL) THEN
   RAISE EXCEPTION 'Geracao exige contrato ativo' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND (OLD.legado_sem_versao OR
   (to_jsonb(OLD)-ARRAY['status','erro','processado_em','venda_id']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['status','erro','processado_em','venda_id'])
   OR (OLD.venda_id IS NOT NULL AND OLD.venda_id IS DISTINCT FROM NEW.venda_id)
   OR OLD.status IN ('concluida','ignorada')) THEN
   RAISE EXCEPTION 'Identidade e resultado da geracao preservados' USING ERRCODE='23514'; END IF;
  SELECT * INTO v FROM erp.contratos_vendas_versoes WHERE tenant_id=tid AND id=NEW.contrato_versao_id;
  IF v.status IS DISTINCT FROM 'efetivada' OR NEW.periodo_inicio<v.vigencia_inicio OR NEW.periodo_fim>coalesce(v.vigencia_fim,'infinity'::date)
   OR EXISTS(SELECT 1 FROM erp.contratos_vendas_geracoes x WHERE x.tenant_id=tid AND x.contrato_id=NEW.contrato_id AND x.id<>NEW.id
    AND ((NOT x.legado_sem_versao AND x.periodo_inicio<=NEW.periodo_fim AND x.periodo_fim>=NEW.periodo_inicio)
      OR (x.legado_sem_versao AND date_trunc('month',x.competencia)=date_trunc('month',NEW.competencia)))) THEN
   RAISE EXCEPTION 'Ciclo ou versao invalida; historico legado exige revisao explicita' USING ERRCODE='23514'; END IF;
  IF NEW.periodo_fim<>(NEW.periodo_inicio+CASE v.periodicidade WHEN 'semanal' THEN interval '7 days' WHEN 'quinzenal' THEN interval '15 days' WHEN 'mensal' THEN interval '1 month' WHEN 'bimestral' THEN interval '2 months' WHEN 'trimestral' THEN interval '3 months' WHEN 'semestral' THEN interval '6 months' ELSE interval '1 year' END-interval '1 day')::date THEN
   RAISE EXCEPTION 'Duracao do ciclo incompativel com periodicidade' USING ERRCODE='23514'; END IF;
  IF (NEW.status='concluida') IS DISTINCT FROM (NEW.venda_id IS NOT NULL) THEN RAISE EXCEPTION 'Resultado da geracao inconsistente' USING ERRCODE='23514'; END IF;
  IF NEW.venda_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM erp.vendas s JOIN erp.contratos_vendas c ON c.tenant_id=s.tenant_id AND c.cliente_id=s.cliente_id WHERE c.tenant_id=tid AND c.id=NEW.contrato_id AND s.id=NEW.venda_id) THEN
   RAISE EXCEPTION 'Venda pertence a outro cliente' USING ERRCODE='23514'; END IF;
 ELSE
  IF TG_OP='DELETE' OR (TG_OP='UPDATE' AND (OLD.status<>'executando'
    OR (to_jsonb(OLD)-ARRAY['fim','status','erro']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['fim','status','erro']))) THEN
   RAISE EXCEPTION 'Tentativa encerrada imutavel' USING ERRCODE='23514'; END IF;
  SELECT * INTO g FROM erp.contratos_vendas_geracoes WHERE tenant_id=tid AND id=NEW.geracao_id;
  IF (NEW.status='sucesso' AND g.status<>'concluida') OR (NEW.status='executando' AND g.status<>'processando') THEN
   RAISE EXCEPTION 'Tentativa incompativel com geracao' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['contratos_vendas_versoes','contratos_vendas_itens','contratos_vendas_geracoes','contratos_vendas_geracoes_tentativas'] LOOP
 EXECUTE format('CREATE TRIGGER validar_contrato_versionado BEFORE INSERT OR UPDATE OR DELETE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.validar_contrato_versionado()',t);
 END LOOP;
END $$;
-- Eventos gerados pelo banco compartilham a transacao da alteracao.
CREATE FUNCTION erp.registrar_evolucao_documento() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE j jsonb; antes jsonb; tid bigint; doc bigint; parcela bigint; pagamento bigint; lado text; autor bigint; ev text;
BEGIN
 j:=CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 IF TG_OP<>'INSERT' THEN antes:=to_jsonb(OLD); END IF;
 tid:=(j->>'tenant_id')::bigint;
 autor:=nullif(current_setting('app.erp_user_id',true),'')::bigint;
 ev:=TG_TABLE_NAME||'.'||lower(TG_OP);
 IF TG_TABLE_NAME='contratos_vendas' OR TG_TABLE_NAME='contratos_vendas_versoes' THEN
  doc:=CASE WHEN TG_TABLE_NAME='contratos_vendas' THEN (j->>'id')::bigint ELSE (j->>'contrato_id')::bigint END;
  INSERT INTO erp.contratos_vendas_eventos(tenant_id,contrato_id,contrato_versao_id,evento,criado_por,dados)
   VALUES(tid,doc,CASE WHEN TG_TABLE_NAME='contratos_vendas_versoes' THEN (j->>'id')::bigint END,ev,autor,jsonb_build_object('antes',antes,'depois',j));
 ELSE
  IF TG_TABLE_NAME='pagamentos' THEN
   lado:=j->>'tipo'; pagamento:=(j->>'id')::bigint; parcela:=(j->>('conta_'||lado||'_parcela_id'))::bigint;
   EXECUTE format('SELECT conta_%s_id FROM erp.contas_%s_parcelas WHERE tenant_id=$1 AND id=$2',lado,lado) INTO doc USING tid,parcela;
  ELSE
   lado:=CASE WHEN TG_TABLE_NAME LIKE 'contas_receber%' THEN 'receber' ELSE 'pagar' END;
   IF TG_TABLE_NAME LIKE '%parcelas' THEN doc:=(j->>('conta_'||lado||'_id'))::bigint; parcela:=(j->>'id')::bigint;
   ELSE doc:=(j->>'id')::bigint; END IF;
  END IF;
  IF lado='receber' THEN
   INSERT INTO erp.contas_receber_eventos(tenant_id,conta_receber_id,conta_receber_parcela_id,pagamento_id,evento,criado_por,dados)
   VALUES(tid,doc,parcela,pagamento,ev,autor,jsonb_build_object('antes',antes,'depois',j));
  ELSE
   INSERT INTO erp.contas_pagar_eventos(tenant_id,conta_pagar_id,evento,criado_por,dados)
   VALUES(tid,doc,ev,autor,jsonb_build_object('antes',antes,'depois',j));
  END IF;
 END IF;
 RETURN NULL;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['contas_receber','contas_receber_parcelas','contas_pagar','contas_pagar_parcelas','pagamentos','contratos_vendas','contratos_vendas_versoes'] LOOP
 EXECUTE format('CREATE TRIGGER registrar_evolucao AFTER INSERT OR UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.registrar_evolucao_documento()',t);
 END LOOP;
END $$;
-- Dados antigos sao copiados apenas quando suficientes para formar um registro real.
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,email,telefone,criado_por)
 SELECT tenant_id,id,nome,nullif(btrim(email),''),coalesce(nullif(btrim(telefone),''),nullif(btrim(celular),'')),criado_por FROM erp.entidades
 WHERE nullif(btrim(email),'') IS NOT NULL OR coalesce(nullif(btrim(telefone),''),nullif(btrim(celular),'')) IS NOT NULL;
INSERT INTO erp.entidades_enderecos(tenant_id,entidade_id,identificacao,logradouro,numero,complemento,bairro,cidade,uf,cep,pais,criado_por)
 SELECT tenant_id,id,'Endereco existente',logradouro,numero,complemento,bairro,cidade,uf,cep,pais,criado_por FROM erp.entidades
 WHERE nullif(btrim(logradouro),'') IS NOT NULL AND nullif(btrim(cidade),'') IS NOT NULL;

CREATE FUNCTION erp.preservar_arquivo_referenciado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(OLD.tenant_id);
 IF EXISTS(SELECT 1 FROM erp.contratos_vendas_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.vendas_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.ordens_servico_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id)
 OR EXISTS(SELECT 1 FROM erp.contas_receber_arquivos WHERE tenant_id=OLD.tenant_id AND arquivo_id=OLD.id) THEN
  IF TG_OP='DELETE' OR (to_jsonb(OLD)-ARRAY['atualizado_em','atualizado_por']) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['atualizado_em','atualizado_por']) THEN
  RAISE EXCEPTION 'Arquivo referenciado preservado' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
CREATE TRIGGER preservar_arquivo_referenciado BEFORE UPDATE OR DELETE ON erp.arquivos FOR EACH ROW EXECUTE FUNCTION erp.preservar_arquivo_referenciado();
CREATE FUNCTION erp.validar_arquivo_anexo() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM erp.arquivos WHERE tenant_id=NEW.tenant_id AND id=NEW.arquivo_id AND excluido_em IS NULL) THEN
 RAISE EXCEPTION 'Arquivo indisponivel' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION erp.snapshot_documento_cliente() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE e erp.entidades;
BEGIN
 IF TG_OP='INSERT' THEN
  SELECT * INTO e FROM erp.entidades WHERE tenant_id=NEW.tenant_id AND id=NEW.cliente_id;
  NEW.cliente_snapshot:=jsonb_build_object('nome',e.nome,'documento',e.documento,'email',e.email,'logradouro',e.logradouro,'numero',e.numero,'cidade',e.cidade,'uf',e.uf,'origem','cadastro_na_criacao');
 ELSIF OLD.cliente_snapshot IS DISTINCT FROM NEW.cliente_snapshot THEN
  RAISE EXCEPTION 'Snapshot documental preservado' USING ERRCODE='23514';
 ELSIF OLD.cliente_id IS DISTINCT FROM NEW.cliente_id THEN
  RAISE EXCEPTION 'Troca de cliente exige novo documento para preservar identidade' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['vendas','ordens_servico','contratos_vendas'] LOOP
 -- Nao atualizar documentos antigos: nao ha evidencia para reconstruir seu snapshot.
 EXECUTE format('ALTER TABLE erp.%I ADD COLUMN cliente_snapshot jsonb NOT NULL DEFAULT ''{"origem":"historico_sem_snapshot"}''::jsonb CHECK(jsonb_typeof(cliente_snapshot)=''object'')',t);
 EXECUTE format('CREATE TRIGGER snapshot_documento_cliente BEFORE INSERT OR UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.snapshot_documento_cliente()',t);
 END LOOP;
END $$;
CREATE FUNCTION erp.preservar_contato_legado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF pg_trigger_depth()>1 THEN RETURN NEW; END IF;
 IF ROW(OLD.email,OLD.telefone,OLD.celular,OLD.contato_cobranca_emails,OLD.contato_cobranca_whatsapp,OLD.logradouro,OLD.numero,OLD.complemento,OLD.bairro,OLD.cidade,OLD.uf,OLD.cep,OLD.pais)
 IS DISTINCT FROM ROW(NEW.email,NEW.telefone,NEW.celular,NEW.contato_cobranca_emails,NEW.contato_cobranca_whatsapp,NEW.logradouro,NEW.numero,NEW.complemento,NEW.bairro,NEW.cidade,NEW.uf,NEW.cep,NEW.pais) THEN
 RAISE EXCEPTION 'Atualize contatos e enderecos nas estruturas normalizadas; campos legados preservados' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER preservar_contato_legado BEFORE UPDATE ON erp.entidades FOR EACH ROW EXECUTE FUNCTION erp.preservar_contato_legado();

ALTER TABLE erp.entidades_contatos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.entidades_contatos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.entidades_contatos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.entidades_contatos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.entidades_contatos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE INDEX entidades_contatos_entidade_idx ON erp.entidades_contatos(tenant_id,entidade_id);
CREATE TRIGGER validar_principais BEFORE INSERT OR UPDATE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.validar_principais_entidade();

ALTER TABLE erp.entidades_enderecos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.entidades_enderecos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.entidades_enderecos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.entidades_enderecos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.entidades_enderecos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.cadastros.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE INDEX entidades_enderecos_entidade_idx ON erp.entidades_enderecos(tenant_id,entidade_id);
CREATE TRIGGER validar_principais BEFORE INSERT OR UPDATE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.validar_principais_entidade();

ALTER TABLE erp.contratos_vendas_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contratos_vendas_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.contratos_vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.vendas_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.vendas_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.vendas_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.vendas_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.vendas_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.vendas_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.ordens_servico_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.ordens_servico_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.ordens_servico_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.ordens_servico_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.ordens_servico_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.ordens_servico_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.ordens_servico_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.contas_receber_arquivos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contas_receber_arquivos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contas_receber_arquivos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contas_receber_arquivos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contas_receber_arquivos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contas_receber_arquivos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();
CREATE TRIGGER validar_arquivo BEFORE INSERT ON erp.contas_receber_arquivos FOR EACH ROW EXECUTE FUNCTION erp.validar_arquivo_anexo();

ALTER TABLE erp.contas_receber_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contas_receber_eventos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contas_receber_eventos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contas_receber_eventos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contas_receber_eventos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.financeiro.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contas_receber_eventos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_versoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_versoes FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.contratos_vendas_versoes TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_versoes_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_versoes FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_versoes FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_eventos FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.contratos_vendas_eventos TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_eventos_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_eventos FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_eventos FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

ALTER TABLE erp.contratos_vendas_geracoes_tentativas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.contratos_vendas_geracoes_tentativas FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON erp.contratos_vendas_geracoes_tentativas TO erp_runtime;
GRANT USAGE,SELECT ON SEQUENCE erp.contratos_vendas_geracoes_tentativas_id_seq TO erp_runtime;
CREATE POLICY acesso ON erp.contratos_vendas_geracoes_tentativas FOR ALL TO erp_runtime USING(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar')) WITH CHECK(shared.has_erp_capability(tenant_id,'erp.vendas.gerenciar'));
CREATE TRIGGER a_proteger_identidade BEFORE INSERT OR UPDATE OR DELETE ON erp.contratos_vendas_geracoes_tentativas FOR EACH ROW EXECUTE FUNCTION erp.proteger_identidade_nova();

REVOKE ALL ON FUNCTION erp.travar_evolucao(bigint),erp.proteger_identidade_nova(),erp.validar_principais_entidade(),
 erp.validar_evento_receber(),erp.validar_contrato_versionado(),erp.registrar_evolucao_documento(),
 erp.preservar_arquivo_referenciado(),erp.validar_arquivo_anexo(),erp.snapshot_documento_cliente(),erp.preservar_contato_legado() FROM PUBLIC;
UPDATE erp.entidades_contatos c SET finalidades=ARRAY['comercial','financeiro']::text[]
 FROM erp.entidades e WHERE e.tenant_id=c.tenant_id AND e.id=c.entidade_id AND c.email=ANY(e.contato_cobranca_emails);
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,email,finalidades,criado_por)
 SELECT DISTINCT e.tenant_id,e.id,e.nome,btrim(endereco),ARRAY['financeiro']::text[],e.criado_por
 FROM erp.entidades e CROSS JOIN LATERAL unnest(e.contato_cobranca_emails) endereco
 WHERE nullif(btrim(endereco),'') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM erp.entidades_contatos c WHERE c.tenant_id=e.tenant_id AND c.entidade_id=e.id AND c.email=btrim(endereco));
INSERT INTO erp.entidades_contatos(tenant_id,entidade_id,nome,telefone,whatsapp,finalidades,criado_por)
 SELECT tenant_id,id,nome,contato_cobranca_whatsapp,true,ARRAY['financeiro']::text[],criado_por FROM erp.entidades WHERE nullif(btrim(contato_cobranca_whatsapp),'') IS NOT NULL;
CREATE FUNCTION erp.refletir_cadastro_normalizado() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t bigint; e bigint; c erp.entidades_contatos; a erp.entidades_enderecos;
BEGIN
 t:=CASE WHEN TG_OP='DELETE' THEN OLD.tenant_id ELSE NEW.tenant_id END;
 e:=CASE WHEN TG_OP='DELETE' THEN OLD.entidade_id ELSE NEW.entidade_id END;
 IF TG_OP='UPDATE' AND OLD.entidade_id<>NEW.entidade_id THEN RAISE EXCEPTION 'Nao mover contato ou endereco entre entidades' USING ERRCODE='23514'; END IF;
 IF TG_TABLE_NAME='entidades_contatos' THEN
  SELECT * INTO c FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'comercial'=ANY(finalidades)
   ORDER BY ('comercial'=ANY(principais)) DESC,id LIMIT 1;
  UPDATE erp.entidades SET email=c.email,telefone=c.telefone,celular=NULL,
   contato_cobranca_emails=ARRAY(SELECT DISTINCT email FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'financeiro'=ANY(finalidades) AND nullif(btrim(email),'') IS NOT NULL),
   contato_cobranca_whatsapp=(SELECT telefone FROM erp.entidades_contatos WHERE tenant_id=t AND entidade_id=e AND ativo AND whatsapp AND 'financeiro'=ANY(finalidades) ORDER BY ('financeiro'=ANY(principais)) DESC,id LIMIT 1)
   WHERE tenant_id=t AND id=e;
 ELSE
  SELECT * INTO a FROM erp.entidades_enderecos WHERE tenant_id=t AND entidade_id=e AND ativo AND 'comercial'=ANY(finalidades)
   ORDER BY ('comercial'=ANY(principais)) DESC,id LIMIT 1;
  UPDATE erp.entidades SET logradouro=a.logradouro,numero=a.numero,complemento=a.complemento,bairro=a.bairro,cidade=a.cidade,uf=a.uf,cep=a.cep,pais=coalesce(a.pais,'Brasil') WHERE tenant_id=t AND id=e;
 END IF;
 RETURN NULL;
END $$;
CREATE TRIGGER refletir_cadastro AFTER INSERT OR UPDATE OR DELETE ON erp.entidades_contatos FOR EACH ROW EXECUTE FUNCTION erp.refletir_cadastro_normalizado();
CREATE TRIGGER refletir_cadastro AFTER INSERT OR UPDATE OR DELETE ON erp.entidades_enderecos FOR EACH ROW EXECUTE FUNCTION erp.refletir_cadastro_normalizado();
REVOKE ALL ON FUNCTION erp.refletir_cadastro_normalizado() FROM PUBLIC;
CREATE FUNCTION erp.validar_cabecalho_contrato() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM erp.travar_evolucao(NEW.tenant_id);
 IF NEW.status='ativo' AND NOT EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=NEW.tenant_id AND contrato_id=NEW.id AND status='efetivada') THEN
  RAISE EXCEPTION 'Contrato ativo exige versao efetivada' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' AND EXISTS(SELECT 1 FROM erp.contratos_vendas_versoes WHERE tenant_id=OLD.tenant_id AND contrato_id=OLD.id) AND
 ROW(OLD.data_inicio,OLD.data_fim,OLD.periodicidade,OLD.dia_vencimento,OLD.reajuste_indice,OLD.reajuste_percentual,OLD.categoria_id,OLD.centro_custo_id,OLD.conta_financeira_id,OLD.metodo_pagamento_id)
 IS DISTINCT FROM ROW(NEW.data_inicio,NEW.data_fim,NEW.periodicidade,NEW.dia_vencimento,NEW.reajuste_indice,NEW.reajuste_percentual,NEW.categoria_id,NEW.centro_custo_id,NEW.conta_financeira_id,NEW.metodo_pagamento_id) THEN
 RAISE EXCEPTION 'Condicoes comerciais devem ser alteradas por nova versao' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER validar_cabecalho_contrato BEFORE INSERT OR UPDATE ON erp.contratos_vendas FOR EACH ROW EXECUTE FUNCTION erp.validar_cabecalho_contrato();
REVOKE ALL ON FUNCTION erp.validar_cabecalho_contrato() FROM PUBLIC;
COMMIT;
