BEGIN;

-- Fase 1.5 — devolução de venda: itens devolvidos voltam ao estoque e o valor é tratado de uma das três formas:
--   abater   → baixa sem dinheiro (desconto = valor) nas parcelas em aberto da venda;
--   credito  → saldo de crédito do cliente, usado depois como baixa sem dinheiro em outra parcela dele;
--   reembolso→ conta a pagar ao cliente.
-- Nenhuma das três cria entrada ou saída de caixa fictícia: baixas de abatimento e de uso de crédito têm valor
-- líquido zero, então fluxo de caixa e resultado por caixa não mudam.

CREATE TABLE erp.devolucoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  venda_id bigint NOT NULL,
  cliente_id bigint NOT NULL,
  numero text NOT NULL CHECK (btrim(numero) <> ''),
  data_devolucao date NOT NULL DEFAULT erp.hoje(),
  motivo text NOT NULL CHECK (btrim(motivo) <> ''),
  tratamento text NOT NULL CHECK (tratamento IN ('abater', 'credito', 'reembolso')),
  valor_total numeric(18,2) NOT NULL CHECK (valor_total > 0),
  valor_credito numeric(18,2) NOT NULL DEFAULT 0 CHECK (valor_credito >= 0 AND valor_credito <= valor_total),
  conta_pagar_id bigint,
  documento_estoque_id bigint,
  chave_idempotencia text NOT NULL CHECK (btrim(chave_idempotencia) <> ''),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, numero),
  UNIQUE (empresa_id, chave_idempotencia),
  FOREIGN KEY (empresa_id, venda_id) REFERENCES erp.vendas(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, cliente_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, conta_pagar_id) REFERENCES erp.contas_pagar(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, documento_estoque_id) REFERENCES erp.documentos_estoque(empresa_id, id) ON DELETE RESTRICT,
  CHECK ((tratamento = 'credito') = (valor_credito > 0)),
  CHECK ((tratamento = 'reembolso') = (conta_pagar_id IS NOT NULL))
);
COMMENT ON TABLE erp.devolucoes IS 'Devoluções de venda (produto devolvido ou serviço desfeito) e o tratamento financeiro escolhido.';
CREATE INDEX devolucoes_venda_idx ON erp.devolucoes(empresa_id, venda_id);
CREATE INDEX devolucoes_cliente_idx ON erp.devolucoes(empresa_id, cliente_id);

CREATE TABLE erp.devolucoes_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  devolucao_id bigint NOT NULL,
  venda_item_id bigint NOT NULL,
  quantidade numeric(18,4) NOT NULL CHECK (quantidade > 0),
  valor numeric(18,2) NOT NULL CHECK (valor >= 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, devolucao_id, venda_item_id),
  FOREIGN KEY (empresa_id, devolucao_id) REFERENCES erp.devolucoes(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY (empresa_id, venda_item_id) REFERENCES erp.vendas_itens(empresa_id, id) ON DELETE RESTRICT
);
CREATE INDEX devolucoes_itens_venda_item_idx ON erp.devolucoes_itens(empresa_id, venda_item_id);

-- Baixas ligadas à devolução: abatimento (origem devolucao) e uso de crédito (origem credito_cliente).
ALTER TABLE erp.pagamentos ADD COLUMN devolucao_id bigint;
ALTER TABLE erp.pagamentos ADD CONSTRAINT pagamentos_devolucao_fk FOREIGN KEY (empresa_id, devolucao_id) REFERENCES erp.devolucoes(empresa_id, id) ON DELETE RESTRICT;
CREATE INDEX pagamentos_devolucao_idx ON erp.pagamentos(empresa_id, devolucao_id) WHERE devolucao_id IS NOT NULL;
DO $origem$
DECLARE c record;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint WHERE conrelid = 'erp.pagamentos'::regclass AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%origem%' AND pg_get_constraintdef(oid) LIKE '%conciliacao%' LOOP
    EXECUTE format('ALTER TABLE erp.pagamentos DROP CONSTRAINT %I', c.conname);
  END LOOP;
END
$origem$;
ALTER TABLE erp.pagamentos ADD CONSTRAINT pagamentos_origem_check
  CHECK (origem IN ('manual','conciliacao','boleto','pix','cartao','api','estorno','devolucao','credito_cliente'));
ALTER TABLE erp.pagamentos ADD CONSTRAINT pagamentos_devolucao_sem_dinheiro_chk
  CHECK (origem NOT IN ('devolucao','credito_cliente') OR (devolucao_id IS NOT NULL AND tipo = 'receber' AND desconto = valor AND juros = 0 AND multa = 0 AND taxa = 0)
    OR estorno_de_pagamento_id IS NOT NULL);

-- Numeração DEV-AAAA-NNNN.
ALTER TABLE erp.numeracoes DROP CONSTRAINT IF EXISTS numeracoes_tipo_check;
ALTER TABLE erp.numeracoes ADD CONSTRAINT numeracoes_tipo_check
  CHECK (tipo IN ('venda','orcamento','pedido','compra','ordem_servico','contrato','inventario','transferencia_estoque','devolucao'));
CREATE OR REPLACE FUNCTION erp.proximo_numero(empresa_id bigint, tipo text, data date)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog'
AS $function$
#variable_conflict use_column
DECLARE
  v_empresa bigint := proximo_numero.empresa_id;
  v_tipo text := proximo_numero.tipo;
  v_ano integer := extract(year FROM coalesce(proximo_numero.data, erp.hoje()))::integer;
  v_prefixo text; v_tabela text; v_numero text; v_n bigint; v_existe boolean;
BEGIN
  IF shared.erp_empresa_contexto() IS NOT NULL AND (v_empresa IS DISTINCT FROM shared.erp_empresa_contexto() OR NOT shared.is_tenant_member(v_empresa)) THEN
    RAISE EXCEPTION 'Numeração fora da empresa da sessão' USING ERRCODE='42501';
  END IF;
  SELECT x.prefixo, x.tabela INTO v_prefixo, v_tabela FROM (VALUES
    ('venda','VEN','vendas'),('orcamento','ORC','vendas'),('pedido','PED','vendas'),('compra','COM','compras'),
    ('ordem_servico','OS','ordens_servico'),('contrato','CTR','contratos_vendas'),('inventario','INV','inventarios'),
    ('transferencia_estoque','TRF','transferencias_estoque'),('devolucao','DEV','devolucoes')) AS x(tipo, prefixo, tabela)
  WHERE x.tipo = v_tipo;
  IF v_prefixo IS NULL THEN RAISE EXCEPTION 'Tipo de numeração inválido' USING ERRCODE='22023'; END IF;
  LOOP
    INSERT INTO erp.numeracoes AS n (empresa_id, tipo, ano, proximo) VALUES (v_empresa, v_tipo, v_ano, 2)
    ON CONFLICT (empresa_id, tipo, ano) DO UPDATE SET proximo = n.proximo + 1, atualizado_em = now()
    RETURNING n.proximo - 1 INTO v_n;
    v_numero := format('%s-%s-%s', v_prefixo, v_ano, lpad(v_n::text, 4, '0'));
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM erp.%I WHERE empresa_id=$1 AND numero=$2)', v_tabela) INTO v_existe USING v_empresa, v_numero;
    EXIT WHEN NOT v_existe;
  END LOOP;
  RETURN v_numero;
END
$function$;

SELECT erp.criar_politicas_padrao('devolucoes', 'vendas', 'erp.vendas.gerenciar');
SELECT erp.criar_politicas_padrao('devolucoes_itens', 'vendas', 'erp.vendas.gerenciar');

COMMIT;
