BEGIN;

-- Generated mode classifies existing demonstrations without rewriting frozen invoice data.
ALTER TABLE erp.notas_fiscais ADD COLUMN modo_operacao text GENERATED ALWAYS AS
 (CASE WHEN provedor='simulador_local' THEN 'simulacao' ELSE 'real' END) STORED,
 ADD COLUMN simulacao_cenario text NOT NULL DEFAULT 'sucesso'
 CHECK(simulacao_cenario IN ('sucesso','rejeicao','demora','timeout'));
ALTER TABLE erp.notas_fiscais ADD CONSTRAINT notas_fiscais_simulacao_chk CHECK(
 modo_operacao<>'simulacao' OR (ambiente='homologacao' AND numero LIKE 'DEMO-%'
 AND chave_acesso IS NULL AND metadata @> '{"simulado":true,"sem_validade_fiscal":true}'::jsonb));

CREATE OR REPLACE FUNCTION erp.validar_integridade_nota_fiscal() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE documento record; config record;
BEGIN
  IF TG_OP='UPDATE' AND OLD.provedor='simulador_local' AND NEW.provedor IS DISTINCT FROM OLD.provedor THEN
    RAISE EXCEPTION 'Uma nota simulada não pode ser convertida em nota real' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' THEN
    IF OLD.conteudo_bloqueado_em IS NOT NULL THEN RAISE EXCEPTION 'Documento fiscal autorizado não pode ser excluído' USING ERRCODE='23514'; END IF;
    RETURN OLD;
  END IF;
  IF TG_OP='UPDATE' AND OLD.conteudo_bloqueado_em IS NOT NULL THEN
    IF (to_jsonb(NEW)-ARRAY['modo_operacao','status','atualizado_em','atualizado_por','cancelada_em','erro_codigo','erro_mensagem','codigo_status_sefaz','motivo_status_sefaz','resposta_provedor','xml_url','pdf_url','danfe_url','versao'])
      IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['modo_operacao','status','atualizado_em','atualizado_por','cancelada_em','erro_codigo','erro_mensagem','codigo_status_sefaz','motivo_status_sefaz','resposta_provedor','xml_url','pdf_url','danfe_url','versao']) THEN
      RAISE EXCEPTION 'Conteúdo fiscal autorizado é imutável' USING ERRCODE='23514';
    END IF;
    IF NEW.status NOT IN ('emitida','cancelada','corrigida','denegada') OR
      (OLD.status IN ('cancelada','denegada') AND NEW.status<>OLD.status) THEN
      RAISE EXCEPTION 'Transição de documento fiscal finalizado inválida' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
  END IF;
  IF TG_OP='INSERT' THEN NEW.conteudo_bloqueado_em:=NULL; END IF;
  IF NEW.venda_id IS NOT NULL THEN
    SELECT cliente_id INTO documento FROM erp.vendas WHERE empresa_id=NEW.empresa_id AND id=NEW.venda_id;
    IF documento.cliente_id IS DISTINCT FROM NEW.entidade_id THEN RAISE EXCEPTION 'Destinatário diferente do cliente da venda' USING ERRCODE='23514'; END IF;
  END IF;
  IF NEW.compra_id IS NOT NULL THEN
    SELECT fornecedor_id INTO documento FROM erp.compras WHERE empresa_id=NEW.empresa_id AND id=NEW.compra_id;
    IF documento.fornecedor_id IS DISTINCT FROM NEW.entidade_id THEN RAISE EXCEPTION 'Entidade diferente do fornecedor da compra' USING ERRCODE='23514'; END IF;
  END IF;
  IF NEW.provedor IS DISTINCT FROM 'simulador_local' AND NEW.direcao='saida' AND NEW.status IN ('pronta_envio','aguardando_retorno','emitida','corrigida','denegada') THEN
    SELECT * INTO config FROM erp.configuracoes_fiscais WHERE empresa_id=NEW.empresa_id AND id=NEW.configuracao_fiscal_id;
    IF NOT FOUND OR NEW.provedor IS DISTINCT FROM config.provedor OR NEW.ambiente IS DISTINCT FROM config.ambiente
      OR NEW.modelo_emissao IS NULL OR NEW.emitente_snapshot='{}'::jsonb OR NEW.destinatario_snapshot='{}'::jsonb THEN
      RAISE EXCEPTION 'Preparação fiscal incompleta ou configuração incompatível' USING ERRCODE='23514';
    END IF;
    IF NEW.status='pronta_envio' AND (NOT config.ativo OR config.excluido_em IS NOT NULL) THEN
      RAISE EXCEPTION 'Configuração fiscal inativa' USING ERRCODE='23514';
    END IF;
    IF NEW.modelo_emissao='nfse_nacional' AND (NEW.data_competencia IS NULL OR NEW.numero_dps IS NULL OR NEW.serie_dps IS NULL
      OR NEW.codigo_municipio_emissao IS NULL OR NEW.codigo_municipio_prestacao IS NULL) THEN
      RAISE EXCEPTION 'Identificação da DPS nacional incompleta' USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;

ALTER TABLE erp.notas_fiscais_tentativas DROP CONSTRAINT notas_fiscais_tentativas_acao_check;
ALTER TABLE erp.notas_fiscais_tentativas ADD CONSTRAINT notas_fiscais_tentativas_acao_check
 CHECK(acao IN ('criar','editar','excluir','emitir','consultar','cancelar','corrigir','substituir','inutilizar'));

CREATE TABLE erp.notas_fiscais_pdfs(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
 nota_fiscal_id bigint NOT NULL,versao integer NOT NULL CHECK(versao>0),
 conteudo bytea NOT NULL CHECK(octet_length(conteudo) BETWEEN 100 AND 2097152),
 hash_sha256 text NOT NULL CHECK(hash_sha256 ~ '^[0-9a-f]{64}$'),
 nome text NOT NULL CHECK(nome ~ '^DEMO-[a-zA-Z0-9-]+\.pdf$'),
 criado_em timestamptz NOT NULL DEFAULT now(),criado_por bigint REFERENCES shared.usuarios(id),
 UNIQUE(empresa_id,id),UNIQUE(empresa_id,nota_fiscal_id,versao),
 FOREIGN KEY(empresa_id,nota_fiscal_id) REFERENCES erp.notas_fiscais(empresa_id,id) ON DELETE RESTRICT
);
ALTER TABLE erp.notas_fiscais_pdfs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON erp.notas_fiscais_pdfs FROM PUBLIC,anon,authenticated,erp_runtime;
GRANT SELECT,INSERT ON erp.notas_fiscais_pdfs TO erp_runtime,service_role;
GRANT USAGE,SELECT ON SEQUENCE erp.notas_fiscais_pdfs_id_seq TO erp_runtime,service_role;
CREATE POLICY ler_pdf_fiscal ON erp.notas_fiscais_pdfs FOR SELECT TO erp_runtime USING(
 EXISTS(SELECT 1 FROM erp.notas_fiscais n WHERE n.empresa_id=notas_fiscais_pdfs.empresa_id
 AND n.id=notas_fiscais_pdfs.nota_fiscal_id AND n.excluido_em IS NULL));
CREATE POLICY inserir_pdf_fiscal ON erp.notas_fiscais_pdfs FOR INSERT TO erp_runtime WITH CHECK(
 shared.has_erp_capability(empresa_id,'erp.vendas.gerenciar') AND EXISTS(
 SELECT 1 FROM erp.notas_fiscais n WHERE n.empresa_id=notas_fiscais_pdfs.empresa_id
 AND n.id=notas_fiscais_pdfs.nota_fiscal_id AND n.modo_operacao='simulacao' AND n.tipo='nfse'));
CREATE TRIGGER pdf_fiscal_imutavel BEFORE UPDATE OR DELETE ON erp.notas_fiscais_pdfs
 FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();
COMMENT ON TABLE erp.notas_fiscais_pdfs IS 'PDFs demonstrativos privados e versionados, servidos somente pela API autenticada. Sem transmissão fiscal externa.';
COMMIT;
