BEGIN;

ALTER TABLE erp.vendas
  ADD COLUMN IF NOT EXISTS tipo_documento text NOT NULL DEFAULT 'venda',
  ADD COLUMN IF NOT EXISTS venda_origem_id bigint,
  ADD COLUMN IF NOT EXISTS validade_em date,
  ADD COLUMN IF NOT EXISTS local_estoque_id bigint;

ALTER TABLE erp.compras
  ADD COLUMN IF NOT EXISTS local_estoque_id bigint;

ALTER TABLE erp.vendas
  ADD CONSTRAINT vendas_tipo_documento_chk CHECK (tipo_documento IN ('orcamento', 'pedido', 'venda')),
  ADD CONSTRAINT vendas_origem_documento_fk FOREIGN KEY (tenant_id, venda_origem_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT vendas_local_estoque_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT;

ALTER TABLE erp.compras
  ADD CONSTRAINT compras_local_estoque_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS erp.contratos_vendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  cliente_id bigint NOT NULL,
  numero text NOT NULL,
  descricao text NOT NULL,
  data_inicio date NOT NULL,
  data_fim date,
  periodicidade text NOT NULL DEFAULT 'mensal',
  dia_vencimento integer NOT NULL DEFAULT 1,
  proxima_geracao_em date,
  status text NOT NULL DEFAULT 'rascunho',
  reajuste_indice text,
  reajuste_percentual numeric(9,4),
  categoria_id bigint,
  centro_custo_id bigint,
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  observacoes text,
  chave_idempotencia text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT contratos_vendas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contratos_vendas_periodicidade_chk CHECK (periodicidade IN ('semanal', 'quinzenal', 'mensal', 'bimestral', 'trimestral', 'semestral', 'anual')),
  CONSTRAINT contratos_vendas_status_chk CHECK (status IN ('rascunho', 'ativo', 'pausado', 'encerrado', 'cancelado')),
  CONSTRAINT contratos_vendas_datas_chk CHECK (data_fim IS NULL OR data_fim >= data_inicio),
  CONSTRAINT contratos_vendas_vencimento_chk CHECK (dia_vencimento BETWEEN 1 AND 31),
  CONSTRAINT contratos_vendas_reajuste_chk CHECK (reajuste_percentual IS NULL OR reajuste_percentual >= 0),
  CONSTRAINT contratos_vendas_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contratos_vendas_versao_chk CHECK (versao > 0),
  CONSTRAINT contratos_vendas_cliente_fk FOREIGN KEY (tenant_id, cliente_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contratos_vendas_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contratos_vendas_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contratos_vendas_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contratos_vendas_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contratos_vendas_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  contrato_id bigint NOT NULL,
  produto_id bigint,
  servico_id bigint,
  descricao text NOT NULL,
  quantidade numeric(18,4) NOT NULL DEFAULT 1,
  valor_unitario numeric(18,4) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  total numeric(18,2) NOT NULL DEFAULT 0,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT contratos_vendas_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contratos_vendas_itens_origem_chk CHECK ((produto_id IS NOT NULL AND servico_id IS NULL) OR (produto_id IS NULL AND servico_id IS NOT NULL)),
  CONSTRAINT contratos_vendas_itens_valores_chk CHECK (quantidade > 0 AND valor_unitario >= 0 AND desconto >= 0 AND total >= 0),
  CONSTRAINT contratos_vendas_itens_contrato_fk FOREIGN KEY (tenant_id, contrato_id)
    REFERENCES erp.contratos_vendas (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT contratos_vendas_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contratos_vendas_itens_servico_fk FOREIGN KEY (tenant_id, servico_id)
    REFERENCES erp.servicos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contratos_vendas_geracoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  contrato_id bigint NOT NULL,
  competencia date NOT NULL,
  venda_id bigint,
  status text NOT NULL DEFAULT 'pendente',
  erro text,
  chave_idempotencia text NOT NULL,
  processado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT contratos_vendas_geracoes_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contratos_vendas_geracoes_status_chk CHECK (status IN ('pendente', 'processando', 'concluida', 'falha', 'ignorada')),
  CONSTRAINT contratos_vendas_geracoes_contrato_fk FOREIGN KEY (tenant_id, contrato_id)
    REFERENCES erp.contratos_vendas (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT contratos_vendas_geracoes_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.importacoes_bancarias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_financeira_id bigint NOT NULL,
  formato text NOT NULL DEFAULT 'ofx',
  nome_arquivo text NOT NULL,
  hash_arquivo text NOT NULL,
  periodo_inicio date,
  periodo_fim date,
  status text NOT NULL DEFAULT 'processando',
  total_linhas integer NOT NULL DEFAULT 0,
  total_importadas integer NOT NULL DEFAULT 0,
  total_ignoradas integer NOT NULL DEFAULT 0,
  erro text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  concluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT importacoes_bancarias_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT importacoes_bancarias_formato_chk CHECK (formato IN ('ofx', 'csv', 'api')),
  CONSTRAINT importacoes_bancarias_status_chk CHECK (status IN ('processando', 'concluida', 'parcial', 'falha')),
  CONSTRAINT importacoes_bancarias_totais_chk CHECK (total_linhas >= 0 AND total_importadas >= 0 AND total_ignoradas >= 0),
  CONSTRAINT importacoes_bancarias_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT importacoes_bancarias_conta_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.transacoes_bancarias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_financeira_id bigint NOT NULL,
  importacao_bancaria_id bigint,
  identificador_externo text,
  data_transacao date NOT NULL,
  data_compensacao date,
  tipo text NOT NULL,
  valor numeric(18,2) NOT NULL,
  descricao text NOT NULL,
  documento text,
  contraparte text,
  saldo_apos numeric(18,2),
  status text NOT NULL DEFAULT 'pendente',
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT transacoes_bancarias_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT transacoes_bancarias_tipo_chk CHECK (tipo IN ('credito', 'debito')),
  CONSTRAINT transacoes_bancarias_status_chk CHECK (status IN ('pendente', 'conciliada', 'ignorada')),
  CONSTRAINT transacoes_bancarias_valor_chk CHECK (valor > 0),
  CONSTRAINT transacoes_bancarias_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT transacoes_bancarias_conta_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT transacoes_bancarias_importacao_fk FOREIGN KEY (tenant_id, importacao_bancaria_id)
    REFERENCES erp.importacoes_bancarias (tenant_id, id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS erp.conciliacoes_bancarias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_financeira_id bigint NOT NULL,
  periodo_inicio date,
  periodo_fim date,
  status text NOT NULL DEFAULT 'aberta',
  saldo_extrato numeric(18,2),
  saldo_sistema numeric(18,2),
  conciliado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT conciliacoes_bancarias_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT conciliacoes_bancarias_status_chk CHECK (status IN ('aberta', 'concluida', 'cancelada')),
  CONSTRAINT conciliacoes_bancarias_periodo_chk CHECK (periodo_fim IS NULL OR periodo_inicio IS NULL OR periodo_fim >= periodo_inicio),
  CONSTRAINT conciliacoes_bancarias_conta_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.conciliacoes_bancarias_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conciliacao_id bigint NOT NULL,
  transacao_bancaria_id bigint NOT NULL,
  pagamento_id bigint,
  transferencia_financeira_id bigint,
  valor_conciliado numeric(18,2) NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT conciliacoes_bancarias_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT conciliacoes_bancarias_itens_transacao_key UNIQUE (tenant_id, transacao_bancaria_id),
  CONSTRAINT conciliacoes_bancarias_itens_origem_chk CHECK ((pagamento_id IS NOT NULL)::int + (transferencia_financeira_id IS NOT NULL)::int = 1),
  CONSTRAINT conciliacoes_bancarias_itens_valor_chk CHECK (valor_conciliado > 0),
  CONSTRAINT conciliacoes_bancarias_itens_conciliacao_fk FOREIGN KEY (tenant_id, conciliacao_id)
    REFERENCES erp.conciliacoes_bancarias (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT conciliacoes_bancarias_itens_transacao_fk FOREIGN KEY (tenant_id, transacao_bancaria_id)
    REFERENCES erp.transacoes_bancarias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT conciliacoes_bancarias_itens_pagamento_fk FOREIGN KEY (tenant_id, pagamento_id)
    REFERENCES erp.pagamentos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT conciliacoes_bancarias_itens_transferencia_fk FOREIGN KEY (tenant_id, transferencia_financeira_id)
    REFERENCES erp.transferencias_financeiras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.fechamentos_periodos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  modulo text NOT NULL,
  periodo_inicio date NOT NULL,
  periodo_fim date NOT NULL,
  motivo text,
  fechado_em timestamptz NOT NULL DEFAULT now(),
  reaberto_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  reaberto_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT fechamentos_periodos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT fechamentos_periodos_modulo_chk CHECK (modulo IN ('financeiro', 'estoque', 'vendas', 'compras', 'todos')),
  CONSTRAINT fechamentos_periodos_datas_chk CHECK (periodo_fim >= periodo_inicio)
);

CREATE TABLE IF NOT EXISTS erp.importacoes_dados (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo text NOT NULL,
  nome_arquivo text NOT NULL,
  hash_arquivo text NOT NULL,
  status text NOT NULL DEFAULT 'validando',
  total_linhas integer NOT NULL DEFAULT 0,
  total_validas integer NOT NULL DEFAULT 0,
  total_importadas integer NOT NULL DEFAULT 0,
  total_erros integer NOT NULL DEFAULT 0,
  mapeamento jsonb NOT NULL DEFAULT '{}'::jsonb,
  erro text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  concluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT importacoes_dados_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT importacoes_dados_tipo_chk CHECK (tipo IN ('clientes', 'fornecedores', 'produtos', 'servicos', 'contas_receber', 'contas_pagar')),
  CONSTRAINT importacoes_dados_status_chk CHECK (status IN ('validando', 'pronta', 'processando', 'concluida', 'parcial', 'falha', 'cancelada')),
  CONSTRAINT importacoes_dados_totais_chk CHECK (total_linhas >= 0 AND total_validas >= 0 AND total_importadas >= 0 AND total_erros >= 0),
  CONSTRAINT importacoes_dados_mapeamento_chk CHECK (jsonb_typeof(mapeamento) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.importacoes_dados_linhas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  importacao_id bigint NOT NULL,
  numero_linha integer NOT NULL,
  dados_originais jsonb NOT NULL,
  dados_normalizados jsonb,
  status text NOT NULL DEFAULT 'pendente',
  erros jsonb NOT NULL DEFAULT '[]'::jsonb,
  registro_id bigint,
  criado_em timestamptz NOT NULL DEFAULT now(),
  processado_em timestamptz,
  CONSTRAINT importacoes_dados_linhas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT importacoes_dados_linhas_numero_key UNIQUE (tenant_id, importacao_id, numero_linha),
  CONSTRAINT importacoes_dados_linhas_numero_chk CHECK (numero_linha > 0),
  CONSTRAINT importacoes_dados_linhas_status_chk CHECK (status IN ('pendente', 'valida', 'erro', 'importada', 'ignorada')),
  CONSTRAINT importacoes_dados_linhas_json_chk CHECK (jsonb_typeof(dados_originais) = 'object' AND (dados_normalizados IS NULL OR jsonb_typeof(dados_normalizados) = 'object') AND jsonb_typeof(erros) = 'array'),
  CONSTRAINT importacoes_dados_linhas_importacao_fk FOREIGN KEY (tenant_id, importacao_id)
    REFERENCES erp.importacoes_dados (tenant_id, id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS contratos_vendas_numero_unico_idx
  ON erp.contratos_vendas (tenant_id, numero) WHERE excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS contratos_vendas_idempotencia_idx
  ON erp.contratos_vendas (tenant_id, chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS contratos_vendas_geracoes_competencia_idx
  ON erp.contratos_vendas_geracoes (tenant_id, contrato_id, competencia);
CREATE UNIQUE INDEX IF NOT EXISTS contratos_vendas_geracoes_idempotencia_idx
  ON erp.contratos_vendas_geracoes (tenant_id, chave_idempotencia);
CREATE UNIQUE INDEX IF NOT EXISTS importacoes_bancarias_hash_idx
  ON erp.importacoes_bancarias (tenant_id, conta_financeira_id, hash_arquivo);
CREATE UNIQUE INDEX IF NOT EXISTS transacoes_bancarias_externa_idx
  ON erp.transacoes_bancarias (tenant_id, conta_financeira_id, identificador_externo)
  WHERE identificador_externo IS NOT NULL AND excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS fechamentos_periodos_ativo_idx
  ON erp.fechamentos_periodos (tenant_id, modulo, periodo_inicio, periodo_fim) WHERE reaberto_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS importacoes_dados_hash_idx
  ON erp.importacoes_dados (tenant_id, tipo, hash_arquivo) WHERE status <> 'cancelada';
CREATE INDEX IF NOT EXISTS transacoes_bancarias_pendentes_idx
  ON erp.transacoes_bancarias (tenant_id, conta_financeira_id, data_transacao DESC) WHERE status = 'pendente' AND excluido_em IS NULL;

CREATE OR REPLACE VIEW erp.vw_fluxo_caixa_diario
WITH (security_invoker = true)
AS
WITH movimentos AS (
  SELECT pagamentos.tenant_id, pagamentos.conta_financeira_id, pagamentos.data_pagamento AS data,
    CASE WHEN pagamentos.tipo = 'receber' THEN pagamentos.valor_liquido ELSE 0 END AS entradas,
    CASE WHEN pagamentos.tipo = 'pagar' THEN pagamentos.valor_liquido ELSE 0 END AS saidas
  FROM erp.pagamentos
  WHERE pagamentos.excluido_em IS NULL AND pagamentos.estornado_em IS NULL AND pagamentos.estorno_de_pagamento_id IS NULL
  UNION ALL
  SELECT transferencias.tenant_id, transferencias.conta_destino_id, transferencias.data_transferencia, transferencias.valor, 0
  FROM erp.transferencias_financeiras AS transferencias
  WHERE transferencias.excluido_em IS NULL AND transferencias.status = 'concluida'
  UNION ALL
  SELECT transferencias.tenant_id, transferencias.conta_origem_id, transferencias.data_transferencia, 0, transferencias.valor
  FROM erp.transferencias_financeiras AS transferencias
  WHERE transferencias.excluido_em IS NULL AND transferencias.status = 'concluida'
)
SELECT tenant_id, conta_financeira_id, data,
  sum(entradas)::numeric(18,2) AS entradas,
  sum(saidas)::numeric(18,2) AS saidas,
  (sum(entradas) - sum(saidas))::numeric(18,2) AS saldo_dia
FROM movimentos
GROUP BY tenant_id, conta_financeira_id, data;

CREATE OR REPLACE VIEW erp.vw_dre_gerencial
WITH (security_invoker = true)
AS
SELECT contas.tenant_id,
  date_trunc('month', COALESCE(contas.data_competencia, contas.data_emissao))::date AS competencia,
  categorias.id AS categoria_id,
  categorias.nome AS categoria,
  'receita'::text AS tipo,
  sum(contas.valor_total)::numeric(18,2) AS valor
FROM erp.contas_receber AS contas
LEFT JOIN erp.categorias AS categorias ON categorias.tenant_id = contas.tenant_id AND categorias.id = contas.categoria_id
WHERE contas.excluido_em IS NULL AND contas.status <> 'cancelado'
GROUP BY contas.tenant_id, date_trunc('month', COALESCE(contas.data_competencia, contas.data_emissao))::date, categorias.id, categorias.nome
UNION ALL
SELECT contas.tenant_id,
  date_trunc('month', COALESCE(contas.data_competencia, contas.data_emissao))::date,
  categorias.id, categorias.nome, 'despesa'::text,
  (sum(contas.valor_total) * -1)::numeric(18,2)
FROM erp.contas_pagar AS contas
LEFT JOIN erp.categorias AS categorias ON categorias.tenant_id = contas.tenant_id AND categorias.id = contas.categoria_id
WHERE contas.excluido_em IS NULL AND contas.status <> 'cancelado'
GROUP BY contas.tenant_id, date_trunc('month', COALESCE(contas.data_competencia, contas.data_emissao))::date, categorias.id, categorias.nome;

CREATE OR REPLACE VIEW erp.vw_aging_receber
WITH (security_invoker = true)
AS
SELECT parcelas.tenant_id, contas.cliente_id, entidades.nome AS cliente,
  parcelas.id AS parcela_id, contas.id AS conta_id, parcelas.data_vencimento,
  greatest(parcelas.valor - parcelas.valor_pago, 0)::numeric(18,2) AS saldo,
  greatest(CURRENT_DATE - parcelas.data_vencimento, 0) AS dias_atraso,
  CASE WHEN parcelas.data_vencimento >= CURRENT_DATE THEN 'a_vencer'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 30 THEN '1_30'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 60 THEN '31_60'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 90 THEN '61_90' ELSE 'mais_90' END AS faixa
FROM erp.contas_receber_parcelas AS parcelas
JOIN erp.contas_receber AS contas ON contas.tenant_id = parcelas.tenant_id AND contas.id = parcelas.conta_receber_id
JOIN erp.entidades ON entidades.tenant_id = contas.tenant_id AND entidades.id = contas.cliente_id
WHERE parcelas.excluido_em IS NULL AND parcelas.status IN ('aberto', 'parcial', 'vencido');

CREATE OR REPLACE VIEW erp.vw_aging_pagar
WITH (security_invoker = true)
AS
SELECT parcelas.tenant_id, contas.fornecedor_id, entidades.nome AS fornecedor,
  parcelas.id AS parcela_id, contas.id AS conta_id, parcelas.data_vencimento,
  greatest(parcelas.valor - parcelas.valor_pago, 0)::numeric(18,2) AS saldo,
  greatest(CURRENT_DATE - parcelas.data_vencimento, 0) AS dias_atraso,
  CASE WHEN parcelas.data_vencimento >= CURRENT_DATE THEN 'a_vencer'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 30 THEN '1_30'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 60 THEN '31_60'
    WHEN CURRENT_DATE - parcelas.data_vencimento <= 90 THEN '61_90' ELSE 'mais_90' END AS faixa
FROM erp.contas_pagar_parcelas AS parcelas
JOIN erp.contas_pagar AS contas ON contas.tenant_id = parcelas.tenant_id AND contas.id = parcelas.conta_pagar_id
JOIN erp.entidades ON entidades.tenant_id = contas.tenant_id AND entidades.id = contas.fornecedor_id
WHERE parcelas.excluido_em IS NULL AND parcelas.status IN ('aberto', 'parcial', 'vencido');

CREATE OR REPLACE VIEW erp.vw_giro_estoque
WITH (security_invoker = true)
AS
SELECT posicao.tenant_id, posicao.produto_id, posicao.produto,
  posicao.local_estoque_id, posicao.local_estoque, posicao.quantidade_fisica,
  COALESCE(sum(abs(movimentos.quantidade)) FILTER (WHERE movimentos.quantidade < 0 AND movimentos.ocorrido_em >= now() - interval '90 days'), 0) AS saidas_90_dias,
  CASE WHEN posicao.quantidade_fisica > 0 THEN
    COALESCE(sum(abs(movimentos.quantidade)) FILTER (WHERE movimentos.quantidade < 0 AND movimentos.ocorrido_em >= now() - interval '90 days'), 0) / posicao.quantidade_fisica
  ELSE 0 END AS giro_90_dias
FROM erp.vw_posicao_estoque AS posicao
LEFT JOIN erp.movimentacoes_estoque AS movimentos
  ON movimentos.tenant_id = posicao.tenant_id AND movimentos.produto_id = posicao.produto_id AND movimentos.local_estoque_id = posicao.local_estoque_id
GROUP BY posicao.tenant_id, posicao.produto_id, posicao.produto, posicao.local_estoque_id, posicao.local_estoque, posicao.quantidade_fisica;

DO $$
DECLARE
  tabela text;
BEGIN
  FOREACH tabela IN ARRAY ARRAY[
    'contratos_vendas', 'contratos_vendas_itens', 'contratos_vendas_geracoes',
    'importacoes_bancarias', 'transacoes_bancarias', 'conciliacoes_bancarias',
    'conciliacoes_bancarias_itens', 'fechamentos_periodos', 'importacoes_dados', 'importacoes_dados_linhas'
  ]
  LOOP
    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))', tabela || '_select_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', tabela || '_insert_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR UPDATE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member''])) WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', tabela || '_update_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR DELETE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'']))', tabela || '_delete_policy', tabela);
  END LOOP;

  FOREACH tabela IN ARRAY ARRAY['contratos_vendas', 'contratos_vendas_itens', 'transacoes_bancarias', 'conciliacoes_bancarias']
  LOOP
    EXECUTE format('CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()', tabela);
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON erp.contratos_vendas, erp.contratos_vendas_itens,
  erp.contratos_vendas_geracoes, erp.importacoes_bancarias, erp.transacoes_bancarias,
  erp.conciliacoes_bancarias, erp.conciliacoes_bancarias_itens, erp.fechamentos_periodos,
  erp.importacoes_dados, erp.importacoes_dados_linhas TO authenticated, service_role;
GRANT SELECT ON erp.vw_fluxo_caixa_diario, erp.vw_dre_gerencial, erp.vw_aging_receber,
  erp.vw_aging_pagar, erp.vw_giro_estoque TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO authenticated, service_role;

COMMIT;
