BEGIN;

-- Fase 1 — comercial: tabelas de preço, limite de crédito e bloqueio, transporte na venda e comissões.
-- Mesmo padrão das demais tabelas do ERP: empresa em toda chave, RLS por capacidade avaliada uma vez por
-- consulta (shared.erp_empresa_contexto), exclusão lógica, auditoria de usuário e versão.

-- Políticas no padrão da migração 20261008100000 (permissão calculada uma vez para a empresa da sessão).
CREATE OR REPLACE FUNCTION erp.criar_politicas_padrao(p_tabela text, p_leitura text, p_escrita text)
RETURNS void
LANGUAGE plpgsql
SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  ler text := format('CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.can_read_erp_module(shared.erp_empresa_contexto(), %L::text)) ELSE shared.can_read_erp_module(empresa_id, %L::text) END', p_leitura, p_leitura);
  gravar text := format('CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.has_erp_capability(shared.erp_empresa_contexto(), %L::text)) ELSE shared.has_erp_capability(empresa_id, %L::text) END', p_escrita, p_escrita);
BEGIN
  EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', p_tabela);
  EXECUTE format('CREATE POLICY %I ON erp.%I FOR SELECT USING (%s)', p_tabela || '_select_policy', p_tabela, ler);
  EXECUTE format('CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (%s)', p_tabela || '_insert_policy', p_tabela, gravar);
  EXECUTE format('CREATE POLICY %I ON erp.%I FOR UPDATE USING (%s) WITH CHECK (%s)', p_tabela || '_update_policy', p_tabela, gravar, gravar);
  EXECUTE format('CREATE POLICY %I ON erp.%I FOR DELETE USING (%s)', p_tabela || '_delete_policy', p_tabela, gravar);
  EXECUTE format('REVOKE ALL ON erp.%I FROM PUBLIC', p_tabela);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON erp.%I TO erp_runtime', p_tabela);
  EXECUTE format('CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()', p_tabela);
END
$function$;

-- 1.1 Tabelas de preço -----------------------------------------------------------------------------------
CREATE TABLE erp.tabelas_preco (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  nome text NOT NULL CHECK (btrim(nome) <> ''),
  descricao text,
  padrao boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  vigencia_inicio date,
  vigencia_fim date,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  UNIQUE (empresa_id, id),
  CHECK (vigencia_fim IS NULL OR vigencia_inicio IS NULL OR vigencia_fim >= vigencia_inicio)
);
COMMENT ON TABLE erp.tabelas_preco IS 'Listas de preço por cliente, canal ou campanha; uma pode ser a padrão da empresa.';
CREATE UNIQUE INDEX tabelas_preco_padrao_idx ON erp.tabelas_preco(empresa_id) WHERE padrao AND ativo AND excluido_em IS NULL;
CREATE UNIQUE INDEX tabelas_preco_nome_idx ON erp.tabelas_preco(empresa_id, lower(nome)) WHERE excluido_em IS NULL;

CREATE TABLE erp.tabelas_preco_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  tabela_preco_id bigint NOT NULL,
  produto_id bigint,
  servico_id bigint,
  preco numeric(18,4) NOT NULL CHECK (preco >= 0),
  preco_minimo numeric(18,4) CHECK (preco_minimo IS NULL OR preco_minimo >= 0),
  desconto_maximo_percentual numeric(9,4) CHECK (desconto_maximo_percentual IS NULL OR desconto_maximo_percentual BETWEEN 0 AND 100),
  quantidade_minima numeric(18,4) NOT NULL DEFAULT 1 CHECK (quantidade_minima > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, tabela_preco_id) REFERENCES erp.tabelas_preco(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY (empresa_id, produto_id) REFERENCES erp.produtos(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, servico_id) REFERENCES erp.servicos(empresa_id, id) ON DELETE RESTRICT,
  CHECK ((produto_id IS NOT NULL) <> (servico_id IS NOT NULL)),
  CHECK (preco_minimo IS NULL OR preco_minimo <= preco)
);
COMMENT ON TABLE erp.tabelas_preco_itens IS 'Preço por item e faixa de quantidade, com preço mínimo e desconto máximo opcionais.';
CREATE UNIQUE INDEX tabelas_preco_itens_faixa_idx ON erp.tabelas_preco_itens(empresa_id, tabela_preco_id, coalesce(produto_id, 0), coalesce(servico_id, 0), quantidade_minima) WHERE excluido_em IS NULL;
CREATE INDEX tabelas_preco_itens_produto_idx ON erp.tabelas_preco_itens(empresa_id, produto_id) WHERE produto_id IS NOT NULL AND excluido_em IS NULL;
CREATE INDEX tabelas_preco_itens_servico_idx ON erp.tabelas_preco_itens(empresa_id, servico_id) WHERE servico_id IS NOT NULL AND excluido_em IS NULL;

ALTER TABLE erp.entidades ADD COLUMN tabela_preco_id bigint;
ALTER TABLE erp.entidades ADD CONSTRAINT entidades_tabela_preco_fk FOREIGN KEY (empresa_id, tabela_preco_id) REFERENCES erp.tabelas_preco(empresa_id, id) ON DELETE RESTRICT;
ALTER TABLE erp.vendas ADD COLUMN tabela_preco_id bigint;
ALTER TABLE erp.vendas ADD CONSTRAINT vendas_tabela_preco_fk FOREIGN KEY (empresa_id, tabela_preco_id) REFERENCES erp.tabelas_preco(empresa_id, id) ON DELETE RESTRICT;
ALTER TABLE erp.vendas_itens ADD COLUMN preco_tabela numeric(18,4) CHECK (preco_tabela IS NULL OR preco_tabela >= 0);
COMMENT ON COLUMN erp.vendas_itens.preco_tabela IS 'Preço sugerido pela tabela no momento da venda (referência para desconto e comissão).';

-- 1.3 Limite de crédito e bloqueio comercial -------------------------------------------------------------
ALTER TABLE erp.entidades ADD COLUMN limite_credito numeric(18,2) CHECK (limite_credito IS NULL OR limite_credito >= 0);
ALTER TABLE erp.entidades ADD COLUMN bloqueio_comercial boolean NOT NULL DEFAULT false;
ALTER TABLE erp.entidades ADD COLUMN bloqueio_motivo text;
ALTER TABLE erp.entidades ADD CONSTRAINT entidades_bloqueio_motivo_chk CHECK (NOT bloqueio_comercial OR nullif(btrim(bloqueio_motivo), '') IS NOT NULL);
ALTER TABLE erp.vendas ADD COLUMN credito_liberado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL;
ALTER TABLE erp.vendas ADD COLUMN credito_liberado_em timestamptz;
ALTER TABLE erp.vendas ADD COLUMN credito_liberado_motivo text;
ALTER TABLE erp.vendas ADD CONSTRAINT vendas_credito_liberado_chk CHECK ((credito_liberado_em IS NULL) = (credito_liberado_por IS NULL));

-- 1.6 Transporte na venda (dados exigidos pela NF-e) -----------------------------------------------------
ALTER TABLE erp.vendas ADD COLUMN transportadora_id bigint;
ALTER TABLE erp.vendas ADD CONSTRAINT vendas_transportadora_fk FOREIGN KEY (empresa_id, transportadora_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT;
ALTER TABLE erp.vendas ADD COLUMN modalidade_frete text CHECK (modalidade_frete IS NULL OR modalidade_frete IN ('emitente','destinatario','terceiros','proprio_remetente','proprio_destinatario','sem_frete'));
ALTER TABLE erp.vendas ADD COLUMN volumes integer CHECK (volumes IS NULL OR volumes >= 0);
ALTER TABLE erp.vendas ADD COLUMN especie_volumes text;
ALTER TABLE erp.vendas ADD COLUMN peso_bruto numeric(18,3) CHECK (peso_bruto IS NULL OR peso_bruto >= 0);
ALTER TABLE erp.vendas ADD COLUMN peso_liquido numeric(18,3) CHECK (peso_liquido IS NULL OR peso_liquido >= 0);
COMMENT ON COLUMN erp.vendas.modalidade_frete IS 'modFrete da NF-e: emitente (0/CIF), destinatario (1/FOB), terceiros (2), proprio_remetente (3), proprio_destinatario (4), sem_frete (9).';
CREATE INDEX vendas_transportadora_idx ON erp.vendas(empresa_id, transportadora_id) WHERE transportadora_id IS NOT NULL;

-- 1.2 Comissões ------------------------------------------------------------------------------------------
CREATE TABLE erp.comissoes_regras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  nome text NOT NULL CHECK (btrim(nome) <> ''),
  vendedor_id bigint,
  produto_id bigint,
  servico_id bigint,
  categoria_id bigint,
  percentual numeric(9,4) NOT NULL CHECK (percentual > 0 AND percentual <= 100),
  base text NOT NULL DEFAULT 'faturamento' CHECK (base IN ('faturamento','recebimento')),
  ativo boolean NOT NULL DEFAULT true,
  vigencia_inicio date,
  vigencia_fim date,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, vendedor_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, produto_id) REFERENCES erp.produtos(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, servico_id) REFERENCES erp.servicos(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, categoria_id) REFERENCES erp.categorias(empresa_id, id) ON DELETE RESTRICT,
  CHECK (num_nonnulls(produto_id, servico_id, categoria_id) <= 1),
  CHECK (vigencia_fim IS NULL OR vigencia_inicio IS NULL OR vigencia_fim >= vigencia_inicio)
);
COMMENT ON TABLE erp.comissoes_regras IS 'Percentual de comissão; a regra mais específica (vendedor, item, categoria) vale para cada item vendido.';
CREATE INDEX comissoes_regras_vendedor_idx ON erp.comissoes_regras(empresa_id, vendedor_id) WHERE excluido_em IS NULL AND ativo;

CREATE TABLE erp.comissoes_lancamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  venda_id bigint NOT NULL,
  venda_item_id bigint NOT NULL,
  vendedor_id bigint NOT NULL,
  regra_id bigint,
  base text NOT NULL CHECK (base IN ('faturamento','recebimento')),
  valor_base numeric(18,2) NOT NULL CHECK (valor_base >= 0),
  percentual numeric(9,4) NOT NULL CHECK (percentual > 0 AND percentual <= 100),
  valor numeric(18,2) NOT NULL CHECK (valor >= 0),
  valor_pago numeric(18,2) NOT NULL DEFAULT 0 CHECK (valor_pago >= 0 AND valor_pago <= valor),
  competencia date NOT NULL,
  status text NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa','cancelada')),
  cancelado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, venda_id) REFERENCES erp.vendas(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, venda_item_id) REFERENCES erp.vendas_itens(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, vendedor_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, regra_id) REFERENCES erp.comissoes_regras(empresa_id, id) ON DELETE RESTRICT,
  CHECK ((status = 'cancelada') = (cancelado_em IS NOT NULL))
);
COMMENT ON TABLE erp.comissoes_lancamentos IS 'Comissão de cada item de venda confirmada. Base faturamento libera tudo na confirmação; base recebimento libera na proporção recebida da venda.';
CREATE UNIQUE INDEX comissoes_lancamentos_item_idx ON erp.comissoes_lancamentos(empresa_id, venda_item_id) WHERE status = 'ativa';
CREATE INDEX comissoes_lancamentos_vendedor_idx ON erp.comissoes_lancamentos(empresa_id, vendedor_id, competencia);
CREATE INDEX comissoes_lancamentos_venda_idx ON erp.comissoes_lancamentos(empresa_id, venda_id);

CREATE TABLE erp.comissoes_pagamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  vendedor_id bigint NOT NULL,
  conta_pagar_id bigint NOT NULL,
  valor numeric(18,2) NOT NULL CHECK (valor > 0),
  competencia_fim date NOT NULL,
  chave_idempotencia text NOT NULL CHECK (btrim(chave_idempotencia) <> ''),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, chave_idempotencia),
  FOREIGN KEY (empresa_id, vendedor_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (empresa_id, conta_pagar_id) REFERENCES erp.contas_pagar(empresa_id, id) ON DELETE RESTRICT
);
CREATE TABLE erp.comissoes_pagamentos_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  pagamento_id bigint NOT NULL,
  lancamento_id bigint NOT NULL,
  valor numeric(18,2) NOT NULL CHECK (valor > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, pagamento_id) REFERENCES erp.comissoes_pagamentos(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY (empresa_id, lancamento_id) REFERENCES erp.comissoes_lancamentos(empresa_id, id) ON DELETE RESTRICT
);
CREATE INDEX comissoes_pagamentos_itens_lancamento_idx ON erp.comissoes_pagamentos_itens(empresa_id, lancamento_id);

SELECT erp.criar_politicas_padrao('tabelas_preco', 'referencias', 'erp.cadastros.gerenciar');
SELECT erp.criar_politicas_padrao('tabelas_preco_itens', 'referencias', 'erp.cadastros.gerenciar');
SELECT erp.criar_politicas_padrao('comissoes_regras', 'vendas', 'erp.vendas.gerenciar');
SELECT erp.criar_politicas_padrao('comissoes_lancamentos', 'vendas', 'erp.vendas.gerenciar');
SELECT erp.criar_politicas_padrao('comissoes_pagamentos', 'financeiro', 'erp.financeiro.gerenciar');
SELECT erp.criar_politicas_padrao('comissoes_pagamentos_itens', 'financeiro', 'erp.financeiro.gerenciar');
-- Pagar comissões atualiza o valor pago dos lançamentos: o financeiro também grava nessa tabela.
CREATE POLICY comissoes_lancamentos_pagamento_policy ON erp.comissoes_lancamentos FOR UPDATE
  USING (CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.has_erp_capability(shared.erp_empresa_contexto(), 'erp.financeiro.gerenciar'::text)) ELSE shared.has_erp_capability(empresa_id, 'erp.financeiro.gerenciar'::text) END)
  WITH CHECK (CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.has_erp_capability(shared.erp_empresa_contexto(), 'erp.financeiro.gerenciar'::text)) ELSE shared.has_erp_capability(empresa_id, 'erp.financeiro.gerenciar'::text) END);
GRANT USAGE ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime;

COMMIT;
