BEGIN;

-- Fase 2E: orçamento financeiro anual (por categoria e mês, consolidado pelos grupos da DRE) e metas de venda.

CREATE TABLE erp.orcamentos_financeiros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  ano integer NOT NULL CHECK (ano BETWEEN 2000 AND 2100),
  nome text NOT NULL CHECK (btrim(nome) <> ''),
  status text NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'aprovado')),
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  CONSTRAINT orcamentos_financeiros_empresa_id_id_key UNIQUE (empresa_id, id)
);
CREATE UNIQUE INDEX orcamentos_financeiros_nome_idx ON erp.orcamentos_financeiros (empresa_id, ano, lower(btrim(nome))) WHERE excluido_em IS NULL;
SELECT erp.criar_politicas_padrao('orcamentos_financeiros', 'financeiro', 'erp.financeiro.gerenciar');

-- Valor sempre positivo; o sinal vem do tipo da categoria (receita soma, despesa subtrai).
CREATE TABLE erp.orcamentos_financeiros_linhas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  orcamento_id bigint NOT NULL,
  categoria_id bigint NOT NULL,
  centro_custo_id bigint,
  mes smallint NOT NULL CHECK (mes BETWEEN 1 AND 12),
  valor numeric(18,2) NOT NULL CHECK (valor >= 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orcamentos_linhas_orcamento_fk FOREIGN KEY (empresa_id, orcamento_id) REFERENCES erp.orcamentos_financeiros(empresa_id, id) ON DELETE CASCADE,
  CONSTRAINT orcamentos_linhas_categoria_fk FOREIGN KEY (empresa_id, categoria_id) REFERENCES erp.categorias(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT orcamentos_linhas_centro_fk FOREIGN KEY (empresa_id, centro_custo_id) REFERENCES erp.centros_custo(empresa_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX orcamentos_linhas_unico ON erp.orcamentos_financeiros_linhas (orcamento_id, categoria_id, coalesce(centro_custo_id, 0), mes);
SELECT erp.criar_politicas_padrao('orcamentos_financeiros_linhas', 'financeiro', 'erp.financeiro.gerenciar');

-- Meta de venda do mês, geral (sem vendedor) ou por vendedor.
CREATE TABLE erp.metas_vendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  vendedor_id bigint,
  mes date NOT NULL CHECK (extract(day FROM mes) = 1),
  valor numeric(18,2) NOT NULL CHECK (valor > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  CONSTRAINT metas_vendas_vendedor_fk FOREIGN KEY (empresa_id, vendedor_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX metas_vendas_unico ON erp.metas_vendas (empresa_id, coalesce(vendedor_id, 0), mes);
SELECT erp.criar_politicas_padrao('metas_vendas', 'vendas', 'erp.vendas.gerenciar');
-- Vendedor restrito às próprias vendas (Fase 1.7) vê só a própria meta.
CREATE POLICY metas_vendas_escopo_vendedor ON erp.metas_vendas AS RESTRICTIVE FOR SELECT
  USING (empresa_id IS DISTINCT FROM shared.erp_empresa_contexto()
    OR (SELECT shared.erp_vendedor_restrito()) IS NULL
    OR vendedor_id = (SELECT shared.erp_vendedor_restrito()));

GRANT USAGE ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime;

COMMIT;
