BEGIN;

-- Fase 2A: DRE estruturada, categorias financeiras × de cadastro e receita prevista.
--
-- 1. erp.dre_grupos: os 9 grupos fixos da DRE de cada empresa (nome e ordem editáveis; não se cria nem apaga).
-- 2. erp.categorias passa a ser só financeira (receita/despesa), com grupo da DRE, opção "Não entra na DRE"
--    e hierarquia de 2 níveis (a subcategoria herda o grupo da categoria-pai).
-- 3. erp.categorias_cadastro: agrupamentos de produtos, serviços, clientes e fornecedores. Os ids são
--    preservados (a mesma categoria mantém o número); produtos, serviços e entidades apontam para ela com o
--    tipo na chave, então o banco recusa, por exemplo, produto em categoria de cliente.
-- 4. contas_receber.tipo_lancamento (previsão/efetivo), simétrico a contas a pagar.

-- 1. Grupos da DRE -------------------------------------------------------------------------------------------
CREATE TABLE erp.dre_grupos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  codigo smallint NOT NULL CHECK (codigo BETWEEN 1 AND 9),
  nome text NOT NULL CHECK (btrim(nome) <> '' AND length(nome) <= 80),
  ordem smallint NOT NULL CHECK (ordem BETWEEN 1 AND 99),
  natureza text NOT NULL CHECK (natureza IN ('receita', 'deducao', 'custo', 'despesa', 'financeiro', 'nao_operacional', 'imposto_lucro')),
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dre_grupos_codigo_unico UNIQUE (empresa_id, codigo),
  CONSTRAINT dre_grupos_empresa_id_id_key UNIQUE (empresa_id, id)
);
COMMENT ON TABLE erp.dre_grupos IS 'Grupos fixos da DRE (1 receita bruta … 9 impostos sobre o lucro). Nome e ordem editáveis; código e natureza fixos.';

CREATE OR REPLACE FUNCTION erp.criar_grupos_dre(p_empresa_id bigint)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
  INSERT INTO erp.dre_grupos (empresa_id, codigo, nome, ordem, natureza)
  SELECT p_empresa_id, g.codigo, g.nome, g.codigo, g.natureza FROM (VALUES
    (1::smallint, 'Receita bruta', 'receita'),
    (2::smallint, 'Deduções da receita', 'deducao'),
    (3::smallint, 'Custos (CMV/CSP)', 'custo'),
    (4::smallint, 'Despesas com pessoal', 'despesa'),
    (5::smallint, 'Despesas administrativas', 'despesa'),
    (6::smallint, 'Despesas comerciais', 'despesa'),
    (7::smallint, 'Resultado financeiro', 'financeiro'),
    (8::smallint, 'Resultado não operacional', 'nao_operacional'),
    (9::smallint, 'Impostos sobre o lucro', 'imposto_lucro')
  ) AS g(codigo, nome, natureza)
  ON CONFLICT (empresa_id, codigo) DO NOTHING
$$;
REVOKE ALL ON FUNCTION erp.criar_grupos_dre(bigint) FROM PUBLIC;

SELECT erp.criar_grupos_dre(id) FROM shared.empresas;

CREATE OR REPLACE FUNCTION erp.criar_grupos_dre_empresa()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
BEGIN PERFORM erp.criar_grupos_dre(NEW.id); RETURN NULL; END $$;
REVOKE ALL ON FUNCTION erp.criar_grupos_dre_empresa() FROM PUBLIC;
CREATE TRIGGER criar_grupos_dre AFTER INSERT ON shared.empresas FOR EACH ROW EXECUTE FUNCTION erp.criar_grupos_dre_empresa();

-- Só nome e ordem mudam.
CREATE OR REPLACE FUNCTION erp.proteger_grupo_dre()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog' AS $$
BEGIN
  IF NEW.empresa_id <> OLD.empresa_id OR NEW.codigo <> OLD.codigo OR NEW.natureza <> OLD.natureza OR NEW.id <> OLD.id THEN
    RAISE EXCEPTION 'Os grupos da DRE são fixos: só nome e ordem podem mudar' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_grupo_dre BEFORE UPDATE ON erp.dre_grupos FOR EACH ROW EXECUTE FUNCTION erp.proteger_grupo_dre();
CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.dre_grupos FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em();

ALTER TABLE erp.dre_grupos ENABLE ROW LEVEL SECURITY;
CREATE POLICY dre_grupos_select_policy ON erp.dre_grupos FOR SELECT
  USING (CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.can_read_erp_module(shared.erp_empresa_contexto(), 'referencias'::text)) ELSE shared.can_read_erp_module(empresa_id, 'referencias'::text) END);
CREATE POLICY dre_grupos_update_policy ON erp.dre_grupos FOR UPDATE
  USING (CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.has_erp_capability(shared.erp_empresa_contexto(), 'erp.financeiro.gerenciar'::text)) ELSE shared.has_erp_capability(empresa_id, 'erp.financeiro.gerenciar'::text) END)
  WITH CHECK (CASE WHEN (empresa_id = shared.erp_empresa_contexto()) THEN (SELECT shared.has_erp_capability(shared.erp_empresa_contexto(), 'erp.financeiro.gerenciar'::text)) ELSE shared.has_erp_capability(empresa_id, 'erp.financeiro.gerenciar'::text) END);
REVOKE ALL ON erp.dre_grupos FROM PUBLIC;
GRANT SELECT, UPDATE ON erp.dre_grupos TO erp_runtime;

-- 2. Categorias de cadastro ----------------------------------------------------------------------------------
CREATE TABLE erp.categorias_cadastro (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  tipo text NOT NULL CHECK (tipo IN ('produto', 'servico', 'cliente', 'fornecedor')),
  nome text NOT NULL CHECK (btrim(nome) <> ''),
  codigo text,
  descricao text,
  categoria_pai_id bigint,
  ativo boolean NOT NULL DEFAULT true,
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  CONSTRAINT categorias_cadastro_empresa_id_id_key UNIQUE (empresa_id, id),
  CONSTRAINT categorias_cadastro_tipo_key UNIQUE (empresa_id, id, tipo),
  -- Subcategoria do mesmo tipo.
  CONSTRAINT categorias_cadastro_pai_fk FOREIGN KEY (empresa_id, categoria_pai_id, tipo)
    REFERENCES erp.categorias_cadastro(empresa_id, id, tipo) ON DELETE RESTRICT
);
CREATE INDEX categorias_cadastro_nome_idx ON erp.categorias_cadastro (empresa_id, tipo, lower(btrim(nome)))
  WHERE excluido_em IS NULL AND categoria_pai_id IS NULL;
CREATE INDEX categorias_cadastro_tipo_idx ON erp.categorias_cadastro (empresa_id, tipo) WHERE excluido_em IS NULL;
COMMENT ON TABLE erp.categorias_cadastro IS 'Agrupamentos de produtos, serviços, clientes e fornecedores. Não classificam dinheiro (isso é erp.categorias).';
SELECT erp.criar_politicas_padrao('categorias_cadastro', 'referencias', 'erp.cadastros.gerenciar');

-- Hierarquia de no máximo 2 níveis (vale para as duas tabelas de categorias).
CREATE OR REPLACE FUNCTION erp.validar_nivel_categoria()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
DECLARE pai_do_pai bigint;
BEGIN
  IF NEW.categoria_pai_id IS NULL THEN RETURN NEW; END IF;
  IF NEW.categoria_pai_id = NEW.id THEN RAISE EXCEPTION 'Categoria não pode ser pai dela mesma' USING ERRCODE = '23514'; END IF;
  EXECUTE format('SELECT categoria_pai_id FROM %I.%I WHERE empresa_id = $1 AND id = $2', TG_TABLE_SCHEMA, TG_TABLE_NAME)
    INTO pai_do_pai USING NEW.empresa_id, NEW.categoria_pai_id;
  IF pai_do_pai IS NOT NULL THEN RAISE EXCEPTION 'Categorias têm no máximo 2 níveis' USING ERRCODE = '23514'; END IF;
  IF TG_OP = 'UPDATE' THEN
    EXECUTE format('SELECT categoria_pai_id FROM %I.%I WHERE empresa_id = $1 AND categoria_pai_id = $2 AND excluido_em IS NULL LIMIT 1', TG_TABLE_SCHEMA, TG_TABLE_NAME)
      INTO pai_do_pai USING NEW.empresa_id, NEW.id;
    IF pai_do_pai IS NOT NULL THEN RAISE EXCEPTION 'Categoria com subcategorias não pode virar subcategoria' USING ERRCODE = '23514'; END IF;
  END IF;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION erp.validar_nivel_categoria() FROM PUBLIC;
CREATE TRIGGER validar_nivel BEFORE INSERT OR UPDATE OF categoria_pai_id ON erp.categorias_cadastro
  FOR EACH ROW EXECUTE FUNCTION erp.validar_nivel_categoria();

ALTER TABLE erp.cadastros_eventos DROP CONSTRAINT cadastros_eventos_tipo_chk;
ALTER TABLE erp.cadastros_eventos ADD CONSTRAINT cadastros_eventos_tipo_chk
  CHECK (entidade_tipo IN ('entidade', 'categoria', 'categoria_cadastro', 'produto', 'servico', 'conta_financeira'));

-- 3. Migração dos dados: de-para (categoria antiga, tipo de cadastro) → categoria de cadastro --------------------
ALTER TABLE erp.categorias DISABLE TRIGGER classificacao_usada;

CREATE TEMP TABLE de_para_categorias (
  empresa_id bigint NOT NULL, antiga_id bigint NOT NULL, tipo text NOT NULL, nova_id bigint, prioridade int NOT NULL,
  PRIMARY KEY (empresa_id, antiga_id, tipo)
) ON COMMIT DROP;

-- Categorias de tipo de cadastro e todas as usadas por produtos/serviços (inclusive "geral").
INSERT INTO de_para_categorias (empresa_id, antiga_id, tipo, prioridade)
SELECT empresa_id, id, tipo, 0 FROM erp.categorias WHERE tipo IN ('produto', 'servico', 'cliente', 'fornecedor')
ON CONFLICT DO NOTHING;
INSERT INTO de_para_categorias (empresa_id, antiga_id, tipo, prioridade)
SELECT DISTINCT p.empresa_id, p.categoria_id, 'produto', 1 FROM erp.produtos p WHERE p.categoria_id IS NOT NULL
ON CONFLICT DO NOTHING;
INSERT INTO de_para_categorias (empresa_id, antiga_id, tipo, prioridade)
SELECT DISTINCT s.empresa_id, s.categoria_id, 'servico', 2 FROM erp.servicos s WHERE s.categoria_id IS NOT NULL
ON CONFLICT DO NOTHING;
-- Regras de comissão por categoria usam a categoria do item vendido.
INSERT INTO de_para_categorias (empresa_id, antiga_id, tipo, prioridade)
SELECT DISTINCT r.empresa_id, r.categoria_id, 'produto', 3 FROM erp.comissoes_regras r
WHERE r.categoria_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM de_para_categorias d WHERE d.empresa_id = r.empresa_id AND d.antiga_id = r.categoria_id)
ON CONFLICT DO NOTHING;

-- O primeiro par de cada categoria mantém o id; os demais (mesma categoria usada como produto e serviço) ganham id novo.
UPDATE de_para_categorias d SET nova_id = d.antiga_id
FROM (SELECT DISTINCT ON (empresa_id, antiga_id) empresa_id, antiga_id, tipo FROM de_para_categorias ORDER BY empresa_id, antiga_id, prioridade, tipo) primeiro
WHERE d.empresa_id = primeiro.empresa_id AND d.antiga_id = primeiro.antiga_id AND d.tipo = primeiro.tipo;
SELECT setval(pg_get_serial_sequence('erp.categorias_cadastro', 'id'), GREATEST((SELECT coalesce(max(id), 0) FROM erp.categorias), 1), true);
UPDATE de_para_categorias SET nova_id = nextval(pg_get_serial_sequence('erp.categorias_cadastro', 'id')) WHERE nova_id IS NULL;

INSERT INTO erp.categorias_cadastro (id, empresa_id, tipo, nome, codigo, descricao, ativo, metadata, criado_em, excluido_em, criado_por, atualizado_por)
SELECT d.nova_id, c.empresa_id, d.tipo, c.nome, CASE WHEN d.nova_id = d.antiga_id THEN c.codigo END, c.metadata ->> 'descricao', c.ativo,
  jsonb_build_object('categoria_financeira_original', c.id), c.criado_em, c.excluido_em, c.criado_por, c.atualizado_por
FROM de_para_categorias d JOIN erp.categorias c ON c.empresa_id = d.empresa_id AND c.id = d.antiga_id;
-- Hierarquia antiga só é copiada quando a pai também virou categoria de cadastro do mesmo tipo.
UPDATE erp.categorias_cadastro f SET categoria_pai_id = dp.nova_id
FROM de_para_categorias d JOIN erp.categorias c ON c.empresa_id = d.empresa_id AND c.id = d.antiga_id
JOIN de_para_categorias dp ON dp.empresa_id = c.empresa_id AND dp.antiga_id = c.categoria_pai_id AND dp.tipo = d.tipo
WHERE f.empresa_id = d.empresa_id AND f.id = d.nova_id
  AND NOT EXISTS (SELECT 1 FROM erp.categorias avo WHERE avo.empresa_id = c.empresa_id AND avo.id = c.categoria_pai_id AND avo.categoria_pai_id IS NOT NULL);

-- Produtos e serviços passam a apontar para a categoria de cadastro (com o tipo na chave).
ALTER TABLE erp.produtos DROP CONSTRAINT produtos_categoria_fk;
ALTER TABLE erp.produtos ADD COLUMN categoria_tipo text NOT NULL DEFAULT 'produto' CHECK (categoria_tipo = 'produto');
UPDATE erp.produtos p SET categoria_id = d.nova_id FROM de_para_categorias d
WHERE d.empresa_id = p.empresa_id AND d.antiga_id = p.categoria_id AND d.tipo = 'produto' AND p.categoria_id IS DISTINCT FROM d.nova_id;
ALTER TABLE erp.produtos ADD CONSTRAINT produtos_categoria_fk FOREIGN KEY (empresa_id, categoria_id, categoria_tipo)
  REFERENCES erp.categorias_cadastro(empresa_id, id, tipo) ON DELETE RESTRICT;

ALTER TABLE erp.servicos DROP CONSTRAINT servicos_categoria_fk;
ALTER TABLE erp.servicos ADD COLUMN categoria_tipo text NOT NULL DEFAULT 'servico' CHECK (categoria_tipo = 'servico');
UPDATE erp.servicos s SET categoria_id = d.nova_id FROM de_para_categorias d
WHERE d.empresa_id = s.empresa_id AND d.antiga_id = s.categoria_id AND d.tipo = 'servico' AND s.categoria_id IS DISTINCT FROM d.nova_id;
ALTER TABLE erp.servicos ADD CONSTRAINT servicos_categoria_fk FOREIGN KEY (empresa_id, categoria_id, categoria_tipo)
  REFERENCES erp.categorias_cadastro(empresa_id, id, tipo) ON DELETE RESTRICT;

ALTER TABLE erp.comissoes_regras DROP CONSTRAINT comissoes_regras_empresa_id_categoria_id_fkey;
UPDATE erp.comissoes_regras r SET categoria_id = d.nova_id
FROM (SELECT DISTINCT ON (empresa_id, antiga_id) empresa_id, antiga_id, nova_id FROM de_para_categorias ORDER BY empresa_id, antiga_id, prioridade) d
WHERE d.empresa_id = r.empresa_id AND d.antiga_id = r.categoria_id AND r.categoria_id IS DISTINCT FROM d.nova_id;
ALTER TABLE erp.comissoes_regras ADD CONSTRAINT comissoes_regras_categoria_fk FOREIGN KEY (empresa_id, categoria_id)
  REFERENCES erp.categorias_cadastro(empresa_id, id) ON DELETE RESTRICT;

-- Clientes e fornecedores: a categoria era guardada pelo nome em metadata->>'categoria'.
ALTER TABLE erp.entidades ADD COLUMN categoria_id bigint, ADD COLUMN categoria_tipo text CHECK (categoria_tipo IN ('cliente', 'fornecedor'));
ALTER TABLE erp.entidades ADD CONSTRAINT entidades_categoria_tipo_chk CHECK ((categoria_id IS NULL) = (categoria_tipo IS NULL));
-- Nomes usados nos cadastros e ainda sem categoria do tipo do papel principal viram categoria de cadastro.
INSERT INTO erp.categorias_cadastro (empresa_id, tipo, nome, metadata)
SELECT DISTINCT e.empresa_id, CASE WHEN e.eh_cliente THEN 'cliente' ELSE 'fornecedor' END, btrim(e.metadata ->> 'categoria'), '{"criada_na_migracao": true}'::jsonb
FROM erp.entidades e
WHERE (e.eh_cliente OR e.eh_fornecedor) AND coalesce(btrim(e.metadata ->> 'categoria'), '') <> ''
  AND NOT EXISTS (SELECT 1 FROM erp.categorias_cadastro c WHERE c.empresa_id = e.empresa_id
    AND c.tipo = CASE WHEN e.eh_cliente THEN 'cliente' ELSE 'fornecedor' END
    AND lower(btrim(c.nome)) = lower(btrim(e.metadata ->> 'categoria')) AND c.excluido_em IS NULL);
UPDATE erp.entidades e SET categoria_tipo = c.tipo, categoria_id = c.id
FROM erp.categorias_cadastro c
WHERE (e.eh_cliente OR e.eh_fornecedor) AND coalesce(btrim(e.metadata ->> 'categoria'), '') <> ''
  AND c.empresa_id = e.empresa_id AND c.excluido_em IS NULL AND c.categoria_pai_id IS NULL
  AND c.tipo = CASE WHEN e.eh_cliente THEN 'cliente' ELSE 'fornecedor' END
  AND lower(btrim(c.nome)) = lower(btrim(e.metadata ->> 'categoria'));
ALTER TABLE erp.entidades ADD CONSTRAINT entidades_categoria_fk FOREIGN KEY (empresa_id, categoria_id, categoria_tipo)
  REFERENCES erp.categorias_cadastro(empresa_id, id, tipo) ON DELETE RESTRICT;
CREATE INDEX entidades_categoria_idx ON erp.entidades (empresa_id, categoria_id) WHERE categoria_id IS NOT NULL;
CREATE INDEX produtos_categoria_cadastro_idx ON erp.produtos (empresa_id, categoria_id) WHERE categoria_id IS NOT NULL;
CREATE INDEX servicos_categoria_cadastro_idx ON erp.servicos (empresa_id, categoria_id) WHERE categoria_id IS NOT NULL;

-- 4. Categorias financeiras: só receita e despesa ------------------------------------------------------------------
-- Uso financeiro de cada categoria (lado receita × despesa).
CREATE TEMP TABLE uso_financeiro ON COMMIT DROP AS
SELECT empresa_id, categoria_id, sum(receita)::int AS receita, sum(despesa)::int AS despesa FROM (
  SELECT empresa_id, categoria_id, count(*) AS receita, 0 AS despesa FROM erp.contas_receber WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, count(*), 0 FROM erp.vendas WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, count(*), 0 FROM erp.contratos_vendas WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, count(*), 0 FROM erp.contratos_vendas_versoes WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, 0, count(*) FROM erp.contas_pagar WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, 0, count(*) FROM erp.compras WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_id, count(*) FILTER (WHERE conta_receber_id IS NOT NULL), count(*) FILTER (WHERE conta_pagar_id IS NOT NULL)
    FROM erp.rateios_financeiros WHERE categoria_id IS NOT NULL GROUP BY 1, 2
  UNION ALL SELECT empresa_id, categoria_ajuste_id, 1, 0 FROM erp.renegociacoes WHERE categoria_ajuste_id IS NOT NULL GROUP BY 1, 2
) u GROUP BY 1, 2;

-- Categorias "geral" ou de cadastro com uso financeiro viram receita ou despesa pelo lado em que são usadas.
UPDATE erp.categorias c SET tipo = CASE WHEN u.despesa > u.receita THEN 'despesa' ELSE 'receita' END,
  metadata = c.metadata || jsonb_build_object('tipo_original', c.tipo)
FROM uso_financeiro u
WHERE u.empresa_id = c.empresa_id AND u.categoria_id = c.id AND c.tipo NOT IN ('receita', 'despesa');
-- As demais categorias de cadastro ou "geral" sem uso financeiro saem da tabela financeira (sem apagar).
UPDATE erp.categorias c SET ativo = false, excluido_em = coalesce(c.excluido_em, now()),
  metadata = c.metadata || jsonb_build_object('tipo_original', c.tipo, 'migrada_para_cadastro',
    EXISTS (SELECT 1 FROM de_para_categorias d WHERE d.empresa_id = c.empresa_id AND d.antiga_id = c.id))
WHERE c.tipo NOT IN ('receita', 'despesa');
-- Subcategoria ativa de uma categoria que saiu da tabela vira raiz.
UPDATE erp.categorias c SET categoria_pai_id = NULL
FROM erp.categorias p WHERE p.empresa_id = c.empresa_id AND p.id = c.categoria_pai_id AND p.tipo NOT IN ('receita', 'despesa');
-- Hierarquia antiga com mais de 2 níveis: o 3º nível sobe para o 2º.
UPDATE erp.categorias c SET categoria_pai_id = p.categoria_pai_id
FROM erp.categorias p WHERE p.empresa_id = c.empresa_id AND p.id = c.categoria_pai_id AND p.categoria_pai_id IS NOT NULL;

ALTER TABLE erp.categorias DROP CONSTRAINT categorias_tipo_chk;
ALTER TABLE erp.categorias ADD CONSTRAINT categorias_tipo_chk CHECK (tipo IN ('receita', 'despesa') OR excluido_em IS NOT NULL);
ALTER TABLE erp.categorias ALTER COLUMN tipo DROP DEFAULT;

ALTER TABLE erp.categorias
  ADD COLUMN dre_grupo_id bigint,
  ADD COLUMN fora_dre boolean NOT NULL DEFAULT false;
ALTER TABLE erp.categorias
  ADD CONSTRAINT categorias_dre_grupo_fk FOREIGN KEY (empresa_id, dre_grupo_id) REFERENCES erp.dre_grupos(empresa_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT categorias_fora_dre_chk CHECK (NOT (fora_dre AND dre_grupo_id IS NOT NULL));
CREATE INDEX categorias_dre_grupo_idx ON erp.categorias (empresa_id, dre_grupo_id) WHERE excluido_em IS NULL;
COMMENT ON COLUMN erp.categorias.dre_grupo_id IS 'Grupo da DRE. Nulo com fora_dre falso = "Não classificado".';
COMMENT ON COLUMN erp.categorias.fora_dre IS 'Movimenta dinheiro mas não é receita nem despesa (empréstimo, aporte, distribuição de lucros, compra de equipamento).';
COMMENT ON COLUMN erp.categorias.entrada_dre IS 'Obsoleta (substituída por dre_grupo_id/fora_dre).';
COMMENT ON COLUMN erp.categorias.considera_custo_dre IS 'Obsoleta (substituída por dre_grupo_id).';
COMMENT ON TABLE erp.categorias IS 'Categorias financeiras (receita/despesa) com grupo da DRE. Agrupamentos de cadastros ficam em erp.categorias_cadastro.';

-- Subcategoria: mesmo tipo da pai e herda a classificação da DRE; mudar a pai repassa às subcategorias.
CREATE OR REPLACE FUNCTION erp.herdar_classificacao_categoria()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
DECLARE pai record;
BEGIN
  IF NEW.categoria_pai_id IS NOT NULL THEN
    SELECT tipo, dre_grupo_id, fora_dre INTO pai FROM erp.categorias WHERE empresa_id = NEW.empresa_id AND id = NEW.categoria_pai_id;
    IF pai.tipo IS DISTINCT FROM NEW.tipo THEN RAISE EXCEPTION 'Subcategoria precisa ser do mesmo tipo da categoria-pai' USING ERRCODE = '23514'; END IF;
    NEW.dre_grupo_id := pai.dre_grupo_id; NEW.fora_dre := pai.fora_dre;
  END IF;
  RETURN NEW;
END $$;
CREATE OR REPLACE FUNCTION erp.repassar_classificacao_categoria()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
BEGIN
  UPDATE erp.categorias SET dre_grupo_id = NEW.dre_grupo_id, fora_dre = NEW.fora_dre
  WHERE empresa_id = NEW.empresa_id AND categoria_pai_id = NEW.id
    AND (dre_grupo_id IS DISTINCT FROM NEW.dre_grupo_id OR fora_dre IS DISTINCT FROM NEW.fora_dre);
  RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION erp.herdar_classificacao_categoria(), erp.repassar_classificacao_categoria() FROM PUBLIC;
CREATE TRIGGER herdar_classificacao BEFORE INSERT OR UPDATE OF categoria_pai_id, dre_grupo_id, fora_dre, tipo ON erp.categorias
  FOR EACH ROW EXECUTE FUNCTION erp.herdar_classificacao_categoria();
CREATE TRIGGER repassar_classificacao AFTER UPDATE OF dre_grupo_id, fora_dre ON erp.categorias
  FOR EACH ROW WHEN (NEW.categoria_pai_id IS NULL) EXECUTE FUNCTION erp.repassar_classificacao_categoria();
CREATE TRIGGER validar_nivel BEFORE INSERT OR UPDATE OF categoria_pai_id ON erp.categorias
  FOR EACH ROW EXECUTE FUNCTION erp.validar_nivel_categoria();

-- A proteção de categoria usada passa a cobrir só o tipo (receita/despesa). Grupo da DRE e organização em
-- subcategorias podem mudar: são classificação gerencial, não alteram lançamentos.
CREATE OR REPLACE FUNCTION erp.preservar_classificacao_usada()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $function$
DECLARE usado boolean:=false; r record; achou boolean; campo text;
BEGIN
 PERFORM erp.travar_evolucao(NEW.empresa_id);
 IF TG_OP='UPDATE' AND (OLD.empresa_id<>NEW.empresa_id OR OLD.id<>NEW.id) THEN RAISE EXCEPTION 'Identidade do cadastro preservada' USING ERRCODE='23514'; END IF;
 IF TG_TABLE_NAME='categorias' THEN
  IF EXISTS(WITH RECURSIVE pais AS (
   SELECT id,categoria_pai_id,ARRAY[id] caminho FROM erp.categorias WHERE empresa_id=NEW.empresa_id AND id=NEW.categoria_pai_id
   UNION ALL SELECT c.id,c.categoria_pai_id,p.caminho||c.id FROM pais p JOIN erp.categorias c ON c.empresa_id=NEW.empresa_id AND c.id=p.categoria_pai_id WHERE NOT c.id=ANY(p.caminho)
  ) SELECT 1 FROM pais WHERE id=NEW.id) OR NEW.categoria_pai_id=NEW.id THEN RAISE EXCEPTION 'Hierarquia de categorias ciclica' USING ERRCODE='23514'; END IF;
  IF TG_OP='INSERT' OR OLD.tipo IS NOT DISTINCT FROM NEW.tipo THEN RETURN NEW; END IF;
  campo:='categoria_id';
 ELSE
  IF TG_OP='INSERT' OR ROW(OLD.saldo_inicial,OLD.data_saldo_inicial,OLD.tipo) IS NOT DISTINCT FROM ROW(NEW.saldo_inicial,NEW.data_saldo_inicial,NEW.tipo) THEN RETURN NEW; END IF;
  campo:='conta_financeira_id';
 END IF;
 FOR r IN SELECT ns.nspname schema_name,cl.relname tabela,a.attname coluna FROM pg_constraint fk
 JOIN pg_class cl ON cl.oid=fk.conrelid JOIN pg_namespace ns ON ns.oid=cl.relnamespace
 JOIN unnest(fk.conkey) k ON true JOIN pg_attribute a ON a.attrelid=cl.oid AND a.attnum=k
 WHERE fk.contype='f' AND fk.confrelid=TG_RELID AND a.attname<>'empresa_id' AND ns.nspname='erp' AND cl.relname<>TG_TABLE_NAME LOOP
  EXECUTE format('SELECT EXISTS(SELECT 1 FROM %I.%I WHERE empresa_id=$1 AND %I=$2)',r.schema_name,r.tabela,r.coluna) INTO achou USING NEW.empresa_id,NEW.id;
  usado:=usado OR achou;
 END LOOP;
 IF usado THEN RAISE EXCEPTION 'Classificacao ou saldo inicial ja utilizado; crie novo cadastro para outra semantica' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $function$;

ALTER TABLE erp.categorias ENABLE TRIGGER classificacao_usada;

-- 5. Receita prevista ------------------------------------------------------------------------------------------
ALTER TABLE erp.contas_receber
  ADD COLUMN tipo_lancamento text NOT NULL DEFAULT 'efetivo',
  ADD COLUMN efetivado_em timestamptz;
ALTER TABLE erp.contas_receber ADD CONSTRAINT contas_receber_tipo_lancamento_chk CHECK (tipo_lancamento IN ('previsao', 'efetivo'));
CREATE INDEX contas_receber_tipo_lancamento_idx ON erp.contas_receber (empresa_id, tipo_lancamento) WHERE tipo_lancamento = 'previsao' AND excluido_em IS NULL;
COMMENT ON COLUMN erp.contas_receber.tipo_lancamento IS 'Receita prevista ou efetiva. A previsão é efetivada em vez de duplicada; previsão não recebe baixa.';

CREATE OR REPLACE FUNCTION erp.efetivacao_receber()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
BEGIN
  PERFORM erp.travar_evolucao(NEW.empresa_id);
  IF TG_OP = 'UPDATE' AND OLD.tipo_lancamento = 'previsao' AND NEW.tipo_lancamento = 'efetivo' THEN NEW.efetivado_em := now(); END IF;
  IF NEW.tipo_lancamento = 'previsao' AND (NEW.efetivado_em IS NOT NULL OR NEW.venda_id IS NOT NULL OR EXISTS (
    SELECT 1 FROM erp.contas_receber_parcelas p WHERE p.empresa_id = NEW.empresa_id AND p.conta_receber_id = NEW.id AND (
      EXISTS (SELECT 1 FROM erp.pagamentos m WHERE m.empresa_id = p.empresa_id AND m.conta_receber_parcela_id = p.id)
      OR EXISTS (SELECT 1 FROM erp.adiantamentos_aplicacoes a WHERE a.empresa_id = p.empresa_id AND a.conta_receber_parcela_id = p.id)
      OR EXISTS (SELECT 1 FROM erp.renegociacoes_parcelas r WHERE r.empresa_id = p.empresa_id AND r.conta_receber_parcela_id = p.id)))) THEN
    RAISE EXCEPTION 'Receita efetivada, vinda de venda ou já utilizada não pode ser previsão' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION erp.efetivacao_receber() FROM PUBLIC;
CREATE TRIGGER efetivacao_receber BEFORE INSERT OR UPDATE ON erp.contas_receber FOR EACH ROW EXECUTE FUNCTION erp.efetivacao_receber();

-- Baixa, adiantamento e renegociação exigem título efetivo dos dois lados.
CREATE OR REPLACE FUNCTION erp.exigir_obrigacao_efetiva()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
DECLARE linha jsonb := to_jsonb(NEW); parcela bigint; tipo text;
BEGIN
  parcela := (linha ->> 'conta_pagar_parcela_id')::bigint;
  IF parcela IS NOT NULL THEN
    SELECT t.tipo_lancamento INTO tipo FROM erp.contas_pagar_parcelas p JOIN erp.contas_pagar t ON t.empresa_id = p.empresa_id AND t.id = p.conta_pagar_id
    WHERE p.empresa_id = NEW.empresa_id AND p.id = parcela;
    IF tipo = 'previsao' THEN RAISE EXCEPTION 'Efetive a previsao antes de liquidar na mesma transacao' USING ERRCODE = '23514'; END IF;
  END IF;
  parcela := (linha ->> 'conta_receber_parcela_id')::bigint;
  IF parcela IS NOT NULL THEN
    SELECT t.tipo_lancamento INTO tipo FROM erp.contas_receber_parcelas p JOIN erp.contas_receber t ON t.empresa_id = p.empresa_id AND t.id = p.conta_receber_id
    WHERE p.empresa_id = NEW.empresa_id AND p.id = parcela;
    IF tipo = 'previsao' THEN RAISE EXCEPTION 'Efetive a receita prevista antes de receber' USING ERRCODE = '23514'; END IF;
  END IF;
  RETURN NEW;
END $$;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime;

COMMIT;
