BEGIN;

-- Fase 2B: anexos em títulos, vendas, compras, contratos e ordens de serviço, e comprovante na baixa.
--
-- Os arquivos ficam no bucket privado erp-anexos (migração 20261007130000), num caminho que começa pela
-- empresa. A tabela erp.arquivos só aceita gravação direta de quem administra configurações; anexar, listar,
-- baixar e remover passam por estas funções, que conferem a permissão do módulo do documento (financeiro,
-- vendas ou compras) e que o documento é da empresa da sessão. O servidor gera o link assinado só depois.

-- Comprovante (ou outro arquivo) de uma baixa: pagamentos não mudam depois de registrados, então o vínculo é
-- uma tabela à parte, como nos demais documentos.
CREATE TABLE erp.pagamentos_arquivos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  pagamento_id bigint NOT NULL,
  arquivo_id bigint NOT NULL,
  finalidade text NOT NULL DEFAULT 'comprovante',
  descricao text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  CONSTRAINT pagamentos_arquivos_pagamento_fk FOREIGN KEY (empresa_id, pagamento_id) REFERENCES erp.pagamentos(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT pagamentos_arquivos_arquivo_fk FOREIGN KEY (empresa_id, arquivo_id) REFERENCES erp.arquivos(empresa_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX pagamentos_arquivos_unico ON erp.pagamentos_arquivos (empresa_id, pagamento_id, arquivo_id) WHERE excluido_em IS NULL;
SELECT erp.criar_politicas_padrao('pagamentos_arquivos', 'financeiro', 'erp.financeiro.baixar');

-- Documento → tabela, tabela de vínculo, coluna do vínculo e permissões de leitura e de escrita.
CREATE OR REPLACE FUNCTION erp.anexo_destino(p_tipo text)
RETURNS TABLE (tabela text, vinculo text, coluna text, leitura text, escrita text, tem_finalidade boolean)
LANGUAGE sql IMMUTABLE SET search_path TO 'pg_catalog' AS $$
  SELECT d.tabela, d.vinculo, d.coluna, d.leitura, d.escrita, d.tem_finalidade FROM (VALUES
    ('conta_pagar', 'contas_pagar', 'contas_pagar_arquivos', 'conta_pagar_id', 'erp.financeiro.visualizar', 'erp.financeiro.gerenciar', false),
    ('conta_receber', 'contas_receber', 'contas_receber_arquivos', 'conta_receber_id', 'erp.financeiro.visualizar', 'erp.financeiro.gerenciar', true),
    ('pagamento', 'pagamentos', 'pagamentos_arquivos', 'pagamento_id', 'erp.financeiro.visualizar', 'erp.financeiro.baixar', true),
    ('venda', 'vendas', 'vendas_arquivos', 'venda_id', 'erp.vendas.visualizar', 'erp.vendas.gerenciar', true),
    ('compra', 'compras', 'compras_arquivos', 'compra_id', 'erp.compras.visualizar', 'erp.compras.gerenciar', false),
    ('contrato', 'contratos_vendas', 'contratos_vendas_arquivos', 'contrato_id', 'erp.vendas.visualizar', 'erp.vendas.gerenciar', true),
    ('ordem_servico', 'ordens_servico', 'ordens_servico_arquivos', 'ordem_servico_id', 'erp.vendas.visualizar', 'erp.vendas.gerenciar', true)
  ) AS d(tipo, tabela, vinculo, coluna, leitura, escrita, tem_finalidade) WHERE d.tipo = p_tipo
$$;

-- Registra o arquivo (pendente até o envio ser confirmado) e o vínculo com o documento.
CREATE OR REPLACE FUNCTION erp.anexar_arquivo(empresa_id bigint, p_tipo text, p_registro_id bigint, p_caminho text, p_nome text,
  p_mime_type text, p_tamanho bigint, p_finalidade text, p_limite_bytes bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
#variable_conflict use_column
DECLARE empresa bigint := shared.erp_empresa_contexto(); usuario bigint := shared.current_user_id(); d record; achou boolean; usado bigint; novo bigint;
BEGIN
  IF $1 IS DISTINCT FROM shared.erp_empresa_contexto() THEN RAISE EXCEPTION 'Empresa diferente da sessão' USING ERRCODE = '42501'; END IF;
  SELECT * INTO d FROM erp.anexo_destino(p_tipo);
  IF d.tabela IS NULL THEN RAISE EXCEPTION 'Tipo de documento sem anexos' USING ERRCODE = '22023'; END IF;
  IF empresa IS NULL OR NOT shared.has_erp_capability(empresa, d.escrita) THEN RAISE EXCEPTION 'Sem permissão para anexar neste documento' USING ERRCODE = '42501'; END IF;
  EXECUTE format('SELECT EXISTS (SELECT 1 FROM erp.%I WHERE empresa_id = $1 AND id = $2%s)', d.tabela,
    CASE WHEN p_tipo = 'pagamento' THEN '' ELSE ' AND excluido_em IS NULL' END) INTO achou USING empresa, p_registro_id;
  IF NOT achou THEN RAISE EXCEPTION 'Documento não encontrado nesta empresa' USING ERRCODE = '22023'; END IF;
  IF p_caminho NOT LIKE empresa::text || '/%' THEN RAISE EXCEPTION 'Caminho fora da empresa' USING ERRCODE = '22023'; END IF;
  SELECT coalesce(sum(tamanho_bytes), 0) INTO usado FROM erp.arquivos WHERE empresa_id = empresa AND excluido_em IS NULL;
  IF usado + p_tamanho > p_limite_bytes THEN RAISE EXCEPTION 'Limite de armazenamento de anexos da empresa atingido' USING ERRCODE = '22023'; END IF;
  -- O vínculo com o documento só é criado na confirmação: arquivos vinculados a vendas, contratos, OS e contas a
  -- receber ficam imutáveis (preservação documental), e o pendente ainda precisa ser atualizado.
  INSERT INTO erp.arquivos (empresa_id, bucket, caminho, nome, mime_type, tamanho_bytes, criado_por, atualizado_por, metadata)
  VALUES (empresa, 'erp-anexos', p_caminho, p_nome, p_mime_type, p_tamanho, usuario, usuario,
    jsonb_build_object('pendente', true, 'documento', p_tipo, 'registro_id', p_registro_id,
      'finalidade', coalesce(nullif(btrim(p_finalidade), ''), CASE WHEN p_tipo = 'pagamento' THEN 'comprovante' ELSE 'anexo' END)))
  RETURNING id INTO novo;
  RETURN novo;
END $$;

-- Arquivo do documento que a sessão pode ler (ou alterar, com p_escrita) — base de confirmar, baixar e remover.
CREATE OR REPLACE FUNCTION erp.anexo_acessivel(empresa_id bigint, p_arquivo_id bigint, p_escrita boolean)
RETURNS TABLE (id bigint, bucket text, caminho text, nome text, mime_type text, tamanho_bytes bigint, pendente boolean, documento text, registro_id bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
#variable_conflict use_column
DECLARE empresa bigint := shared.erp_empresa_contexto(); a record; d record;
BEGIN
  IF $1 IS DISTINCT FROM empresa THEN RETURN; END IF;
  SELECT x.* INTO a FROM erp.arquivos x WHERE x.empresa_id = empresa AND x.id = p_arquivo_id AND x.excluido_em IS NULL;
  IF a.id IS NULL THEN RETURN; END IF;
  SELECT * INTO d FROM erp.anexo_destino(a.metadata ->> 'documento');
  IF d.tabela IS NULL OR NOT shared.has_erp_capability(empresa, CASE WHEN p_escrita THEN d.escrita ELSE d.leitura END) THEN RETURN; END IF;
  RETURN QUERY SELECT a.id, a.bucket, a.caminho, a.nome, a.mime_type, a.tamanho_bytes, coalesce((a.metadata ->> 'pendente')::boolean, false),
    a.metadata ->> 'documento', (a.metadata ->> 'registro_id')::bigint;
END $$;

CREATE OR REPLACE FUNCTION erp.confirmar_anexo(empresa_id bigint, p_arquivo_id bigint, p_hash text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
#variable_conflict use_column
DECLARE empresa bigint := shared.erp_empresa_contexto(); usuario bigint := shared.current_user_id(); a record; d record; finalidade text;
BEGIN
  IF $1 IS DISTINCT FROM empresa THEN RAISE EXCEPTION 'Empresa diferente da sessão' USING ERRCODE = '42501'; END IF;
  SELECT * INTO a FROM erp.anexo_acessivel($1, p_arquivo_id, true);
  IF a.id IS NULL THEN RAISE EXCEPTION 'Anexo não encontrado' USING ERRCODE = '22023'; END IF;
  IF NOT a.pendente THEN RETURN true; END IF;
  SELECT x.metadata ->> 'finalidade' INTO finalidade FROM erp.arquivos x WHERE x.empresa_id = empresa AND x.id = p_arquivo_id;
  UPDATE erp.arquivos SET metadata = metadata || '{"pendente": false}'::jsonb, hash_sha256 = coalesce(p_hash, hash_sha256), atualizado_por = usuario
  WHERE empresa_id = empresa AND id = p_arquivo_id;
  SELECT * INTO d FROM erp.anexo_destino(a.documento);
  IF d.tem_finalidade THEN
    EXECUTE format('INSERT INTO erp.%I (empresa_id, %I, arquivo_id, finalidade, criado_por) VALUES ($1, $2, $3, $4, $5)', d.vinculo, d.coluna)
      USING empresa, a.registro_id, p_arquivo_id, coalesce(finalidade, 'anexo'), usuario;
  ELSE
    EXECUTE format('INSERT INTO erp.%I (empresa_id, %I, arquivo_id, criado_por) VALUES ($1, $2, $3, $4)', d.vinculo, d.coluna)
      USING empresa, a.registro_id, p_arquivo_id, usuario;
  END IF;
  RETURN true;
END $$;

-- Remove o anexo (sem apagar o histórico): arquivo e vínculo ficam marcados como excluídos. Anexos de vendas,
-- contratos, ordens de serviço e contas a receber são documentos preservados e não podem ser removidos.
CREATE OR REPLACE FUNCTION erp.remover_anexo(empresa_id bigint, p_arquivo_id bigint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
#variable_conflict use_column
DECLARE empresa bigint := shared.erp_empresa_contexto(); a record; d record;
BEGIN
  IF $1 IS DISTINCT FROM shared.erp_empresa_contexto() THEN RAISE EXCEPTION 'Empresa diferente da sessão' USING ERRCODE = '42501'; END IF;
  SELECT * INTO a FROM erp.anexo_acessivel($1, p_arquivo_id, true);
  IF a.id IS NULL THEN RAISE EXCEPTION 'Anexo não encontrado ou sem permissão' USING ERRCODE = '42501'; END IF;
  SELECT * INTO d FROM erp.anexo_destino(a.documento);
  IF NOT a.pendente AND d.vinculo NOT IN ('pagamentos_arquivos', 'contas_pagar_arquivos', 'compras_arquivos') THEN
    RAISE EXCEPTION 'Anexo deste documento é preservado e não pode ser removido' USING ERRCODE = '22023';
  END IF;
  UPDATE erp.arquivos SET excluido_em = now(), atualizado_por = shared.current_user_id() WHERE empresa_id = empresa AND id = p_arquivo_id;
  IF NOT a.pendente THEN
    EXECUTE format('UPDATE erp.%I SET excluido_em = now() WHERE empresa_id = $1 AND arquivo_id = $2', d.vinculo) USING empresa, p_arquivo_id;
  END IF;
  RETURN true;
END $$;

-- Anexos confirmados de um documento (para a tela e o chat).
CREATE OR REPLACE FUNCTION erp.listar_anexos(empresa_id bigint, p_tipo text, p_registro_id bigint)
RETURNS TABLE (id bigint, nome text, mime_type text, tamanho_bytes bigint, finalidade text, criado_em timestamptz, criado_por text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog' AS $$
#variable_conflict use_column
DECLARE empresa bigint := shared.erp_empresa_contexto(); d record;
BEGIN
  IF $1 IS DISTINCT FROM empresa THEN RETURN; END IF;
  SELECT * INTO d FROM erp.anexo_destino(p_tipo);
  IF d.tabela IS NULL OR empresa IS NULL OR NOT shared.has_erp_capability(empresa, d.leitura) THEN RETURN; END IF;
  RETURN QUERY EXECUTE format(
    'SELECT a.id, a.nome, a.mime_type, a.tamanho_bytes, %s, a.criado_em, u.full_name::text
     FROM erp.%I v JOIN erp.arquivos a ON a.empresa_id = v.empresa_id AND a.id = v.arquivo_id
     LEFT JOIN shared.usuarios u ON u.id = a.criado_por
     WHERE v.empresa_id = $1 AND v.%I = $2 AND a.excluido_em IS NULL AND NOT coalesce((a.metadata ->> ''pendente'')::boolean, false)%s
     ORDER BY a.criado_em DESC',
    CASE WHEN d.tem_finalidade THEN 'v.finalidade' ELSE '''anexo''::text' END, d.vinculo, d.coluna,
    CASE WHEN d.vinculo IN ('pagamentos_arquivos', 'contas_pagar_arquivos', 'compras_arquivos') THEN ' AND v.excluido_em IS NULL' ELSE '' END)
  USING empresa, p_registro_id;
END $$;

REVOKE ALL ON FUNCTION erp.anexo_destino(text), erp.anexar_arquivo(bigint, text, bigint, text, text, text, bigint, text, bigint),
  erp.anexo_acessivel(bigint, bigint, boolean), erp.confirmar_anexo(bigint, bigint, text), erp.remover_anexo(bigint, bigint), erp.listar_anexos(bigint, text, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION erp.anexo_destino(text), erp.anexar_arquivo(bigint, text, bigint, text, text, text, bigint, text, bigint),
  erp.anexo_acessivel(bigint, bigint, boolean), erp.confirmar_anexo(bigint, bigint, text), erp.remover_anexo(bigint, bigint), erp.listar_anexos(bigint, text, bigint) TO erp_runtime;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime;

COMMIT;
