BEGIN;

ALTER TABLE erp.produtos
  ADD COLUMN IF NOT EXISTS controla_estoque boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS permite_estoque_negativo boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS estoque_minimo numeric(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estoque_maximo numeric(18,4),
  ADD COLUMN IF NOT EXISTS ponto_reposicao numeric(18,4) NOT NULL DEFAULT 0;

ALTER TABLE erp.fornecedores_produtos
  ADD COLUMN IF NOT EXISTS fator_conversao numeric(18,6) NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS erp.locais_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text NOT NULL,
  descricao text,
  endereco jsonb NOT NULL DEFAULT '{}'::jsonb,
  padrao boolean NOT NULL DEFAULT false,
  permite_venda boolean NOT NULL DEFAULT true,
  permite_compra boolean NOT NULL DEFAULT true,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT locais_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT locais_estoque_nome_chk CHECK (btrim(nome) <> ''),
  CONSTRAINT locais_estoque_codigo_chk CHECK (btrim(codigo) <> ''),
  CONSTRAINT locais_estoque_endereco_object_chk CHECK (jsonb_typeof(endereco) = 'object'),
  CONSTRAINT locais_estoque_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT locais_estoque_versao_chk CHECK (versao > 0)
);

CREATE TABLE IF NOT EXISTS erp.saldos_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  produto_id bigint NOT NULL,
  local_estoque_id bigint NOT NULL,
  quantidade_fisica numeric(18,4) NOT NULL DEFAULT 0,
  quantidade_reservada numeric(18,4) NOT NULL DEFAULT 0,
  custo_medio numeric(18,6) NOT NULL DEFAULT 0,
  ultima_movimentacao_em timestamptz,
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT saldos_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT saldos_estoque_produto_local_key UNIQUE (tenant_id, produto_id, local_estoque_id),
  CONSTRAINT saldos_estoque_valores_chk CHECK (quantidade_reservada >= 0 AND custo_medio >= 0 AND versao > 0),
  CONSTRAINT saldos_estoque_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT saldos_estoque_local_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.documentos_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo text NOT NULL,
  numero text,
  data_documento date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'rascunho',
  local_estoque_id bigint,
  entidade_id bigint,
  venda_id bigint,
  compra_id bigint,
  motivo text,
  chave_idempotencia text,
  finalizado_em timestamptz,
  cancelado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT documentos_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT documentos_estoque_tipo_chk CHECK (tipo IN ('entrada', 'saida', 'ajuste', 'devolucao_cliente', 'devolucao_fornecedor')),
  CONSTRAINT documentos_estoque_status_chk CHECK (status IN ('rascunho', 'finalizado', 'cancelado')),
  CONSTRAINT documentos_estoque_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT documentos_estoque_versao_chk CHECK (versao > 0),
  CONSTRAINT documentos_estoque_local_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT documentos_estoque_entidade_fk FOREIGN KEY (tenant_id, entidade_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT documentos_estoque_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT documentos_estoque_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.documentos_estoque_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  documento_estoque_id bigint NOT NULL,
  produto_id bigint NOT NULL,
  quantidade numeric(18,4) NOT NULL,
  custo_unitario numeric(18,6) NOT NULL DEFAULT 0,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT documentos_estoque_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT documentos_estoque_itens_quantidade_chk CHECK (quantidade > 0 AND custo_unitario >= 0),
  CONSTRAINT documentos_estoque_itens_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT documentos_estoque_itens_documento_fk FOREIGN KEY (tenant_id, documento_estoque_id)
    REFERENCES erp.documentos_estoque (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT documentos_estoque_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.movimentacoes_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  produto_id bigint NOT NULL,
  local_estoque_id bigint NOT NULL,
  documento_estoque_id bigint,
  tipo text NOT NULL,
  quantidade numeric(18,4) NOT NULL,
  custo_unitario numeric(18,6) NOT NULL DEFAULT 0,
  custo_medio_apos numeric(18,6) NOT NULL DEFAULT 0,
  saldo_apos numeric(18,4) NOT NULL,
  origem_tipo text NOT NULL,
  origem_id bigint,
  chave_idempotencia text NOT NULL,
  ocorrido_em timestamptz NOT NULL DEFAULT now(),
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT movimentacoes_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT movimentacoes_estoque_tipo_chk CHECK (tipo IN ('entrada', 'saida', 'ajuste_entrada', 'ajuste_saida', 'transferencia_entrada', 'transferencia_saida', 'estorno')),
  CONSTRAINT movimentacoes_estoque_quantidade_chk CHECK (quantidade <> 0 AND custo_unitario >= 0 AND custo_medio_apos >= 0),
  CONSTRAINT movimentacoes_estoque_origem_chk CHECK (btrim(origem_tipo) <> ''),
  CONSTRAINT movimentacoes_estoque_chave_chk CHECK (btrim(chave_idempotencia) <> ''),
  CONSTRAINT movimentacoes_estoque_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT movimentacoes_estoque_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT movimentacoes_estoque_local_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT movimentacoes_estoque_documento_fk FOREIGN KEY (tenant_id, documento_estoque_id)
    REFERENCES erp.documentos_estoque (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.reservas_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  produto_id bigint NOT NULL,
  local_estoque_id bigint NOT NULL,
  venda_id bigint NOT NULL,
  venda_item_id bigint NOT NULL,
  quantidade numeric(18,4) NOT NULL,
  quantidade_atendida numeric(18,4) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'ativa',
  reservada_em timestamptz NOT NULL DEFAULT now(),
  encerrada_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT reservas_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT reservas_estoque_venda_item_produto_key UNIQUE (tenant_id, venda_item_id, produto_id),
  CONSTRAINT reservas_estoque_status_chk CHECK (status IN ('ativa', 'atendida', 'liberada', 'cancelada')),
  CONSTRAINT reservas_estoque_quantidades_chk CHECK (quantidade > 0 AND quantidade_atendida >= 0 AND quantidade_atendida <= quantidade),
  CONSTRAINT reservas_estoque_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT reservas_estoque_local_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT reservas_estoque_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT reservas_estoque_venda_item_fk FOREIGN KEY (tenant_id, venda_item_id)
    REFERENCES erp.vendas_itens (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.inventarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  numero text NOT NULL,
  local_estoque_id bigint NOT NULL,
  data_inventario date NOT NULL DEFAULT CURRENT_DATE,
  tipo text NOT NULL DEFAULT 'completo',
  status text NOT NULL DEFAULT 'rascunho',
  observacoes text,
  iniciado_em timestamptz,
  finalizado_em timestamptz,
  cancelado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT inventarios_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT inventarios_tipo_chk CHECK (tipo IN ('completo', 'parcial')),
  CONSTRAINT inventarios_status_chk CHECK (status IN ('rascunho', 'em_contagem', 'finalizado', 'cancelado')),
  CONSTRAINT inventarios_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT inventarios_versao_chk CHECK (versao > 0),
  CONSTRAINT inventarios_local_fk FOREIGN KEY (tenant_id, local_estoque_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.inventarios_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  inventario_id bigint NOT NULL,
  produto_id bigint NOT NULL,
  quantidade_sistema numeric(18,4) NOT NULL DEFAULT 0,
  quantidade_contada numeric(18,4),
  custo_medio numeric(18,6) NOT NULL DEFAULT 0,
  observacoes text,
  contado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT inventarios_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT inventarios_itens_produto_key UNIQUE (tenant_id, inventario_id, produto_id),
  CONSTRAINT inventarios_itens_valores_chk CHECK (quantidade_contada IS NULL OR quantidade_contada >= 0),
  CONSTRAINT inventarios_itens_inventario_fk FOREIGN KEY (tenant_id, inventario_id)
    REFERENCES erp.inventarios (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT inventarios_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.transferencias_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  numero text NOT NULL,
  local_origem_id bigint NOT NULL,
  local_destino_id bigint NOT NULL,
  data_transferencia date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'rascunho',
  observacoes text,
  chave_idempotencia text,
  finalizada_em timestamptz,
  cancelada_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  versao integer NOT NULL DEFAULT 1,
  CONSTRAINT transferencias_estoque_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT transferencias_estoque_locais_chk CHECK (local_origem_id <> local_destino_id),
  CONSTRAINT transferencias_estoque_status_chk CHECK (status IN ('rascunho', 'finalizada', 'cancelada')),
  CONSTRAINT transferencias_estoque_versao_chk CHECK (versao > 0),
  CONSTRAINT transferencias_estoque_origem_fk FOREIGN KEY (tenant_id, local_origem_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT transferencias_estoque_destino_fk FOREIGN KEY (tenant_id, local_destino_id)
    REFERENCES erp.locais_estoque (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.transferencias_estoque_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  transferencia_id bigint NOT NULL,
  produto_id bigint NOT NULL,
  quantidade numeric(18,4) NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT transferencias_estoque_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT transferencias_estoque_itens_produto_key UNIQUE (tenant_id, transferencia_id, produto_id),
  CONSTRAINT transferencias_estoque_itens_quantidade_chk CHECK (quantidade > 0),
  CONSTRAINT transferencias_estoque_itens_transferencia_fk FOREIGN KEY (tenant_id, transferencia_id)
    REFERENCES erp.transferencias_estoque (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT transferencias_estoque_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.conversoes_unidades_produto (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  produto_id bigint NOT NULL,
  unidade_origem text NOT NULL,
  unidade_destino text NOT NULL,
  fator numeric(18,6) NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT conversoes_unidades_produto_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT conversoes_unidades_produto_unidades_chk CHECK (btrim(unidade_origem) <> '' AND btrim(unidade_destino) <> '' AND unidade_origem <> unidade_destino),
  CONSTRAINT conversoes_unidades_produto_fator_chk CHECK (fator > 0),
  CONSTRAINT conversoes_unidades_produto_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS erp.kits_produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  produto_id bigint NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT kits_produtos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT kits_produtos_produto_key UNIQUE (tenant_id, produto_id),
  CONSTRAINT kits_produtos_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS erp.kits_produtos_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  kit_id bigint NOT NULL,
  produto_componente_id bigint NOT NULL,
  quantidade numeric(18,4) NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT kits_produtos_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT kits_produtos_itens_componente_key UNIQUE (tenant_id, kit_id, produto_componente_id),
  CONSTRAINT kits_produtos_itens_quantidade_chk CHECK (quantidade > 0),
  CONSTRAINT kits_produtos_itens_kit_fk FOREIGN KEY (tenant_id, kit_id)
    REFERENCES erp.kits_produtos (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT kits_produtos_itens_componente_fk FOREIGN KEY (tenant_id, produto_componente_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS locais_estoque_codigo_unico_idx
  ON erp.locais_estoque (tenant_id, lower(codigo)) WHERE excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS locais_estoque_padrao_unico_idx
  ON erp.locais_estoque (tenant_id) WHERE padrao AND ativo AND excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS documentos_estoque_idempotencia_idx
  ON erp.documentos_estoque (tenant_id, chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS movimentacoes_estoque_idempotencia_idx
  ON erp.movimentacoes_estoque (tenant_id, chave_idempotencia);
CREATE UNIQUE INDEX IF NOT EXISTS inventarios_numero_unico_idx
  ON erp.inventarios (tenant_id, numero) WHERE excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS transferencias_estoque_numero_unico_idx
  ON erp.transferencias_estoque (tenant_id, numero) WHERE excluido_em IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS transferencias_estoque_idempotencia_idx
  ON erp.transferencias_estoque (tenant_id, chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS conversoes_unidades_produto_unica_idx
  ON erp.conversoes_unidades_produto (tenant_id, produto_id, lower(unidade_origem), lower(unidade_destino))
  WHERE excluido_em IS NULL AND ativo;
CREATE INDEX IF NOT EXISTS movimentacoes_estoque_extrato_idx
  ON erp.movimentacoes_estoque (tenant_id, produto_id, local_estoque_id, ocorrido_em DESC);
CREATE INDEX IF NOT EXISTS reservas_estoque_ativas_idx
  ON erp.reservas_estoque (tenant_id, produto_id, local_estoque_id) WHERE status = 'ativa';

CREATE OR REPLACE VIEW erp.vw_posicao_estoque
WITH (security_invoker = true)
AS
SELECT
  saldos.tenant_id,
  saldos.produto_id,
  produtos.codigo,
  produtos.sku,
  produtos.nome AS produto,
  produtos.unidade_medida,
  saldos.local_estoque_id,
  locais.nome AS local_estoque,
  saldos.quantidade_fisica,
  saldos.quantidade_reservada,
  saldos.quantidade_fisica - saldos.quantidade_reservada AS quantidade_disponivel,
  saldos.custo_medio,
  saldos.quantidade_fisica * saldos.custo_medio AS valor_estoque,
  produtos.estoque_minimo,
  produtos.ponto_reposicao,
  CASE
    WHEN saldos.quantidade_fisica - saldos.quantidade_reservada <= produtos.ponto_reposicao THEN 'repor'
    ELSE 'normal'
  END AS situacao,
  saldos.ultima_movimentacao_em
FROM erp.saldos_estoque AS saldos
JOIN erp.produtos AS produtos
  ON produtos.tenant_id = saldos.tenant_id AND produtos.id = saldos.produto_id
JOIN erp.locais_estoque AS locais
  ON locais.tenant_id = saldos.tenant_id AND locais.id = saldos.local_estoque_id
WHERE produtos.excluido_em IS NULL AND locais.excluido_em IS NULL;

DO $$
DECLARE
  tabela text;
BEGIN
  FOREACH tabela IN ARRAY ARRAY[
    'locais_estoque', 'saldos_estoque', 'documentos_estoque', 'documentos_estoque_itens',
    'movimentacoes_estoque', 'reservas_estoque', 'inventarios', 'inventarios_itens',
    'transferencias_estoque', 'transferencias_estoque_itens', 'conversoes_unidades_produto',
    'kits_produtos', 'kits_produtos_itens'
  ]
  LOOP
    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))', tabela || '_select_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', tabela || '_insert_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR UPDATE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member''])) WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', tabela || '_update_policy', tabela);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR DELETE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'']))', tabela || '_delete_policy', tabela);
  END LOOP;

  FOREACH tabela IN ARRAY ARRAY[
    'locais_estoque', 'documentos_estoque', 'reservas_estoque', 'inventarios', 'inventarios_itens',
    'transferencias_estoque', 'conversoes_unidades_produto', 'kits_produtos', 'kits_produtos_itens'
  ]
  LOOP
    EXECUTE format('CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()', tabela);
  END LOOP;
END $$;

CREATE TRIGGER bloquear_mutacao_movimentacao_estoque
  BEFORE UPDATE OR DELETE ON erp.movimentacoes_estoque
  FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento();

GRANT SELECT, INSERT, UPDATE, DELETE ON erp.locais_estoque, erp.saldos_estoque,
  erp.documentos_estoque, erp.documentos_estoque_itens, erp.reservas_estoque,
  erp.inventarios, erp.inventarios_itens, erp.transferencias_estoque,
  erp.transferencias_estoque_itens, erp.conversoes_unidades_produto,
  erp.kits_produtos, erp.kits_produtos_itens TO authenticated, service_role;
GRANT SELECT, INSERT ON erp.movimentacoes_estoque TO authenticated, service_role;
GRANT SELECT ON erp.vw_posicao_estoque TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO authenticated, service_role;

COMMIT;
