BEGIN;

ALTER TABLE erp.movimentacoes_estoque ADD COLUMN request_hash text;
ALTER TABLE erp.movimentacoes_estoque ADD COLUMN data_operacional date;
ALTER TABLE erp.documentos_estoque ADD COLUMN request_hash text;
ALTER TABLE erp.inventarios ADD COLUMN chave_idempotencia text;
CREATE UNIQUE INDEX inventarios_operacao_unica ON erp.inventarios(tenant_id, chave_idempotencia) WHERE chave_idempotencia IS NOT NULL;

-- Durable request/result journal; its rows commit together with the stock effects.
CREATE TABLE erp.operacoes_estoque (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants(id),
  recurso text NOT NULL CHECK (recurso IN ('movimentacoes','inventarios','transferencias','locais-estoque','kits','conversoes-unidades')),
  chave_idempotencia text NOT NULL CHECK (length(chave_idempotencia) BETWEEN 1 AND 200),
  request_hash text NOT NULL CHECK (length(request_hash)=64),
  resultado jsonb NOT NULL CHECK (jsonb_typeof(resultado)='object'),
  criado_por bigint NOT NULL REFERENCES shared.users(id),
  criado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,chave_idempotencia)
);
ALTER TABLE erp.operacoes_estoque ENABLE ROW LEVEL SECURITY;
CREATE POLICY operacoes_estoque_leitura ON erp.operacoes_estoque FOR SELECT
  USING (shared.can_read_erp_module(tenant_id,'estoque'));
CREATE POLICY operacoes_estoque_gravacao ON erp.operacoes_estoque FOR INSERT
  WITH CHECK (shared.has_erp_capability(tenant_id, CASE WHEN recurso IN ('movimentacoes','transferencias') THEN 'erp.estoque.movimentar' ELSE 'erp.estoque.ajustar' END)
    OR (recurso='movimentacoes' AND shared.has_erp_capability(tenant_id,'erp.estoque.ajustar')));
GRANT SELECT, INSERT ON erp.operacoes_estoque TO erp_runtime, service_role;
GRANT USAGE, SELECT ON SEQUENCE erp.operacoes_estoque_id_seq TO erp_runtime, service_role;

ALTER POLICY saldos_estoque_insert_policy ON erp.saldos_estoque WITH CHECK
 (shared.has_erp_capability(tenant_id,'erp.estoque.movimentar') OR shared.has_erp_capability(tenant_id,'erp.estoque.ajustar'));
ALTER POLICY saldos_estoque_update_policy ON erp.saldos_estoque USING
 (shared.has_erp_capability(tenant_id,'erp.estoque.movimentar') OR shared.has_erp_capability(tenant_id,'erp.estoque.ajustar')) WITH CHECK
 (shared.has_erp_capability(tenant_id,'erp.estoque.movimentar') OR shared.has_erp_capability(tenant_id,'erp.estoque.ajustar'));
ALTER POLICY movimentacoes_estoque_insert_policy ON erp.movimentacoes_estoque WITH CHECK
 (shared.has_erp_capability(tenant_id, CASE WHEN tipo IN ('ajuste_entrada','ajuste_saida') THEN 'erp.estoque.ajustar' ELSE 'erp.estoque.movimentar' END));

CREATE FUNCTION erp.validar_saldo_estoque_final() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE
  saldo erp.saldos_estoque%ROWTYPE;
  movimentos numeric;
  reservas numeric;
  ultimo erp.movimentacoes_estoque%ROWTYPE;
  negativo boolean;
  linha jsonb := CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
BEGIN
  SELECT * INTO saldo FROM erp.saldos_estoque WHERE tenant_id=(linha->>'tenant_id')::bigint
    AND produto_id=(linha->>'produto_id')::bigint AND local_estoque_id=(linha->>'local_estoque_id')::bigint;
  IF NOT FOUND THEN RAISE EXCEPTION 'Saldo de estoque ausente' USING ERRCODE='23514'; END IF;
  SELECT permite_estoque_negativo INTO negativo FROM erp.produtos WHERE tenant_id=saldo.tenant_id AND id=saldo.produto_id;
  SELECT COALESCE(sum(quantidade),0) INTO movimentos FROM erp.movimentacoes_estoque WHERE tenant_id=saldo.tenant_id AND produto_id=saldo.produto_id AND local_estoque_id=saldo.local_estoque_id;
  SELECT COALESCE(sum(quantidade-quantidade_atendida),0) INTO reservas FROM erp.reservas_estoque WHERE tenant_id=saldo.tenant_id AND produto_id=saldo.produto_id AND local_estoque_id=saldo.local_estoque_id AND status='ativa';
  SELECT * INTO ultimo FROM erp.movimentacoes_estoque WHERE tenant_id=saldo.tenant_id AND produto_id=saldo.produto_id AND local_estoque_id=saldo.local_estoque_id ORDER BY id DESC LIMIT 1;
  IF saldo.quantidade_fisica <> movimentos OR saldo.quantidade_reservada <> reservas
    OR (NOT negativo AND saldo.quantidade_fisica < saldo.quantidade_reservada)
    OR saldo.quantidade_fisica::text IN ('NaN','Infinity','-Infinity')
    OR saldo.custo_medio::text IN ('NaN','Infinity','-Infinity')
    OR (ultimo.id IS NOT NULL AND (ultimo.saldo_apos <> saldo.quantidade_fisica OR ultimo.custo_medio_apos <> saldo.custo_medio)) THEN
    RAISE EXCEPTION 'Saldo, movimentos ou reservas de estoque inconsistentes' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION erp.validar_saldo_estoque_final() FROM PUBLIC;
CREATE CONSTRAINT TRIGGER conferir_saldo_estoque AFTER INSERT OR UPDATE OR DELETE ON erp.saldos_estoque
 DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION erp.validar_saldo_estoque_final();
CREATE CONSTRAINT TRIGGER conferir_movimento_estoque AFTER INSERT ON erp.movimentacoes_estoque
 DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION erp.validar_saldo_estoque_final();
CREATE CONSTRAINT TRIGGER conferir_reserva_estoque AFTER INSERT OR UPDATE OR DELETE ON erp.reservas_estoque
 DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION erp.validar_saldo_estoque_final();

CREATE UNIQUE INDEX vendas_itens_venda_vinculo ON erp.vendas_itens(tenant_id,venda_id,id);
ALTER TABLE erp.reservas_estoque ADD CONSTRAINT reserva_item_da_venda
 FOREIGN KEY(tenant_id,venda_id,venda_item_id) REFERENCES erp.vendas_itens(tenant_id,venda_id,id);

-- Single-level kits match the reservation expansion. Direct DB writes obey the same rule.
CREATE FUNCTION erp.validar_kit_simples() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE raiz bigint;
BEGIN
  PERFORM pg_advisory_xact_lock(NEW.tenant_id::int, hashtext('erp-stock-ledger'));
  SELECT produto_id INTO raiz FROM erp.kits_produtos WHERE tenant_id=NEW.tenant_id AND id=NEW.kit_id;
  IF raiz=NEW.produto_componente_id OR EXISTS(SELECT 1 FROM erp.kits_produtos WHERE tenant_id=NEW.tenant_id AND produto_id=NEW.produto_componente_id AND ativo AND excluido_em IS NULL)
    OR EXISTS(SELECT 1 FROM erp.kits_produtos_itens i JOIN erp.kits_produtos k ON k.tenant_id=i.tenant_id AND k.id=i.kit_id WHERE i.tenant_id=NEW.tenant_id AND i.produto_componente_id=raiz AND k.ativo AND k.excluido_em IS NULL) THEN
    RAISE EXCEPTION 'Kits aninhados ou circulares nao permitidos' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION erp.validar_kit_simples() FROM PUBLIC;
CREATE TRIGGER validar_kit_simples BEFORE INSERT OR UPDATE ON erp.kits_produtos_itens FOR EACH ROW EXECUTE FUNCTION erp.validar_kit_simples();

CREATE FUNCTION erp.validar_ativacao_kit_simples() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(NEW.tenant_id::int,hashtext('erp-stock-ledger'));
 IF NEW.ativo AND NEW.excluido_em IS NULL AND (
   EXISTS(SELECT 1 FROM erp.kits_produtos_itens i JOIN erp.kits_produtos k ON k.tenant_id=i.tenant_id AND k.id=i.kit_id WHERE i.tenant_id=NEW.tenant_id AND i.produto_componente_id=NEW.produto_id AND k.ativo AND k.excluido_em IS NULL)
   OR EXISTS(SELECT 1 FROM erp.kits_produtos_itens i JOIN erp.kits_produtos k ON k.tenant_id=i.tenant_id AND k.produto_id=i.produto_componente_id WHERE i.tenant_id=NEW.tenant_id AND i.kit_id=NEW.id AND k.ativo AND k.excluido_em IS NULL)) THEN
   RAISE EXCEPTION 'Kits aninhados ou circulares nao permitidos' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION erp.validar_ativacao_kit_simples() FROM PUBLIC;
CREATE TRIGGER validar_ativacao_kit_simples BEFORE INSERT OR UPDATE ON erp.kits_produtos FOR EACH ROW EXECUTE FUNCTION erp.validar_ativacao_kit_simples();

CREATE OR REPLACE VIEW erp.vw_giro_estoque WITH (security_invoker=true) AS
SELECT p.tenant_id,p.produto_id,p.produto,p.local_estoque_id,p.local_estoque,p.quantidade_fisica,
 COALESCE(sum(abs(m.quantidade)) FILTER(WHERE m.quantidade<0 AND m.origem_tipo='venda' AND m.ocorrido_em>=now()-interval '90 days'),0) AS saidas_90_dias,
 CASE WHEN p.quantidade_fisica>0 THEN COALESCE(sum(abs(m.quantidade)) FILTER(WHERE m.quantidade<0 AND m.origem_tipo='venda' AND m.ocorrido_em>=now()-interval '90 days'),0)/p.quantidade_fisica ELSE 0 END AS giro_90_dias
FROM erp.vw_posicao_estoque p LEFT JOIN erp.movimentacoes_estoque m ON m.tenant_id=p.tenant_id AND m.produto_id=p.produto_id AND m.local_estoque_id=p.local_estoque_id
GROUP BY p.tenant_id,p.produto_id,p.produto,p.local_estoque_id,p.local_estoque,p.quantidade_fisica;

CREATE FUNCTION erp.travar_ledger_estoque() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$
DECLARE linha jsonb := CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
BEGIN
 PERFORM pg_advisory_xact_lock((linha->>'tenant_id')::int,hashtext('erp-stock-ledger'));
 IF TG_OP='UPDATE' AND TG_TABLE_NAME IN ('saldos_estoque','reservas_estoque') THEN
   IF ROW(OLD.tenant_id,OLD.produto_id,OLD.local_estoque_id) IS DISTINCT FROM ROW(NEW.tenant_id,NEW.produto_id,NEW.local_estoque_id) THEN
     RAISE EXCEPTION 'Vinculo de estoque imutavel' USING ERRCODE='23514';
   END IF;
 END IF;
 RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;
-- This trigger runs before the existing period check. Closures use the same lock.
CREATE TRIGGER a00_travar_ledger_estoque BEFORE INSERT OR UPDATE OR DELETE ON erp.saldos_estoque FOR EACH ROW EXECUTE FUNCTION erp.travar_ledger_estoque();
CREATE TRIGGER a00_travar_ledger_estoque BEFORE INSERT ON erp.movimentacoes_estoque FOR EACH ROW EXECUTE FUNCTION erp.travar_ledger_estoque();
CREATE TRIGGER a00_travar_ledger_estoque BEFORE INSERT OR UPDATE OR DELETE ON erp.reservas_estoque FOR EACH ROW EXECUTE FUNCTION erp.travar_ledger_estoque();
CREATE TRIGGER a00_travar_ledger_estoque BEFORE INSERT OR UPDATE OR DELETE ON erp.fechamentos_periodos FOR EACH ROW EXECUTE FUNCTION erp.travar_ledger_estoque();

-- Preserve every existing period rule; add the explicit operational date first.
DO $$ DECLARE definition text;
BEGIN
 definition:=pg_get_functiondef('erp.validar_periodo_operacional_aberto()'::regprocedure);
 IF position('data_operacao := COALESCE(' in definition)=0 THEN RAISE EXCEPTION 'Definicao de periodo inesperada'; END IF;
 definition:=replace(definition,'data_operacao := COALESCE(', 'data_operacao := COALESCE((payload ->> ''data_operacional'')::date,');
 EXECUTE definition;
END $$;

COMMIT;
