BEGIN;

CREATE TABLE IF NOT EXISTS shared.ai_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES shared.users (id) ON DELETE CASCADE,
  clerk_client_id text NOT NULL,
  provider text NOT NULL DEFAULT 'other',
  client_name text,
  scopes text[] NOT NULL DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'active',
  write_enabled boolean NOT NULL DEFAULT false,
  connected_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  revoked_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ai_connections_identity_key UNIQUE (tenant_id, user_id, clerk_client_id),
  CONSTRAINT ai_connections_provider_chk CHECK (provider IN ('chatgpt', 'claude', 'cli', 'other')),
  CONSTRAINT ai_connections_status_chk CHECK (status IN ('active', 'suspended', 'revoked')),
  CONSTRAINT ai_connections_metadata_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS shared.ai_tool_executions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE CASCADE,
  user_id bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  connection_id bigint REFERENCES shared.ai_connections (id) ON DELETE SET NULL,
  tool_name text NOT NULL,
  tool_version text NOT NULL DEFAULT '1',
  source text NOT NULL,
  risk text NOT NULL,
  status text NOT NULL DEFAULT 'started',
  correlation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key text,
  input_redacted jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_summary jsonb,
  error_code text,
  error_message text,
  duration_ms integer,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  CONSTRAINT ai_tool_executions_source_chk CHECK (source IN ('cli', 'mcp', 'web', 'automation')),
  CONSTRAINT ai_tool_executions_risk_chk CHECK (risk IN ('read', 'write-low', 'write-medium', 'write-critical')),
  CONSTRAINT ai_tool_executions_status_chk CHECK (status IN ('started', 'succeeded', 'failed', 'denied')),
  CONSTRAINT ai_tool_executions_input_chk CHECK (jsonb_typeof(input_redacted) = 'object'),
  CONSTRAINT ai_tool_executions_output_chk CHECK (output_summary IS NULL OR jsonb_typeof(output_summary) = 'object')
);

CREATE TABLE IF NOT EXISTS shared.ai_action_approvals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE CASCADE,
  requested_by bigint NOT NULL REFERENCES shared.users (id) ON DELETE RESTRICT,
  approved_by bigint REFERENCES shared.users (id) ON DELETE RESTRICT,
  connection_id bigint REFERENCES shared.ai_connections (id) ON DELETE SET NULL,
  tool_name text NOT NULL,
  payload jsonb NOT NULL,
  payload_hash text NOT NULL,
  preview jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  expires_at timestamptz NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  decided_at timestamptz,
  consumed_at timestamptz,
  decision_reason text,
  CONSTRAINT ai_action_approvals_status_chk CHECK (status IN ('pending', 'approved', 'rejected', 'expired', 'processing', 'consumed')),
  CONSTRAINT ai_action_approvals_payload_chk CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT ai_action_approvals_preview_chk CHECK (jsonb_typeof(preview) = 'object')
);

CREATE INDEX IF NOT EXISTS ai_connections_tenant_status_idx
  ON shared.ai_connections (tenant_id, status, last_used_at DESC);
CREATE INDEX IF NOT EXISTS ai_tool_executions_tenant_started_idx
  ON shared.ai_tool_executions (tenant_id, started_at DESC);
CREATE INDEX IF NOT EXISTS ai_tool_executions_correlation_idx
  ON shared.ai_tool_executions (correlation_id);
CREATE INDEX IF NOT EXISTS ai_action_approvals_pending_idx
  ON shared.ai_action_approvals (tenant_id, status, expires_at);

ALTER TABLE shared.ai_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared.ai_tool_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared.ai_action_approvals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ai_connections_select ON shared.ai_connections;
CREATE POLICY ai_connections_select ON shared.ai_connections FOR SELECT
  USING (shared.is_tenant_member(tenant_id));
DROP POLICY IF EXISTS ai_connections_manage ON shared.ai_connections;
CREATE POLICY ai_connections_manage ON shared.ai_connections FOR ALL
  USING (shared.has_tenant_role(tenant_id, ARRAY['owner', 'admin']))
  WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY['owner', 'admin']));

DROP POLICY IF EXISTS ai_tool_executions_select ON shared.ai_tool_executions;
CREATE POLICY ai_tool_executions_select ON shared.ai_tool_executions FOR SELECT
  USING (shared.is_tenant_member(tenant_id));

DROP POLICY IF EXISTS ai_action_approvals_select ON shared.ai_action_approvals;
CREATE POLICY ai_action_approvals_select ON shared.ai_action_approvals FOR SELECT
  USING (shared.is_tenant_member(tenant_id));
DROP POLICY IF EXISTS ai_action_approvals_manage ON shared.ai_action_approvals;
CREATE POLICY ai_action_approvals_manage ON shared.ai_action_approvals FOR ALL
  USING (shared.has_tenant_role(tenant_id, ARRAY['owner', 'admin']))
  WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY['owner', 'admin']));

COMMENT ON TABLE shared.ai_connections IS 'Conexoes OAuth de clientes MCP autorizadas por usuario e organizacao.';
COMMENT ON TABLE shared.ai_tool_executions IS 'Auditoria sanitizada de todas as ferramentas da AI Platform.';
COMMENT ON TABLE shared.ai_action_approvals IS 'Aprovacoes humanas obrigatorias para operacoes criticas iniciadas por IA.';

COMMIT;
