BEGIN;

CREATE SCHEMA IF NOT EXISTS shared;

CREATE TABLE IF NOT EXISTS shared.tenants (
  id bigserial PRIMARY KEY,
  name text NOT NULL,
  slug text UNIQUE,
  status text NOT NULL DEFAULT 'active',
  clerk_organization_id text UNIQUE,
  clerk_organization_slug text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenants_status_chk CHECK (status IN ('active', 'suspended', 'disabled')),
  CONSTRAINT tenants_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS shared.users (
  id bigserial PRIMARY KEY,
  email varchar NOT NULL,
  password_hash varchar NOT NULL DEFAULT '',
  full_name varchar,
  auth_user_id uuid UNIQUE,
  clerk_user_id text UNIQUE,
  avatar_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

DO $$
BEGIN
  IF to_regclass('auth.users') IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'users_auth_user_fkey'
        AND conrelid = 'shared.users'::regclass
    )
  THEN
    ALTER TABLE shared.users
      ADD CONSTRAINT users_auth_user_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES auth.users (id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS users_email_idx
  ON shared.users (lower(email::text));

CREATE TABLE IF NOT EXISTS shared.tenant_memberships (
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES shared.users (id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  status text NOT NULL DEFAULT 'active',
  clerk_organization_id text,
  clerk_membership_id text,
  clerk_role text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, user_id),
  CONSTRAINT tenant_memberships_role_chk CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
  CONSTRAINT tenant_memberships_status_chk CHECK (status IN ('active', 'invited', 'suspended')),
  CONSTRAINT tenant_memberships_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS tenant_memberships_user_idx
  ON shared.tenant_memberships (user_id, status);

CREATE INDEX IF NOT EXISTS tenant_memberships_tenant_role_idx
  ON shared.tenant_memberships (tenant_id, role, status);

CREATE OR REPLACE FUNCTION shared.current_auth_user_id()
RETURNS uuid
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  claim_sub text;
BEGIN
  claim_sub := nullif(current_setting('request.jwt.claim.sub', true), '');
  IF claim_sub IS NULL THEN
    RETURN NULL;
  END IF;

  RETURN claim_sub::uuid;
EXCEPTION
  WHEN invalid_text_representation THEN
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION shared.current_user_id()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT users.id
  FROM shared.users AS users
  WHERE users.auth_user_id = shared.current_auth_user_id()
  LIMIT 1
$$;

CREATE OR REPLACE FUNCTION shared.is_tenant_member(input_tenant_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM shared.tenant_memberships AS memberships
    WHERE memberships.tenant_id = input_tenant_id
      AND memberships.user_id = shared.current_user_id()
      AND memberships.status = 'active'
  )
$$;

CREATE OR REPLACE FUNCTION shared.has_tenant_role(input_tenant_id bigint, allowed_roles text[])
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM shared.tenant_memberships AS memberships
    WHERE memberships.tenant_id = input_tenant_id
      AND memberships.user_id = shared.current_user_id()
      AND memberships.status = 'active'
      AND memberships.role = ANY(allowed_roles)
  )
$$;

CREATE SCHEMA IF NOT EXISTS erp;

CREATE OR REPLACE FUNCTION erp.set_atualizado_em()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.atualizado_em = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS erp.entidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo_pessoa text NOT NULL DEFAULT 'juridica',
  nome text NOT NULL,
  nome_fantasia text,
  codigo text,
  documento text,
  rg text,
  inscricao_estadual text,
  inscricao_municipal text,
  inscricao_suframa text,
  indicador_inscricao_estadual text,
  data_nascimento date,
  email text,
  telefone text,
  celular text,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  uf text,
  pais text NOT NULL DEFAULT 'Brasil',
  contato_cobranca_emails text[] NOT NULL DEFAULT ARRAY[]::text[],
  contato_cobranca_whatsapp text,
  optante_simples boolean NOT NULL DEFAULT false,
  orgao_publico boolean NOT NULL DEFAULT false,
  eh_cliente boolean NOT NULL DEFAULT false,
  eh_fornecedor boolean NOT NULL DEFAULT false,
  eh_transportadora boolean NOT NULL DEFAULT false,
  eh_vendedor boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT entidades_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT entidades_tipo_pessoa_chk CHECK (tipo_pessoa IN ('fisica', 'juridica', 'estrangeira')),
  CONSTRAINT entidades_indicador_ie_chk CHECK (
    indicador_inscricao_estadual IS NULL
    OR indicador_inscricao_estadual IN ('contribuinte', 'contribuinte_isento', 'nao_contribuinte')
  ),
  CONSTRAINT entidades_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT entidades_papel_chk CHECK (
    eh_cliente OR eh_fornecedor OR eh_transportadora OR eh_vendedor
  )
);

CREATE TABLE IF NOT EXISTS erp.categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text,
  tipo text NOT NULL DEFAULT 'geral',
  categoria_pai_id bigint,
  entrada_dre boolean NOT NULL DEFAULT false,
  considera_custo_dre boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT categorias_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT categorias_tipo_chk CHECK (tipo IN ('receita', 'despesa', 'produto', 'servico', 'geral')),
  CONSTRAINT categorias_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT categorias_pai_fk FOREIGN KEY (tenant_id, categoria_pai_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.centros_custo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT centros_custo_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT centros_custo_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.contas_financeiras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'banco',
  banco text,
  agencia text,
  conta text,
  digito text,
  saldo_inicial numeric(18,2) NOT NULL DEFAULT 0,
  data_saldo_inicial date,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_financeiras_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_financeiras_tipo_chk CHECK (tipo IN ('caixa', 'banco', 'carteira', 'cartao', 'outro')),
  CONSTRAINT contas_financeiras_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.metodos_pagamento (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'outro',
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT metodos_pagamento_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT metodos_pagamento_tipo_chk CHECK (
    tipo IN ('pix', 'boleto', 'dinheiro', 'cartao_credito', 'cartao_debito', 'transferencia', 'deposito', 'cheque', 'outro')
  ),
  CONSTRAINT metodos_pagamento_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text,
  sku text,
  codigo_barras text,
  descricao text,
  unidade_medida text,
  preco_venda numeric(18,2) NOT NULL DEFAULT 0,
  custo numeric(18,2) NOT NULL DEFAULT 0,
  categoria_id bigint,
  centro_custo_id bigint,
  formato text NOT NULL DEFAULT 'simples',
  ncm text,
  cest text,
  origem text,
  tipo_produto text,
  peso_bruto numeric(18,3),
  peso_liquido numeric(18,3),
  altura numeric(18,3),
  largura numeric(18,3),
  profundidade numeric(18,3),
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT produtos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT produtos_formato_chk CHECK (formato IN ('simples', 'variacao')),
  CONSTRAINT produtos_valores_chk CHECK (
    preco_venda >= 0
    AND custo >= 0
    AND (peso_bruto IS NULL OR peso_bruto >= 0)
    AND (peso_liquido IS NULL OR peso_liquido >= 0)
    AND (altura IS NULL OR altura >= 0)
    AND (largura IS NULL OR largura >= 0)
    AND (profundidade IS NULL OR profundidade >= 0)
  ),
  CONSTRAINT produtos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT produtos_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT produtos_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.servicos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text,
  descricao text,
  preco numeric(18,2) NOT NULL DEFAULT 0,
  custo numeric(18,2) NOT NULL DEFAULT 0,
  categoria_id bigint,
  centro_custo_id bigint,
  codigo_servico_municipal text,
  tipo_servico text,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT servicos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT servicos_valores_chk CHECK (preco >= 0 AND custo >= 0),
  CONSTRAINT servicos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT servicos_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT servicos_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.vendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  cliente_id bigint NOT NULL,
  vendedor_id bigint,
  numero text NOT NULL,
  data_venda date NOT NULL DEFAULT CURRENT_DATE,
  data_competencia date,
  status text NOT NULL DEFAULT 'rascunho',
  situacao text,
  origem text,
  categoria_id bigint,
  centro_custo_id bigint,
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  subtotal numeric(18,2) NOT NULL DEFAULT 0,
  tipo_desconto text,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  frete numeric(18,2) NOT NULL DEFAULT 0,
  total numeric(18,2) NOT NULL DEFAULT 0,
  condicao_pagamento jsonb NOT NULL DEFAULT '{}'::jsonb,
  nsu text,
  observacoes text,
  observacoes_pagamento text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT vendas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT vendas_status_chk CHECK (status IN ('rascunho', 'aprovada', 'cancelada', 'faturada')),
  CONSTRAINT vendas_tipo_desconto_chk CHECK (tipo_desconto IS NULL OR tipo_desconto IN ('valor', 'percentual')),
  CONSTRAINT vendas_valores_chk CHECK (subtotal >= 0 AND desconto >= 0 AND frete >= 0 AND total >= 0),
  CONSTRAINT vendas_condicao_pagamento_object_chk CHECK (jsonb_typeof(condicao_pagamento) = 'object'),
  CONSTRAINT vendas_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT vendas_cliente_fk FOREIGN KEY (tenant_id, cliente_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_vendedor_fk FOREIGN KEY (tenant_id, vendedor_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.vendas_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  venda_id bigint NOT NULL,
  produto_id bigint,
  servico_id bigint,
  descricao text NOT NULL,
  quantidade numeric(18,4) NOT NULL DEFAULT 1,
  valor_unitario numeric(18,4) NOT NULL DEFAULT 0,
  custo_unitario numeric(18,4) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  total numeric(18,2) NOT NULL DEFAULT 0,
  centro_custo_id bigint,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT vendas_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT vendas_itens_origem_chk CHECK (
    (produto_id IS NOT NULL AND servico_id IS NULL)
    OR (produto_id IS NULL AND servico_id IS NOT NULL)
  ),
  CONSTRAINT vendas_itens_valores_chk CHECK (
    quantidade > 0 AND valor_unitario >= 0 AND custo_unitario >= 0 AND desconto >= 0 AND total >= 0
  ),
  CONSTRAINT vendas_itens_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT vendas_itens_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT vendas_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_itens_servico_fk FOREIGN KEY (tenant_id, servico_id)
    REFERENCES erp.servicos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT vendas_itens_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.compras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  fornecedor_id bigint NOT NULL,
  numero text,
  data_compra date NOT NULL DEFAULT CURRENT_DATE,
  data_competencia date,
  status text NOT NULL DEFAULT 'rascunho',
  categoria_id bigint,
  centro_custo_id bigint,
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  subtotal numeric(18,2) NOT NULL DEFAULT 0,
  tipo_desconto text,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  frete numeric(18,2) NOT NULL DEFAULT 0,
  total numeric(18,2) NOT NULL DEFAULT 0,
  condicao_pagamento jsonb NOT NULL DEFAULT '{}'::jsonb,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_status_chk CHECK (status IN ('rascunho', 'aprovada', 'cancelada', 'recebida')),
  CONSTRAINT compras_tipo_desconto_chk CHECK (tipo_desconto IS NULL OR tipo_desconto IN ('valor', 'percentual')),
  CONSTRAINT compras_valores_chk CHECK (subtotal >= 0 AND desconto >= 0 AND frete >= 0 AND total >= 0),
  CONSTRAINT compras_condicao_pagamento_object_chk CHECK (jsonb_typeof(condicao_pagamento) = 'object'),
  CONSTRAINT compras_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_fornecedor_fk FOREIGN KEY (tenant_id, fornecedor_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.compras_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  compra_id bigint NOT NULL,
  produto_id bigint,
  servico_id bigint,
  descricao text NOT NULL,
  quantidade numeric(18,4) NOT NULL DEFAULT 1,
  valor_unitario numeric(18,4) NOT NULL DEFAULT 0,
  total numeric(18,2) NOT NULL DEFAULT 0,
  centro_custo_id bigint,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_itens_origem_chk CHECK (
    (produto_id IS NOT NULL AND servico_id IS NULL)
    OR (produto_id IS NULL AND servico_id IS NOT NULL)
  ),
  CONSTRAINT compras_itens_valores_chk CHECK (quantidade > 0 AND valor_unitario >= 0 AND total >= 0),
  CONSTRAINT compras_itens_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_itens_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT compras_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_itens_servico_fk FOREIGN KEY (tenant_id, servico_id)
    REFERENCES erp.servicos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_itens_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contas_receber (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  cliente_id bigint NOT NULL,
  venda_id bigint,
  descricao text NOT NULL,
  numero_documento text,
  data_competencia date,
  data_emissao date NOT NULL DEFAULT CURRENT_DATE,
  valor_total numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'aberto',
  categoria_id bigint,
  centro_custo_id bigint,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_receber_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_receber_status_chk CHECK (status IN ('aberto', 'parcial', 'pago', 'cancelado', 'vencido')),
  CONSTRAINT contas_receber_valor_chk CHECK (valor_total >= 0),
  CONSTRAINT contas_receber_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contas_receber_cliente_fk FOREIGN KEY (tenant_id, cliente_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_receber_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_receber_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_receber_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contas_receber_parcelas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_receber_id bigint NOT NULL,
  numero_parcela integer NOT NULL DEFAULT 1,
  codigo_referencia text,
  descricao text,
  data_vencimento date NOT NULL,
  data_pagamento_previsto date,
  data_pagamento date,
  valor numeric(18,2) NOT NULL DEFAULT 0,
  valor_bruto numeric(18,2) NOT NULL DEFAULT 0,
  valor_liquido numeric(18,2) NOT NULL DEFAULT 0,
  valor_pago numeric(18,2) NOT NULL DEFAULT 0,
  juros numeric(18,2) NOT NULL DEFAULT 0,
  multa numeric(18,2) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  taxa numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'aberto',
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  nsu text,
  conciliado boolean NOT NULL DEFAULT false,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_receber_parcelas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_receber_parcelas_status_chk CHECK (status IN ('aberto', 'parcial', 'pago', 'cancelado', 'vencido')),
  CONSTRAINT contas_receber_parcelas_valores_chk CHECK (
    numero_parcela > 0
    AND valor >= 0
    AND valor_bruto >= 0
    AND valor_liquido >= 0
    AND valor_pago >= 0
    AND juros >= 0
    AND multa >= 0
    AND desconto >= 0
    AND taxa >= 0
  ),
  CONSTRAINT contas_receber_parcelas_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contas_receber_parcelas_conta_fk FOREIGN KEY (tenant_id, conta_receber_id)
    REFERENCES erp.contas_receber (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT contas_receber_parcelas_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_receber_parcelas_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contas_pagar (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  fornecedor_id bigint NOT NULL,
  compra_id bigint,
  descricao text NOT NULL,
  numero_documento text,
  data_competencia date,
  data_emissao date NOT NULL DEFAULT CURRENT_DATE,
  valor_total numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'aberto',
  categoria_id bigint,
  centro_custo_id bigint,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_pagar_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_pagar_status_chk CHECK (status IN ('aberto', 'parcial', 'pago', 'cancelado', 'vencido')),
  CONSTRAINT contas_pagar_valor_chk CHECK (valor_total >= 0),
  CONSTRAINT contas_pagar_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contas_pagar_fornecedor_fk FOREIGN KEY (tenant_id, fornecedor_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_pagar_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_pagar_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_pagar_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.contas_pagar_parcelas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_pagar_id bigint NOT NULL,
  numero_parcela integer NOT NULL DEFAULT 1,
  codigo_referencia text,
  descricao text,
  data_vencimento date NOT NULL,
  data_pagamento_previsto date,
  data_pagamento date,
  valor numeric(18,2) NOT NULL DEFAULT 0,
  valor_bruto numeric(18,2) NOT NULL DEFAULT 0,
  valor_liquido numeric(18,2) NOT NULL DEFAULT 0,
  valor_pago numeric(18,2) NOT NULL DEFAULT 0,
  juros numeric(18,2) NOT NULL DEFAULT 0,
  multa numeric(18,2) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  taxa numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'aberto',
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  nsu text,
  conciliado boolean NOT NULL DEFAULT false,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_pagar_parcelas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_pagar_parcelas_status_chk CHECK (status IN ('aberto', 'parcial', 'pago', 'cancelado', 'vencido')),
  CONSTRAINT contas_pagar_parcelas_valores_chk CHECK (
    numero_parcela > 0
    AND valor >= 0
    AND valor_bruto >= 0
    AND valor_liquido >= 0
    AND valor_pago >= 0
    AND juros >= 0
    AND multa >= 0
    AND desconto >= 0
    AND taxa >= 0
  ),
  CONSTRAINT contas_pagar_parcelas_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contas_pagar_parcelas_conta_fk FOREIGN KEY (tenant_id, conta_pagar_id)
    REFERENCES erp.contas_pagar (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT contas_pagar_parcelas_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT contas_pagar_parcelas_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.pagamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo text NOT NULL,
  conta_receber_parcela_id bigint,
  conta_pagar_parcela_id bigint,
  conta_financeira_id bigint NOT NULL,
  metodo_pagamento_id bigint,
  data_pagamento date NOT NULL,
  data_credito date,
  valor numeric(18,2) NOT NULL DEFAULT 0,
  juros numeric(18,2) NOT NULL DEFAULT 0,
  multa numeric(18,2) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  taxa numeric(18,2) NOT NULL DEFAULT 0,
  valor_liquido numeric(18,2) NOT NULL DEFAULT 0,
  nsu text,
  conciliado boolean NOT NULL DEFAULT false,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT pagamentos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT pagamentos_tipo_chk CHECK (tipo IN ('receber', 'pagar')),
  CONSTRAINT pagamentos_origem_chk CHECK (
    (tipo = 'receber' AND conta_receber_parcela_id IS NOT NULL AND conta_pagar_parcela_id IS NULL)
    OR (tipo = 'pagar' AND conta_pagar_parcela_id IS NOT NULL AND conta_receber_parcela_id IS NULL)
  ),
  CONSTRAINT pagamentos_valores_chk CHECK (
    valor >= 0 AND juros >= 0 AND multa >= 0 AND desconto >= 0 AND taxa >= 0 AND valor_liquido >= 0
  ),
  CONSTRAINT pagamentos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT pagamentos_conta_receber_parcela_fk FOREIGN KEY (tenant_id, conta_receber_parcela_id)
    REFERENCES erp.contas_receber_parcelas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT pagamentos_conta_pagar_parcela_fk FOREIGN KEY (tenant_id, conta_pagar_parcela_id)
    REFERENCES erp.contas_pagar_parcelas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT pagamentos_conta_financeira_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT pagamentos_metodo_pagamento_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.transferencias_financeiras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_origem_id bigint NOT NULL,
  conta_destino_id bigint NOT NULL,
  data_transferencia date NOT NULL DEFAULT CURRENT_DATE,
  valor numeric(18,2) NOT NULL DEFAULT 0,
  descricao text,
  status text NOT NULL DEFAULT 'pendente',
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT transferencias_financeiras_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT transferencias_financeiras_status_chk CHECK (status IN ('pendente', 'concluida', 'cancelada')),
  CONSTRAINT transferencias_financeiras_valor_chk CHECK (valor > 0),
  CONSTRAINT transferencias_financeiras_contas_diferentes_chk CHECK (conta_origem_id <> conta_destino_id),
  CONSTRAINT transferencias_financeiras_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT transferencias_financeiras_conta_origem_fk FOREIGN KEY (tenant_id, conta_origem_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT transferencias_financeiras_conta_destino_fk FOREIGN KEY (tenant_id, conta_destino_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.rateios_financeiros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo text NOT NULL,
  conta_receber_id bigint,
  conta_pagar_id bigint,
  categoria_id bigint,
  centro_custo_id bigint,
  valor numeric(18,2),
  percentual numeric(9,4),
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT rateios_financeiros_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT rateios_financeiros_tipo_chk CHECK (tipo IN ('receber', 'pagar')),
  CONSTRAINT rateios_financeiros_origem_chk CHECK (
    (tipo = 'receber' AND conta_receber_id IS NOT NULL AND conta_pagar_id IS NULL)
    OR (tipo = 'pagar' AND conta_pagar_id IS NOT NULL AND conta_receber_id IS NULL)
  ),
  CONSTRAINT rateios_financeiros_dimensao_chk CHECK (categoria_id IS NOT NULL OR centro_custo_id IS NOT NULL),
  CONSTRAINT rateios_financeiros_valor_chk CHECK (
    (valor IS NOT NULL OR percentual IS NOT NULL)
    AND (valor IS NULL OR valor >= 0)
    AND (percentual IS NULL OR (percentual >= 0 AND percentual <= 100))
  ),
  CONSTRAINT rateios_financeiros_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT rateios_financeiros_conta_receber_fk FOREIGN KEY (tenant_id, conta_receber_id)
    REFERENCES erp.contas_receber (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT rateios_financeiros_conta_pagar_fk FOREIGN KEY (tenant_id, conta_pagar_id)
    REFERENCES erp.contas_pagar (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT rateios_financeiros_categoria_fk FOREIGN KEY (tenant_id, categoria_id)
    REFERENCES erp.categorias (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT rateios_financeiros_centro_custo_fk FOREIGN KEY (tenant_id, centro_custo_id)
    REFERENCES erp.centros_custo (tenant_id, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS entidades_documento_unico_idx
  ON erp.entidades (tenant_id, documento)
  WHERE documento IS NOT NULL AND documento <> '' AND excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS entidades_codigo_unico_idx
  ON erp.entidades (tenant_id, codigo)
  WHERE codigo IS NOT NULL AND codigo <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS entidades_tenant_nome_idx
  ON erp.entidades (tenant_id, nome);

CREATE INDEX IF NOT EXISTS entidades_papeis_idx
  ON erp.entidades (tenant_id, eh_cliente, eh_fornecedor, eh_transportadora, eh_vendedor)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS categorias_codigo_unico_idx
  ON erp.categorias (tenant_id, codigo)
  WHERE codigo IS NOT NULL AND codigo <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS categorias_tenant_tipo_idx
  ON erp.categorias (tenant_id, tipo)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS centros_custo_codigo_unico_idx
  ON erp.centros_custo (tenant_id, codigo)
  WHERE codigo IS NOT NULL AND codigo <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_financeiras_tenant_tipo_idx
  ON erp.contas_financeiras (tenant_id, tipo)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS metodos_pagamento_tenant_tipo_idx
  ON erp.metodos_pagamento (tenant_id, tipo)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS produtos_codigo_unico_idx
  ON erp.produtos (tenant_id, codigo)
  WHERE codigo IS NOT NULL AND codigo <> '' AND excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS produtos_sku_unico_idx
  ON erp.produtos (tenant_id, sku)
  WHERE sku IS NOT NULL AND sku <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS produtos_tenant_nome_idx
  ON erp.produtos (tenant_id, nome)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS servicos_codigo_unico_idx
  ON erp.servicos (tenant_id, codigo)
  WHERE codigo IS NOT NULL AND codigo <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS servicos_tenant_nome_idx
  ON erp.servicos (tenant_id, nome)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS vendas_numero_unico_idx
  ON erp.vendas (tenant_id, numero)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS vendas_cliente_data_idx
  ON erp.vendas (tenant_id, cliente_id, data_venda DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS vendas_status_data_idx
  ON erp.vendas (tenant_id, status, data_venda DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS vendas_itens_venda_idx
  ON erp.vendas_itens (tenant_id, venda_id)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS compras_numero_unico_idx
  ON erp.compras (tenant_id, numero)
  WHERE numero IS NOT NULL AND numero <> '' AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS compras_fornecedor_data_idx
  ON erp.compras (tenant_id, fornecedor_id, data_compra DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS compras_status_data_idx
  ON erp.compras (tenant_id, status, data_compra DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS compras_itens_compra_idx
  ON erp.compras_itens (tenant_id, compra_id)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_receber_cliente_status_idx
  ON erp.contas_receber (tenant_id, cliente_id, status)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_receber_data_emissao_idx
  ON erp.contas_receber (tenant_id, data_emissao DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_receber_parcelas_vencimento_idx
  ON erp.contas_receber_parcelas (tenant_id, data_vencimento, status)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_receber_parcelas_conta_idx
  ON erp.contas_receber_parcelas (tenant_id, conta_receber_id)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_pagar_fornecedor_status_idx
  ON erp.contas_pagar (tenant_id, fornecedor_id, status)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_pagar_data_emissao_idx
  ON erp.contas_pagar (tenant_id, data_emissao DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_pagar_parcelas_vencimento_idx
  ON erp.contas_pagar_parcelas (tenant_id, data_vencimento, status)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_pagar_parcelas_conta_idx
  ON erp.contas_pagar_parcelas (tenant_id, conta_pagar_id)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS pagamentos_data_idx
  ON erp.pagamentos (tenant_id, data_pagamento DESC, tipo)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS pagamentos_conta_financeira_idx
  ON erp.pagamentos (tenant_id, conta_financeira_id, data_pagamento DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS transferencias_financeiras_data_idx
  ON erp.transferencias_financeiras (tenant_id, data_transferencia DESC, status)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS rateios_financeiros_receber_idx
  ON erp.rateios_financeiros (tenant_id, conta_receber_id)
  WHERE conta_receber_id IS NOT NULL AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS rateios_financeiros_pagar_idx
  ON erp.rateios_financeiros (tenant_id, conta_pagar_id)
  WHERE conta_pagar_id IS NOT NULL AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS rateios_financeiros_categoria_centro_idx
  ON erp.rateios_financeiros (tenant_id, categoria_id, centro_custo_id)
  WHERE excluido_em IS NULL;

DO $$
DECLARE
  table_name text;
  table_names text[] := ARRAY[
    'entidades',
    'categorias',
    'centros_custo',
    'contas_financeiras',
    'metodos_pagamento',
    'produtos',
    'servicos',
    'vendas',
    'vendas_itens',
    'compras',
    'compras_itens',
    'contas_receber',
    'contas_receber_parcelas',
    'contas_pagar',
    'contas_pagar_parcelas',
    'pagamentos',
    'transferencias_financeiras',
    'rateios_financeiros'
  ];
BEGIN
  FOREACH table_name IN ARRAY table_names LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_atualizado_em ON erp.%I', table_name);
    EXECUTE format(
      'CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()',
      table_name
    );

    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', table_name);

    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_select_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_insert_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_update_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_delete_policy', table_name);

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))',
      table_name || '_select_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))',
      table_name || '_insert_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR UPDATE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member''])) WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))',
      table_name || '_update_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR DELETE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'']))',
      table_name || '_delete_policy',
      table_name
    );
  END LOOP;
END $$;

GRANT USAGE ON SCHEMA erp TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA erp TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO authenticated, service_role;

COMMENT ON SCHEMA erp IS 'ERP operacional proprio: cadastros, vendas, compras e financeiro.';
COMMENT ON TABLE erp.entidades IS 'Clientes, fornecedores, transportadoras e vendedores do ERP.';
COMMENT ON TABLE erp.rateios_financeiros IS 'Rateios financeiros por categoria e centro de custo.';

COMMIT;
