BEGIN;

CREATE TABLE IF NOT EXISTS erp.configuracoes_fiscais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  cnpj text NOT NULL,
  razao_social text NOT NULL,
  nome_fantasia text,
  inscricao_estadual text,
  inscricao_municipal text,
  regime_tributario text NOT NULL DEFAULT 'simples_nacional',
  ambiente text NOT NULL DEFAULT 'homologacao',
  provedor text NOT NULL DEFAULT 'focus_nfe',
  focus_empresa_ref text,
  token_secret_ref text,
  endereco_logradouro text,
  endereco_numero text,
  endereco_complemento text,
  endereco_bairro text,
  endereco_codigo_municipio text,
  endereco_municipio text,
  endereco_uf text,
  endereco_cep text,
  endereco_pais text NOT NULL DEFAULT 'BR',
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT configuracoes_fiscais_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT configuracoes_fiscais_regime_chk CHECK (
    regime_tributario IN ('simples_nacional', 'simples_nacional_excesso', 'lucro_presumido', 'lucro_real', 'mei', 'outro')
  ),
  CONSTRAINT configuracoes_fiscais_ambiente_chk CHECK (ambiente IN ('homologacao', 'producao')),
  CONSTRAINT configuracoes_fiscais_provedor_chk CHECK (provedor IN ('focus_nfe')),
  CONSTRAINT configuracoes_fiscais_uf_chk CHECK (endereco_uf IS NULL OR endereco_uf ~ '^[A-Z]{2}$'),
  CONSTRAINT configuracoes_fiscais_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.notas_fiscais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  venda_id bigint,
  compra_id bigint,
  entidade_id bigint NOT NULL,
  configuracao_fiscal_id bigint,
  tipo text NOT NULL DEFAULT 'nfe',
  direcao text NOT NULL DEFAULT 'saida',
  finalidade text NOT NULL DEFAULT 'normal',
  natureza_operacao text,
  ref_focus text NOT NULL,
  status text NOT NULL DEFAULT 'rascunho',
  numero text,
  serie text,
  chave_acesso text,
  protocolo text,
  valor_produtos numeric(18,2) NOT NULL DEFAULT 0,
  valor_servicos numeric(18,2) NOT NULL DEFAULT 0,
  valor_total numeric(18,2) NOT NULL DEFAULT 0,
  xml_url text,
  pdf_url text,
  danfe_url text,
  payload_enviado jsonb NOT NULL DEFAULT '{}'::jsonb,
  resposta_focus jsonb NOT NULL DEFAULT '{}'::jsonb,
  erro_codigo text,
  erro_mensagem text,
  emitida_em timestamptz,
  autorizada_em timestamptz,
  cancelada_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT notas_fiscais_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT notas_fiscais_tipo_chk CHECK (tipo IN ('nfe', 'nfce', 'nfse')),
  CONSTRAINT notas_fiscais_direcao_chk CHECK (direcao IN ('saida', 'entrada')),
  CONSTRAINT notas_fiscais_finalidade_chk CHECK (finalidade IN ('normal', 'complementar', 'ajuste', 'devolucao')),
  CONSTRAINT notas_fiscais_status_chk CHECK (
    status IN ('rascunho', 'pronta_envio', 'aguardando_retorno', 'emitida', 'falha', 'cancelada', 'denegada', 'corrigida')
  ),
  CONSTRAINT notas_fiscais_valores_chk CHECK (valor_produtos >= 0 AND valor_servicos >= 0 AND valor_total >= 0),
  CONSTRAINT notas_fiscais_payload_object_chk CHECK (jsonb_typeof(payload_enviado) = 'object'),
  CONSTRAINT notas_fiscais_resposta_object_chk CHECK (jsonb_typeof(resposta_focus) = 'object'),
  CONSTRAINT notas_fiscais_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT notas_fiscais_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_entidade_fk FOREIGN KEY (tenant_id, entidade_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_configuracao_fk FOREIGN KEY (tenant_id, configuracao_fiscal_id)
    REFERENCES erp.configuracoes_fiscais (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.notas_fiscais_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nota_fiscal_id bigint NOT NULL,
  venda_item_id bigint,
  compra_item_id bigint,
  produto_id bigint,
  servico_id bigint,
  tipo_item text NOT NULL DEFAULT 'produto',
  descricao text NOT NULL,
  quantidade numeric(18,4) NOT NULL DEFAULT 1,
  valor_unitario numeric(18,4) NOT NULL DEFAULT 0,
  valor_total numeric(18,2) NOT NULL DEFAULT 0,
  ncm text,
  cfop text,
  cst text,
  csosn text,
  codigo_servico_municipal text,
  aliquota_iss numeric(9,4),
  payload_item jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT notas_fiscais_itens_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT notas_fiscais_itens_tipo_chk CHECK (tipo_item IN ('produto', 'servico')),
  CONSTRAINT notas_fiscais_itens_origem_chk CHECK (
    (produto_id IS NULL OR servico_id IS NULL)
    AND (venda_item_id IS NULL OR compra_item_id IS NULL)
  ),
  CONSTRAINT notas_fiscais_itens_valores_chk CHECK (
    quantidade > 0
    AND valor_unitario >= 0
    AND valor_total >= 0
    AND (aliquota_iss IS NULL OR aliquota_iss >= 0)
  ),
  CONSTRAINT notas_fiscais_itens_payload_object_chk CHECK (jsonb_typeof(payload_item) = 'object'),
  CONSTRAINT notas_fiscais_itens_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT notas_fiscais_itens_nota_fk FOREIGN KEY (tenant_id, nota_fiscal_id)
    REFERENCES erp.notas_fiscais (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT notas_fiscais_itens_venda_item_fk FOREIGN KEY (tenant_id, venda_item_id)
    REFERENCES erp.vendas_itens (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_itens_compra_item_fk FOREIGN KEY (tenant_id, compra_item_id)
    REFERENCES erp.compras_itens (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_itens_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT notas_fiscais_itens_servico_fk FOREIGN KEY (tenant_id, servico_id)
    REFERENCES erp.servicos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.notas_fiscais_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nota_fiscal_id bigint NOT NULL,
  provedor text NOT NULL DEFAULT 'focus_nfe',
  evento text NOT NULL,
  status_anterior text,
  status_novo text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  recebido_em timestamptz NOT NULL DEFAULT now(),
  processado_em timestamptz,
  erro_mensagem text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT notas_fiscais_eventos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT notas_fiscais_eventos_provedor_chk CHECK (provedor IN ('focus_nfe')),
  CONSTRAINT notas_fiscais_eventos_payload_object_chk CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT notas_fiscais_eventos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT notas_fiscais_eventos_nota_fk FOREIGN KEY (tenant_id, nota_fiscal_id)
    REFERENCES erp.notas_fiscais (tenant_id, id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS configuracoes_fiscais_cnpj_ativo_idx
  ON erp.configuracoes_fiscais (tenant_id, cnpj)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS notas_fiscais_ref_focus_unica_idx
  ON erp.notas_fiscais (tenant_id, ref_focus)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS notas_fiscais_venda_tipo_unica_idx
  ON erp.notas_fiscais (tenant_id, venda_id, tipo)
  WHERE venda_id IS NOT NULL
    AND excluido_em IS NULL
    AND status <> 'cancelada';

CREATE INDEX IF NOT EXISTS notas_fiscais_tenant_status_idx
  ON erp.notas_fiscais (tenant_id, status, atualizado_em DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS notas_fiscais_entidade_idx
  ON erp.notas_fiscais (tenant_id, entidade_id, criado_em DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS notas_fiscais_chave_acesso_idx
  ON erp.notas_fiscais (tenant_id, chave_acesso)
  WHERE chave_acesso IS NOT NULL AND excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS notas_fiscais_itens_nota_idx
  ON erp.notas_fiscais_itens (tenant_id, nota_fiscal_id)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS notas_fiscais_eventos_nota_idx
  ON erp.notas_fiscais_eventos (tenant_id, nota_fiscal_id, recebido_em DESC)
  WHERE excluido_em IS NULL;

DO $$
DECLARE
  table_name text;
  table_names text[] := ARRAY[
    'configuracoes_fiscais',
    'notas_fiscais',
    'notas_fiscais_itens',
    'notas_fiscais_eventos'
  ];
BEGIN
  FOREACH table_name IN ARRAY table_names LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_atualizado_em ON erp.%I', table_name);
    EXECUTE format(
      'CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()',
      table_name
    );

    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', table_name);

    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_select_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_insert_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_update_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_delete_policy', table_name);

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))',
      table_name || '_select_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))',
      table_name || '_insert_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR UPDATE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member''])) WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))',
      table_name || '_update_policy',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR DELETE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'']))',
      table_name || '_delete_policy',
      table_name
    );
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA erp TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO authenticated, service_role;

COMMENT ON TABLE erp.configuracoes_fiscais IS 'Configuracoes fiscais por tenant/empresa para emissao via provedor fiscal.';
COMMENT ON TABLE erp.notas_fiscais IS 'Documentos fiscais emitidos ou preparados a partir de vendas, compras e operacoes fiscais.';
COMMENT ON TABLE erp.notas_fiscais_itens IS 'Snapshot fiscal dos itens da nota no momento da emissao.';
COMMENT ON TABLE erp.notas_fiscais_eventos IS 'Eventos, webhooks e historico de status de notas fiscais.';
COMMENT ON COLUMN erp.configuracoes_fiscais.token_secret_ref IS 'Referencia do segredo do token fiscal. Nao armazenar token puro nesta tabela.';
COMMENT ON INDEX erp.notas_fiscais_ref_focus_unica_idx IS 'Garante idempotencia por ref enviada ao provedor Focus NFe.';
COMMENT ON INDEX erp.notas_fiscais_venda_tipo_unica_idx IS 'Evita duplicidade de nota fiscal ativa do mesmo tipo para a mesma venda.';

COMMIT;
