BEGIN;

-- Fase 2C: conciliação bancária em uso e cartão pelo modelo da "conta da maquininha".
--
-- 1. Regras de lançamento: transação do extrato cuja descrição contém um texto (tarifa, IOF, rendimento…) vira,
--    na importação, um título pago na categoria da regra e já conciliado.
-- 2. Conta financeira do tipo "maquininha" (Stone, Cielo, Mercado Pago…): a venda no cartão é quitada nela, a
--    taxa vira despesa e o dinheiro chega ao banco por repasses (transferências pendentes até o extrato confirmar).
-- 3. Forma de pagamento com taxa, prazo e contas do cartão.

-- 1. Regras de lançamento automático --------------------------------------------------------------------------
CREATE TABLE erp.regras_lancamento_bancario (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES shared.empresas(id) ON DELETE RESTRICT,
  conta_financeira_id bigint,
  nome text NOT NULL CHECK (btrim(nome) <> ''),
  descricao_contem text NOT NULL CHECK (length(btrim(descricao_contem)) >= 3),
  tipo_transacao text NOT NULL CHECK (tipo_transacao IN ('credito', 'debito')),
  categoria_id bigint NOT NULL,
  entidade_id bigint NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  versao integer NOT NULL DEFAULT 1 CHECK (versao > 0),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.usuarios(id) ON DELETE SET NULL,
  CONSTRAINT regras_lancamento_conta_fk FOREIGN KEY (empresa_id, conta_financeira_id) REFERENCES erp.contas_financeiras(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT regras_lancamento_categoria_fk FOREIGN KEY (empresa_id, categoria_id) REFERENCES erp.categorias(empresa_id, id) ON DELETE RESTRICT,
  CONSTRAINT regras_lancamento_entidade_fk FOREIGN KEY (empresa_id, entidade_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT
);
CREATE INDEX regras_lancamento_ativas_idx ON erp.regras_lancamento_bancario (empresa_id) WHERE ativo AND excluido_em IS NULL;
COMMENT ON TABLE erp.regras_lancamento_bancario IS 'Transação importada cuja descrição contém o texto vira título pago e conciliado (categoria e cliente/fornecedor da regra).';
SELECT erp.criar_politicas_padrao('regras_lancamento_bancario', 'financeiro', 'erp.financeiro.gerenciar');

-- Saldo informado pelo banco no arquivo importado (OFX LEDGERBAL ou coluna de saldo do CSV).
ALTER TABLE erp.importacoes_bancarias
  ADD COLUMN saldo_extrato numeric(18,2),
  ADD COLUMN saldo_extrato_data date;
ALTER TABLE erp.importacoes_bancarias DROP CONSTRAINT IF EXISTS importacoes_bancarias_formato_chk;

-- 2. Conta da maquininha ---------------------------------------------------------------------------------------
ALTER TABLE erp.contas_financeiras DROP CONSTRAINT contas_financeiras_tipo_chk;
ALTER TABLE erp.contas_financeiras ADD CONSTRAINT contas_financeiras_tipo_chk
  CHECK (tipo IN ('caixa', 'banco', 'carteira', 'cartao', 'maquininha', 'outro'));
COMMENT ON COLUMN erp.contas_financeiras.tipo IS 'maquininha = saldo a receber da adquirente (cartão): não é caixa disponível até o repasse ao banco.';

-- 3. Forma de pagamento com cartão -------------------------------------------------------------------------------
ALTER TABLE erp.metodos_pagamento
  ADD COLUMN taxa_percentual numeric(7,4) NOT NULL DEFAULT 0 CHECK (taxa_percentual BETWEEN 0 AND 100),
  ADD COLUMN taxa_fixa numeric(18,2) NOT NULL DEFAULT 0 CHECK (taxa_fixa >= 0),
  ADD COLUMN prazo_repasse_dias integer NOT NULL DEFAULT 0 CHECK (prazo_repasse_dias BETWEEN 0 AND 365),
  ADD COLUMN repasse text NOT NULL DEFAULT 'unico' CHECK (repasse IN ('unico', 'parcelado')),
  ADD COLUMN conta_maquininha_id bigint,
  ADD COLUMN conta_destino_id bigint,
  ADD COLUMN categoria_taxa_id bigint,
  ADD COLUMN adquirente_id bigint,
  ADD COLUMN versao integer NOT NULL DEFAULT 1 CHECK (versao > 0);
ALTER TABLE erp.metodos_pagamento
  ADD CONSTRAINT metodos_pagamento_maquininha_fk FOREIGN KEY (empresa_id, conta_maquininha_id) REFERENCES erp.contas_financeiras(empresa_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT metodos_pagamento_destino_fk FOREIGN KEY (empresa_id, conta_destino_id) REFERENCES erp.contas_financeiras(empresa_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT metodos_pagamento_categoria_taxa_fk FOREIGN KEY (empresa_id, categoria_taxa_id) REFERENCES erp.categorias(empresa_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT metodos_pagamento_adquirente_fk FOREIGN KEY (empresa_id, adquirente_id) REFERENCES erp.entidades(empresa_id, id) ON DELETE RESTRICT,
  -- Cartão pela maquininha: conta de destino, categoria da taxa e adquirente (fornecedor da taxa) são obrigatórios.
  ADD CONSTRAINT metodos_pagamento_cartao_chk CHECK (conta_maquininha_id IS NULL
    OR (conta_destino_id IS NOT NULL AND conta_destino_id <> conta_maquininha_id AND categoria_taxa_id IS NOT NULL AND adquirente_id IS NOT NULL));
COMMENT ON COLUMN erp.metodos_pagamento.repasse IS 'unico = a adquirente repassa tudo em D+prazo (antecipação); parcelado = um repasse por parcela do cartão, a cada 30 dias.';

-- Repasse previsto da maquininha: transferência pendente até o crédito aparecer no extrato do banco.
ALTER TABLE erp.transferencias_financeiras ADD COLUMN pagamento_origem_id bigint;
ALTER TABLE erp.transferencias_financeiras ADD CONSTRAINT transferencias_pagamento_origem_fk
  FOREIGN KEY (empresa_id, pagamento_origem_id) REFERENCES erp.pagamentos(empresa_id, id) ON DELETE RESTRICT;
CREATE INDEX transferencias_pendentes_idx ON erp.transferencias_financeiras (empresa_id, conta_destino_id, data_transferencia)
  WHERE status = 'pendente' AND excluido_em IS NULL;
COMMENT ON COLUMN erp.transferencias_financeiras.pagamento_origem_id IS 'Recebimento no cartão que gerou este repasse da maquininha.';

GRANT USAGE ON ALL SEQUENCES IN SCHEMA erp TO erp_runtime;

COMMIT;
