BEGIN;

CREATE TABLE IF NOT EXISTS erp.naturezas_operacao_compra (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nome text NOT NULL,
  codigo text,
  atualiza_estoque boolean NOT NULL DEFAULT false,
  gera_financeiro_padrao boolean NOT NULL DEFAULT true,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT naturezas_operacao_compra_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT naturezas_operacao_compra_nome_chk CHECK (btrim(nome) <> ''),
  CONSTRAINT naturezas_operacao_compra_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

ALTER TABLE erp.compras
  ADD COLUMN IF NOT EXISTS tipo_compra text NOT NULL DEFAULT 'produto',
  ADD COLUMN IF NOT EXISTS tipo_movimento text NOT NULL DEFAULT 'cotacao',
  ADD COLUMN IF NOT EXISTS natureza_operacao_id bigint,
  ADD COLUMN IF NOT EXISTS data_prevista_entrega date,
  ADD COLUMN IF NOT EXISTS responsavel_id bigint,
  ADD COLUMN IF NOT EXISTS origem text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS fornecedor_nome_snapshot text,
  ADD COLUMN IF NOT EXISTS fornecedor_documento_snapshot text,
  ADD COLUMN IF NOT EXISTS seguro numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outras_despesas numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS impostos_retidos numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS atualiza_estoque boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS motivo_cancelamento text;

UPDATE erp.compras
SET tipo_movimento = CASE status
  WHEN 'confirmada' THEN 'compra'
  WHEN 'recebida' THEN 'compra'
  WHEN 'cancelada' THEN 'cancelada'
  ELSE 'cotacao'
END;

UPDATE erp.compras AS compras
SET
  fornecedor_nome_snapshot = COALESCE(compras.fornecedor_nome_snapshot, entidades.nome),
  fornecedor_documento_snapshot = COALESCE(compras.fornecedor_documento_snapshot, entidades.documento)
FROM erp.entidades AS entidades
WHERE entidades.tenant_id = compras.tenant_id
  AND entidades.id = compras.fornecedor_id;

ALTER TABLE erp.compras
  DROP CONSTRAINT IF EXISTS compras_tipo_compra_chk,
  DROP CONSTRAINT IF EXISTS compras_tipo_movimento_chk,
  DROP CONSTRAINT IF EXISTS compras_origem_chk,
  DROP CONSTRAINT IF EXISTS compras_valores_completos_chk,
  DROP CONSTRAINT IF EXISTS compras_versao_chk;

ALTER TABLE erp.compras
  ADD CONSTRAINT compras_tipo_compra_chk CHECK (tipo_compra IN ('produto', 'servico')),
  ADD CONSTRAINT compras_tipo_movimento_chk CHECK (tipo_movimento IN ('cotacao', 'pedido_recorrente', 'pedido_compra', 'compra', 'cancelada')),
  ADD CONSTRAINT compras_origem_chk CHECK (origem IN ('manual', 'xml', 'api', 'recorrencia', 'integracao')),
  ADD CONSTRAINT compras_valores_completos_chk CHECK (
    seguro >= 0 AND outras_despesas >= 0 AND impostos_retidos >= 0
  ),
  ADD CONSTRAINT compras_versao_chk CHECK (versao > 0),
  ADD CONSTRAINT compras_natureza_fk FOREIGN KEY (tenant_id, natureza_operacao_id)
    REFERENCES erp.naturezas_operacao_compra (tenant_id, id) ON DELETE RESTRICT,
  ADD CONSTRAINT compras_responsavel_fk FOREIGN KEY (responsavel_id)
    REFERENCES shared.users (id) ON DELETE SET NULL;

ALTER TABLE erp.compras_itens
  ADD COLUMN IF NOT EXISTS unidade text,
  ADD COLUMN IF NOT EXISTS detalhes text,
  ADD COLUMN IF NOT EXISTS percentual_desconto numeric(9,4),
  ADD COLUMN IF NOT EXISTS valor_desconto numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_bruto numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_liquido numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_codigo_snapshot text,
  ADD COLUMN IF NOT EXISTS item_descricao_snapshot text,
  ADD COLUMN IF NOT EXISTS item_unidade_snapshot text;

UPDATE erp.compras_itens
SET
  valor_bruto = ROUND((quantidade * valor_unitario)::numeric, 2),
  valor_desconto = COALESCE(valor_desconto, 0),
  valor_liquido = total,
  item_descricao_snapshot = COALESCE(item_descricao_snapshot, descricao);

ALTER TABLE erp.compras_itens
  DROP CONSTRAINT IF EXISTS compras_itens_valores_completos_chk;

ALTER TABLE erp.compras_itens
  ADD CONSTRAINT compras_itens_valores_completos_chk CHECK (
    valor_desconto >= 0
    AND valor_bruto >= 0
    AND valor_liquido >= 0
    AND (percentual_desconto IS NULL OR (percentual_desconto >= 0 AND percentual_desconto <= 100))
  );

CREATE TABLE IF NOT EXISTS erp.compras_parcelas_previstas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  compra_id bigint NOT NULL,
  numero_parcela integer NOT NULL,
  descricao text,
  data_vencimento date NOT NULL,
  valor numeric(18,2) NOT NULL,
  percentual numeric(9,4),
  conta_financeira_id bigint,
  metodo_pagamento_id bigint,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_parcelas_previstas_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_parcelas_previstas_valores_chk CHECK (
    numero_parcela > 0 AND numero_parcela <= 48 AND valor > 0
    AND (percentual IS NULL OR (percentual > 0 AND percentual <= 100))
  ),
  CONSTRAINT compras_parcelas_previstas_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_parcelas_previstas_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT compras_parcelas_previstas_conta_fk FOREIGN KEY (tenant_id, conta_financeira_id)
    REFERENCES erp.contas_financeiras (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT compras_parcelas_previstas_metodo_fk FOREIGN KEY (tenant_id, metodo_pagamento_id)
    REFERENCES erp.metodos_pagamento (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.compras_recorrencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  compra_modelo_id bigint NOT NULL,
  intervalo integer NOT NULL DEFAULT 1,
  frequencia text NOT NULL DEFAULT 'mes',
  inicio_em date NOT NULL,
  termino_tipo text NOT NULL DEFAULT 'ocorrencias',
  termino_em date,
  quantidade_ocorrencias integer,
  proxima_competencia date,
  ativa boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_recorrencias_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_recorrencias_frequencia_chk CHECK (frequencia IN ('dia', 'semana', 'mes', 'ano')),
  CONSTRAINT compras_recorrencias_termino_chk CHECK (termino_tipo IN ('data', 'ocorrencias', 'indeterminado')),
  CONSTRAINT compras_recorrencias_valores_chk CHECK (
    intervalo > 0 AND (quantidade_ocorrencias IS NULL OR quantidade_ocorrencias BETWEEN 1 AND 366)
  ),
  CONSTRAINT compras_recorrencias_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_recorrencias_compra_fk FOREIGN KEY (tenant_id, compra_modelo_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.compras_recorrencias_geracoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  recorrencia_id bigint NOT NULL,
  compra_id bigint NOT NULL,
  competencia date NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_recorrencias_geracoes_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_recorrencias_geracoes_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_recorrencias_geracoes_recorrencia_fk FOREIGN KEY (tenant_id, recorrencia_id)
    REFERENCES erp.compras_recorrencias (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT compras_recorrencias_geracoes_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.arquivos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  bucket text NOT NULL,
  caminho text NOT NULL,
  nome text NOT NULL,
  mime_type text,
  tamanho_bytes bigint,
  hash_sha256 text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT arquivos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT arquivos_caminho_chk CHECK (btrim(bucket) <> '' AND btrim(caminho) <> '' AND btrim(nome) <> ''),
  CONSTRAINT arquivos_tamanho_chk CHECK (tamanho_bytes IS NULL OR tamanho_bytes >= 0),
  CONSTRAINT arquivos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.compras_arquivos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  compra_id bigint NOT NULL,
  arquivo_id bigint NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT compras_arquivos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_arquivos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT compras_arquivos_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT compras_arquivos_arquivo_fk FOREIGN KEY (tenant_id, arquivo_id)
    REFERENCES erp.arquivos (tenant_id, id) ON DELETE RESTRICT
);

ALTER TABLE erp.contas_pagar
  ADD COLUMN IF NOT EXISTS origem text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS tipo_lancamento text NOT NULL DEFAULT 'efetivo',
  ADD COLUMN IF NOT EXISTS compra_recorrencia_id bigint,
  ADD COLUMN IF NOT EXISTS fornecedor_nome_snapshot text,
  ADD COLUMN IF NOT EXISTS fornecedor_documento_snapshot text,
  ADD COLUMN IF NOT EXISTS efetivado_em timestamptz,
  ADD COLUMN IF NOT EXISTS cancelado_em timestamptz,
  ADD COLUMN IF NOT EXISTS motivo_cancelamento text;

UPDATE erp.contas_pagar
SET origem = 'compra', tipo_lancamento = 'efetivo', efetivado_em = COALESCE(efetivado_em, criado_em)
WHERE compra_id IS NOT NULL;

UPDATE erp.contas_pagar AS contas
SET
  fornecedor_nome_snapshot = COALESCE(contas.fornecedor_nome_snapshot, entidades.nome),
  fornecedor_documento_snapshot = COALESCE(contas.fornecedor_documento_snapshot, entidades.documento)
FROM erp.entidades AS entidades
WHERE entidades.tenant_id = contas.tenant_id
  AND entidades.id = contas.fornecedor_id;

ALTER TABLE erp.contas_pagar
  DROP CONSTRAINT IF EXISTS contas_pagar_origem_chk,
  DROP CONSTRAINT IF EXISTS contas_pagar_tipo_lancamento_chk;

ALTER TABLE erp.contas_pagar
  ADD CONSTRAINT contas_pagar_origem_chk CHECK (origem IN ('manual', 'compra', 'recorrencia', 'xml', 'api', 'integracao')),
  ADD CONSTRAINT contas_pagar_tipo_lancamento_chk CHECK (tipo_lancamento IN ('previsao', 'efetivo')),
  ADD CONSTRAINT contas_pagar_compra_recorrencia_fk FOREIGN KEY (tenant_id, compra_recorrencia_id)
    REFERENCES erp.compras_recorrencias (tenant_id, id) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS erp.recorrencias_financeiras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  tipo text NOT NULL DEFAULT 'pagar',
  intervalo integer NOT NULL DEFAULT 1,
  frequencia text NOT NULL DEFAULT 'mes',
  inicio_em date NOT NULL,
  termino_tipo text NOT NULL DEFAULT 'ocorrencias',
  termino_em date,
  quantidade_ocorrencias integer,
  ativa boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT recorrencias_financeiras_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT recorrencias_financeiras_tipo_chk CHECK (tipo IN ('pagar', 'receber')),
  CONSTRAINT recorrencias_financeiras_frequencia_chk CHECK (frequencia IN ('dia', 'semana', 'mes', 'ano')),
  CONSTRAINT recorrencias_financeiras_termino_chk CHECK (termino_tipo IN ('data', 'ocorrencias', 'indeterminado')),
  CONSTRAINT recorrencias_financeiras_valores_chk CHECK (
    intervalo > 0 AND (quantidade_ocorrencias IS NULL OR quantidade_ocorrencias BETWEEN 1 AND 366)
  ),
  CONSTRAINT recorrencias_financeiras_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object')
);

ALTER TABLE erp.contas_pagar
  ADD COLUMN IF NOT EXISTS recorrencia_financeira_id bigint,
  ADD CONSTRAINT contas_pagar_recorrencia_financeira_fk FOREIGN KEY (tenant_id, recorrencia_financeira_id)
    REFERENCES erp.recorrencias_financeiras (tenant_id, id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS contas_pagar_recorrencia_competencia_unica_idx
  ON erp.contas_pagar (tenant_id, recorrencia_financeira_id, data_competencia)
  WHERE recorrencia_financeira_id IS NOT NULL AND excluido_em IS NULL;

CREATE TABLE IF NOT EXISTS erp.contas_pagar_arquivos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_pagar_id bigint NOT NULL,
  arquivo_id bigint NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contas_pagar_arquivos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_pagar_arquivos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT contas_pagar_arquivos_conta_fk FOREIGN KEY (tenant_id, conta_pagar_id)
    REFERENCES erp.contas_pagar (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT contas_pagar_arquivos_arquivo_fk FOREIGN KEY (tenant_id, arquivo_id)
    REFERENCES erp.arquivos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.compras_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  compra_id bigint NOT NULL,
  evento text NOT NULL,
  dados jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT compras_eventos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT compras_eventos_dados_object_chk CHECK (jsonb_typeof(dados) = 'object'),
  CONSTRAINT compras_eventos_compra_fk FOREIGN KEY (tenant_id, compra_id)
    REFERENCES erp.compras (tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS erp.contas_pagar_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  conta_pagar_id bigint NOT NULL,
  evento text NOT NULL,
  dados jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT contas_pagar_eventos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT contas_pagar_eventos_dados_object_chk CHECK (jsonb_typeof(dados) = 'object'),
  CONSTRAINT contas_pagar_eventos_conta_fk FOREIGN KEY (tenant_id, conta_pagar_id)
    REFERENCES erp.contas_pagar (tenant_id, id) ON DELETE CASCADE
);

ALTER TABLE erp.notas_fiscais
  ALTER COLUMN ref_focus DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS notas_fiscais_entrada_chave_unica_idx
  ON erp.notas_fiscais (tenant_id, chave_acesso)
  WHERE direcao = 'entrada' AND chave_acesso IS NOT NULL AND excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS compras_parcelas_previstas_numero_unico_idx
  ON erp.compras_parcelas_previstas (tenant_id, compra_id, numero_parcela)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS compras_recorrencias_compra_unica_idx
  ON erp.compras_recorrencias (tenant_id, compra_modelo_id)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS compras_recorrencias_geracoes_unica_idx
  ON erp.compras_recorrencias_geracoes (tenant_id, recorrencia_id, competencia)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS arquivos_caminho_unico_idx
  ON erp.arquivos (tenant_id, bucket, caminho)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS compras_arquivos_unico_idx
  ON erp.compras_arquivos (tenant_id, compra_id, arquivo_id)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS contas_pagar_arquivos_unico_idx
  ON erp.contas_pagar_arquivos (tenant_id, conta_pagar_id, arquivo_id)
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS contas_pagar_parcelas_numero_unico_idx
  ON erp.contas_pagar_parcelas (tenant_id, conta_pagar_id, numero_parcela)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS compras_movimento_data_idx
  ON erp.compras (tenant_id, tipo_movimento, data_compra DESC)
  WHERE excluido_em IS NULL;

CREATE INDEX IF NOT EXISTS contas_pagar_tipo_vencimento_idx
  ON erp.contas_pagar (tenant_id, tipo_lancamento, status)
  WHERE excluido_em IS NULL;

DO $$
DECLARE
  table_name text;
  table_names text[] := ARRAY[
    'naturezas_operacao_compra',
    'compras_parcelas_previstas',
    'compras_recorrencias',
    'compras_recorrencias_geracoes',
    'recorrencias_financeiras',
    'arquivos',
    'compras_arquivos',
    'contas_pagar_arquivos',
    'compras_eventos',
    'contas_pagar_eventos'
  ];
BEGIN
  FOREACH table_name IN ARRAY table_names LOOP
    IF table_name NOT IN ('compras_eventos', 'contas_pagar_eventos') THEN
      EXECUTE format('DROP TRIGGER IF EXISTS set_atualizado_em ON erp.%I', table_name);
      EXECUTE format(
        'CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()',
        table_name
      );
    END IF;

    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_select_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_insert_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_update_policy', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', table_name || '_delete_policy', table_name);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))', table_name || '_select_policy', table_name);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR INSERT WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', table_name || '_insert_policy', table_name);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR UPDATE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member''])) WITH CHECK (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'', ''member'']))', table_name || '_update_policy', table_name);
    EXECUTE format('CREATE POLICY %I ON erp.%I FOR DELETE USING (shared.has_tenant_role(tenant_id, ARRAY[''owner'', ''admin'']))', table_name || '_delete_policy', table_name);
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA erp TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO authenticated, service_role;

COMMENT ON COLUMN erp.compras.tipo_movimento IS 'Etapa Conta Azul-like: cotacao, pedido recorrente, pedido de compra, compra efetiva ou cancelada.';
COMMENT ON COLUMN erp.contas_pagar.tipo_lancamento IS 'Previsao de pedido ou despesa efetiva. A previsao e convertida em vez de duplicada.';

COMMIT;
