BEGIN;

ALTER TABLE erp.entidades
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1;

ALTER TABLE erp.categorias
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1;

ALTER TABLE erp.produtos
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1;

ALTER TABLE erp.servicos
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1;

ALTER TABLE erp.contas_financeiras
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1;

ALTER TABLE erp.notas_fiscais
  ADD COLUMN IF NOT EXISTS versao integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS xml_hash text,
  ADD COLUMN IF NOT EXISTS destinatario_documento text,
  ADD COLUMN IF NOT EXISTS codigo_status_sefaz text,
  ADD COLUMN IF NOT EXISTS motivo_status_sefaz text;

ALTER TABLE erp.compras
  ADD COLUMN IF NOT EXISTS impostos_adicionais numeric(18,2) NOT NULL DEFAULT 0;

ALTER TABLE erp.recorrencias_financeiras
  ADD COLUMN IF NOT EXISTS proxima_competencia date,
  ADD COLUMN IF NOT EXISTS gerado_ate date,
  ADD COLUMN IF NOT EXISTS pausada_em timestamptz,
  ADD COLUMN IF NOT EXISTS encerrada_em timestamptz;

DO $$
DECLARE
  tabela text;
BEGIN
  FOREACH tabela IN ARRAY ARRAY['entidades', 'categorias', 'produtos', 'servicos', 'contas_financeiras', 'notas_fiscais']
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = tabela || '_versao_chk'
        AND conrelid = format('erp.%I', tabela)::regclass
    ) THEN
      EXECUTE format(
        'ALTER TABLE erp.%I ADD CONSTRAINT %I CHECK (versao > 0)',
        tabela,
        tabela || '_versao_chk'
      );
    END IF;
  END LOOP;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'compras_impostos_adicionais_chk'
      AND conrelid = 'erp.compras'::regclass
  ) THEN
    ALTER TABLE erp.compras
      ADD CONSTRAINT compras_impostos_adicionais_chk CHECK (impostos_adicionais >= 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS erp.cadastros_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  entidade_tipo text NOT NULL,
  entidade_id bigint NOT NULL,
  evento text NOT NULL,
  versao integer NOT NULL,
  dados jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT cadastros_eventos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT cadastros_eventos_tipo_chk CHECK (
    entidade_tipo IN ('entidade', 'categoria', 'produto', 'servico', 'conta_financeira')
  ),
  CONSTRAINT cadastros_eventos_versao_chk CHECK (versao > 0),
  CONSTRAINT cadastros_eventos_dados_object_chk CHECK (jsonb_typeof(dados) = 'object')
);

CREATE TABLE IF NOT EXISTS erp.vendas_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  venda_id bigint NOT NULL,
  evento text NOT NULL,
  status_anterior text,
  status_novo text,
  versao integer NOT NULL,
  dados jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  CONSTRAINT vendas_eventos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT vendas_eventos_versao_chk CHECK (versao > 0),
  CONSTRAINT vendas_eventos_dados_object_chk CHECK (jsonb_typeof(dados) = 'object'),
  CONSTRAINT vendas_eventos_venda_fk FOREIGN KEY (tenant_id, venda_id)
    REFERENCES erp.vendas (tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS erp.fornecedores_produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  fornecedor_id bigint NOT NULL,
  produto_id bigint NOT NULL,
  codigo_fornecedor text NOT NULL,
  descricao_fornecedor text,
  unidade_fornecedor text,
  ultimo_custo numeric(18,4),
  ultima_compra_em date,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  excluido_em timestamptz,
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT fornecedores_produtos_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT fornecedores_produtos_codigo_chk CHECK (btrim(codigo_fornecedor) <> ''),
  CONSTRAINT fornecedores_produtos_custo_chk CHECK (ultimo_custo IS NULL OR ultimo_custo >= 0),
  CONSTRAINT fornecedores_produtos_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT fornecedores_produtos_fornecedor_fk FOREIGN KEY (tenant_id, fornecedor_id)
    REFERENCES erp.entidades (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT fornecedores_produtos_produto_fk FOREIGN KEY (tenant_id, produto_id)
    REFERENCES erp.produtos (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS erp.notas_fiscais_totais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES shared.tenants (id) ON DELETE RESTRICT,
  nota_fiscal_id bigint NOT NULL,
  base_icms numeric(18,2) NOT NULL DEFAULT 0,
  valor_icms numeric(18,2) NOT NULL DEFAULT 0,
  base_icms_st numeric(18,2) NOT NULL DEFAULT 0,
  valor_icms_st numeric(18,2) NOT NULL DEFAULT 0,
  valor_fcp numeric(18,2) NOT NULL DEFAULT 0,
  valor_fcp_st numeric(18,2) NOT NULL DEFAULT 0,
  valor_ipi numeric(18,2) NOT NULL DEFAULT 0,
  valor_ii numeric(18,2) NOT NULL DEFAULT 0,
  valor_pis numeric(18,2) NOT NULL DEFAULT 0,
  valor_cofins numeric(18,2) NOT NULL DEFAULT 0,
  valor_seguro numeric(18,2) NOT NULL DEFAULT 0,
  outras_despesas numeric(18,2) NOT NULL DEFAULT 0,
  desconto numeric(18,2) NOT NULL DEFAULT 0,
  frete numeric(18,2) NOT NULL DEFAULT 0,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  criado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  atualizado_por bigint REFERENCES shared.users (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT notas_fiscais_totais_tenant_id_id_key UNIQUE (tenant_id, id),
  CONSTRAINT notas_fiscais_totais_nota_key UNIQUE (tenant_id, nota_fiscal_id),
  CONSTRAINT notas_fiscais_totais_valores_chk CHECK (
    base_icms >= 0 AND valor_icms >= 0 AND base_icms_st >= 0 AND valor_icms_st >= 0
    AND valor_fcp >= 0 AND valor_fcp_st >= 0 AND valor_ipi >= 0 AND valor_ii >= 0
    AND valor_pis >= 0 AND valor_cofins >= 0 AND valor_seguro >= 0
    AND outras_despesas >= 0 AND desconto >= 0 AND frete >= 0
  ),
  CONSTRAINT notas_fiscais_totais_metadata_object_chk CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT notas_fiscais_totais_nota_fk FOREIGN KEY (tenant_id, nota_fiscal_id)
    REFERENCES erp.notas_fiscais (tenant_id, id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS fornecedores_produtos_codigo_unico_idx
  ON erp.fornecedores_produtos (tenant_id, fornecedor_id, lower(codigo_fornecedor))
  WHERE excluido_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS fornecedores_produtos_vinculo_unico_idx
  ON erp.fornecedores_produtos (tenant_id, fornecedor_id, produto_id)
  WHERE excluido_em IS NULL AND ativo;

CREATE INDEX IF NOT EXISTS cadastros_eventos_entidade_idx
  ON erp.cadastros_eventos (tenant_id, entidade_tipo, entidade_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS vendas_eventos_venda_idx
  ON erp.vendas_eventos (tenant_id, venda_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS recorrencias_financeiras_proxima_idx
  ON erp.recorrencias_financeiras (tenant_id, proxima_competencia)
  WHERE excluido_em IS NULL AND ativa AND pausada_em IS NULL AND encerrada_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS notas_fiscais_xml_hash_unico_idx
  ON erp.notas_fiscais (tenant_id, xml_hash)
  WHERE xml_hash IS NOT NULL AND excluido_em IS NULL;

CREATE OR REPLACE FUNCTION erp.validar_fechamento_compra(p_tenant_id bigint, p_compra_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  documento erp.compras%ROWTYPE;
  total_itens numeric(18,2);
  total_parcelas numeric(18,2);
BEGIN
  SELECT * INTO documento
  FROM erp.compras
  WHERE tenant_id = p_tenant_id AND id = p_compra_id AND excluido_em IS NULL;

  IF NOT FOUND OR documento.status = 'rascunho' OR documento.status = 'cancelada' THEN
    RETURN;
  END IF;

  SELECT COALESCE(sum(total), 0) INTO total_itens
  FROM erp.compras_itens
  WHERE tenant_id = p_tenant_id AND compra_id = p_compra_id AND excluido_em IS NULL;

  IF round(total_itens, 2) <> round(documento.subtotal, 2) THEN
    RAISE EXCEPTION 'Soma dos itens da compra (%) difere do subtotal (%)', total_itens, documento.subtotal;
  END IF;

  IF round(documento.subtotal - documento.desconto + documento.frete
      + documento.seguro + documento.outras_despesas - documento.impostos_retidos
      + documento.impostos_adicionais, 2)
    <> round(documento.total, 2) THEN
    RAISE EXCEPTION 'Composicao do total da compra invalida';
  END IF;

  SELECT COALESCE(sum(valor), 0) INTO total_parcelas
  FROM erp.compras_parcelas_previstas
  WHERE tenant_id = p_tenant_id AND compra_id = p_compra_id AND excluido_em IS NULL;

  IF round(total_parcelas, 2) <> round(documento.total, 2) THEN
    RAISE EXCEPTION 'Soma das parcelas da compra (%) difere do total (%)', total_parcelas, documento.total;
  END IF;
END;
$$;

DO $$
DECLARE
  tabela text;
BEGIN
  FOREACH tabela IN ARRAY ARRAY['fornecedores_produtos', 'notas_fiscais_totais']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_atualizado_em ON erp.%I', tabela);
    EXECUTE format(
      'CREATE TRIGGER set_atualizado_em BEFORE UPDATE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.set_atualizado_em()',
      tabela
    );
  END LOOP;

  FOREACH tabela IN ARRAY ARRAY['cadastros_eventos', 'vendas_eventos']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS bloquear_mutacao_evento ON erp.%I', tabela);
    EXECUTE format(
      'CREATE TRIGGER bloquear_mutacao_evento BEFORE UPDATE OR DELETE ON erp.%I FOR EACH ROW EXECUTE FUNCTION erp.bloquear_mutacao_evento()',
      tabela
    );
  END LOOP;

  FOREACH tabela IN ARRAY ARRAY['cadastros_eventos', 'vendas_eventos', 'fornecedores_produtos', 'notas_fiscais_totais']
  LOOP
    EXECUTE format('ALTER TABLE erp.%I ENABLE ROW LEVEL SECURITY', tabela);
    EXECUTE format('DROP POLICY IF EXISTS %I ON erp.%I', tabela || '_select_policy', tabela);
    EXECUTE format(
      'CREATE POLICY %I ON erp.%I FOR SELECT USING (shared.is_tenant_member(tenant_id))',
      tabela || '_select_policy',
      tabela
    );
  END LOOP;
END $$;

REVOKE INSERT, UPDATE, DELETE ON erp.cadastros_eventos, erp.vendas_eventos,
  erp.fornecedores_produtos, erp.notas_fiscais_totais FROM authenticated;
GRANT SELECT ON erp.cadastros_eventos, erp.vendas_eventos,
  erp.fornecedores_produtos, erp.notas_fiscais_totais TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON erp.cadastros_eventos, erp.vendas_eventos,
  erp.fornecedores_produtos, erp.notas_fiscais_totais TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO service_role;

COMMIT;
