export {
  ensureGroupExists,
  insertKpiInGroup,
  insertChartInGroup,
  setDashboardAttrs,
  upsertHeaderTag,
  buildMeasureExpr,
  normalizeSchemaTable,
  removeWidgetByIdDSL,
  removeGroupByIdDSL,
  setOrInsertStylingTw,
  setGroupStyleJson,
  dedupeWidgetByIdDSL,
  updateWidgetStylingTwAndKpiBg,
  setAttrOnNode,
  setAttrOnDatasource,
  setConfigOnNode,
  getWidgetTagKind,
  ensureSectionExists,
  insertKpiInSection,
  insertChartInSection,
  removeSectionByIdDSL,
  updateArticleTitleByIdDSL,
  // Inline-first helpers
  upsertHeaderSimple,
  ensureSectionExistsInline,
  updateSectionStyleInline,
  insertKpiArticleInline,
  insertChartArticleInline,
  updateArticleInline,
} from './HelperEditorToDSL';
