// Generated by scripts/erp/api-catalog.mjs. Permissions are enforced in each handler.
export const ERP_API_ROUTES = [
  {
    "path": "/api/erp/[entityId]/[id]",
    "route": "src/app/api/erp/[entityId]/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/cadastros/registro.ts",
    "methods": [
      "GET",
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/[entityId]/resumo",
    "route": "src/app/api/erp/[entityId]/resumo/route.ts",
    "handler": "src/products/erp/api/handlers/cadastros/resumo.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/[entityId]",
    "route": "src/app/api/erp/[entityId]/route.ts",
    "handler": "src/products/erp/api/handlers/cadastros/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Optional header; operation-specific behavior.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/acesso",
    "route": "src/app/api/erp/acesso/route.ts",
    "handler": "src/products/erp/api/handlers/acesso/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/anexos/[id]/confirmar",
    "route": "src/app/api/erp/anexos/[id]/confirmar/route.ts",
    "handler": "src/products/erp/api/handlers/anexos/confirmar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/anexos/[id]",
    "route": "src/app/api/erp/anexos/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/anexos/registro.ts",
    "methods": [
      "GET",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/anexos",
    "route": "src/app/api/erp/anexos/route.ts",
    "handler": "src/products/erp/api/handlers/anexos/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar",
      "erp.compras.visualizar",
      "erp.financeiro.baixar",
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar",
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/automacoes",
    "route": "src/app/api/erp/automacoes/route.ts",
    "handler": "src/products/erp/api/handlers/automacoes/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.configuracoes.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/bancos/importar-ofx",
    "route": "src/app/api/erp/bancos/importar-ofx/route.ts",
    "handler": "src/products/erp/api/handlers/bancos/importar-ofx.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 4194304,
    "capabilities": [
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/catalogos/busca",
    "route": "src/app/api/erp/catalogos/busca/route.ts",
    "handler": "src/products/erp/api/handlers/catalogos/busca.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/catalogos/categorias",
    "route": "src/app/api/erp/catalogos/categorias/route.ts",
    "handler": "src/products/erp/api/handlers/catalogos/categorias.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/comissoes/pagar",
    "route": "src/app/api/erp/comissoes/pagar/route.ts",
    "handler": "src/products/erp/api/handlers/comissoes/pagar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/comissoes/regras/[id]",
    "route": "src/app/api/erp/comissoes/regras/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/comissoes/regra.ts",
    "methods": [
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/comissoes/regras",
    "route": "src/app/api/erp/comissoes/regras/route.ts",
    "handler": "src/products/erp/api/handlers/comissoes/regras.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/comissoes",
    "route": "src/app/api/erp/comissoes/route.ts",
    "handler": "src/products/erp/api/handlers/comissoes/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras/[id]/cancelar",
    "route": "src/app/api/erp/compras/[id]/cancelar/route.ts",
    "handler": "src/products/erp/api/handlers/compras/cancelar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras/[id]/confirmar",
    "route": "src/app/api/erp/compras/[id]/confirmar/route.ts",
    "handler": "src/products/erp/api/handlers/compras/confirmar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras/[id]/receber",
    "route": "src/app/api/erp/compras/[id]/receber/route.ts",
    "handler": "src/products/erp/api/handlers/compras/receber.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Optional header; operation-specific behavior.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras/[id]",
    "route": "src/app/api/erp/compras/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/compras/registro.ts",
    "methods": [
      "GET",
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar",
      "erp.compras.visualizar",
      "erp.estoque.visualizar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras/catalogos",
    "route": "src/app/api/erp/compras/catalogos/route.ts",
    "handler": "src/products/erp/api/handlers/compras/catalogos.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/compras",
    "route": "src/app/api/erp/compras/route.ts",
    "handler": "src/products/erp/api/handlers/compras/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar",
      "erp.compras.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Optional header; operation-specific behavior.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/concluidas",
    "route": "src/app/api/erp/conciliacao/concluidas/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/concluidas.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/lancamentos",
    "route": "src/app/api/erp/conciliacao/lancamentos/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/lancamentos.ts",
    "methods": [
      "GET",
      "POST",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/regras",
    "route": "src/app/api/erp/conciliacao/regras/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/regras.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/sugestoes",
    "route": "src/app/api/erp/conciliacao/sugestoes/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/sugestoes.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/transacoes/[id]/desfazer",
    "route": "src/app/api/erp/conciliacao/transacoes/[id]/desfazer/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/transacoes-desfazer.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/conciliacao/transacoes/[id]/ignorar",
    "route": "src/app/api/erp/conciliacao/transacoes/[id]/ignorar/route.ts",
    "handler": "src/products/erp/api/handlers/conciliacao/transacoes-ignorar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/contas-pagar-parcelas/[id]/baixar",
    "route": "src/app/api/erp/contas-pagar-parcelas/[id]/baixar/route.ts",
    "handler": "src/products/erp/api/handlers/contas-pagar-parcelas/baixar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.baixar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/contas-receber-parcelas/[id]/baixar",
    "route": "src/app/api/erp/contas-receber-parcelas/[id]/baixar/route.ts",
    "handler": "src/products/erp/api/handlers/contas-receber-parcelas/baixar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.baixar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/contratos/[id]",
    "route": "src/app/api/erp/contratos/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/contratos/registro.ts",
    "methods": [
      "GET",
      "PATCH"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/contratos/processar",
    "route": "src/app/api/erp/contratos/processar/route.ts",
    "handler": "src/products/erp/api/handlers/contratos/processar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/dashboards/[dashboardId]/registros",
    "route": "src/app/api/erp/dashboards/[dashboardId]/registros/route.ts",
    "handler": "src/products/erp/api/handlers/dashboards/records.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/dashboards/[dashboardId]",
    "route": "src/app/api/erp/dashboards/[dashboardId]/route.ts",
    "handler": "src/products/erp/api/handlers/dashboards/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/devolucoes/[id]",
    "route": "src/app/api/erp/devolucoes/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/devolucoes/registro.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/devolucoes/[id]/usar-credito",
    "route": "src/app/api/erp/devolucoes/[id]/usar-credito/route.ts",
    "handler": "src/products/erp/api/handlers/devolucoes/usar-credito.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.baixar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/devolucoes",
    "route": "src/app/api/erp/devolucoes/route.ts",
    "handler": "src/products/erp/api/handlers/devolucoes/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/estoque/contagem",
    "route": "src/app/api/erp/estoque/contagem/route.ts",
    "handler": "src/products/erp/api/handlers/estoque/contagem.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.estoque.ajustar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/fechamentos",
    "route": "src/app/api/erp/fechamentos/route.ts",
    "handler": "src/products/erp/api/handlers/fechamentos/index.ts",
    "methods": [
      "GET",
      "POST",
      "PATCH"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.configuracoes.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/financeiro/[operation]",
    "route": "src/app/api/erp/financeiro/[operation]/route.ts",
    "handler": "src/products/erp/api/handlers/financeiro/operation.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.estornar",
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/financeiro/formas-pagamento",
    "route": "src/app/api/erp/financeiro/formas-pagamento/route.ts",
    "handler": "src/products/erp/api/handlers/financeiro/formas-pagamento.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/historicos/[kind]/[id]",
    "route": "src/app/api/erp/historicos/[kind]/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/historicos/kind.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.visualizar",
      "erp.financeiro.visualizar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/importacoes/[type]",
    "route": "src/app/api/erp/importacoes/[type]/route.ts",
    "handler": "src/products/erp/api/handlers/importacoes/type.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 4194304,
    "capabilities": [
      "erp.cadastros.gerenciar",
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/importacoes/lotes/[id]",
    "route": "src/app/api/erp/importacoes/lotes/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/importacoes/lotes.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 4194304,
    "capabilities": [
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/internal/automacoes",
    "route": "src/app/api/erp/internal/automacoes/route.ts",
    "handler": "src/products/erp/api/handlers/internal/automacoes.ts",
    "methods": [
      "GET"
    ],
    "authentication": "cron",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/metas-vendas",
    "route": "src/app/api/erp/metas-vendas/route.ts",
    "handler": "src/products/erp/api/handlers/metas-vendas/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/notas-compra",
    "route": "src/app/api/erp/notas-compra/route.ts",
    "handler": "src/products/erp/api/handlers/notas-compra/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.compras.gerenciar",
      "erp.compras.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": true
  },
  {
    "path": "/api/erp/notas-servico/[id]/[operation]",
    "route": "src/app/api/erp/notas-servico/[id]/[operation]/route.ts",
    "handler": "src/products/erp/api/handlers/notas-servico/operation.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 65536,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/notas-servico/[id]",
    "route": "src/app/api/erp/notas-servico/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/notas-servico/detail.ts",
    "methods": [
      "GET",
      "PATCH"
    ],
    "authentication": "session",
    "maxBodyBytes": 65536,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/notas-servico",
    "route": "src/app/api/erp/notas-servico/route.ts",
    "handler": "src/products/erp/api/handlers/notas-servico/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 65536,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/operacoes/[resource]",
    "route": "src/app/api/erp/operacoes/[resource]/route.ts",
    "handler": "src/products/erp/api/handlers/operacoes/resource.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.estoque.ajustar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for selected resources; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/operacoes/catalogos",
    "route": "src/app/api/erp/operacoes/catalogos/route.ts",
    "handler": "src/products/erp/api/handlers/operacoes/catalogos.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/orcamentos-financeiros",
    "route": "src/app/api/erp/orcamentos-financeiros/route.ts",
    "handler": "src/products/erp/api/handlers/orcamentos-financeiros/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/orcamentos/[id]/acao",
    "route": "src/app/api/erp/orcamentos/[id]/acao/route.ts",
    "handler": "src/products/erp/api/handlers/orcamentos/acao.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/orcamentos/[id]/converter",
    "route": "src/app/api/erp/orcamentos/[id]/converter/route.ts",
    "handler": "src/products/erp/api/handlers/orcamentos/converter.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/ordens-servico/[id]/acao",
    "route": "src/app/api/erp/ordens-servico/[id]/acao/route.ts",
    "handler": "src/products/erp/api/handlers/ordens-servico/acao.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/ordens-servico/[id]",
    "route": "src/app/api/erp/ordens-servico/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/ordens-servico/registro.ts",
    "methods": [
      "GET",
      "PATCH"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/ordens-servico",
    "route": "src/app/api/erp/ordens-servico/route.ts",
    "handler": "src/products/erp/api/handlers/ordens-servico/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/pagamentos/[id]/estornar",
    "route": "src/app/api/erp/pagamentos/[id]/estornar/route.ts",
    "handler": "src/products/erp/api/handlers/pagamentos/estornar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.estornar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Optional header; operation-specific behavior.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/pagamentos",
    "route": "src/app/api/erp/pagamentos/route.ts",
    "handler": "src/products/erp/api/handlers/pagamentos/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/recorrencias/processar",
    "route": "src/app/api/erp/recorrencias/processar/route.ts",
    "handler": "src/products/erp/api/handlers/recorrencias/processar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/recorrencias",
    "route": "src/app/api/erp/recorrencias/route.ts",
    "handler": "src/products/erp/api/handlers/recorrencias/index.ts",
    "methods": [
      "GET",
      "PATCH"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.configuracoes.gerenciar",
      "erp.financeiro.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/relatorios/[report]",
    "route": "src/app/api/erp/relatorios/[report]/route.ts",
    "handler": "src/products/erp/api/handlers/relatorios/report.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.relatorios.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/relatorios/dre",
    "route": "src/app/api/erp/relatorios/dre/route.ts",
    "handler": "src/products/erp/api/handlers/relatorios/dre.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.relatorios.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/resumo/profissional",
    "route": "src/app/api/erp/resumo/profissional/route.ts",
    "handler": "src/products/erp/api/handlers/resumo/profissional.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.relatorios.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/resumo",
    "route": "src/app/api/erp/resumo/route.ts",
    "handler": "src/products/erp/api/handlers/resumo/index.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.relatorios.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/tabelas-preco/[id]",
    "route": "src/app/api/erp/tabelas-preco/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/tabelas-preco/registro.ts",
    "methods": [
      "GET",
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.cadastros.gerenciar",
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/tabelas-preco",
    "route": "src/app/api/erp/tabelas-preco/route.ts",
    "handler": "src/products/erp/api/handlers/tabelas-preco/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.cadastros.gerenciar",
      "erp.cadastros.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/titulos/[side]/[id]",
    "route": "src/app/api/erp/titulos/[side]/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/titulos/registro.ts",
    "methods": [
      "GET",
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/titulos/[side]",
    "route": "src/app/api/erp/titulos/[side]/route.ts",
    "handler": "src/products/erp/api/handlers/titulos/side.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.financeiro.gerenciar",
      "erp.financeiro.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/atender-parcial",
    "route": "src/app/api/erp/vendas/[id]/atender-parcial/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/atender-parcial.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Optional header; operation-specific behavior.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/atender",
    "route": "src/app/api/erp/vendas/[id]/atender/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/atender.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/cancelar",
    "route": "src/app/api/erp/vendas/[id]/cancelar/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/cancelar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/confirmar",
    "route": "src/app/api/erp/vendas/[id]/confirmar/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/confirmar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/devolucoes",
    "route": "src/app/api/erp/vendas/[id]/devolucoes/route.ts",
    "handler": "src/products/erp/api/handlers/devolucoes/venda.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/[id]/faturar-parcial",
    "route": "src/app/api/erp/vendas/[id]/faturar-parcial/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/faturar-parcial.ts",
    "methods": [
      "POST"
    ],
    "authentication": "none",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": true
  },
  {
    "path": "/api/erp/vendas/[id]/faturar",
    "route": "src/app/api/erp/vendas/[id]/faturar/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/faturar.ts",
    "methods": [
      "POST"
    ],
    "authentication": "none",
    "maxBodyBytes": 1048576,
    "capabilities": [],
    "permissionRule": "Session or dynamic module/operation capability; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": true
  },
  {
    "path": "/api/erp/vendas/[id]/pre-validacao-fiscal",
    "route": "src/app/api/erp/vendas/[id]/pre-validacao-fiscal/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/pre-validacao-fiscal.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": true
  },
  {
    "path": "/api/erp/vendas/[id]",
    "route": "src/app/api/erp/vendas/[id]/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/registro.ts",
    "methods": [
      "GET",
      "PATCH",
      "DELETE"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.estoque.visualizar",
      "erp.financeiro.visualizar",
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas/catalogos",
    "route": "src/app/api/erp/vendas/catalogos/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/catalogos.ts",
    "methods": [
      "GET"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Business-operation rules; see handler.",
    "transportOnlyFiscal": false
  },
  {
    "path": "/api/erp/vendas",
    "route": "src/app/api/erp/vendas/route.ts",
    "handler": "src/products/erp/api/handlers/vendas/index.ts",
    "methods": [
      "GET",
      "POST"
    ],
    "authentication": "session",
    "maxBodyBytes": 1048576,
    "capabilities": [
      "erp.vendas.gerenciar",
      "erp.vendas.visualizar"
    ],
    "permissionRule": "Capabilities vary by method; see handler.",
    "idempotency": "Required for one or more writes; see handler.",
    "transportOnlyFiscal": false
  }
] as const
