import { browserProposalFields } from './proposalFields'
import { formControlsSource } from './formControls'
import { CHATGPTPLUGIN_VERSION } from '../shared/version'
export const FORM_URI='ui://chatgptplugin/form/v1.html'
export function renderFormHtml(origin:string) {
  const descriptors=JSON.stringify(browserProposalFields()).replaceAll('<','\\u003c')
  return html.replace('const origin=null',`const descriptors=${descriptors};const origin=${JSON.stringify(new URL(origin).origin)}`).replace('/* visual-controls */',formControlsSource)
}
const html=String.raw`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{font:15px system-ui;margin:0;padding:24px;color:#17212b;background:#fff}h1{font-size:26px}label{display:block;margin:14px 0 5px}input,select,textarea,button{font:inherit;border:1px solid #ccd5df;border-radius:8px;padding:10px;color:inherit;background:#fff}input,select,textarea{width:100%}textarea{min-height:170px}button{cursor:pointer;margin:14px 8px 0 0}button:disabled{opacity:.5}#submit{background:#345ce6;color:white}#status{white-space:pre-wrap}small{color:#566575}a{color:#345ce6}input:focus-visible,select:focus-visible,textarea:focus-visible,button:focus-visible{outline:2px solid #345ce6;outline-offset:2px}@media(prefers-color-scheme:dark){body{background:#171b20;color:#e9edf1}input,select,textarea,button{background:#222830;color:inherit}small{color:#bdc5d0}}
</style></head><body><h1>Preparar proposta</h1><p>Escolha a empresa e confira os dados. A execução exige sua aprovação no ERP.</p>
<label for="company">Empresa</label><select id="company"><option value="">Escolha uma empresa</option></select><label for="kind">Operação</label><select id="kind"></select>
<form id="form"><section id="fields"></section><button id="submit" type="submit">Preparar para revisão</button></form>
<details><summary>Arquivo de proposta</summary><p><small>Arquivos .erp-proposta contêm somente os dados da proposta. Carregar ou salvar o arquivo não altera registros no ERP.</small></p><input id="upload" type="file" accept=".erp-proposta"><label for="document">Conteúdo do arquivo</label><textarea id="document" spellcheck="false"></textarea><button id="apply">Carregar no formulário</button><button id="export">Baixar arquivo</button><button id="savefile" disabled>Salvar arquivo aberto</button></details><p id="status" role="status">Conectando…</p><div id="review"></div>
<script>(function(){const origin=null;
const pending=new Map();let seq=1,busy=false,key=null,lastPayload=null,file=null,etag=null,writable=false;
const $=id=>document.getElementById(id),status=$('status');
/* visual-controls */
const kinds=Object.fromEntries(Object.entries(descriptors).map(([kind,def])=>[kind,[def.title,Object.keys(def.fields)]]));
const labels=Object.fromEntries(Object.values(descriptors).flatMap(def=>Object.entries(def.fields).map(([field,meta])=>[field,meta.label])));
function request(method,params){return new Promise((resolve,reject)=>{const id=seq++,timer=setTimeout(()=>{pending.delete(id);reject(new Error('A conexão demorou. Confira o resultado antes de repetir.'))},20000);pending.set(id,{resolve,reject,timer});parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function unpack(r){if(r.isError)throw new Error(JSON.parse(r.content[0].text).message||'Operação indisponível.');if(!r.structuredContent?.ok)throw new Error('Resposta indisponível.');return r.structuredContent.data}
function render(data={}){
 controlsRevision++;$('fields').replaceChildren();for(const name of kinds[$('kind').value][1]){
 const label=document.createElement('label');label.htmlFor='f-'+name;label.textContent=(labels[name]||name).replace(' (ID)','').replace(' (JSON)','');const meta=descriptors[$('kind').value].fields[name];
 const choices=meta.choices?(meta.required?meta.choices:['',...meta.choices]):null,input=createControl(name,meta,choices,data);input.required=Boolean(meta.required);input.id='f-'+name;input.dataset.field=name;
 if(choices)for(const value of choices){const option=document.createElement('option');option.value=value;option.textContent=value||'Manter valor';input.append(option)}
 else if(!input.catalogKind&&!input.dataset.array&&(name.endsWith('_id')||meta.number)){input.type='number';input.min=name.endsWith('_id')?'1':'0';input.step=name.endsWith('_id')?'1':'0.01'}
 else if(meta.date)input.type='date';else if(name==='email')input.type='email';
 if(!input.catalogKind&&!input.dataset.array)input.value=data[name]!==undefined?(meta.json?JSON.stringify(data[name],null,2):String(data[name])):choices?choices[0]:'';
 $('fields').append(label,input);if(input.catalogKind)activateCatalog(input,label.textContent);
 if(['editar_conta_pagar','editar_conta_receber'].includes($('kind').value)&&['numero_documento','centro_custo_id','conta_financeira_id','observacoes'].includes(name)){
 const clearLabel=document.createElement('label'),clear=document.createElement('input');clear.type='checkbox';clear.style.width='auto';clear.setAttribute('aria-label','Apagar '+label.textContent);clear.onchange=()=>{input.dataset.clear=clear.checked?'true':'false';input.disabled=clear.checked};clearLabel.append(clear,document.createTextNode(' Apagar este campo'));$('fields').append(clearLabel);
 }
 }
 if($('kind').value.startsWith('editar_')){const load=document.createElement('button');load.type='button';load.textContent='Carregar dados atuais';load.onclick=()=>prefillRecord().catch(e=>status.textContent=e.message);$('fields').append(load)}
 $('review').replaceChildren();key=null;lastPayload=null;
}
function proposal(){const dados={};for(const e of $('fields').querySelectorAll('[data-field]')){const value=e.value.trim(),name=e.dataset.field;if(e.dataset.clear==='true'){dados[name]=null;continue}if(!value)continue;dados[name]=descriptors[$('kind').value].fields[name].json?JSON.parse(value):e.type==='number'||e.dataset.numeric?Number(value):value}return {tipo:$('kind').value,dados}}
function parseDocument(text){if(new TextEncoder().encode(text).length>24000)throw new Error('Arquivo maior que 24 KB.');const v=JSON.parse(text);if(!v||typeof v!=='object'||Object.keys(v).some(k=>!['tipo','dados'].includes(k))||!kinds[v.tipo]||!v.dados||typeof v.dados!=='object'||Array.isArray(v.dados))throw new Error('Arquivo de proposta inválido.');if(Object.keys(v.dados).some(k=>!kinds[v.tipo][1].includes(k)))throw new Error('O arquivo contém campos não suportados neste formulário.');return v}
function applyDocument(text){const p=parseDocument(text);$('kind').value=p.tipo;render(p.dados);$('document').value=JSON.stringify(p,null,2);status.textContent='Dados carregados. Confira o formulário antes de preparar a revisão.'}
async function readFile(input){if(!input?.name?.endsWith('.erp-proposta')||typeof input.resourceUri!=='string')throw new Error('Tipo de arquivo não suportado.');const result=await request('resources/read',{uri:input.resourceUri,_meta:{'openai/resource':{representation:'text'}}});const c=result.contents?.find(c=>c.uri===input.resourceUri&&typeof c.text==='string');if(!c)throw new Error('Arquivo de texto indisponível.');applyDocument(c.text);const meta=c._meta?.['openai/resource'];file=input;etag=meta?.etag||null;writable=meta?.writable===true&&typeof etag==='string';$('savefile').disabled=!writable}
window.addEventListener('message',event=>{if(event.source!==parent||event.data?.jsonrpc!=='2.0')return;const m=event.data,e=pending.get(m.id);if(e){clearTimeout(e.timer);pending.delete(m.id);m.error?e.reject(new Error(m.error.message||'Falha na conexão')):e.resolve(m.result);return}if(m.method==='ui/notifications/tool-input'&&m.params?.arguments?.file)readFile(m.params.arguments.file).catch(e=>status.textContent=e.message)});
for(const [value,[name]] of Object.entries(kinds)){const o=document.createElement('option');o.value=value;o.textContent=name;$('kind').append(o)}$('kind').onchange=()=>render();$('company').onchange=()=>render();render();
$('form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;$('submit').disabled=true;try{const empresa_id=Number($('company').value);if(!empresa_id)throw new Error('Escolha uma empresa.');const proposta=proposal(),payload=JSON.stringify({empresa_id,proposta});if(payload!==lastPayload){key=crypto.randomUUID();lastPayload=payload}const data=unpack(await request('tools/call',{name:'preparar_rascunho',arguments:{empresa_id,chave_operacao:key,proposta}}));const url=new URL(data.revisao_url);if(url.origin!==origin||!/^\/chatgptplugin\/approvals\/[0-9a-f-]{36}$/.test(url.pathname))throw new Error('Link de revisão inválido.');$('review').replaceChildren();const button=document.createElement('button');button.type='button';button.textContent='Abrir revisão no ERP';button.onclick=()=>request('ui/open-link',{url:url.href}).catch(e=>status.textContent=e.message);$('review').append(button);status.textContent='Proposta preparada. Abra a revisão para aprovar no ERP.';$('document').value=JSON.stringify(proposta,null,2)}catch(e){status.textContent=e.message}finally{busy=false;$('submit').disabled=false}};
$('upload').onchange=async()=>{try{const f=$('upload').files[0];if(!f||!f.name.endsWith('.erp-proposta')||f.size>24000)throw new Error('Selecione um arquivo .erp-proposta de até 24 KB.');applyDocument(await f.text());file=null;writable=false;etag=null;$('savefile').disabled=true}catch(e){status.textContent=e.message}};
$('apply').onclick=()=>{try{applyDocument($('document').value)}catch(e){status.textContent=e.message}};
$('export').onclick=()=>{try{const text=JSON.stringify(proposal(),null,2);parseDocument(text);const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='proposta.erp-proposta';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){status.textContent=e.message}};
$('savefile').onclick=async()=>{if(!file||!writable||!etag)return;try{const text=JSON.stringify(proposal(),null,2);parseDocument(text);$('document').value=text;const result=await request('openai/resources/write',{uri:file.resourceUri,ifMatch:etag,text});if(result.outcome!=='saved')throw new Error(result.outcome==='conflict'?'O arquivo mudou. Abra novamente antes de salvar.':'Não foi possível salvar o arquivo.');etag=result.etag;status.textContent='Arquivo salvo. Os registros do ERP só mudam após a aprovação da proposta.'}catch(e){status.textContent=e.message}};
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'chatgptplugin-form',version:'${CHATGPTPLUGIN_VERSION}'},appCapabilities:{}}).then(async()=>{parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',params:{}},'*');const data=unpack(await request('tools/call',{name:'meu_acesso',arguments:{}}));for(const c of data.empresas){const o=document.createElement('option');o.value=String(c.id);o.textContent=c.name;$('company').append(o)}if(data.empresas.length===1)$('company').value=String(data.empresas[0].id);status.textContent='Escolha a operação e preencha os dados.'}).catch(e=>status.textContent=e.message);
})();</script></body></html>`
