export const PANEL_URI='ui://chatgptplugin/panel/v1.html'
export function renderPanelHtml(origin:string) {
  return panelHtml.replace('let resourceOrigin=null',`let resourceOrigin=${JSON.stringify(new URL(origin).origin)}`)
}
// Documento autocontido: dados externos entram apenas por textContent, sem scripts ou recursos remotos.
export const panelHtml=String.raw`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark}*{box-sizing:border-box}body{font:var(--font-text-sm-size,15px) var(--font-sans,system-ui,sans-serif);margin:0;padding:16px;color:var(--color-text-primary,light-dark(#17212b,#e9edf1));background:transparent}h1{margin:6px 0 10px;font-size:var(--font-heading-md-size,22px)}p{line-height:1.5}.muted{opacity:.65;font-size:13px}button,select,input{font:inherit;border:1px solid light-dark(#d4dbe1,#444c56);border-radius:10px;padding:10px 12px;background:light-dark(#fff,#222830);color:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:wait}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #4675ed;outline-offset:2px}nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}nav button[aria-pressed=true]{background:#345ce6;color:#fff}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.toolbar input{flex:1;min-width:140px}#content{overflow:auto;max-height:65vh;border:1px solid light-dark(#e3e8ee,#333c46);border-radius:14px;padding:16px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid light-dark(#e3e8ee,#333c46);white-space:nowrap}article{padding:14px 0;border-bottom:1px solid light-dark(#e3e8ee,#333c46)}article h2{font-size:17px;margin:0 0 6px}.pager{display:flex;align-items:center;gap:12px;margin-top:16px}
</style></head><body><p class="muted">Cognito ERP · ChatGPT Plugin</p><h1>Seu ERP, nesta conversa</h1><p class="muted">Consulte clientes, vendas, orçamentos e compras. Para criar ou alterar dados, peça na conversa.</p><label for="company">Empresa</label> <select id="company"><option value="">Escolha uma empresa</option></select>
<nav aria-label="Consultas"><button data-tool="buscar_cadastros" aria-pressed="true">Clientes</button><button data-tool="listar_vendas" aria-pressed="false">Vendas</button><button data-tool="orcamentos" aria-pressed="false">Orçamentos</button><button data-tool="listar_compras" aria-pressed="false">Compras</button></nav>
<div class="toolbar"><input id="search" aria-label="Buscar" placeholder="Buscar por nome ou número"><button id="refresh">Consultar</button></div><p id="status" role="status" class="muted">Conectando…</p><section id="content" aria-label="Resultados"></section><div class="pager"><button id="previous" disabled>Anterior</button><span id="page">Página 1</span><button id="next" disabled>Próxima</button></div>
<script>
(function(){
const pending=new Map();let sequence=1;let tool='buscar_cadastros';let page=1;let busy=false;let selected=null;let resourceOrigin=null;let serial=0;let pageSize=20;let preferredCompany=null;
const company=document.getElementById('company'),status=document.getElementById('status'),content=document.getElementById('content'),search=document.getElementById('search');
function request(method,params){return new Promise((resolve,reject)=>{const id=sequence++;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('A conexão demorou. Tente novamente.'))},20000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function notify(method,params){window.parent.postMessage({jsonrpc:'2.0',method,params},'*')}
function text(tag,value){const element=document.createElement(tag);element.textContent=String(value==null?'—':value);return element}
function unpack(result){if(result.isError){let error;try{error=JSON.parse(result.content[0].text)}catch{}throw new Error(error?.message||'Não foi possível consultar.')}if(!result.structuredContent?.ok)throw new Error('Resposta indisponível.');return result.structuredContent.data}
function access(data){if(!Array.isArray(data?.empresas))return;company.replaceChildren(text('option','Escolha uma empresa'));company.firstChild.value='';for(const item of data.empresas){const option=text('option',item.name);option.value=String(item.id);company.append(option)}selected=data.empresa_selecionada||(data.empresas.some(c=>c.id===preferredCompany)?preferredCompany:null)||(data.empresas.length===1?data.empresas[0].id:null);company.value=selected?String(selected):'';status.textContent=selected?'Escolha uma consulta.':'Escolha a empresa para consultar.';if(selected)load()}
function render(data){content.replaceChildren();const rows=data.records||[];if(!rows.length){content.append(text('p','Nenhum registro encontrado.'));return}
const labels={id:'ID',nome:'Nome',numero:'Número',cliente:'Cliente',fornecedor:'Fornecedor',data:'Data',total:'Total',status:'Situação',tipo:'Tipo',tipo_documento:'Documento',atendimento_status:'Atendimento',fiscal_status:'Fiscal'};const keys=Object.keys(rows[0]).filter(k=>k!=='__total');const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(const key of keys)tr.append(text('th',labels[key]||key));head.append(tr);table.append(head);const body=document.createElement('tbody');for(const row of rows){const line=document.createElement('tr');for(const key of keys)line.append(text('td',key==='total'?Number(row[key]).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):row[key]));body.append(line)}table.append(body);content.append(table)}
async function load(){if(!selected||busy)return;busy=true;const ticket=++serial;const requestedTool=tool;status.textContent='Consultando…';document.getElementById('refresh').disabled=true;company.disabled=true;try{const args={empresa_id:selected,pagina:page,por_pagina:pageSize};if(tool==='buscar_cadastros')args.tipo='clientes';if(tool==='orcamentos')args.tipo_documento='orcamento';if(search.value.trim())args.busca=search.value.trim();const data=unpack(await request('tools/call',{name:tool==='orcamentos'?'listar_vendas':tool,arguments:args}));if(ticket!==serial||requestedTool!==tool)return;render(data);status.textContent=data.total!==undefined?data.total+' registros':'Consulta concluída';document.getElementById('page').textContent='Página '+page;document.getElementById('previous').disabled=page===1;document.getElementById('next').disabled=!(data.hasMore??page*pageSize<data.total)}catch(error){if(ticket===serial)status.textContent=error.message}finally{busy=false;document.getElementById('refresh').disabled=false;company.disabled=false}}
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=='2.0')return;const entry=pending.get(message.id);if(entry){clearTimeout(entry.timer);pending.delete(message.id);message.error?entry.reject(new Error(message.error.message||'Falha na conexão')):entry.resolve(message.result);return}if(message.method==='ui/notifications/tool-result'){const data=message.params?.structuredContent?.data;if(data?.empresas)access(data)}if(message.method==='ui/notifications/host-context-changed'){const theme=message.params?.theme;if(theme==='dark'||theme==='light')document.documentElement.style.colorScheme=theme}});
company.onchange=()=>{selected=Number(company.value)||null;page=1;serial++;content.replaceChildren();load()};for(const button of document.querySelectorAll('nav button'))button.onclick=()=>{if(busy)return;tool=button.dataset.tool;page=1;for(const sibling of document.querySelectorAll('nav button'))sibling.setAttribute('aria-pressed',String(sibling===button));load()};document.getElementById('refresh').onclick=()=>{page=1;load()};document.getElementById('previous').onclick=()=>{if(!busy&&page>1){page--;load()}};document.getElementById('next').onclick=()=>{if(!busy){page++;load()}};search.onkeydown=event=>{if(event.key==='Enter'){page=1;load()}};
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'chatgptplugin-panel',version:'1.1.0'},appCapabilities:{}}).then(async result=>{const origin=result?.hostContext?.theme;if(origin==='dark'||origin==='light')document.documentElement.style.colorScheme=origin;const vars=result?.hostContext?.styles?.variables;if(vars)for(const [key,value] of Object.entries(vars))if(/^--[a-z0-9-]+$/.test(key)&&typeof value==='string')document.documentElement.style.setProperty(key,value);notify('ui/notifications/initialized',{});try{const prefs=await request('tools/call',{name:'ler_configuracoes',arguments:{}});const values=prefs.structuredContent?.values;if(values){pageSize=values.por_pagina||20;preferredCompany=Number(values.empresa_preferida)||null}}catch{}const data=unpack(await request('tools/call',{name:'meu_acesso',arguments:{}}));access(data)}).catch(error=>{status.textContent=error.message});

})();
</script></body></html>`
